force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/classes/Test_IM_Alternative_Country_NameObject.cls
/*Developer Name: Madhu Paladugu
  Company       : TheCloudFountain Inc.
  Desrciption   : Test utility for IM_Alternative_Country_NameObject trigger.
  Date          : 12/3/12
  case number   : 00924109   */
@isTest(seeallData=true)
private class Test_IM_Alternative_Country_NameObject {

    static testMethod void runTest() {
      
      triggerFlowControl.setControlEnabled(false);//allow triggers to run without limit
      List<Trigger_Activation_Settings__c> customsettings = Trigger_Activation_Settings__c.getall().values();
      List<Trigger_Activation_Settings__c> updatesettings = new List<Trigger_Activation_Settings__c>();
      for(Trigger_Activation_Settings__c cs : customsettings){
        if(cs.Object__c == 'IM_Alternative_Country_Name__c') {
          cs.Value__c='True';
          updatesettings.add(cs);
        }
      }
      update updatesettings;
      
        IM_Country__c c = new IM_Country__c(name='This is a test');
        insert c;
        
        IM_Alternative_Country_Name__c acs = new IM_Alternative_Country_Name__c(Alternative_Name__c = 'Test Country',
                                                                               IM_Country__c = c.id);
        insert acs;
        
        IM_Alternative_Country_Name__c ac = [Select Id, Alternative_Name__c from IM_Alternative_Country_Name__c where IM_Country__c = :c.Id limit 1];
        
        boolean genError = false;
        //test renaming the root country
        try{
          ac.Alternative_Name__c = 'x';
          update ac;
        }
        catch(Exception e)
        {
          genError = true;
        }
        
         System.assertEquals(genError, false);
        
        genError = false;
        //test deleting the root country
        try{
          delete ac;
        }
        catch(Exception e)
        {
          genError = true;
        }
        
        System.assertEquals(genError, false);
        
    }
}