force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Functional_Area__c.field-meta.xml
<CustomField>
    <fullName>IM_Functional_Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Archives</fullName>
            </value>
            <value>
                <fullName>Compliance Management</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Library</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>IM_Lead_Source_Most_Recent__c</fullName>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
                <label>Inbound Call</label>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>IM_Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-Suspect</fullName>
                <default>true</default>
                <label>0-Suspect</label>
            </value>
            <value>
                <fullName>1-Inquiry</fullName>
            </value>
            <value>
                <fullName>2-Marketing Qual</fullName>
            </value>
            <value>
                <fullName>3-Sales Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Most_Recent__c</fullName>
    <inlineHelpText>For new opportunities on existing customers, add the most recent source of the lead</inlineHelpText>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <inlineHelpText>The operational source system the customer ID is managed through</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SKP Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>Other Europe</fullName>
            </value>
            <value>
                <fullName>SB IMLA</fullName>
            </value>
            <value>
                <fullName>SKP IMLA</fullName>
            </value>
            <value>
                <fullName>Other IMLA</fullName>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>SKP IMAP</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SRMS IMAP</fullName>
            </value>
            <value>
                <fullName>Tape Guard IMAP</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>SB IMAP</fullName>
            </value>
            <value>
                <fullName>TRSQL</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TOBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/OpportunityProductSelection__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to take product class and product line names in to apex class while adding product</description>
    <label>OpportunityProductSelection</label>
</CustomObject>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Class_Name__c</fullName>
    <label>Product Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/test_OpportunityOwnerInfoScheduler.cls
/*
Auhtor      : Nagesh Ganji
Created Date: Apr 5,2010
Description : Tester utility class for Opportunity owner info update scheduler class(OpportunityOwnerInfoScheduler)
*/ 

@istest
private class test_OpportunityOwnerInfoScheduler {
    
    public static Account testAccount1;
    public static Opportunity testOpp1;
    public static List<Opportunity> lstOp = new List<Opportunity>();
    public static Database.SaveResult[] srList ;
    static testmethod void myUnitTest() {
        setup();
        /*
IM_Country__c cntry = CountryNameTranslator.getOrCreateTestCountry
( (new IM_Country__c(name = 'United Kingdom',
Region__c = 'Europe')));
Test.startTest();
triggerFlowControl.setControlEnabled(false);

Account A = new Account(name='Account4TestMethod');
insert A;

//Create a new Opportunity
Opportunity opp1 = new Opportunity();
opp1.AccountId = A.Id;
opp1.Name = 'Opportunity4TestMethod';
opp1.CloseDate = Date.today();
opp1.StageName = '1 - Qualification';
opp1.Type = 'Renewal';
opp1.Lead_Source_Most_Recent__c = 'Email';


insert opp1;
*/
        //Create a Lead and convert to create an Opportunity 
        Test.startTest();
        Lead l = new Lead();
        Id imeRecTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('IME Lead').getRecordTypeId();        
        l.LastName = 'Lead4UnitTest';
        l.Company = 'Account4UnitTest';
        l.FirstName = 'Lead';
        l.IM_Lead_Source_Most_Recent__c = 'Email';
        l.IM_Lead_Stage__c = '1-Inquiry';        
        l.IM_Lead_Stage__c = '1-Inquiry';
        l.Email = 'testemail@email.com';
        l.Phone = '1112223333';
        l.Street = 'TestStreet';
        l.City = 'London';
        l.State = 'MA';
        l.Country = 'United Kingdom';
        l.PostalCode = '02111';
        l.RecordTypeId = imeRecTypeId;     
        l.IM_Functional_Area__c = 'x';
        
        
        triggerFlowControl.setControlEnabled(true);
        insert l;
        
        Campaign c = new Campaign(name='Campaign4UnitTest');
        insert c;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = c.Id;
        cm.LeadId = l.Id;
        insert cm;
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(l.id);
        
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        //Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        
        // Schedule the test job  
        String jobId = System.schedule('testOptyOwnerInfoUpdateSchdl','0 15 16 9 5 ? 2025',
                                       new OpportunityOwnerInfoScheduler ());
        
        // Get the information from the CronTrigger API object  
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same  
        System.assertEquals('0 15 16 9 5 ? 2025', ct.CronExpression);
        
        // Verify the job has not run  
        System.assertEquals(0, ct.TimesTriggered);
        
        Test.stopTest();
        
        
        
    }
    public static testMethod void testschedule() {
        Test.StartTest();
        OpportunityOwnerInfoScheduler sh1 = new OpportunityOwnerInfoScheduler();
        OpportunityOwnerInfoBatchUpdateTest.setup();
        String sch = '0 0 23 * * ?'; system.schedule('Test OpportunityOwnerInfoScheduler Check', sch, sh1); 
        Test.stopTest(); 
    }
    
    public static void setup() {
        IM_Country__c testCountry = new IM_Country__c(Name='United States');
        insert testCountry;        
        IM_Alternative_Country_Name__c country = new IM_Alternative_Country_Name__c(IM_Country__c = testCountry.Id, Alternative_Name__c='United States');
        insert country; 
        triggerFlowControl.setControlEnabled(false);
        testAccount1 = new Account();
        testAccount1.Name = 'TestAccount1';
        testAccount1.BillingCountry = 'United States';
        testAccount1.BillingPostalCode = '11209';
        testAccount1.BillingState = 'NY'; 
        testAccount1.BillingCity = 'Ancaster';
        testAccount1.BillingStreet ='1142 Wilson St W';
        insert testAccount1;
        
        
        OpportunityProductSelection__c oppprodsel = new OpportunityProductSelection__c();
        oppprodsel.Name = 'CloudSolutionsProduct';
        oppprodsel.Product_Class_Name__c = 'Data Backup and Recovery';
        oppprodsel.Product_Line_Name__c = 'Cloud Solutions';              
        insert oppprodsel; 
        Country_Settings__c setting = new Country_Settings__c();
        setting.Name = 'United States';
        setting.object_name__c = 'Account';
        insert setting;
        
        Profile p = [Select id from profile where name = 'IM_Custom Sys Admin'];
        IM_Country__c cntry = CountryNameTranslator.getOrCreateTestCountry
            ( (new IM_Country__c(name = 'United Kingdom',
                                 Region__c = 'Europe')));
        IM_Country__c cntry1 = CountryNameTranslator.getOrCreateTestCountry
            ( (new IM_Country__c(name = 'Denmark',
                                 Region__c = 'Asia Pacific')));
        
        
        RecordType EUOppType = [select id from RecordType
                                where name = 'Standard Opportunity'
                                and sObjectType = 'Opportunity'];
        
        
        Product2 product = 
            new Product2(
                Secondary_Product_Allowed__c=true, 
                Name='test', 
                CurrencyIsoCode='GBP', 
                IsActive=true);
        insert product;
        Id standardPB = Test.getStandardPricebookId();
        testOpp1 = new Opportunity(
            name = 'Opportunity4TestMethod'
            ,Source_System__c = 'Other Europe'
            ,Billing_Country__c = cntry.id 
            ,Lead_Source_Most_Recent__c = 'Email'
            ,Type = 'Renewal'
            ,StageName = '1 - Qualification'
            ,IM_Servicing_Region__c ='London'
            ,IME_Reason_Won__c = 'Benchmarking'
            ,AccountId = testAccount1.Id   
            ,IM_Booked_Date__c = System.today(),
            CloseDate= system.today()
            ,RecordTypeId = EUOppType.Id,
            IM_Commit_to_Forecast__c = true
            ,IM_Stage_5_Entered_Date__c  = System.today()
            ,CurrencyIsoCode='GBP',pricebook2ID= standardPB,Owner_Email__c='testOpp1@testOpp1.com'
        );
        insert testOpp1;
    }
    
}