force-app/main/default/objects/Archive_Email__b/Archive_Email__b.object-meta.xml
<CustomObject>
    <label>Archive Email</label>
    <pluralLabel>Archive Emails</pluralLabel>
</CustomObject>

force-app/main/default/objects/Archive_Email__b/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Archive Emails</relationshipLabel>
    <relationshipName>Archive_Emails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Archive_Email__b/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Email__b/fields/FromAddress__c.field-meta.xml
<CustomField>
    <fullName>FromAddress__c</fullName>
    <label>FromAddress</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Category__c</fullName>
    <description>value selected by the Sales tools team and is dependent on Case Category</description>
    <label>Case Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Community/Chat</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Configuration/Development</fullName>
            </value>
            <value>
                <fullName>Data Maintenance</fullName>
            </value>
            <value>
                <fullName>IMGA</fullName>
            </value>
            <value>
                <fullName>Import Request</fullName>
            </value>
            <value>
                <fullName>IT Development</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outage/Critical Incident</fullName>
            </value>
            <value>
                <fullName>Reports/Dashboards</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Software Request</fullName>
            </value>
            <value>
                <fullName>Territory Alignment</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>User Management</fullName>
            </value>
            <value>
                <fullName>Vendor Development</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Emails_Archived__c.field-meta.xml
<CustomField>
    <fullName>Emails_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to mark when the case has its email archived and converted into big object records</description>
    <label>Emails Archived?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Completion_Date__c</fullName>
    <label>Project Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Transition_Date__c.field-meta.xml
<CustomField>
    <fullName>Transition_Date__c</fullName>
    <inlineHelpText>Date transition call (60 day follow-up)with customer is complete</inlineHelpText>
    <label>Transition Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/NCSP_New_Customer_Setup.recordType-meta.xml
<RecordType>
    <fullName>NCSP_New_Customer_Setup</fullName>
    <active>true</active>
    <businessProcess>NCSP New Customer Support Process</businessProcess>
    <description>Used by NCSP to manage on boarding Accutrac, Tape Catalog Manager and Data Restoration Assurance Program opportunities</description>
    <label>NCSP: New Customer Setup</label>
</RecordType>

force-app/main/default/objects/Case_Email_Count__c/Case_Email_Count__c.object-meta.xml
<CustomObject>
    <description>Custom object contains the year and month wise email counts for cases. Used in the report</description>
    <label>Case Email Count</label>
    <nameField>
        <label>Case Email Count Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Email Counts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseEmailMessagesBigObjectCountTest.cls
/**
* Class: CaseEmailMessagesBigObjectCountTest
*
* Author: TCS
*
* Purpose: This is a test class for CaseEmailMessagesBigObjectCount
*
* Requirement: GitLab : #31411 
*
* Change History:
*
* Developer                     Date 	             		Description
* -------------------------------------------------------------------------------------------
* Praneel                       11/Jul/2025               test class for CaseEmailMessagesBigObjectCount
*/

@isTest
public class CaseEmailMessagesBigObjectCountTest {
	
    static final String CLOSED_STATUS = 'Closed';
    static final String OPEN_STATUS = 'Open';
    static final String SUBJECT = 'Subject';
    static final String BODY = 'Body';
    static final Id CASE_RECORDTYPE = Schema.SobjectType.Case.getRecordTypeInfosByDeveloperName().get('NCSP_New_Customer_Setup').getRecordTypeId();
    static final Integer RECORD_COUNT = 10;
    static final Date TODAY = Date.today();
    static final String RANDOM_EMAIL = '123';
    
        
     @testsetup
    static void setup1() {
        List<Case> cases = new SObjectBuilder(Case.SObjectType)
            .put(Case.Status, CLOSED_STATUS)
            .put(Case.RecordTypeId, CASE_RECORDTYPE)
            .put(Case.Project_Completion_Date__c, TODAY)
            .put(Case.Transition_Date__c, System.Now())
            .put(Case.Origin,'NAS_EMAIL_English_Auto_Response_AskCS')
            .put(Case.Emails_Archived__c, true)
            .count(RECORD_COUNT).create().getRecords();

        List<EmailMessage> emails = new SobjectBuilder(EmailMessage.SobjectType)
        .put(EmailMessage.ParentId, cases)
        .put(EmailMessage.Subject, SUBJECT)
        .put(EmailMessage.TextBody, BODY)
        .put(EmailMessage.FromAddress,'dkdow@dmdp.cld')
        .count(RECORD_COUNT).create().getRecords();

        new SobjectBuilder(Attachment.SobjectType)
        .put(Attachment.ParentId, emails)
        .put(Attachment.Name, SUBJECT)
        .put(Attachment.Body, Blob.valueOf('TEST'))
        .count(RECORD_COUNT).create();
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion;
        
       // List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
         id documents = [select contentdocumentid from contentversion where id =: contentVersion.id].contentdocumentid;
        
        //create ContentDocumentLink  record
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = emails[0].id;
        cdl.ContentDocumentId = documents;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        
        Case newCase = (Case) new SobjectBuilder(Case.SobjectType)
            .put(Case.RecordTypeId, Schema.SObjectType.Case.getRecordTypeInfosByName().get('IM Employees Support Case Closed (Locked)').getRecordTypeId())
            .put(Case.Subject, 'Holder_TEST123')
            .put(Case.Status, 'Closed')
            .put(Case.Case_Sub_Category__c, 'IT Development')
        //    .put(Case.Origin,'NAS_EMAIL_English_Auto_Response_AskCS')
            .create().getRecord();
        
        List<EmailMessage> testEmail1 = new SobjectBuilder(EmailMessage.SobjectType)
        .put(EmailMessage.ParentId, newCase)
        .put(EmailMessage.Subject, SUBJECT)
        .put(EmailMessage.TextBody, BODY)
        .put(EmailMessage.FromAddress,'dkdow@dmdp.cld')
        .count(2).create().getRecords();
        
        

        
         Archive_Email__b archivedEmail = new Archive_Email__b(
            Case__c = newCase.Id,
            Email__c = RANDOM_EMAIL,
            FromAddress__c = '29329@irm.com'
           
        );
        
      //  Database.insertImmediate(archivedEmail);
            } 
    
   
    
    @isTest
    static void testCaseEmailMsgWithoutArchival(){
        
       test.starttest();
        try {
            CaseEmailMessagesBigObjectCount caseEmailBigObj = new CaseEmailMessagesBigObjectCount();
            
            
           caseEmailBigObj.emailMessageCountByMonth.put(Date.today().month()+' '+Date.today().year(),new Case_Email_Count__c());
            String chron = '0 0 23 * * ?';        
            system.schedule('Test Sched3', chron, caseEmailBigObj);
           // caseEmailBigObj.execute(null);
        } catch(exception e){
            system.debug('error occured while executing the test method '+e.getMessage());
        }
        Test.stopTest();
    }
    
     @isTest
    static void testInvalidDateRange() {
        try {
            new CaseEmailMessagesBigObjectCount(Date.today(), Date.today().addDays(-1));
            System.assert(false, 'Should have thrown exception');
        } catch (IllegalArgumentException e) {
            System.assertEquals('Invalid date range', e.getMessage());
        }
    }
    
    
}