force-app/main/default/objects/Case/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Australia / New Zealand</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Category__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Category__c</fullName>
    <description>This field is used to track the category of Service request</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amendment of customer details</fullName>
            </value>
            <value>
                <fullName>Authorised User Requests</fullName>
            </value>
            <value>
                <fullName>Billing &amp; Invoice Issues</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Create a new Order</fullName>
            </value>
            <value>
                <fullName>Energy (UK)</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Online system support</fullName>
            </value>
            <value>
                <fullName>Order Enquiry</fullName>
            </value>
            <value>
                <fullName>Relationship Management</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Sales Enquiry</fullName>
            </value>
            <value>
                <fullName>Authorized User Requests</fullName>
            </value>
            <value>
                <fullName>Non Conformance (Australia)</fullName>
            </value>
            <value>
                <fullName>Manual Billing (UK)</fullName>
            </value>
            <value>
                <fullName>Billing Maintenance (UK)</fullName>
            </value>
            <value>
                <fullName>Service Order Adjustment (UK)</fullName>
            </value>
            <value>
                <fullName>Standard Billing Scheduled (UK)</fullName>
            </value>
            <value>
                <fullName>Non Standard Billing (UK)</fullName>
            </value>
            <value>
                <fullName>SKP invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>SBE invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>Manual invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>DMS invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>Pricing &amp; Contracts (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Country__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Customer_AccountId__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Customer_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases (Customer Account)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Number_of_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Number_of_Line_Items__c</fullName>
    <label>Number of Line Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IME_SC_Sub_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Non-order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IME_SC_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Closure</fullName>
            </value>
            <value>
                <fullName>Account Transfer</fullName>
            </value>
            <value>
                <fullName>Add/amend customer rate</fullName>
            </value>
            <value>
                <fullName>Additional Boxes Received (Australia Only)</fullName>
            </value>
            <value>
                <fullName>Add New Authorised Users (DP)</fullName>
            </value>
            <value>
                <fullName>Add New Authorised Users (RM/SS)</fullName>
            </value>
            <value>
                <fullName>Add New Authorized Users</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Reports</fullName>
            </value>
            <value>
                <fullName>ANC – Disputed Debt</fullName>
            </value>
            <value>
                <fullName>ANC - New</fullName>
            </value>
            <value>
                <fullName>ANC - Query</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>Bad Survey Score</fullName>
            </value>
            <value>
                <fullName>Barcode Error (Australia Only)</fullName>
            </value>
            <value>
                <fullName>Blending/grouping of rates</fullName>
            </value>
            <value>
                <fullName>Box/file movements between accounts</fullName>
            </value>
            <value>
                <fullName>Box/file restriction changes</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Cancel an order</fullName>
            </value>
            <value>
                <fullName>Cannot access website</fullName>
            </value>
            <value>
                <fullName>Cannot pay invoice</fullName>
            </value>
            <value>
                <fullName>Change an order</fullName>
            </value>
            <value>
                <fullName>Change transport priority</fullName>
            </value>
            <value>
                <fullName>Checking Authorised users (DP)</fullName>
            </value>
            <value>
                <fullName>Checking Authorised users (RM/SS)</fullName>
            </value>
            <value>
                <fullName>Checking Authorized users</fullName>
            </value>
            <value>
                <fullName>Code Red procedure</fullName>
            </value>
            <value>
                <fullName>Company Name changes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>IM_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Accounts_AM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IME_SC_Toggle_Country_Features__c/IME_SC_Toggle_Country_Features__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting will be used to identify the feature availability in particular country.</description>
    <label>IME_SC_Toggle_Country_Features</label>
</CustomObject>

force-app/main/default/classes/Test_IRM_SC_AssignCasetoAccManager.cls
/************************
Developer Name: Venkateswarlu Avula
Case Number   : 01814315
Date          : 10/8/13
purpose       : Test Utility for IRM_SC_AssignCasetoAccManager  class
***********************/

@isTest(seeAllData=true)
private class Test_IRM_SC_AssignCasetoAccManager
{
    static testMethod void testAssignCasetoAccManager()
    {
        Test.startTest();
        ID caseRecordType = DataFactory.getRecordTypeId('Case','IME SC Case');   
        User ManagerUser = DataFactory.createUsersLst(1)[0];
        List<Case> caseList = new List<Case>();
        List<IM_Customer_Account__c> custAccList = new List<IM_Customer_Account__c>();
        Group queue = [Select g.Name, g.Id From Group g where Name Like 'IME SC %queue%' LIMIT 1];
        
        GroupMember grpMember = new GroupMember (UserOrGroupId = ManagerUser.Id, GroupId = queue.Id);
        
        /*Profile sysAdmin = [Select Id, Name from Profile where Name LIKE '%System Admin%' LIMIT 1];
        UserRole CSRuser = [Select Name, Id From UserRole where Name LIKE '%CSR%' LIMIT 1];
        User ManagerUser = new User(FirstName = 'Test', LastName = 'User', ProfileId = sysAdmin.Id, ManagerId = null,
                              LanguageLocaleKey = 'en_US', IsActive = true, TimeZoneSidKey = 'Europe/London',
                              Username = 'TestUser1@support.com', Email = 'testUser@support.com',
                              Alias = 'tUse', EmailEncodingKey = 'ISO-8859-1', CommunityNickname = 'tOwn1',
                              LocaleSidKey = 'en_US', Country='Australia');
                              
        insert ManagerUser;*/
        User currentUser = new User ( Id = UserInfo.getUserId() );
        System.runAs(currentUser)
        {
            //Creation of Account
            Account testAccount = new Account(Name='Test Account', BillingCountry = 'Australia');
            insert testAccount;
            
            
            //Creation of IM Country record
            IM_Country__c country = new IM_Country__c(Name = 'France');
            insert country;
            
            //Creation of Customer Account
            IM_Customer_Account__c caseCustomerAccount1 = new IM_Customer_Account__c(Name = '123', IM_Account_Manager__c = ManagerUser.Id, 
                                                         Billing_Country__c = country.Id, IM_Account__c = testAccount.id);
            custAccList.add(caseCustomerAccount1);
            
                  
            insert custAccList;
            
            
            
            //insert Case
            Case newCase = new Case();
            newCase.Origin = 'AUS_EMAIL_NSW';
            newCase.OwnerId = queue.Id;
            newCase.RecordTypeId = caseRecordType;
            newCase.IME_SC_Category__c= 'Order Enquiry';
            newCase.IME_SC_Sub_Category__c = 'Change an order';
            newCase.IME_SC_Request_Type__c = 'Order';
            newCase.IME_SC_Number_of_Line_Items__c = 1;
            newCase.IME_SC_Customer_AccountId__c = caseCustomerAccount1.id;
            caseList.add(newCase);
            
            //insert case with Queue;
            Case newCaseQueue = new Case();
            newCaseQueue.Origin = 'AUS_EMAIL_NSW';
            newCaseQueue.OwnerId = queue.Id;
            newCaseQueue.Status = 'Validated';
            newCaseQueue.IME_SC_Country__c = 'Australia';
            newCaseQueue.RecordTypeId = caseRecordType;
            newCaseQueue.IME_SC_Category__c= 'Order Enquiry';
            newCaseQueue.IME_SC_Sub_Category__c = 'Change an order';
            newCaseQueue.IME_SC_Request_Type__c = 'Order';
            newCaseQueue.IME_SC_Number_of_Line_Items__c = 1;
            newCaseQueue.IME_SC_Customer_AccountId__c = caseCustomerAccount1.id;
            
            caseList.add(newCaseQueue);
            
             //insert Case
            Case newCase1 = new Case();
            newCase1.Origin = 'AUS_EMAIL_NSW';
            newCase1.OwnerId = queue.Id;
            newCase1.Status = 'Assigned';
            newCase1.RecordTypeId = caseRecordType;
            newCase1.IME_SC_Category__c= 'Order Enquiry';
            newCase1.IME_SC_Sub_Category__c = 'Change an order';
            newCase1.IME_SC_Request_Type__c = 'Order';
            newCase1.IME_SC_Number_of_Line_Items__c = 1;
            newCase1.IME_SC_Customer_AccountId__c = caseCustomerAccount1.id;
            caseList.add(newCase1);
          
          //insert Case
            Case newCase2 = new Case();
            newCase2.Origin = 'AUS_EMAIL_NSW';
            newCase2.OwnerId = queue.Id;
            newCase2.Status = 'Validated';
            newCase2.IME_SC_Country__c = 'Australia';
            newCase2.OwnerId = queue.Id;
            newCase2.RecordTypeId = caseRecordType;
            newCase2.IME_SC_Category__c= 'Order Enquiry';
            newCase2.IME_SC_Sub_Category__c = 'Change an order';
            newCase2.IME_SC_Request_Type__c = 'Order';
            newCase2.IME_SC_Number_of_Line_Items__c = 1;
            newCase2.IME_SC_Customer_AccountId__c = caseCustomerAccount1.id;
            caseList.add(newCase2);
            
            insert caseList;
            
            List<IME_SC_Toggle_Country_Features__c> toggleFeaturesCustomSetting = IME_SC_Toggle_Country_Features__c.getall().values();
            IRM_SC_AssignCaseToAccManager objAssCaseToAccMngr = new IRM_SC_AssignCaseToAccManager();
            System.runAs(ManagerUser)
            {
                objAssCaseToAccMngr.assignCaseToAccManager(caseList);
            }  
            Test.stopTest();
        }
    }
}