force-app/main/default/objects/Case/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Australia / New Zealand</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer_ID__r.IM_Customer_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Customer Profile that is created by the Send to NCSP wizard and associated to this case and opportunity</description>
    <label>Customer Profile</label>
    <referenceTo>Customer_Profile__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_welcome_call_completed__c.field-meta.xml
<CustomField>
    <fullName>Date_welcome_call_completed__c</fullName>
    <label>Date Welcome Call Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the opportunity that created this NCSP case for on boarding. Populated by an Apex trigger when the case is created</description>
    <label>NCSP Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (NCSP Opportunity)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Service_line__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Service_line__c</fullName>
    <label>NCSP Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accutrac</fullName>
            </value>
            <value>
                <fullName>CDR</fullName>
            </value>
            <value>
                <fullName>Cloud Archive</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>DB&amp;R</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>DRCMI</fullName>
            </value>
            <value>
                <fullName>eVault</fullName>
                <label>EVault</label>
            </value>
            <value>
                <fullName>Geological Core</fullName>
            </value>
            <value>
                <fullName>Iron Cloud</fullName>
            </value>
            <value>
                <fullName>Live Vault</fullName>
            </value>
            <value>
                <fullName>One Time Shred</fullName>
            </value>
            <value>
                <fullName>RM</fullName>
            </value>
            <value>
                <fullName>RM/Shred</fullName>
            </value>
            <value>
                <fullName>RM Pathology</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>SKP Shell</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Vault Climate Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Onboarding_Images_And_Links__c/Customer_Onboarding_Images_And_Links__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Customer Onboarding Images And Links</label>
</CustomObject>

force-app/main/default/objects/Customer_Profile__c/Customer_Profile__c.object-meta.xml
<CustomObject>
    <description>information specific to the related opportunity for on boarding a customer</description>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Customer Profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Profile__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <label>Billing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Profile__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Customer Name should match the contract not the opportunity account name- exceptions for large partner accounts may include location reference as part  of the name.</description>
    <inlineHelpText>Customer Name should match the contract not the opportunity account name- exceptions for large partner accounts may include location reference as part  of the name.</inlineHelpText>
    <label>Customer Name</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Profile__c/fields/NCSP_Service_Line__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Service_Line__c</fullName>
    <description>Select primary Service Lines offered on this opportunity</description>
    <inlineHelpText>Select primary Service Lines offered on this opportunity. If there are two service lines on this opportunity enter the additional service line in the Second Service Line field.</inlineHelpText>
    <label>NCSP Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deal_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accutrac</fullName>
            </value>
            <value>
                <fullName>Analytics Dashboard</fullName>
            </value>
            <value>
                <fullName>CDR</fullName>
            </value>
            <value>
                <fullName>Cloud Archive</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>DB&amp;R</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>DRCMI</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>EVault</fullName>
            </value>
            <value>
                <fullName>Geological Core</fullName>
            </value>
            <value>
                <fullName>Iron Cloud</fullName>
            </value>
            <value>
                <fullName>Live Vault</fullName>
            </value>
            <value>
                <fullName>One Time Shred</fullName>
            </value>
            <value>
                <fullName>RM</fullName>
            </value>
            <value>
                <fullName>RM Pathology</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
            </value>
            <value>
                <fullName>Vault Climate Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_Name_For_Service_Line__c/Template_Name_For_Service_Line__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the mapping from Service Line to the type of template to use</description>
    <label>Template Name For Service Line</label>
</CustomObject>

force-app/main/default/classes/TestQueryBuilder.cls
@isTest
private class TestQueryBuilder {
    static String closedStatusLabel;
    static String openStatusLabel;
    static Account testAct;
    static Opportunity testOpp;
    static Contact testContact;
    static Contact testContact2;
    static User testUser;
    static User testUser2;
    static Group testGroup;
    static {
        System.runAs(TestingUtils.ADMIN_USER) {
            testAct = TestingUtils.createAccounts(1, true)[0];
            testOpp = TestingUtils.createOpportunity('testOpp', testAct.Id, true);
            testContact = TestingUtils.createContact(testAct.Id, true);
            testContact2 = TestingUtils.createContact(testAct.Id, true);
            testUser = TestingUtil.createUsers(1, true)[0];
            testUser2 = TestingUtil.createUsers(1, true)[0];
        }

        List<Template_Name_For_Service_Line__c> caseLinkTemplate = Test.loadData(Template_Name_For_Service_Line__c.SObjectType,'TemplateNameForServiceLine');
        List<Customer_Onboarding_Images_And_Links__c> coImagesAndLinks = Test.loadData(Customer_Onboarding_Images_And_Links__c.SObjectType,'CustomerOnboardingImagesAndLinks');
    }

    static void setup() {
        List<CaseStatus> closedStatus = [Select Id, MasterLabel From CaseStatus Where IsClosed = true AND MasterLabel='Closed' LIMIT 1];
        System.assertEquals(1, closedStatus.size(), 'We did not get back a CaseStatus that is Closed called "Closed". Change query to look for an existing Closed CaseStatus');
        closedStatusLabel = closedStatus[0].MasterLabel;
        List<CaseStatus> openStatus = [Select Id, MasterLabel From CaseStatus Where IsClosed = false AND MasterLabel='New' LIMIT 1];
        System.assertEquals(1, openStatus.size(), 'We did not get back a CaseStatus that is Open called "New". Change query to look for an existing Open CaseStatus');
        openStatusLabel = openStatus[0].MasterLabel;
    
        List<Group> testGroups = [Select Id from Group where DeveloperName = :WelcomeEmailController.NCSP_QUEUE_NAME and Type = 'Queue' Limit 1];
        
        if( testGroups.isEmpty() )
        {
            testGroup = new Group(Name='NCSP FIFO', DeveloperName = 'NCSP_FIFO_First_in_First_out', Type = 'Queue');
            insert testGroup;
    
            QueueSobject testQueue = new QueueSObject(QueueId = testGroup.Id, SobjectType = 'Case');
            System.runAs(TestingUtils.ADMIN_USER) {
                insert testQueue;
            }
        }
        else{
            testGroup = testGroups[0];
        }
    }
        /*
    *   Case fieldset : (Id), CaseNumber, OwnerId, IsClosed, Date_welcome_call_completed__c, NCSP_Opportunity__c, NCSP_Service_line__c
    *   Contact fieldset : (Id), Email, Name, Phone
    *   Customer_Profile__c fieldset: (Id), Billing_Address__c, Billing_City__c, Billing_Country__c, Customer_Name__c
    */
    static testMethod void testQueryBuilder() {
        setup();
        Set<String> caseFields = new Set<String>{'OwnerId', 'Date_welcome_call_completed__c', 'NCSP_Opportunity__c', 'NCSP_Service_line__c'};
        Set<String> contactFields = new Set<String>{'Email', 'FirstName', 'LastName'};
        Set<String> customerProfileFields = new Set<String>{'Billing_Address__c', 'Billing_City__c', 'Billing_Country__c', 'Customer_Name__c'};

        List<Customer_Profile__c> testCPs = new List<Customer_Profile__c>();
        for (Integer i=0; i<4; i++) 
            testCPs.add(TestingUtils.createCustomerProfile(testOpp.Id, null, false));
        UnitTest.addData(testCPs).tag('Customer Profiles');
        UnitTest.get('Customer Profiles').insertAll();

        List<Contact> testContacts = new List<Contact>();
        for (Integer i=0; i<4; i++) 
            testContacts.add(TestingUtils.createContact(testAct.Id, false));
        UnitTest.addData(testContacts).tag('Contacts');
        UnitTest.get('Contacts').insertAll();

        List<Case> testCases = TestingUtils.createCases(100, testOpp, testContact, false);
        UnitTest.addData(testCases).tag('Cases').property('Customer_Profile__c').assignFrom('Customer Profiles')
                                                .property('ContactId').assignFrom('Contacts');
        UnitTest.get('Cases').insertAll();

        for (String field : caseFields) {
            try {
                UnitTest.get('Cases').getList()[0].get(field);
            } catch (SObjectException e) {
                System.assert(e.getMessage().contains(field), 'We are expecting to get an error message for trying to access field that was not queried for');
            }
        }

        // Give the fields value and then update
        UnitTest.get('Cases').property('OwnerId').assign(testUser.Id).property('Date_welcome_call_completed__c').assign(Date.newInstance(1999, 1, 19))
                             .property('NCSP_Opportunity__c').assign(testOpp.Id).property('NCSP_Service_line__c').assign('Shred');
        UnitTest.get('Contacts').property('Email').assign('test@bw.com').property('FirstName').assign('Homer').property('LastName').assign('Simpson');
        UnitTest.get('Customer Profiles').property('Billing_Address__c').assign('1 main st').property('Billing_City__c').assign('Boston').property('Customer_Name__c').assign('Bart Simpson');
        UnitTest.get('Cases').updateAll();
        UnitTest.get('Contacts').updateAll();
        UnitTest.get('Customer Profiles').updateAll();

        Test.startTest();
            QueryBuilder qb = new QueryBuilder(Case.SObjectType, new List<Id>(Pluck.ids(UnitTest.get('Cases').getList())));
            qb.addFields(caseFields).addFieldsToObject('Contact', contactFields).addFieldsToObject('Customer_Profile__c', customerProfileFields);
            List<Case> casesWithFields = (List<Case>) qb.runQuery();
        Test.stopTest();

        System.assertEquals(UnitTest.getIDs('Cases'), Pluck.ids(casesWithFields), 'We expect to get the same set of Ids from the query builder');
        for (Case actualCase : casesWithFields) {
            for (String field : caseFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).getPropertyValue(field), actualCase.get(field), 'We expect to have no problem accessing the case fields in the field set. We also expect the value to be what we set');
            }
            for (String field : contactFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).traverse('ContactId').getPropertyValue(field), actualCase.getSobject('Contact').get(field), 'We expect to have no problem accessing the contact fields in the field set. We also expect the value to be what we set');
            }
            for (String field : customerProfileFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).traverse('Customer_Profile__c').getPropertyValue(field), actualCase.getSobject('Customer_Profile__r').get(field), 'We expect to have no problem accessing the customer profile fields in the field set. We also expect the value to be what we set');
            }
        }
    }

    /*
    *   Case fieldset : (Id), CaseNumber, OwnerId, IsClosed, Date_welcome_call_completed__c, NCSP_Opportunity__c, NCSP_Service_line__c
    *   Contact fieldset : (Id), Email, Name, Phone
    *   Customer_Profile__c fieldset: (Id), Billing_Address__c, Billing_City__c, Billing_Country__c, Customer_Name__c
    */
    static testMethod void testQueryBuilderUsingFieldPaths() {
        setup();
        List<String> fieldPaths = new List<String>{'OwnerId', 'Date_welcome_call_completed__c', 'NCSP_Opportunity__c', 'NCSP_Service_line__c', 
                                                    'Contact.Email', 'Contact.FirstName', 'Contact.LastName', 
                                                    'Customer_Profile__r.Billing_Address__c', 'Customer_Profile__r.Billing_City__c', 'Customer_Profile__r.Billing_Country__c', 'Customer_Profile__r.Customer_Name__c'};
        Set<String> caseFields = new Set<String>{'OwnerId', 'Date_welcome_call_completed__c', 'NCSP_Opportunity__c', 'NCSP_Service_line__c'};
        Set<String> contactFields = new Set<String>{'Email', 'FirstName', 'LastName'};
        Set<String> customerProfileFields = new Set<String>{'Billing_Address__c', 'Billing_City__c', 'Billing_Country__c', 'Customer_Name__c'};

        List<Customer_Profile__c> testCPs = new List<Customer_Profile__c>();
        for (Integer i=0; i<4; i++) 
            testCPs.add(TestingUtils.createCustomerProfile(testOpp.Id, null, false));
        UnitTest.addData(testCPs).tag('Customer Profiles');
        UnitTest.get('Customer Profiles').insertAll();

        List<Contact> testContacts = new List<Contact>();
        for (Integer i=0; i<4; i++) 
            testContacts.add(TestingUtils.createContact(testAct.Id, false));
        UnitTest.addData(testContacts).tag('Contacts');
        UnitTest.get('Contacts').insertAll();

        List<Case> testCases = TestingUtils.createCases(100, testOpp, testContact, false);
        UnitTest.addData(testCases).tag('Cases').property('Customer_Profile__c').assignFrom('Customer Profiles')
                                                .property('ContactId').assignFrom('Contacts');
        UnitTest.get('Cases').insertAll();

        for (String field : caseFields) {
            try {
                UnitTest.get('Cases').getList()[0].get(field);
            } catch (SObjectException e) {
                System.assert(e.getMessage().contains(field), 'We are expecting to get an error message for trying to access field that was not queried for');
            }
        }

        // Give the fields value and then update
        UnitTest.get('Cases').property('OwnerId').assign(testUser.Id).property('Date_welcome_call_completed__c').assign(Date.newInstance(1999, 1, 19))
                             .property('NCSP_Opportunity__c').assign(testOpp.Id).property('NCSP_Service_line__c').assign('Shred');
        UnitTest.get('Contacts').property('Email').assign('test@bw.com').property('FirstName').assign('Homer').property('LastName').assign('Simpson');
        UnitTest.get('Customer Profiles').property('Billing_Address__c').assign('1 main st').property('Billing_City__c').assign('Boston').property('Customer_Name__c').assign('Bart Simpson');
        UnitTest.get('Cases').updateAll();
        UnitTest.get('Contacts').updateAll();
        UnitTest.get('Customer Profiles').updateAll();

        Test.startTest();
            QueryBuilder qb = new QueryBuilder(Case.SObjectType, new List<Id>(Pluck.ids(UnitTest.get('Cases').getList())));
            qb.addFieldsUsingFieldPaths(fieldPaths);
            List<Case> casesWithFields = (List<Case>) qb.runQuery();
        Test.stopTest();

        System.assertEquals(UnitTest.getIDs('Cases'), Pluck.ids(casesWithFields), 'We expect to get the same set of Ids from the query builder');
        for (Case actualCase : casesWithFields) {
            for (String field : caseFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).getPropertyValue(field), actualCase.get(field), 'We expect to have no problem accessing the case fields in the field set. We also expect the value to be what we set');
            }
            for (String field : contactFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).traverse('ContactId').getPropertyValue(field), actualCase.getSobject('Contact').get(field), 'We expect to have no problem accessing the contact fields in the field set. We also expect the value to be what we set');
            }
            for (String field : customerProfileFields) {
                System.assertEquals(UnitTest.analyze('Cases').selectByID(actualCase.Id).traverse('Customer_Profile__c').getPropertyValue(field), actualCase.getSobject('Customer_Profile__r').get(field), 'We expect to have no problem accessing the customer profile fields in the field set. We also expect the value to be what we set');
            }
        }
    }

    static testMethod void testQueryBuilderWithEmptyIdList() {
        List<String> fieldPaths = new List<String>{'OwnerId', 'Date_welcome_call_completed__c', 'NCSP_Opportunity__c', 'NCSP_Service_line__c', 
                                                    'Contact.Email', 'Contact.FirstName', 'Contact.LastName', 
                                                    'Customer_Profile__r.Billing_Address__c', 'Customer_Profile__r.Billing_City__c', 'Customer_Profile__r.Billing_Country__c', 'Customer_Profile__r.Customer_Name__c'};
        Test.startTest();
            QueryBuilder qb = new QueryBuilder(Case.SObjectType, new List<Id>());
            qb.addFieldsUsingFieldPaths(fieldPaths);
            List<Case> casesWithFields = (List<Case>) qb.runQuery();
        Test.stopTest();

        System.assert(casesWithFields.isEmpty(), 'runQuery should not error and it should return an empty list');
    }

    static Map<Integer, String> alphabet = new Map<Integer, String>{ 0=>'a', 1=>'b', 2=>'c', 3=>'d', 4=>'e',
                                                                     5=>'g', 6=>'h', 7=>'i', 8=>'j', 9=>'k'};

    static testMethod void testQueryBuilderOrderByDesc() {
        List<Contact> testContacts = new List<Contact>();
        Integer i;
        for (i=0; i<10; i++) 
            testContacts.add(TestingUtils.createContact(testAct.Id, false));

        i=0;
        for (Contact c : testContacts) 
            c.LastName = alphabet.get(i++);
        insert testContacts;

        Test.startTest();
            QueryBuilder qb = new QueryBuilder(Contact.SObjectType, new List<Id>(Pluck.ids(testContacts)));
            qb.addField('LastName').orderBy('LastName', false);
            List<Contact> contactsDesc = (List<Contact>) qb.runQuery();
        Test.stopTest();

        for (i=0; i<10; i++)
            System.assertEquals(alphabet.get(9-i), contactsDesc[i].LastName, 'Order should be descending by LastName'); 
    }

    static testMethod void testQueryBuilderOrderByAsc() {
        List<Contact> testContacts = new List<Contact>();
        Integer i;
        for (i=0; i<10; i++) 
            testContacts.add(TestingUtils.createContact(testAct.Id, false));

        i=0;
        for (Contact c : testContacts) 
            c.LastName = alphabet.get(i++);
        insert testContacts;

        Test.startTest();
            QueryBuilder qb = new QueryBuilder(Contact.SObjectType, new List<Id>(Pluck.ids(testContacts)));
            qb.addField('LastName').orderBy('LastName', true);
            List<Contact> contactsAsc = (List<Contact>) qb.runQuery();
        Test.stopTest();

        for (i=0; i<10; i++)
            System.assertEquals(alphabet.get(i), contactsAsc[i].LastName, 'Order should be ascending by LastName'); 
    }

}