force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Initial_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Due_Date__c</fullName>
    <label>Initial Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Cloned__c.field-meta.xml
<CustomField>
    <fullName>Is_Cloned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recurring_Case__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Days__c.field-meta.xml
<CustomField>
    <fullName>SLA_Days__c</fullName>
    <label>SLA (Days)</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_Date__c</fullName>
    <inlineHelpText>This is derived based on created date + SLA Days and takes into consideration the related Customer&apos;s Market Holiday Schedule and time zone.</inlineHelpText>
    <label>SLA Target Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>false</active>
    <businessProcess>Issues and Tasks</businessProcess>
    <description>A request to resolve a service question or concern</description>
    <label>Issue</label>
</RecordType>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Customer_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>IM_Customer_Account_Name__c</fullName>
    <description>Descriptive name of Customer account from external (Billing) system</description>
    <inlineHelpText>Descriptive name of Customer account from external (Billing) system</inlineHelpText>
    <label>Customer Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_District_Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>IM_District_Branch_Id__c</fullName>
    <description>This is a Source (Billing) System District Id
(maybe same as Oracle billing Id if billed out of Oracle)</description>
    <inlineHelpText>This is a Source (Billing) System District Id
(maybe same as Oracle billing Id if billed out of Oracle)</inlineHelpText>
    <label>District/Branch ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Source_System_Code__c.field-meta.xml
<CustomField>
    <fullName>IM_Source_System_Code__c</fullName>
    <description>Used to identify Business Line. Is based on 4 char values provided by NA BI and used to formulate the Inventory System Number</description>
    <label>Source System Code</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SB NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_CustomerAccountsCases.cls
/************************************************************************
** CLIENT
**   Iron Mountain
**
** MODULE
**   Test_CustomerAccountsCases (Apex Class)
**
** PURPOSE
**   To cover 'CustomerAccountsCases' Apex Class. 
**
** NOTES
**   Created test class with dummy data to get code coverage always.
**
** CHANGE LOG
**   [[Version; Date; Author; Project/Case; Description]]
**   v1.0; 2013/05/07; Srinivasa Rao/Randstad; Reviewing code coverage for all components/Case#01367998; Initial release
**
************************************************************************/
@isTest(SeeAllData=true)
private class Test_CustomerAccountsCases {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        ID caseRecordType =  DataFactory.getRecordTypeId('Case','Issue');
        ID accountRecordType =  DataFactory.getRecordTypeId('Account','IMGA Record Type'); 
        
        /*List<RecordType> lstRecordType =[Select r.SobjectType, r.Id From RecordType r where sobjectType ='Account'];        
        if(lstRecordType.size() > 0){            
            accountRecordType = lstRecordType[0].ID;            
        }
        
        List<RecordType> lstRecordType2 =[Select r.SobjectType, r.Id From RecordType r where sobjectType ='Case' and name = 'Issue'];        
        if(lstRecordType2.size() > 0){
            caseRecordType = lstRecordType2[0].ID;
        }*/
        
        Account acc = new Account(Name = 'eotuer'+system.now(),RecordTypeId =accountRecordType, BillingCountry='Canada');
        insert acc;
        
        Contact con = new Contact(AccountId=acc.id , LastName = 'test',Phone = '123456', Email='Testsrinu.mandalapu@randstad.com');
        insert con;
        
        IM_Customer_Account__c custAcc = new IM_Customer_Account__c();
        custAcc.Name = 'Test cust account';
        custAcc.IM_Customer_Account_Name__c = 'Test Account Name';
        custAcc.IM_District_Branch_Id__c = '101';
        custAcc.IM_Source_System_Code__c = 'Test';
        custAcc.IM_Account__c = acc.id;
        custAcc.Source_System__c = 'SB NA';
        custAcc.CurrencyIsoCode='USD';
        insert custAcc; 
        
        // Create 
        Case newCase = new Case();      
        String usrId = UserInfo.getUserId();
        newCase.OwnerId = usrId;
        newCase.RecordTypeId = caseRecordType;
        newCase.AccountId = acc.Id;
        newCase.Customer_ID__c = custAcc.Id;
        newCase.ContactId = con.Id;
        newCase.Origin = 'Email';                     
        newCase.Subject = 'Test';
        newCase.Description = 'Test';
        newCase.Priority = 'Normal';
        newCase.Status = 'New';
        newCase.Is_Cloned__c = true;
        newCase.Recurring_Case__c = false;
        newCase.SLA_Days__c =1;
        DateTime dtInitialTargetDate = DateTime.now();
        newCase.Initial_Due_Date__c = dtInitialTargetDate.date();
        newCase.SLA_Target_Date__c = dtInitialTargetDate;
        insert newCase;
        
        List<Case> lstCases=new List<Case>();
        lstCases.add(newCase);
        //Passing List of Cases to to numberOfCases method to return customer cases.
        CustomerAccountsCases.numberOfCases(lstCases);       
        
    }
}