force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Initial_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Due_Date__c</fullName>
    <label>Initial Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Cloned__c.field-meta.xml
<CustomField>
    <fullName>Is_Cloned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recurring_Case__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recurring_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Frequency__c</fullName>
    <label>Recurring Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every 2 Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Every 6 Months</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Days__c.field-meta.xml
<CustomField>
    <fullName>SLA_Days__c</fullName>
    <label>SLA (Days)</label>
    <precision>17</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>SLA_Target_Date__c</fullName>
    <inlineHelpText>This is derived based on created date + SLA Days and takes into consideration the related Customer&apos;s Market Holiday Schedule and time zone.</inlineHelpText>
    <label>SLA Target Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Customer_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>IM_Customer_Account_Name__c</fullName>
    <description>Descriptive name of Customer account from external (Billing) system</description>
    <inlineHelpText>Descriptive name of Customer account from external (Billing) system</inlineHelpText>
    <label>Customer Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_District_Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>IM_District_Branch_Id__c</fullName>
    <description>This is a Source (Billing) System District Id
(maybe same as Oracle billing Id if billed out of Oracle)</description>
    <inlineHelpText>This is a Source (Billing) System District Id
(maybe same as Oracle billing Id if billed out of Oracle)</inlineHelpText>
    <label>District/Branch ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Source_System_Code__c.field-meta.xml
<CustomField>
    <fullName>IM_Source_System_Code__c</fullName>
    <description>Used to identify Business Line. Is based on 4 char values provided by NA BI and used to formulate the Inventory System Number</description>
    <label>Source System Code</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SB NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testCaseSolutionsController.cls
// Name:testCaseSolutionsController
// Description: This class contains unit tests for validating the behavior of CaseSolutionsController class
// Created By: Vinod Kumar
// Created date : 17 September 2010
// ************************Version Updates********************************************
//
// Updated Date     Updated By      Update Comments 
//  
// 
// ************************************************************************************ 
@isTest
private class testCaseSolutionsController {
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
             
        // Create test data
        
        ID caseRecordType;
        ID accountRecordType;
        List<RecordType> lstRecordType =[Select r.SobjectType, r.Id From RecordType r where sobjectType ='Account' and r.name = 'Standard Account'];
        
        if(lstRecordType.size() > 0){
            
            accountRecordType = lstRecordType[0].ID;
            
        }
        List<RecordType> lstRecordType2 =[Select r.SobjectType, r.Id From RecordType r where sobjectType ='Case' ];
        
        if(lstRecordType2.size() > 0){
            caseRecordType = lstRecordType2[0].ID;
        }
        
        IM_Country__c testCountry = new IM_Country__c(Name='United States');
        insert testCountry;        
        IM_Alternative_Country_Name__c country = new IM_Alternative_Country_Name__c(IM_Country__c = testCountry.Id, Alternative_Name__c='United States');
        insert country;
        
        Account acc = new Account(Name = 'testAccount1',RecordTypeId =accountRecordType,BillingCountry = 'United States');
        insert acc;        
        Contact con = new Contact(AccountId=acc.id ,MailingCountry='United States', firstname='1', LastName = 'test',Phone = '123456', Email='vinod.kumar@metacube.com');
        insert con;
        
        IM_Customer_Account__c custAcc = new IM_Customer_Account__c();
        custAcc.Name = 'Test'+ string.valueOf(Math.random());
        custAcc.IM_Customer_Account_Name__c = 'Test Account Name';
        custAcc.IM_District_Branch_Id__c = '101';
        custAcc.IM_Source_System_Code__c = 'Test';
        custAcc.Source_System__c = 'SB NA';
        custAcc.IM_Account__c = acc.id;
        insert custAcc;   
        // Create 
        Case newCase = new Case();
      
        String usrId = UserInfo.getUserId();
        newCase.OwnerId = usrId;
        newCase.RecordTypeId = caseRecordType;
        newCase.AccountId = acc.Id;
        newCase.Customer_ID__c = custAcc.Id;
        newCase.ContactId = con.Id;
        newCase.Origin = 'Email';        
             
        newCase.Subject = 'Test';
        newCase.Description = 'Test';
        newCase.Priority = 'Normal';
        newCase.Status = 'New';
       // newCase.Is_Cloned__c = true;
       // newCase.Recurring_Case__c = false;
        //newCase.Recurring_Frequency__c = c.Recurring_Frequency__c;
       // newCase.SLA_Days__c =1;
        //DateTime dtInitialTargetDate = DateTime.now();
       // newCase.Initial_Due_Date__c = dtInitialTargetDate.date();
        //newCase.SLA_Target_Date__c = dtInitialTargetDate;
        ApexPages.StandardController std = new ApexPages.StandardController(newCase);
        caseSolutionsController cSolution = new caseSolutionsController(std);
      
                      
    }
}