force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/GSC_Category__c.field-meta.xml
<CustomField>
    <fullName>GSC_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amendment of Customer Details</fullName>
            </value>
            <value>
                <fullName>Billing &amp; Invoice</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Create a new Order</fullName>
            </value>
            <value>
                <fullName>CX Survey</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Online system support</fullName>
            </value>
            <value>
                <fullName>Order Enquiry</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Sales Enquiry</fullName>
            </value>
            <value>
                <fullName>Destruction Records Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/GSC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>GSC_Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>GSC_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add, Amend, Remove Authorised User</fullName>
            </value>
            <value>
                <fullName>Billing Address Update (Mail/ E-Mail)</fullName>
            </value>
            <value>
                <fullName>Site Address Update</fullName>
            </value>
            <value>
                <fullName>Site Contact Name Update</fullName>
            </value>
            <value>
                <fullName>Billing Contact Name Update</fullName>
            </value>
            <value>
                <fullName>Company Name changes</fullName>
            </value>
            <value>
                <fullName>Account Restructure</fullName>
            </value>
            <value>
                <fullName>Research Item</fullName>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
            </value>
            <value>
                <fullName>Close Account/ Termination Request</fullName>
            </value>
            <value>
                <fullName>Billing Dispute</fullName>
            </value>
            <value>
                <fullName>Copy of Invoice, Credit / Debit Memo</fullName>
            </value>
            <value>
                <fullName>Payment / Allocation Enquiry</fullName>
            </value>
            <value>
                <fullName>Invoice /Line Item Questions</fullName>
            </value>
            <value>
                <fullName>Customer Billing Portal Add, Amend or Remove</fullName>
            </value>
            <value>
                <fullName>Invoice Amendment</fullName>
            </value>
            <value>
                <fullName>Add / Remove Customer Suspension</fullName>
            </value>
            <value>
                <fullName>PO Maintenance (Purchase Order Add, Update, Remove)</fullName>
            </value>
            <value>
                <fullName>Bankruptcy/Insolvency</fullName>
            </value>
            <value>
                <fullName>Non Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Add/amend customer rate</fullName>
            </value>
            <value>
                <fullName>Contract Discrepancy</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Response Required</fullName>
            </value>
            <value>
                <fullName>High Level Escalation</fullName>
            </value>
            <value>
                <fullName>Low Level Escalation</fullName>
            </value>
            <value>
                <fullName>Service Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Country__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GSCUpdateAutoFollowUpDatesTest.cls
/********************************************************************************************************
* @Description: This Apex Class is test class for the class "GSCUpdateAutoFollowUpDates"
* @Copyright: Iron Mountain
* @Author: Simranjit Kaur
* @Created on:  04/19/2024(MM/DD/YYYY)
* @MainClass Name: GSCUpdateAutoFollowUpDates
*
* Modification Log: (Date (MM/DD/YYYY) - Name - Change Summary - Reference(#story,#incident))
* 
* 04/19/2024 - Simranjit Kaur - Initial Development - GitLab #22253
* ===================================================
*
********************************************************************************************************/
@isTest
public class GSCUpdateAutoFollowUpDatesTest {
	@istest static void test_method(){
		List<GSCUpdateAutoFollowUpDates.DataWrapper> dw= new List<GSCUpdateAutoFollowUpDates.DataWrapper>();
    	GSCUpdateAutoFollowUpDates.DataWrapper testdata = new GSCUpdateAutoFollowUpDates.DataWrapper();
        //Creating Test Data
        Case testCase= new Case (Subject='Test Case', Description='Test Case', Priority = 'Medium', Origin= 'PER_EMAIL_CS', IME_SC_Country__C= 'Peru');
        Account newAcc = new Account(Name ='Test');
        Contact newCon = new Contact();
    	EmailMessage emsg = new EmailMessage(FromAddress='simranjit.kaur.prtnr@ironmountain.com', FromName= 'Test Name',Subject='Subject test', TextBody='This is test email');
        IM_Customer_Account__c cusAcc = new IM_Customer_Account__c();
        RecordType[] recordTypeList = [select id, name, SobjectType from RecordType where name like 'Global Service Case' and SobjectType = 'Case' Limit 1];
        // Perform test
        Test.startTest();
        insert newAcc;
        newCon.LastName = 'Test Contact';
        newCon.AccountId = newAcc.id;
        insert newCon;
        cusAcc.Name='Test';
        cusAcc.IM_Account__c= newAcc.id;
        insert cusAcc;
        testCase.AccountId =newAcc.id;
        testCase.Customer_ID__c = cusAcc.id;
        testCase.ContactId = newCon.id;
        testCase.RecordTypeId = recordTypeList[0].id;
        testCase.GSC_Category__c = 'Amendment of Customer Details';
        testCase.GSC_Sub_Category__c = 'Add, Amend, Remove Authorised User';
        testCase.Status = 'In Progress';
        insert testCase;
    	emsg.Does_this_Case_Require_More_Information__c = 'Yes';
    	emsg.parentId = testCase.id;
        emsg.status = '3';
        emsg.MessageDate =System.now(); 
        emsg.Incoming = false;
    	insert emsg;
        testdata.recordID=(emsg.Id);
        testdata.country = (testCase.IME_SC_Country__C);
        dw.add(testdata);
        System.debug(testdata);
        GSCUpdateAutoFollowUpDates.calculateAutoFollowUpDates(dw);
        Test.stopTest();
    }
    @istest static void test_method_Metadata(){
		List<GSCUpdateAutoFollowUpDates.DataWrapper> dw= new List<GSCUpdateAutoFollowUpDates.DataWrapper>();
    	GSCUpdateAutoFollowUpDates.DataWrapper testdata = new GSCUpdateAutoFollowUpDates.DataWrapper();
        //Creating Test Data
        Case testCase= new Case (Subject='Test Case', Description='Test Case', Priority = 'Medium', Origin= 'POL_EMAIL_CS', IME_SC_Country__C= 'Poland');
        Account newAcc = new Account(Name ='Test');
        Contact newCon = new Contact();
    	EmailMessage emsg = new EmailMessage(FromAddress='simranjit.kaur.prtnr@ironmountain.com', FromName= 'Test Name',Subject='Subject test', TextBody='This is test email');
        IM_Customer_Account__c cusAcc = new IM_Customer_Account__c();
        RecordType[] recordTypeList = [select id, name, SobjectType from RecordType where name like 'Global Service Case' and SobjectType = 'Case' Limit 1];
        // Perform test
        Test.startTest();
        insert newAcc;
        newCon.LastName = 'Test Contact';
        newCon.AccountId = newAcc.id;
        insert newCon;
        cusAcc.Name='Test';
        cusAcc.IM_Account__c= newAcc.id;
        insert cusAcc;
        testCase.AccountId =newAcc.id;
        testCase.Customer_ID__c = cusAcc.id;
        testCase.ContactId = newCon.id;
        testCase.RecordTypeId = recordTypeList[0].id;
        testCase.GSC_Category__c = 'Amendment of Customer Details';
        testCase.GSC_Sub_Category__c = 'Add, Amend, Remove Authorised User';
        testCase.Status = 'In Progress';
        insert testCase;
    	emsg.Does_this_Case_Require_More_Information__c = 'Yes';
    	emsg.parentId = testCase.id;
        emsg.status = '3';
        emsg.MessageDate =System.now(); 
        emsg.Incoming = false;
    	insert emsg;
        testdata.recordID=(emsg.Id);
        testdata.country = (testCase.IME_SC_Country__C);
        dw.add(testdata);
        System.debug(testdata);
        GSCUpdateAutoFollowUpDates.calculateAutoFollowUpDates(dw);
        Test.stopTest();
    }
}