force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Customer_AccountId__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Customer_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases (Customer Account)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the opportunity that created this NCSP case for on boarding. Populated by an Apex trigger when the case is created</description>
    <label>NCSP Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (NCSP Opportunity)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Commissionable_Window_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Commissionable_Window_Close_Date__c</fullName>
    <description>Value of Commissionable_Window__c Months past First Bill Date (Closedate)
CloseDate formerly First Bill Date, Booked Date is now First Bill Date.</description>
    <formula>DATE(
year(IM_Booked_Date__c)
+ floor((month(IM_Booked_Date__c) + Commissionable_Window__c)/12) + if(and(month(IM_Booked_Date__c)=12,Commissionable_Window__c&gt;=12),-1,0)
,
if( mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ) = 0, 12 , mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ))
,
min( 
day(IM_Booked_Date__c),
case(
max( mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ) , 1),
9,30,
4,30,
6,30,
11,30,
2,28,
31
)
)
)</formula>
    <label>Commissionable Window Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <inlineHelpText>The customer account ID as setup in the billing system. SKP, ARCVMS etc</inlineHelpText>
    <label>Customer ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Bill_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Booked_Date__c</fullName>
    <description>CloseDate formerly First Bill Date, Booked Date is now First Bill Date.</description>
    <formula>if( Sales_Segment__c = &quot;Digital&quot;,  CloseDate ,  IM_Booked_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Bill / Booked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Sold_To__c</fullName>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Up-Sell Oracle Account ID#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IMGA_Name__c.field-meta.xml
<CustomField>
    <fullName>IMGA_Name__c</fullName>
    <description>Returns the IMGA name of the Account that the Opportunity is attached to.</description>
    <formula>Account.IM_IMGA_Indexed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IMGA Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upsell_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>filtered look up to the customer account table for North America</description>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Upsell Customer ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 7) OR 4 OR 5 OR 6</booleanFilter>
        <filterItems>
            <field>IM_Customer_Account__c.Source_System__c</field>
            <operation>equals</operation>
            <value>SB NA, SKP NA, Business Central - ITRenew, Archivum CHE, ARCVMS Europe, ONeils Europe, Other Europe, SKP Europe</value>
        </filterItems>
        <filterItems>
            <field>IM_Customer_Account__c.IM_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>IM_Customer_Account__c.IM_Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>DM SITAD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>Secure IT Asset Disposition</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell/Lift</value>
        </filterItems>
        <infoMessage>This lookup shows Customer IDs related to the Opportunity’s Account Hierarchy.  The Opportunity and Customer ID Accounts must match unless prepaid OTS deal.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2B_CreateOpportunity.cls
public class B2B_CreateOpportunity {
    //"System" is a reserved variable string, so we need to do a string replace after this has been generated. 
    public string systemStringToBeReplaced; 
    public string format;
    public string userId;
 //   public filterObj filter;
    public addDetailsObj addDetails;
 
    
    public B2B_CreateOpportunity(Opportunity OpptyParam) {
      Map<String, Schema.RecordTypeInfo> opportunityRecordTypeIdMap = B2B_IntegrationHelper.getRecordType();
      Id  NARecordTypeID = opportunityRecordTypeIdMap.get('Standard Opportunity').getRecordTypeId();
      Id  EURecordTypeID = opportunityRecordTypeIdMap.get('IME Standard Opportunity').getRecordTypeId();
        if(NARecordTypeID == OpptyParam.RecordTypeId){
        this.systemStringToBeReplaced  = 'AMER'; 
        } else if(EURecordTypeID == OpptyParam.RecordTypeId){
        this.systemStringToBeReplaced  = 'EURO'; 
        }
        this.format= 'application/json';
        this.userID = UserInfo.getUserEmail().substring(0,7);
  //    this.filter = new filterObj(validateJson);
        this.addDetails= new addDetailsObj(OpptyParam);
        
    }
    
 /*    public class filterObj{
        public string modeOfOperation;
        public filterObj(boolean validateJson){
            this.modeOfOperation = (validateJson) ? 'CREATE' : 'UPDATE';
        }
    }
 */   
    public class addDetailsObj{
        public Opportunityobj opportunity;
        public addDetailsObj(Opportunity OpptyParam ){
            this.opportunity= new Opportunityobj(OpptyParam);
        }
    }
    //CloseDate formerly First Bill Date, Booked Date is now First Bill Date
    public class Opportunityobj{
        public String opportunityID; 
        public String name;
        public String type;
        public String stage;
        public List<CustomerDetailsobj> customerDetails;
        public String bookedDate ; 
        public String finalBilledDate; 
        public String firstBilledDate; 
        public String owner;
        public String commissionEndDate; 
        public Opportunityobj(Opportunity OpptyParam){
            this.opportunityID=OpptyParam.Id;
            this.name=OpptyParam.Name;
            this.type=OpptyParam.Type;
            this.stage=OpptyParam.StageName.substring(0,1);
            this.customerDetails= new  List<CustomerDetailsobj>{new CustomerDetailsobj(OpptyParam)};
            Date bookdate = (OpptyParam.IM_Booked_Date__c != null) ? Date.valueOf(OpptyParam.IM_Booked_Date__c) : null;
            if(bookdate != null)
            {
            Datetime bookdatetime = datetime.newInstance( bookdate.year(),bookdate.month(),bookdate.day());
            this.bookedDate=bookdatetime.format('yyyy/MM/dd');
            }
            else {
            this.bookedDate='';
            }
           
       /*     Date finalbilldate=OpptyParam.First_Bill_Booked_Date__c;
            Datetime finalbilldatetime = datetime.newInstance( finalbilldate.year(),
                                                           finalbilldate.month(),
                                                           finalbilldate.day());
            this.finalBilledDate=finalbilldatetime.format('yyyy/MM/dd');  */
            Date firstbilleddate = (OpptyParam.First_Bill_Booked_Date__c != null) ? Date.valueOf(OpptyParam.First_Bill_Booked_Date__c) : null;
            if(firstbilleddate != null){
            Datetime firstbilleddatetime = datetime.newInstance(firstbilleddate.year(),firstbilleddate.month(),firstbilleddate.day());
            this.firstBilledDate=firstbilleddatetime.format('yyyy/MM/dd');
            } else {
            this.firstBilledDate='';
            }
            this.owner=OpptyParam.Owner.Name;
            Date commissiondate = (OpptyParam.Commissionable_Window_Close_Date__c != null) ? Date.valueOf(OpptyParam.Commissionable_Window_Close_Date__c) : null;
            if(commissiondate != null){
            Datetime commissiondatetime = datetime.newInstance(commissiondate.year(),commissiondate.month(),commissiondate.day());
            this.commissionEndDate=commissiondatetime.format('yyyy/MM/dd');
            }
            else{
            this.commissionEndDate=null;
            }
        }
    }
    
    public class CustomerDetailsobj{
        public String customerId;
        public String caseNumber;
        public String IMGA;
        public CustomerDetailsobj(Opportunity OpptyParam){
        Map<String, Schema.RecordTypeInfo> opportunityRecordTypeIdMap = B2B_IntegrationHelper.getRecordType();
        Id  NARecordTypeID = opportunityRecordTypeIdMap.get('Standard Opportunity').getRecordTypeId();
        Id  EURecordTypeID = opportunityRecordTypeIdMap.get('IME Standard Opportunity').getRecordTypeId();
            if(OpptyParam.Type=='New Deal'){
                if(NARecordTypeID ==OpptyParam.RecordTypeId){
                  if(OpptyParam.Cases1__r.size()>0){
                    for(Case ca:OpptyParam.Cases1__r ){
                       this.customerId=ca.Customer_ID__r.Name;
                       this.caseNumber=ca.CaseNumber;
                       this.IMGA=OpptyParam.IMGA_Name__c;
                    }
                  } 
               } else if(EURecordTypeID == OpptyParam.RecordTypeId || test.isRunningTest()){
               this.customerId=OpptyParam.Customer_Account_Number__c;
               this.caseNumber='NA';
               this.IMGA=OpptyParam.IMGA_Name__c;
               }
            } else 
            {
                if(NARecordTypeID ==OpptyParam.RecordTypeId){
                   this.customerId=OpptyParam.Upsell_Customer_ID__r.Name; 
                } 
                else if(EURecordTypeID == OpptyParam.RecordTypeId)
                {
                    this.customerId=OpptyParam.IM_Up_Sell_Sold_To__c; 
                }
            this.caseNumber='NA';
            this.IMGA=OpptyParam.IMGA_Name__c;
            }
        }
    }
 }