force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Cut_Off__c.field-meta.xml
<CustomField>
    <fullName>Cut_Off__c</fullName>
    <label>Cut Off SLA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Order_Team__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rush</fullName>
            </value>
            <value>
                <fullName>12:30</fullName>
            </value>
            <value>
                <fullName>15:00</fullName>
            </value>
            <value>
                <fullName>15:30</fullName>
            </value>
            <value>
                <fullName>16:00</fullName>
            </value>
            <value>
                <fullName>17:00</fullName>
            </value>
            <value>
                <fullName>17:30</fullName>
            </value>
            <value>
                <fullName>18:12</fullName>
            </value>
            <value>
                <fullName>Next day</fullName>
            </value>
            <value>
                <fullName>14:00</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>14:30</fullName>
            </value>
            <value>
                <fullName>16:30</fullName>
            </value>
            <value>
                <fullName>18:00</fullName>
            </value>
            <value>
                <fullName>12:45</fullName>
            </value>
            <value>
                <fullName>13:45</fullName>
            </value>
            <value>
                <fullName>09:00</fullName>
            </value>
            <value>
                <fullName>14:15</fullName>
            </value>
            <value>
                <fullName>15:15</fullName>
            </value>
            <value>
                <fullName>15:45</fullName>
            </value>
            <value>
                <fullName>16:45</fullName>
            </value>
            <value>
                <fullName>14:45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NAS_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>NAS_Order_Number__c</fullName>
    <description>Field for the Order number for the case being handled</description>
    <inlineHelpText>Order Number for Current Case</inlineHelpText>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Team__c.field-meta.xml
<CustomField>
    <fullName>Order_Team__c</fullName>
    <description>Team the work is assigned to. used for skills/routing purposes</description>
    <label>Order Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RM Bangalore</fullName>
            </value>
            <value>
                <fullName>Calgary City</fullName>
            </value>
            <value>
                <fullName>Shared Transition</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Faxback</fullName>
            </value>
            <value>
                <fullName>RM Domestic</fullName>
            </value>
            <value>
                <fullName>HB</fullName>
            </value>
            <value>
                <fullName>Health Information Systems</fullName>
            </value>
            <value>
                <fullName>Honeywell</fullName>
            </value>
            <value>
                <fullName>Medical Immediate</fullName>
            </value>
            <value>
                <fullName>MetLife RM</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
            <value>
                <fullName>Stericycle</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Quebec National Bank</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>TDFIL - Toronto Dominion Bank</fullName>
            </value>
            <value>
                <fullName>British Colombia Government</fullName>
            </value>
            <value>
                <fullName>British Colombia Immediate</fullName>
            </value>
            <value>
                <fullName>British Colombia Vancouver</fullName>
            </value>
            <value>
                <fullName>UKI RM Orders</fullName>
            </value>
            <value>
                <fullName>UKI DM Orders</fullName>
            </value>
            <value>
                <fullName>IND OEC Orders</fullName>
            </value>
            <value>
                <fullName>IND Orders 1 (Supplies/Collection)</fullName>
            </value>
            <value>
                <fullName>IND Orders 2 (Deliveries/complex)</fullName>
            </value>
            <value>
                <fullName>IND Bulk</fullName>
            </value>
            <value>
                <fullName>IND RECALL Orders</fullName>
            </value>
            <value>
                <fullName>IND Orders TOP 20 customers</fullName>
            </value>
            <value>
                <fullName>ANZ SD Orders</fullName>
            </value>
            <value>
                <fullName>ANZ RM Orders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SB NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
public with sharing class CaseTriggerHandlerTest {
    @isTest
    static void CreateSupportCaseTest(){
        List<Account> acct=TestingUtils.createAccounts(1,True);
        Contact cnt = TestingUtils.createContact(acct[0].id, False);
        cnt.Email='Testcnt@gmail.com';
        insert cnt;        
        Id CustomerTypeRId = Schema.SObjectType.IM_Customer_Account__c.getRecordTypeInfosByName().get('NA Customer Account').getRecordTypeId();
        IM_Customer_Account__c ca=new IM_Customer_Account__c();
        ca.Name='Test Customer Account';
        ca.Source_System__c = 'SB NA';
        ca.IM_Account__c = acct[0].Id;
        ca.RecordTypeId = CustomerTypeRId;
        insert ca;
        Id CaseTypeRId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Global Orders').getRecordTypeId();
        Case testCase;        
        list<Case> csList = new List<Case>();
        for (Integer i=0;i<2;i++) {
        Case m = new Case();
        String usrId = UserInfo.getUserId();
        m.OwnerId = usrId;
        m.RecordTypeId = CaseTypeRId;
        m.AccountId = ca.IM_Account__c;
        m.Customer_ID__c = ca.Id;
        m.Origin = 'NAS_EM_Orders';
        m.Cut_Off__c='Rush';
        m.Order_team__C = 'Honeywell';     
        m.Subject = 'Test ' +i;
        m.Description = 'Test' +i;
        m.Priority = 'Normal';
        m.NAS_Order_Number__c = '8990' + i;
        m.Status = 'New';
        m.ContactId= cnt.Id;  

        csList.add(m);
        }       
        Test.startTest();
        CaseTriggerHandler.isRecordInserted = true;
        insert csList;
        UPDATE csList;
        DELETE csList;
    	Test.stopTest();        
    }
}