force-app/main/default/objects/Case/fields/IM_Division__c.field-meta.xml
<CustomField>
    <fullName>IM_Division__c</fullName>
    <inlineHelpText>Users please select the IM Division that corresponds with your default Division. For example, Digital = IM Digital; 
IMAP = Asia Pacific; 
IME = Europe; 
IMLA = Latin America;
IMNA = North America; 
BPM = Business Process Management</inlineHelpText>
    <label>IM Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>IMAP</fullName>
            </value>
            <value>
                <fullName>IME</fullName>
            </value>
            <value>
                <fullName>IMLA</fullName>
            </value>
            <value>
                <fullName>IMNA</fullName>
            </value>
            <value>
                <fullName>BPM</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>IPM</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>DivestCo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IM_Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>IM_Employee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IM employee the suport team should contact to discuss the case</description>
    <inlineHelpText>Enter the name of the IM employee contact reporting the case.</inlineHelpText>
    <label>IM Employee Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access/Visibility/Sharing Rules</fullName>
            </value>
            <value>
                <fullName>Account Manager/Sales Update</fullName>
            </value>
            <value>
                <fullName>Account Set Up</fullName>
            </value>
            <value>
                <fullName>Account Team</fullName>
            </value>
            <value>
                <fullName>Activities/Tasks/Events</fullName>
            </value>
            <value>
                <fullName>Amend Details</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Login</fullName>
            </value>
            <value>
                <fullName>Case Team</fullName>
            </value>
            <value>
                <fullName>Company Mergers &amp; Divestitures</fullName>
            </value>
            <value>
                <fullName>CPQ/Billing</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Create/Deactivate User</fullName>
            </value>
            <value>
                <fullName>Create/Import Records</fullName>
            </value>
            <value>
                <fullName>Customer address amendments</fullName>
            </value>
            <value>
                <fullName>Customer Grouping/IMGA</fullName>
            </value>
            <value>
                <fullName>D&amp;B Hoovers</fullName>
            </value>
            <value>
                <fullName>Delete Records</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Error Message</fullName>
            </value>
            <value>
                <fullName>Forecast/Pipeline</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>IMGA Maintenance</fullName>
                <label>IMGA/Hierarchy Maintenance</label>
            </value>
            <value>
                <fullName>IMGA Maintenance Request</fullName>
            </value>
            <value>
                <fullName>IM Group (IMGA)/ Hierarchy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Knowledge Articles</fullName>
            </value>
            <value>
                <fullName>Lead Convert</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <inlineHelpText>The Relevant Object in Salesforce.com that the issue is related to.</inlineHelpText>
    <label>Related To:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Plans</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>At Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cases</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Customer Account/Client Code</fullName>
            </value>
            <value>
                <fullName>Dashboards</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>DocuSign</fullName>
            </value>
            <value>
                <fullName>Email Templates</fullName>
            </value>
            <value>
                <fullName>Home Page</fullName>
            </value>
            <value>
                <fullName>IMGA</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>M2/M4 Coverages</fullName>
            </value>
            <value>
                <fullName>NA Software Request</fullName>
            </value>
            <value>
                <fullName>Opportunities</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outlook Integration</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Quote2Win</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Schedule A</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Territory Management</fullName>
            </value>
            <value>
                <fullName>Translation Workbench</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Due_Date__c</fullName>
    <inlineHelpText>Release date originally requested by IM Employee Contact or Business Sponsor</inlineHelpText>
    <label>Requested Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>Please paste the URL for the master record here. Additional record URLs should be pasted into the description field below.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <businessProcess>Issues and Tasks</businessProcess>
    <description>A request to modify, adjust, research, or supply customer account information</description>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/TaskTriggerHelper.cls
public class TaskTriggerHelper{
   public static void createCaseWhenNeeded(List<Task> TaskLst){
   
  // List<QueueSobject> lstQueues = [SELECT Id,queue.Name, QueueId FROM QueueSobject WHERE SobjectType = 'Case' and queue.Name = 'IME UK Contact Data Integrity'];
     Group grp = [select Id,Name from Group where Name = 'IME UK Contact Data Integrity' and Type = 'Queue'];
    list<contact> conList = new List<contact>();
      ID recTypeIME = Schema.SObjectType.Case.getRecordTypeInfosByName().get('IM Employees Support Case').getRecordTypeId();
 /*   Map<string,ID> IdCaseQueue = new Map<string,ID>();
   for(QueueSobject queueSobject : lstQueues){
   IdCaseQueue.put(queueSobject.queue.Name, queueSobject.QueueId);
   }*/
   
       List<Case> casesToCreate = new List<Case>();
       system.debug('TaskLst------'+TaskLst);
       for(Task tsk :TaskLst){
       if(tsk.Subject == 'Contact Validated')
       {
      conList = [SELECT Contact.Firstname, Contact.lastname, Email, Phone, MailingStreet, MailingCity, MailingPostalCode, MailingCountry FROM Contact where id=: tsk.whoId];
     string newLine = '\r\n';
     string NoAddress = '';
     string phone = conList[0].Phone;
     string MStreet = conList[0].MailingStreet;
     string MCity = conList[0].MailingCity;
     string MPostal = conList[0].MailingPostalCode;
     string MCountry = conList[0].MailingCountry;   
       system.debug('conList-------'+conlist);
           system.debug('case creation---');
           //system.debug('IdCaseQueue.get(IME UK Contact Data Integrity)---'+IdCaseQueue.get('IME UK Contact Data Integrity'));
               Case caseToAdd = new Case();
               //caseToAdd.OwnerId =  IdCaseQueue.get('IME UK Contact Data Integrity');
               caseToAdd.RecordTypeId = recTypeIME;
               caseToAdd.Related_To__c = 'Contacts';
               caseToAdd.Status = 'New';
               caseToAdd.Issue__c = 'Other';
               caseToAdd.Origin = 'Internal';
               caseToAdd.AccountId = tsk.whatId;
               caseToAdd.IM_Division__c = 'IME';
               caseToAdd.ContactId = tsk.whoId;
               caseToAdd.Priority = 'Medium';
              // caseToAdd.IM_Employee_Contact__c = '';
               //caseToAdd.Requested_Due_Date__c = null;
               caseToAdd.URL__c = '';
               caseToAdd.Subject = 'Validate Contact details in SKP/SecureBase';
              // if(conList[0].Phone == Null || conList[0].MailingStreet == NULL || conList[0].MailingCity == NULL || conList[0].MailingPostalCode == NULL || conList[0].MailingCountry == NULL)
             //  {
               if(conList[0].Phone == Null)
               {
               phone = NoAddress;
               }
               if(conList[0].MailingStreet == Null)
               {
               MStreet = NoAddress;
               }
               if(conList[0].MailingCity == Null)
               {
               MCity = NoAddress;
               }
               if(conList[0].MailingPostalCode == Null)
               {
               MPostal = NoAddress;
               }
               if(conList[0].MailingCountry == Null)
               {
               MCountry = NoAddress;
               }
               
              // }
              // else{
               caseToAdd.Description = 'This Contact has been validated in Salesforce. Please ensure that the following details are up-to-date in SKP/SecureBase'+newLine+''+newLine+'FirstName = '+conList[0].Firstname+''+newLine+'LastName = '+conList[0].Lastname+''+newLine+'Email = '+conList[0].Email+''+newLine+'Phone No. = '+Phone+''+newLine+'Address= '+MStreet+''+newLine+''+MCity+''+newLine+''+MPostal+''+newLine+''+MCountry+'.';
              // }
               system.debug('added to case list---');
               casesToCreate.add(caseToAdd);
               system.debug('caseToAdd.RecordTypeId------'+caseToAdd.RecordTypeId);
               }
           }
       system.debug('inserting cases-');
       system.debug('casesToCreate------'+casesToCreate);
       insert casesToCreate;
      
   }
  }