force-app/main/default/objects/Case/fields/IM_Division__c.field-meta.xml
<CustomField>
    <fullName>IM_Division__c</fullName>
    <inlineHelpText>Users please select the IM Division that corresponds with your default Division. For example, Digital = IM Digital; 
IMAP = Asia Pacific; 
IME = Europe; 
IMLA = Latin America;
IMNA = North America; 
BPM = Business Process Management</inlineHelpText>
    <label>IM Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>IMAP</fullName>
            </value>
            <value>
                <fullName>IME</fullName>
            </value>
            <value>
                <fullName>IMLA</fullName>
            </value>
            <value>
                <fullName>IMNA</fullName>
            </value>
            <value>
                <fullName>BPM</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>IPM</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>DivestCo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IM_Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>IM_Employee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IM employee the suport team should contact to discuss the case</description>
    <inlineHelpText>Enter the name of the IM employee contact reporting the case.</inlineHelpText>
    <label>IM Employee Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Country__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Number_of_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Number_of_Line_Items__c</fullName>
    <label>Number of Line Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IME_SC_Sub_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Non-order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access/Visibility/Sharing Rules</fullName>
            </value>
            <value>
                <fullName>Account Manager/Sales Update</fullName>
            </value>
            <value>
                <fullName>Account Set Up</fullName>
            </value>
            <value>
                <fullName>Account Team</fullName>
            </value>
            <value>
                <fullName>Activities/Tasks/Events</fullName>
            </value>
            <value>
                <fullName>Amend Details</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Login</fullName>
            </value>
            <value>
                <fullName>Case Team</fullName>
            </value>
            <value>
                <fullName>Company Mergers &amp; Divestitures</fullName>
            </value>
            <value>
                <fullName>CPQ/Billing</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Create/Deactivate User</fullName>
            </value>
            <value>
                <fullName>Create/Import Records</fullName>
            </value>
            <value>
                <fullName>Customer address amendments</fullName>
            </value>
            <value>
                <fullName>Customer Grouping/IMGA</fullName>
            </value>
            <value>
                <fullName>D&amp;B Hoovers</fullName>
            </value>
            <value>
                <fullName>Delete Records</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Error Message</fullName>
            </value>
            <value>
                <fullName>Forecast/Pipeline</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>IMGA Maintenance</fullName>
                <label>IMGA/Hierarchy Maintenance</label>
            </value>
            <value>
                <fullName>IMGA Maintenance Request</fullName>
            </value>
            <value>
                <fullName>IM Group (IMGA)/ Hierarchy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Knowledge Articles</fullName>
            </value>
            <value>
                <fullName>Lead Convert</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <inlineHelpText>The Relevant Object in Salesforce.com that the issue is related to.</inlineHelpText>
    <label>Related To:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Plans</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>At Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cases</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Customer Account/Client Code</fullName>
            </value>
            <value>
                <fullName>Dashboards</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>DocuSign</fullName>
            </value>
            <value>
                <fullName>Email Templates</fullName>
            </value>
            <value>
                <fullName>Home Page</fullName>
            </value>
            <value>
                <fullName>IMGA</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>M2/M4 Coverages</fullName>
            </value>
            <value>
                <fullName>NA Software Request</fullName>
            </value>
            <value>
                <fullName>Opportunities</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outlook Integration</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Quote2Win</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Schedule A</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Territory Management</fullName>
            </value>
            <value>
                <fullName>Translation Workbench</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IRM_SC_RaiseOnBoardingCaseTest.cls
/**  
       * Name       : IRM_SC_RaiseCaseInfoTrigger
       * Description   : Test class for IME_SC_RaiseCaseInfoTrigger
       * Copyright      : HCL Technologies
       * Author       : Sejal Shah
       * Modification Log: Created:12-Mar-2012 
**/
@isTest (SeeAllData=true)
private class IRM_SC_RaiseOnBoardingCaseTest
{
    
    //to test IME_SC_RaiseCaseInfoTrigger
    static testMethod void myUnitTest() 
    {
        case sendNotification= new case();
        ID caseRecordTypeOnBoarding =  DataFactory.getRecordTypeId('Case','IM Employees Support Case');
        ID caseRecordType =  DataFactory.getRecordTypeId('Case','IME SC Case');
        User ManagerUser = DataFactory.createUsersLst(1)[0];
        
        /*RecordType caseRecordTypeOnBoarding = [select id from RecordType where name='IM Employees Support Case'];
        RecordType caseRecordType = [select id from RecordType where name='IME SC Case'];    
        Profile sysAdmin = [Select Id, Name from Profile where Name LIKE '%System Admin%' LIMIT 1];
        
        User ManagerUser = new User(FirstName = 'Test', LastName = 'User', ProfileId = sysAdmin.Id, ManagerId = null,
                              LanguageLocaleKey = 'en_US', IsActive = true, TimeZoneSidKey = 'Europe/London',
                              Username = 'TestUser1@support.com', Email = 'testUser@support.com',
                              Alias = 'tUse', EmailEncodingKey = 'ISO-8859-1', CommunityNickname = 'tOwn1',
                              LocaleSidKey = 'en_US', Country='FRANCE');*/
                              
        /*  User Owner1 = new User(FirstName = 'Test', LastName = 'Manager', ProfileId = sysAdmin.Id, 
                              LanguageLocaleKey = 'en_US', IsActive = true, TimeZoneSidKey = 'Europe/London',
                              Username = 'TestOwner@support.com', Email = 'testOwner@support.com',
                              Alias = 'tOwn', EmailEncodingKey = 'ISO-8859-1', CommunityNickname = 'tOwner',
                              LocaleSidKey = 'en_US', Country='Australia'); 
                              */                     
                              
        System.runAs(ManagerUser)
        {
           //Creation of Account
           Account testAccount = new Account(Name='Test Account');
           insert testAccount;
            
           //Creation of Contact
           Contact caseContact = new Contact(FirstName = 'Test', LastName = 'User');
           insert caseContact;
                            
           case testOnBoarding = new case();
           testOnBoarding.Status = 'New';
           testOnBoarding.RecordTypeId = caseRecordTypeOnBoarding;
           testOnBoarding.AccountID = testAccount.id;
           testOnBoarding.ContactID = caseContact.id; 
           testOnBoarding.IM_Employee_Contact__c = ManagerUser.id;       
           testOnBoarding.IME_SC_Request_Type__c = 'Order';
           testOnBoarding.IME_SC_Country__c = 'France';
           testOnBoarding.Subject = 'Test On Boarding 123'; 
           testOnBoarding.Related_To__c = 'Customer Account/Client Code';
           testOnBoarding.Issue__c = 'Account Set Up';
           testOnBoarding.IME_SC_Number_of_Line_Items__c = 1;
            
           testOnBoarding.IM_Division__c = 'IME';
           //insert testCaseHalfDay;
           //testCases.add(testOnBoarding); 
           Test.startTest();
           insert testOnBoarding;
           testOnBoarding.Status = 'Closed';
           update testOnBoarding;
           
           Test.stopTest();   
           }
           
           
           }

}