force-app/main/default/objects/Case/fields/IM_Division__c.field-meta.xml
<CustomField>
    <fullName>IM_Division__c</fullName>
    <inlineHelpText>Users please select the IM Division that corresponds with your default Division. For example, Digital = IM Digital; 
IMAP = Asia Pacific; 
IME = Europe; 
IMLA = Latin America;
IMNA = North America; 
BPM = Business Process Management</inlineHelpText>
    <label>IM Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>IMAP</fullName>
            </value>
            <value>
                <fullName>IME</fullName>
            </value>
            <value>
                <fullName>IMLA</fullName>
            </value>
            <value>
                <fullName>IMNA</fullName>
            </value>
            <value>
                <fullName>BPM</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>IPM</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>DivestCo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IM_Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>IM_Employee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IM employee the suport team should contact to discuss the case</description>
    <inlineHelpText>Enter the name of the IM employee contact reporting the case.</inlineHelpText>
    <label>IM Employee Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Access/Visibility/Sharing Rules</fullName>
            </value>
            <value>
                <fullName>Account Manager/Sales Update</fullName>
            </value>
            <value>
                <fullName>Account Set Up</fullName>
            </value>
            <value>
                <fullName>Account Team</fullName>
            </value>
            <value>
                <fullName>Activities/Tasks/Events</fullName>
            </value>
            <value>
                <fullName>Amend Details</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Can&apos;t Login</fullName>
            </value>
            <value>
                <fullName>Case Team</fullName>
            </value>
            <value>
                <fullName>Company Mergers &amp; Divestitures</fullName>
            </value>
            <value>
                <fullName>CPQ/Billing</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Create/Deactivate User</fullName>
            </value>
            <value>
                <fullName>Create/Import Records</fullName>
            </value>
            <value>
                <fullName>Customer address amendments</fullName>
            </value>
            <value>
                <fullName>Customer Grouping/IMGA</fullName>
            </value>
            <value>
                <fullName>D&amp;B Hoovers</fullName>
            </value>
            <value>
                <fullName>Delete Records</fullName>
            </value>
            <value>
                <fullName>Email Template</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Error Message</fullName>
            </value>
            <value>
                <fullName>Forecast/Pipeline</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>IMGA Maintenance</fullName>
                <label>IMGA/Hierarchy Maintenance</label>
            </value>
            <value>
                <fullName>IMGA Maintenance Request</fullName>
            </value>
            <value>
                <fullName>IM Group (IMGA)/ Hierarchy</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Knowledge Articles</fullName>
            </value>
            <value>
                <fullName>Lead Convert</fullName>
            </value>
            <value>
                <fullName>Request Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <inlineHelpText>The Relevant Object in Salesforce.com that the issue is related to.</inlineHelpText>
    <label>Related To:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Plans</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>At Risk Assessment</fullName>
            </value>
            <value>
                <fullName>Campaigns</fullName>
            </value>
            <value>
                <fullName>Cases</fullName>
            </value>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Customer Account/Client Code</fullName>
            </value>
            <value>
                <fullName>Dashboards</fullName>
            </value>
            <value>
                <fullName>Documents</fullName>
            </value>
            <value>
                <fullName>DocuSign</fullName>
            </value>
            <value>
                <fullName>Email Templates</fullName>
            </value>
            <value>
                <fullName>Home Page</fullName>
            </value>
            <value>
                <fullName>IMGA</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>M2/M4 Coverages</fullName>
            </value>
            <value>
                <fullName>NA Software Request</fullName>
            </value>
            <value>
                <fullName>Opportunities</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outlook Integration</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Quote2Win</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Schedule A</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Territory Management</fullName>
            </value>
            <value>
                <fullName>Translation Workbench</fullName>
            </value>
            <value>
                <fullName>Users</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <inlineHelpText>Please paste the URL for the master record here. Additional record URLs should be pasted into the description field below.</inlineHelpText>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/IME_CreateCase_Lightning.cls
public class IME_CreateCase_Lightning
{    
    public String OppId{get; set;}
    public String Type{get; set;}
    public Opportunity currentRecord{get; set;}
    public List<Case> ExistingCase{get; set;}
    public List<Case> contractCaseList{get; set;}
    public String caseNumber{get;set;}
    public Id casidnew {get;set;}
    
    public IME_CreateCase_Lightning()
    { 
        OppId = ApexPages.currentPage().getParameters().get('oppid');
        Type = ApexPages.currentPage().getParameters().get('Type');
        System.debug('Oppty Id>>>>'+OppId);
        System.debug('Type>>>>'+Type);
    }
    
    
    public void CreateCase(){
        //AccountSetUp button for lightning
        currentRecord = [SELECT Id,StageName,Name,AccountId FROM Opportunity WHERE Id = :OppId];
        if(Type=='AccountSetup'){
            String opportunityId = '%' + OppId + '%';
            if(currentRecord!=null){
                ExistingCase = [Select Id,Subject,accountId From Case where Subject = 'Account Setup' and accountId = : currentRecord.AccountId and url__c like :opportunityId Limit 1];
            }
            if(ExistingCase.size()>0)
            {
                apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'An Account Setup case has already been requested for this opportunity'));
            }
            system.debug('testtesttest');
            if(ExistingCase.size()==0){
                system.debug('Entering CreateCase method for Acc setup');
                String AccSetupCaseId = createAccountSetupCase(oppid);
                List<Case> cs = [Select Id,CaseNumber from Case Where Id =:AccSetupCaseId];
                if(cs.size()>0)
                {
                    system.debug('Successs!!!'+cs);
                    caseNumber = cs[0].CaseNumber;
                    Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'New case#'+caseNumber+System.Label.IME_SC_NEW_CASE)); 
                }
            }
        }
        //Request Contract Button for lightning
        else if(Type=='Request Contract')
        {
            System.debug('Request contract Condition Meet>>>');
            if(currentRecord.StageName =='Lost'||
               currentRecord.StageName =='Dead'||
               currentRecord.StageName =='Postponed'||
               currentRecord.StageName =='0 - Pre-Qualification'||
               currentRecord.StageName =='1 - Qualification'||
               currentRecord.StageName =='2 - Solution Developed'||
               currentRecord.StageName =='3 - Solution Agreed')
            {
                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'A contract request may only be created when the opportunity is in sales stage 4, 5 or 6'));
            }
            else
            {
                String opportunityId = '%' + OppId + '%'; 
                contractCaseList = [Select Id,Subject,accountId From Case where Subject = 'Contract Request' and accountId = : currentRecord.AccountId and url__c like :opportunityId Limit 1];
                System.debug('Contract List>>>'+contractCaseList.size());
                if(contractCaseList.size()>0)
                {
                    Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'A contract request has already been created for this opportunity')); 
                }
                else
                {
                    String contractCase = createContractCase(oppid);
                    System.debug('Contract case Id>>>'+contractCase);
                    List<Case> cs = [Select Id,CaseNumber from Case Where Id =:contractCase];
                    if(cs.size()>0)
                    {
                        caseNumber = cs[0].CaseNumber;
                        Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'New case#'+caseNumber+System.Label.IME_SC_NEW_CASE)); 
                    }
                }
            }
        }
    }
    
    public string createAccountSetupCase(ID op_id){ 
        
        String casidnew;
        Case casnw = new Case();
        RecordType rtyp = new RecordType();
        
        //Querying the Case Record Type
        rtyp = [Select Id From RecordType  Where SobjectType = 'Case' and name = 'IM Employees Support Case']; 
        
        //Querying the Queue
        Group grp = [select Id,Name from Group where Name = 'IME UK Account Setup' and Type = 'Queue']; 
        
        //Getting the List of Users from Current User
        List<User> usrLstnew = [SELECT Name, Id, Division FROM User WHERE Id = : UserInfo.getUserId()];
        
        //Querying the opportunity 
        Opportunity opp = [Select id, Name, account.name,accountid from opportunity where id=: op_id];
        
        //List<Case> casLstnew = new List<Case>();
        //Creating a Case
        for(User usrnew: usrLstnew)
        {
            casnw.OwnerId = UserInfo.getUserId();
            casnw.Related_To__c = 'Customer Account/Client Code';
            casnw.Issue__c  = 'Account Set Up';
            casnw.RecordTypeId = rtyp.id;
            casnw.Status = 'New';
            casnw.Origin = 'Internal';
            casnw.IM_Division__c = usrnew.Division;
            casnw.Priority = 'Medium';
            casnw.Subject = 'Account Setup';
            casnw.Description = 'Please Setup Account for the following Opportunity:'+opp.Name+System.label.IME_ServerURL+opp.id;
            casnw.AccountId = opp.accountid; 
            casnw.IM_Employee_Contact__c = UserInfo.getUserId();
            casnw.URL__c = System.label.IME_ServerURL+opp.id;
            
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            dmo.EmailHeader.TriggerUserEmail = true;
            casnw.setOptions(dmo);
            
        }   
        Insert casnw;
        casidnew = casnw.Id;
        return casidnew; 
    }  
    
    public string createContractCase(ID op_id)
    {         
        Case cas = new Case();
        RecordType rtype = new RecordType();
        
        //Querying the Case Record Type
        rtype = [Select Id From RecordType  Where SobjectType = 'Case' and name = 'IM Employees Support Case']; 
        
        //Querying the Queue
        Group grp = [select Id,Name from Group where Name = 'IME UK Account Setup' and Type = 'Queue']; 
        
        //Getting the List of Users from Current User
        List<User> usrLst = [SELECT Name, Id,Division FROM User WHERE Id = : UserInfo.getUserId()];
        
        //Querying the opportunity 
        Opportunity opp = [Select id, Name, account.name,accountid from opportunity where id=: op_id];
        System.debug('');
        
        //List<Case> casLst = new List<Case>();
        //Creating a Case
        for(User usr: usrLst)
        {
            
            cas.OwnerId = UserInfo.getUserId();
            cas.Related_To__c = 'Contracts';
            cas.Issue__c  = 'Request Contract';
            cas.RecordTypeId = rtype.id;
            cas.Status = 'New';
            cas.Origin = 'Internal';
            cas.IM_Division__c = usr.Division;
            cas.Priority = 'Medium';
            cas.Subject = 'Contract Request';
            cas.Description = 'Please Create Contract for the following Opportunity:'+opp.Name+System.label.IME_ServerURL+opp.id;
            cas.AccountId = opp.accountid; 
            cas.IM_Employee_Contact__c = UserInfo.getUserId();
            cas.URL__c = System.label.IME_ServerURL+opp.id;
            
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            cas.setOptions(dmo);
            
        }   
        Insert cas; 
        casidnew = cas.Id;
        return casidnew;     
    }
    
    public pagereference GoToOppty(){
        pagereference ref = new pagereference('/'+oppid);
        ref.setRedirect(true);
        return ref;
    } 
    
   /* public pagereference GoToCase(){
        pagereference ref = new pagereference('/'+casidnew);
        ref.setRedirect(true);
        return ref;
    } */
}