force-app/main/default/objects/Case/fields/IM_Employee_Contact__c.field-meta.xml
<CustomField>
    <fullName>IM_Employee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IM employee the suport team should contact to discuss the case</description>
    <inlineHelpText>Enter the name of the IM employee contact reporting the case.</inlineHelpText>
    <label>IM Employee Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Category__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Category__c</fullName>
    <description>This field is used to track the category of Service request</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amendment of customer details</fullName>
            </value>
            <value>
                <fullName>Authorised User Requests</fullName>
            </value>
            <value>
                <fullName>Billing &amp; Invoice Issues</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Contract Issues</fullName>
            </value>
            <value>
                <fullName>Create a new Order</fullName>
            </value>
            <value>
                <fullName>Energy (UK)</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Online system support</fullName>
            </value>
            <value>
                <fullName>Order Enquiry</fullName>
            </value>
            <value>
                <fullName>Relationship Management</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Sales Enquiry</fullName>
            </value>
            <value>
                <fullName>Authorized User Requests</fullName>
            </value>
            <value>
                <fullName>Non Conformance (Australia)</fullName>
            </value>
            <value>
                <fullName>Manual Billing (UK)</fullName>
            </value>
            <value>
                <fullName>Billing Maintenance (UK)</fullName>
            </value>
            <value>
                <fullName>Service Order Adjustment (UK)</fullName>
            </value>
            <value>
                <fullName>Standard Billing Scheduled (UK)</fullName>
            </value>
            <value>
                <fullName>Non Standard Billing (UK)</fullName>
            </value>
            <value>
                <fullName>SKP invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>SBE invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>Manual invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>DMS invoices (DEU)</fullName>
            </value>
            <value>
                <fullName>Pricing &amp; Contracts (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Country__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Number_of_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Number_of_Line_Items__c</fullName>
    <label>Number of Line Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IME_SC_Sub_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Non-order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IME_SC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IME_SC_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Closure</fullName>
            </value>
            <value>
                <fullName>Account Transfer</fullName>
            </value>
            <value>
                <fullName>Add/amend customer rate</fullName>
            </value>
            <value>
                <fullName>Additional Boxes Received (Australia Only)</fullName>
            </value>
            <value>
                <fullName>Add New Authorised Users (DP)</fullName>
            </value>
            <value>
                <fullName>Add New Authorised Users (RM/SS)</fullName>
            </value>
            <value>
                <fullName>Add New Authorized Users</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Ad-hoc Reports</fullName>
            </value>
            <value>
                <fullName>ANC – Disputed Debt</fullName>
            </value>
            <value>
                <fullName>ANC - New</fullName>
            </value>
            <value>
                <fullName>ANC - Query</fullName>
            </value>
            <value>
                <fullName>Attachments</fullName>
            </value>
            <value>
                <fullName>Bad Survey Score</fullName>
            </value>
            <value>
                <fullName>Barcode Error (Australia Only)</fullName>
            </value>
            <value>
                <fullName>Blending/grouping of rates</fullName>
            </value>
            <value>
                <fullName>Box/file movements between accounts</fullName>
            </value>
            <value>
                <fullName>Box/file restriction changes</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Cancel an order</fullName>
            </value>
            <value>
                <fullName>Cannot access website</fullName>
            </value>
            <value>
                <fullName>Cannot pay invoice</fullName>
            </value>
            <value>
                <fullName>Change an order</fullName>
            </value>
            <value>
                <fullName>Change transport priority</fullName>
            </value>
            <value>
                <fullName>Checking Authorised users (DP)</fullName>
            </value>
            <value>
                <fullName>Checking Authorised users (RM/SS)</fullName>
            </value>
            <value>
                <fullName>Checking Authorized users</fullName>
            </value>
            <value>
                <fullName>Code Red procedure</fullName>
            </value>
            <value>
                <fullName>Company Name changes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IME_SC_RequestType__c/IME_SC_RequestType__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Automate Request Type based on Category and Sub Category.</description>
    <label>IME SC RequestType</label>
</CustomObject>

force-app/main/default/objects/IME_SC_RequestType__c/fields/IME_SC_Category__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_Category__c</fullName>
    <label>IME_SC_Category</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IME_SC_RequestType__c/fields/IME_SC_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>IME_SC_SubCategory__c</fullName>
    <label>IME_SC_SubCategory</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IRM_SC_UpdateCaseInfoClassTest.cls
/**  
       * Name            : IRM_SC_UpdateCaseInfoClassTest
       * Description     : Test class for IRM_SC_UpdateCaseInfoClass, IRM_SC_SelectRecordType, IRM_SC_AssignCaseToAccManager
       * Copyright       : HCL Technologies
       * Author          : Sejal Shah
       * Modification Log: Created:12-Mar-2012 
**/
@isTest
private class IRM_SC_UpdateCaseInfoClassTest {

    public static List<Case> getListOfCases() {
        ID recTypeId =  DataFactory.getRecordTypeId('Case','IME SC Case');
        List<Case> caseList = new List<Case>();
        
        User currentUser = new User(Id = UserInfo.getUserId());
        System.runAs(currentUser) {
            
            User ManagerUser = DataFactory.createUsersLst(1)[0];
            User manager_Manager = DataFactory.createUsersLst(1)[0];
            manager_Manager.ManagerId = ManagerUser.id;
            update manager_Manager;
            
            User manager = DataFactory.createUsersLst(1)[0];
            User Owner1 = DataFactory.createUsersLst(1)[0];
            Owner1.ManagerId = manager.Id;
            Update owner1;
        }
     Contact caseContact = new Contact(FirstName = 'Dummy1111', LastName = 'Contact1111',Phone='789',email='invalid1111@ironmountain.com');
        insert caseContact;
        
        // Fetch the queue (Group)
        Group queue = [Select g.Name, g.Id From Group g where Name Like 'IME SC %queue%' LIMIT 1];
        
        // Insert Case records
        Case newCase = new Case();
        newCase.Origin = 'AUS_EMAIL_NSW';
        newCase.RecordTypeId = recTypeId;
        newCase.IME_SC_Category__c = 'Order Enquiry';
        newCase.IME_SC_Sub_Category__c = 'Change an order';
        newCase.IME_SC_Request_Type__c = 'Order';
        newCase.IME_SC_Number_of_Line_Items__c = 1;
        newCase.OwnerId = currentUser.id;
        newCase.status='Assigned';
        caseList.add(newCase);
        
        Case newCase1 = new Case();
        newCase1.Origin = 'AUS_EMAIL_NSW';
        newCase1.OwnerId = currentUser.id; 
        newCase1.Status = 'Validated';
        newCase1.IME_SC_Country__c = 'Australia';
        newCase1.RecordTypeId = recTypeId;
        newCase1.IME_SC_Category__c = 'Order Enquiry';
        newCase1.IME_SC_Sub_Category__c = 'Change an order';
        newCase1.IME_SC_Request_Type__c = 'Order';
        newCase1.IME_SC_Number_of_Line_Items__c = 1;
        caseList.add(newCase1);

        Case newCaseQueue = new Case();
        newCaseQueue.Origin = 'AUS_EMAIL_NSW';
        newCaseQueue.OwnerId = queue.Id; // Assign to queue (Group)
        newCaseQueue.Status = 'Validated';
        newCaseQueue.IME_SC_Country__c = 'Australia';
        newCaseQueue.RecordTypeId = recTypeId;
        newCaseQueue.IME_SC_Category__c = 'Order Enquiry';
        newCaseQueue.IME_SC_Sub_Category__c = 'Change an order';
        newCaseQueue.IME_SC_Request_Type__c = 'Order';
        newCaseQueue.IME_SC_Number_of_Line_Items__c = 1;
        caseList.add(newCaseQueue);
        return caseList;
    }

    @isTest
    public static void testPopulateUsers() {
        List<Case> caseList = getListOfCases();
        IRM_SC_UpdateCaseInfoClass updateClass = new IRM_SC_UpdateCaseInfoClass();
        
        Test.startTest();
        updateClass.populateUsers(caseList);
        Test.stopTest();
    }

    @isTest
    public static void testUpdateStatus() {
        List<Case> caseList = getListOfCases();
        Map<Id, Case> oldCaseMap = new Map<Id, Case>();
        
        for (Case c : caseList) {
            oldCaseMap.put(c.Id, c);
        }
        
        IRM_SC_UpdateCaseInfoClass updateClass = new IRM_SC_UpdateCaseInfoClass();
        
        Test.startTest();
        updateClass.updateStatus(caseList, oldCaseMap);
        Test.stopTest();
        
    } 
    // Test queue assignment and status update in the queue
    @isTest
public static void testQueueHandling() {
    List<Case> caseList = getListOfCases();
    insert caseList;
    for (Case c : caseList) {
         if (String.valueOf(c.OwnerId).startsWith('00G')) { // Check if it's assigned to a queue (Group)
            System.assertEquals('Validated', c.Status);
        }
    }
}
    
@isTest
   public static void testPopulateRequestType() {
           IME_SC_RequestType__c requestType = new IME_SC_RequestType__c(
            Name = 'Test Request Type',
            IME_SC_Category__c = 'Hardware',
            IME_SC_SubCategory__c = 'Laptop'
        );
        insert requestType;

        Test.startTest();
        Map<String, IME_SC_RequestType__c> allRequestTypes = new Map<String, IME_SC_RequestType__c>();
        allRequestTypes.put(requestType.Name, requestType);
       
       Contact testContact = new Contact(LastName = 'Test', Email = 'test@example.com');
       insert testContact;

       Case oldCase = new Case(
            Subject = 'Old case',
            IME_SC_Category__c = 'Hardware',
            IME_SC_Sub_Category__c = 'Desktop',
            IME_SC_Request_Type__c = 'Order',
            ContactId = testContact.Id
        );
        insert oldCase;

        // New version of the Case with changed Sub Category
        Case newCase = new Case(
            Id = oldCase.Id,
            Subject = 'Updated Case',
            IME_SC_Category__c = 'Hardware',
            IME_SC_Sub_Category__c = 'Laptop',
            ContactId = testContact.Id
        );

        // Another new Case that has no match in RequestType list
        Case unmatchedCase = new Case(
            Subject = 'Unmatched',
            IME_SC_Category__c = 'Software',
            IME_SC_Sub_Category__c = 'Antivirus',
            ContactId = testContact.Id
        );

        // Case with blank category
        Case blankCase = new Case(
            Subject = 'Blank Category',
            IME_SC_Category__c = '',
            IME_SC_Sub_Category__c = '',
            ContactId = testContact.Id );

        List<Case> newCases = new List<Case>{ newCase, unmatchedCase, blankCase };
        Map<Id, Case> oldMap = new Map<Id, Case>{ oldCase.Id => oldCase };

        new IRM_SC_UpdateCaseInfoClass().populateRequestType(newCases, oldMap);
        Test.stopTest();
 }
    
@isTest
  public  static void testPopulateContactForEmailToCase() {
        
        // Step 1: Create test data for Contacts
        Contact contact1 = new Contact(
            LastName = 'Test1',
            Email = 'test@example.com',
            AccountId = null // assuming no Account related
        );
        insert contact1;
        
        Contact contact2 = new Contact(
            LastName = 'Test2',
            Email = 'test@example.com',
            AccountId = null // assuming no Account related
        );
        insert contact2;
      
      Contact contact3 = new Contact(
            LastName = 'Test3',
            Email = 'unique@example.com',
            AccountId = null // assuming no Account related
        );
        insert contact3;

      User user1 = new User(
            Alias = 'test1',
            Email = 't79879@example.com',
            ProfileId = UserInfo.getProfileId(), // Use a valid profile ID
            Username = '2025060998@example.com',
            LastName = 'Use791',
            FirstName = 'Test1',
            CompanyName = 'Test Company',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
          country='India'
        );
        insert user1;

        User user2 = new User(
            Alias = 'te26',
            Email = 'kjhjkh56r@example.com',
            ProfileId = UserInfo.getProfileId(), // Use a valid profile ID
            Username = 'T15430t798@example.comk',
            LastName = 'U68',
            FirstName = 'Te982',
            CompanyName = 'Test Company',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            country='India'
        );
        insert user2;

       // Step 2: Create test Case records with SuppliedEmail and no ContactId
        Case case1 = new Case(
            Subject = 'Case 1',
            SuppliedEmail = 'test@example.com',
            ContactId = null, 
            IM_Employee_Contact__c = user1.Id 
        );
        
        Case case2 = new Case(
            Subject = 'Case 2',
            SuppliedEmail = 'unique@example.com',
            ContactId = null, 
            IM_Employee_Contact__c = user2.Id 
        );
        
        Case case3 = new Case(
            Subject = 'Case 3 with no match',
            SuppliedEmail = 'no_match@example.com',
            ContactId = null, 
            IM_Employee_Contact__c = user2.Id 
        );

        List<Case> newCaseList = new List<Case>{ case1, case2, case3 };
        insert newCaseList;
 
        Test.startTest();
        new IRM_SC_UpdateCaseInfoClass().populateContactForEmailToCase(newCaseList);
        update newCaseList;
        Test.stopTest();
  } 
 }