force-app/main/default/objects/Case/fields/NAS_CECOMM_Event_Status__c.field-meta.xml
<CustomField>
    <fullName>NAS_CECOMM_Event_Status__c</fullName>
    <label>NAS CECOMM Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Notified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NAS_External_ID__c.field-meta.xml
<CustomField>
    <fullName>NAS_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>NAS External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/NAS_Root_Cause_Reason__c.field-meta.xml
<CustomField>
    <fullName>NAS_Root_Cause_Reason__c</fullName>
    <description>List of Root causes that is dependent on the type of case.</description>
    <inlineHelpText>What was the root cause of this case?</inlineHelpText>
    <label>Root Cause Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account Balance Inquiry</fullName>
            </value>
            <value>
                <fullName>Account Closure/Negotiation of Pricing-Contract (CLAS)</fullName>
            </value>
            <value>
                <fullName>Account Closure Request</fullName>
            </value>
            <value>
                <fullName>Account Consolidation</fullName>
            </value>
            <value>
                <fullName>Account Maintenance</fullName>
            </value>
            <value>
                <fullName>Account Maintenance (CallBacks/Hold Code/Record Code/Special Instr.)</fullName>
            </value>
            <value>
                <fullName>Account Parameters</fullName>
            </value>
            <value>
                <fullName>Account Reconciliation</fullName>
            </value>
            <value>
                <fullName>Account Setup</fullName>
            </value>
            <value>
                <fullName>Accounts Payable Inquiry</fullName>
            </value>
            <value>
                <fullName>Accutrac Info Requested</fullName>
            </value>
            <value>
                <fullName>Acquisition Related (dispute related to pricing/contract, service, billing, payments)</fullName>
            </value>
            <value>
                <fullName>Add/Remove Customer ID to IMC Company Profile</fullName>
            </value>
            <value>
                <fullName>Additional Containers</fullName>
            </value>
            <value>
                <fullName>Address Incorrect</fullName>
            </value>
            <value>
                <fullName>Address Report</fullName>
            </value>
            <value>
                <fullName>Adjusted Balance Due (invoice update to reflect adjustment balance due)</fullName>
            </value>
            <value>
                <fullName>Admin Fee Rollback</fullName>
            </value>
            <value>
                <fullName>Agents Processing Error</fullName>
            </value>
            <value>
                <fullName>Aging Report</fullName>
            </value>
            <value>
                <fullName>Annual Pricing Increase Concern</fullName>
            </value>
            <value>
                <fullName>App Issues</fullName>
            </value>
            <value>
                <fullName>AR Reimbursements</fullName>
            </value>
            <value>
                <fullName>Payment Research/Reconcilation (payment reapp, billing/receivable reconciliation)</fullName>
                <label>AR Related</label>
            </value>
            <value>
                <fullName>Authorization Update</fullName>
            </value>
            <value>
                <fullName>SKP User Report</fullName>
                <label>Authorized User Report</label>
            </value>
            <value>
                <fullName>Autopay</fullName>
            </value>
            <value>
                <fullName>Autopay Add/Update/Inquiry</fullName>
            </value>
            <value>
                <fullName>Autopay Failure (expire/update needed)</fullName>
            </value>
            <value>
                <fullName>BBB Complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NAS_UpdateSKPEventQueueableTest.cls
@isTest
public with sharing class NAS_UpdateSKPEventQueueableTest {
	/**
     * @name setupTestData
     * @description Sets up Test data needed for all test cases in this Test Class.
    **/
	@testSetup 
    public static void setupTestData()
    {
        NAS_TestDataFactory.setupTestData(1);
    	NAS_TestDataFactory.createCase(1, NAS_Constants.NAS_GENERAL_SUPPORT_CASE_RECORDTYPE, 
                                       true, NAS_Constants.PICKLIST_STATUS_CASE_NEW);
		List<Case> caseList = [SELECT Id FROM Case];
        for(Case c : caseList)
       	{
       		c.Type = 'Account Maintenance';
    		c.NAS_Root_Cause_Reason__c = 'Account Maintenance (CallBacks/Hold Code/Record Code/Special Instr.)';
    		c.NAS_External_Id__c = 'CECOMM5006C00000486GMQAY';
    		c.NAS_CECOMM_Event_Status__c = NAS_Constants.CECOMM_CREATED;
       	}
       	update caseList;
		/*for(Case c : caseList)
       	{
       		c.Status = NAS_Constants.CASE_STATUS_CLOSED;
       	}*/
       	//update caseList; 
    }

    @isTest
    public static void testNAS_UpdateSKPEventQueueable() {
    	Test.setMock(HttpCalloutMock.class, new NAS_TestMockHttpResponseGenerator());
		List<Case> caseList = [SELECT Id FROM Case];
        Test.startTest();
		NAS_UpdateSKPEventQueueable.updateEvent();
        Test.stopTest();
    }
}