force-app/main/default/objects/Case/fields/NCSP_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the opportunity that created this NCSP case for on boarding. Populated by an Apex trigger when the case is created</description>
    <label>NCSP Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (NCSP Opportunity)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>IM_Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accelerated Information Consolidation</fullName>
            </value>
            <value>
                <fullName>Backup Care</fullName>
            </value>
            <value>
                <fullName>Cubic Ft</fullName>
            </value>
            <value>
                <fullName>Customer Billable Audits</fullName>
            </value>
            <value>
                <fullName>Data Restoration</fullName>
            </value>
            <value>
                <fullName>DC - Cross Connect</fullName>
            </value>
            <value>
                <fullName>DC - Data Domain Services</fullName>
            </value>
            <value>
                <fullName>DC - Helping Hands</fullName>
            </value>
            <value>
                <fullName>DC - Installation / Implementation</fullName>
            </value>
            <value>
                <fullName>DC - Managed Internet</fullName>
            </value>
            <value>
                <fullName>DC - Network Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Other MRC Service</fullName>
            </value>
            <value>
                <fullName>DC - Rent</fullName>
            </value>
            <value>
                <fullName>DC - Retail Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Special Projects</fullName>
            </value>
            <value>
                <fullName>Destruction</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>EV Up-Sell  - Gigs</fullName>
            </value>
            <value>
                <fullName>EV Up Sell - Seats</fullName>
            </value>
            <value>
                <fullName>IMAGES</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – Carton Level</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – File Level</fullName>
            </value>
            <value>
                <fullName>Inventory Pack/Purge/Shift</fullName>
            </value>
            <value>
                <fullName>Inventory Relocation</fullName>
            </value>
            <value>
                <fullName>Labour Hours</fullName>
            </value>
            <value>
                <fullName>Library Move</fullName>
            </value>
            <value>
                <fullName>Linear Ft</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Shred - Add Bins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Detail__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Detail__c</fullName>
    <inlineHelpText>Enter a detailed description of the Department, Division, or Location that the deal was sold to.  There is no need to put a Contact Name, Company Name, or Revenue Type as this has already been provided in the other fields on the Opportunity.</inlineHelpText>
    <label>Up-Sell Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Quantity__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Quantity__c</fullName>
    <inlineHelpText>Please enter a Quantity.  
Examples:  for cubic ft and linear ft, enter the total amount involved in the up-sell.  For up-sells on rotations (Wkly-Daily, Mthly-Wkly, etc), enter 1.</inlineHelpText>
    <label>Up-Sell Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Sold_To__c</fullName>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Up-Sell Oracle Account ID#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NCSP_Status__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Status__c</fullName>
    <description>tracks the progress of the NCSP case related to this opportunity. The value is updated by an APEX trigger on the Case.</description>
    <label>NCSP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent to NCSP</fullName>
                <color>#0B6FCE</color>
                <label>Sent to NCSP</label>
            </value>
            <value>
                <fullName>Contract Approved</fullName>
                <color>#E27001</color>
                <label>Contract Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#A845DC</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Service Scheduled</fullName>
                <color>#419249</color>
                <label>Service Scheduled</label>
            </value>
            <value>
                <fullName>Service Completed</fullName>
                <color>#CC9933</color>
                <label>Service Completed</label>
            </value>
            <value>
                <fullName>Custom Setup</fullName>
                <color>#33CCFF</color>
                <label>Custom Setup</label>
            </value>
            <value>
                <fullName>Local Market Setup</fullName>
            </value>
            <value>
                <fullName>Special Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Completed__c.field-meta.xml
<CustomField>
    <fullName>Order_Completed__c</fullName>
    <label>Order Completed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upsell_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>filtered look up to the customer account table for North America</description>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Upsell Customer ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 7) OR 4 OR 5 OR 6</booleanFilter>
        <filterItems>
            <field>IM_Customer_Account__c.Source_System__c</field>
            <operation>equals</operation>
            <value>SB NA, SKP NA, Business Central - ITRenew, Archivum CHE, ARCVMS Europe, ONeils Europe, Other Europe, SKP Europe</value>
        </filterItems>
        <filterItems>
            <field>IM_Customer_Account__c.IM_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>IM_Customer_Account__c.IM_Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>DM SITAD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>Secure IT Asset Disposition</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell/Lift</value>
        </filterItems>
        <infoMessage>This lookup shows Customer IDs related to the Opportunity’s Account Hierarchy.  The Opportunity and Customer ID Accounts must match unless prepaid OTS deal.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NCSPSellLiftWizardCtrExt.cls
public with sharing class NCSPSellLiftWizardCtrExt
{
    public static final String OPP_ID_PARAM = 'Id';
    public static final String CONFIRMATION_OPP_STATUS = 'Escalated';

    public Opportunity opp {get; private set;}
    public Boolean showMainFrame {get; private set;}

    public List<PageReference> prev;
    public ApexPages.StandardController ctr;

    {
        showMainFrame = false;
    }

    public NCSPSellLiftWizardCtrExt(ApexPages.StandardController controller)
    {
        ctr = controller;
        Id paramOppId = ApexPages.currentPage().getParameters().get(OPP_ID_PARAM);


        if( null == paramOppId )
        {
            Apexpages.addMessage( new Apexpages.Message ( Apexpages.Severity.Error , 'Opportunity Not Found') );
            return;
        }

        List<Opportunity> opptyLst = [Select Id, Order_Completed__c, Upsell_Customer_ID__c, IM_Unit_of_Measure__c, IM_Up_Sell_Quantity__c,
                                             IM_Up_Sell_Detail__c,IM_Up_Sell_Sold_To__c, (SELECT Id FROM Cases1__r WHERE RecordTypeId IN :NCSPWizardCtrl.recordCreatedInWizard LIMIT 1)
                                        from Opportunity where id = :paramOppId];

        if( opptyLst.isEmpty() )
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter a valid Opportunity into the URL argument ' +  OPP_ID_PARAM));
            return;
        }

        opp = opptyLst[0];

        // TODO : move to a label
         if( opp.Cases1__r != null && opp.Cases1__r.size() > 0 ){
            Apexpages.addMessage( new Apexpages.Message ( Apexpages.Severity.Warning , 'This Opportunity already has a NCSP Case attached to it ') );
            return;
        }

        prev = new List<PageReference>();

        showMainFrame = true;

    }

    public PageReference orderCompletedNextPage()
    {
        prev.add(ApexPages.currentPage());
   /*     if( opp.Order_Completed__c == 'Yes')
        {
            return Page.NCSPUpsellDetails;
        }
        else
        {
            return goToVisitStepOneOfWizard();
        } */
       return goToVisitStepOneOfWizard();
    }

    public PageReference goToVisitStepOneOfWizard()
    {
        PageReference stepOneOfWizard = Page.NCSPWizard_Step1;
        stepOneOfWizard.getParameters().put(NCSPWizardCtrl.OPP_ID_PARAM, opp.Id);
        try{
            update opp;
            return stepOneOfWizard;
        }
        catch(System.DmlException e)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() );
            ApexPages.addMessage(myMsg);
            return null;
        }
        
    }

    public PageReference upsellDetailsNextPage()
    {
        prev.add(ApexPages.currentPage());
        return Page.NCSPUpsellDetailsConfirmation;
    }

    public PageReference confirmationNext()
    {
        try
        {
           opp.NCSP_Status__c = CONFIRMATION_OPP_STATUS;           
            update opp;
            return ctr.save();
        }
        catch(System.DmlException e)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage() );
            ApexPages.addMessage(myMsg);
            return null;
        }
    }

    public PageReference previous()
    {
        if(prev.size() == 0)
            return ctr.cancel();
        return prev.remove(prev.size()-1);
    }
}