force-app/main/default/objects/Deal_Review__c/Deal_Review__c.object-meta.xml
<CustomObject>
    <label>Deal Review</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Deal Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Reviews</relationshipLabel>
    <relationshipName>Deal_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Dedicated_Capital__c.field-meta.xml
<CustomField>
    <fullName>Dedicated_Capital__c</fullName>
    <label>Dedicated Capital</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Floor_Revenue_Realization_Percent__c.field-meta.xml
<CustomField>
    <fullName>Floor_Revenue_Realization_Percent__c</fullName>
    <label>% Floor Revenue Realization</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/No_PA_Model_Required__c.field-meta.xml
<CustomField>
    <fullName>No_PA_Model_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No PA Model Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Reason_for_No_PA_Model__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_No_PA_Model__c</fullName>
    <label>Reason for No PA Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing rates with no rate changes</fullName>
            </value>
            <value>
                <fullName>Pre-approved or list rates</fullName>
            </value>
            <value>
                <fullName>Other pricing model or tool</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Previously approved Framework pricing</fullName>
            </value>
            <value>
                <fullName>Smart Quoting Model</fullName>
            </value>
            <value>
                <fullName>Affiliating to existing approved pricing</fullName>
                <isActive>false</isActive>
                <label>Affiliating to existing approved pricing</label>
            </value>
            <value>
                <fullName>Leveraging pre-approved pricing proposal</fullName>
                <isActive>false</isActive>
                <label>Leveraging pre-approved pricing proposal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Schedule_A__c.field-meta.xml
<CustomField>
    <fullName>Schedule_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PA Model Upload</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <filterItems>
            <field>Schedule_A__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Schedule_A__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_A__c</referenceTo>
    <relationshipLabel>Deal Reviews</relationshipLabel>
    <relationshipName>Deal_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Submitter_Comments__c.field-meta.xml
<CustomField>
    <fullName>Submitter_Comments__c</fullName>
    <label>Submitter Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Hidden field used to create warning flags on the deal review page when the user is not following the proper process</description>
    <label>Utility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_A__c/Schedule_A__c.object-meta.xml
<CustomObject>
    <description>Schedule A Custom Object</description>
    <label>PA Model Approval</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Schedule A</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Model Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_A__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account associated with the Schedule A</description>
    <inlineHelpText>Account associated with the Schedule A</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedule A List</relationshipLabel>
    <relationshipName>Schedule_A</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_A__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Schedule A Reference</description>
    <inlineHelpText>Schedule A Reference</inlineHelpText>
    <label>Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Schedule A</description>
    <inlineHelpText>Status of the Schedule A</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pricing Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/Schedule_A_Quote_Item__c.object-meta.xml
<CustomObject>
    <description>Schedule A Quote item pricing per Schedule A</description>
    <label>Schedule A Quote Item</label>
    <nameField>
        <displayFormat>SAL-{00000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule A Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Cashview_Cost_Line__c.field-meta.xml
<CustomField>
    <fullName>Cashview_Cost_Line__c</fullName>
    <label>Cashview Cost (Line)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Cashview_Margin_Line__c.field-meta.xml
<CustomField>
    <fullName>Cashview_Margin_Line__c</fullName>
    <formula>Line_Revenue__c - (Cashview_Cost_Line__c *  XML_Proposed_Volume__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashview Margin $ (Line)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Current_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Price__c</fullName>
    <label>Current Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Current_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Volume__c</fullName>
    <label>Current Volume</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Floor_Price__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price__c</fullName>
    <description>Gets stamped with the original price as uploaded in the PA Model - needed to enable the rep to price down to but not below the approved Floor Price</description>
    <label>Floor Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Line_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Line_Revenue__c</fullName>
    <description>Adding field to hold the revenue of PA Model Lines</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF ( Product__r.ProductCode = &apos;Next Day Delivery&apos;,
SUBSTITUTE( Product__r.ProductCode,  &quot;Next Day&quot;,  &quot;Standard&quot; ),
IF(Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 2&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 3&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 4&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone Metro&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone Metro NY&apos; , SUBSTITUTE( Product__r.ProductCode,  &quot;Next Day&quot;,  &quot;Standard Delivery&quot; ),Product__r.ProductCode))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <description>Product Number</description>
    <inlineHelpText>Product Bill Code</inlineHelpText>
    <label>Product Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Proposed_Price__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Price__c</fullName>
    <description>Proposed Price of Item</description>
    <inlineHelpText>Proposed Price of Item</inlineHelpText>
    <label>Proposed Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Schedule_A__c.field-meta.xml
<CustomField>
    <fullName>Schedule_A__c</fullName>
    <description>Parent Schedule A</description>
    <inlineHelpText>Schedule A Quote Item</inlineHelpText>
    <label>Schedule A</label>
    <referenceTo>Schedule_A__c</referenceTo>
    <relationshipLabel>Schedule A Quote Items</relationshipLabel>
    <relationshipName>Schedule_A_Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <label>Target Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <formula>TEXT(Product__r.IM_Unit_of_Measure__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/XML_Proposed_Volume__c.field-meta.xml
<CustomField>
    <fullName>XML_Proposed_Volume__c</fullName>
    <label>Proposed Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProjectQuickActionControllerTest.cls
@isTest
public class ProjectQuickActionControllerTest {
    @isTest
    static void testGetScheduleAQuoteItems_ReturnsItems() {
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        // Create Schedule_A__c record
        Schedule_A__c scheduleA = new Schedule_A__c(Status__c = 'Active',Account__c = acc.Id,Reference__c = 'Test' );
        insert scheduleA;

        // Create Deal_Review__c record and link to Schedule_A__c
        Deal_Review__c dealReview = new Deal_Review__c( Utility__c = False, Schedule_A__c = scheduleA.Id);
        insert dealReview;

        // Create pse__Proj__c record and link to Deal_Review__c
        pse__Proj__c project = new pse__Proj__c(Name = 'Test Project',pse__Account__c = acc.Id, Service_State__c = 'Test State', Deal_Review__c = dealReview.Id);
        insert project;

        // Create Schedule_A_Quote_Item__c record with XML_Proposed_Volume__c > 0 and correct Schedule_A__c
        Schedule_A_Quote_Item__c quoteItem = new Schedule_A_Quote_Item__c(
          //  Name = 'Test Quote Item',
           // Product_Name__c = 'Product 1',
            Product_Number__c = 'PN001',
          //  Unit_of_Measure__c = 'Unit',
            Cashview_Cost_Line__c = 100,
          //  Cashview_Margin_Line__c = 25,
            XML_Proposed_Volume__c = 10,
            Proposed_Price__c = 500,
            Target_Price__c = 550,
            Floor_Price__c = 450,
            Current_Price__c = 470,
            Current_Volume__c = 5,
            Line_Revenue__c = 2500,
            Schedule_A__c = scheduleA.Id
        );
        insert quoteItem;

        Test.startTest();
        List<Schedule_A_Quote_Item__c> result = ProjectQuickActionController.getScheduleAQuoteItems(project.Id);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Should return one quote item');
        System.assertEquals(quoteItem.Id, result[0].Id, 'Returned quote item Id should match inserted quote item');
    }

    @isTest
    static void testGetScheduleAQuoteItems_NullConditions() {
		Account acc = new Account(Name = 'Test Account');
        insert acc;
		
        // Create pse__Proj__c record without Deal_Review__c
        pse__Proj__c projectWithoutDealReview = new pse__Proj__c(pse__Account__c = acc.Id,Name = 'No Deal Review', Service_State__c = 'Test State');
        insert projectWithoutDealReview;

        Test.startTest();
        List<Schedule_A_Quote_Item__c> result1 = ProjectQuickActionController.getScheduleAQuoteItems(projectWithoutDealReview.Id);
        Test.stopTest();

        System.assertEquals(0, result1.size(), 'Should return empty list if Deal_Review__c is null');

      /*  // Create Deal_Review__c without Schedule_A__c
        Deal_Review__c dealReview = new Deal_Review__c(No_PA_Model_Required__c = true,Reason_for_No_PA_Model__c = 'Other',Dedicated_Capital__c = 100.0000,Floor_Revenue_Realization_Percent__c = 105,Submitter_Comments__c = 'Test Comments', Utility__c = False, Status__c = 'Approved');
        insert dealReview;

        pse__Proj__c projectWithoutScheduleA = new pse__Proj__c(pse__Account__c = acc.Id,Name = 'Project No ScheduleA', Service_State__c = 'Test State', Deal_Review__c = dealReview.Id);
        insert projectWithoutScheduleA;

        Test.startTest();
        List<Schedule_A_Quote_Item__c> result2 = ProjectQuickActionController.getScheduleAQuoteItems(projectWithoutScheduleA.Id);
        Test.stopTest();

        System.assertEquals(0, result2.size(), 'Should return empty list if Schedule_A__c is null in Deal_Review__c'); */
    } 
}