force-app/main/default/objects/Deal_Review__c/Deal_Review__c.object-meta.xml
<CustomObject>
    <label>Deal Review</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Deal Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Review__c/fields/Schedule_A__c.field-meta.xml
<CustomField>
    <fullName>Schedule_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PA Model Upload</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <filterItems>
            <field>Schedule_A__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Schedule_A__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Schedule_A__c</referenceTo>
    <relationshipLabel>Deal Reviews</relationshipLabel>
    <relationshipName>Deal_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule_A__c/Schedule_A__c.object-meta.xml
<CustomObject>
    <description>Schedule A Custom Object</description>
    <label>PA Model Approval</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Schedule A</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Model Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_A_Quote_Item__c/Schedule_A_Quote_Item__c.object-meta.xml
<CustomObject>
    <description>Schedule A Quote item pricing per Schedule A</description>
    <label>Schedule A Quote Item</label>
    <nameField>
        <displayFormat>SAL-{00000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule A Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Cashview_Cost_Line__c.field-meta.xml
<CustomField>
    <fullName>Cashview_Cost_Line__c</fullName>
    <label>Cashview Cost (Line)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Cashview_Margin_Line__c.field-meta.xml
<CustomField>
    <fullName>Cashview_Margin_Line__c</fullName>
    <formula>Line_Revenue__c - (Cashview_Cost_Line__c *  XML_Proposed_Volume__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cashview Margin $ (Line)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Current_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Price__c</fullName>
    <label>Current Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Current_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Volume__c</fullName>
    <label>Current Volume</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Floor_Price__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price__c</fullName>
    <description>Gets stamped with the original price as uploaded in the PA Model - needed to enable the rep to price down to but not below the approved Floor Price</description>
    <label>Floor Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Line_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Line_Revenue__c</fullName>
    <description>Adding field to hold the revenue of PA Model Lines</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF ( Product__r.ProductCode = &apos;Next Day Delivery&apos;,
SUBSTITUTE( Product__r.ProductCode,  &quot;Next Day&quot;,  &quot;Standard&quot; ),
IF(Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 2&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 3&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone 4&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone Metro&apos; || Product__r.ProductCode = &apos;Trip Charge, Next Day, Zone Metro NY&apos; , SUBSTITUTE( Product__r.ProductCode,  &quot;Next Day&quot;,  &quot;Standard Delivery&quot; ),Product__r.ProductCode))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Product_Number__c.field-meta.xml
<CustomField>
    <fullName>Product_Number__c</fullName>
    <description>Product Number</description>
    <inlineHelpText>Product Bill Code</inlineHelpText>
    <label>Product Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Proposed_Price__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Price__c</fullName>
    <description>Proposed Price of Item</description>
    <inlineHelpText>Proposed Price of Item</inlineHelpText>
    <label>Proposed Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Schedule_A__c.field-meta.xml
<CustomField>
    <fullName>Schedule_A__c</fullName>
    <description>Parent Schedule A</description>
    <inlineHelpText>Schedule A Quote Item</inlineHelpText>
    <label>Schedule A</label>
    <referenceTo>Schedule_A__c</referenceTo>
    <relationshipLabel>Schedule A Quote Items</relationshipLabel>
    <relationshipName>Schedule_A_Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <label>Target Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <formula>TEXT(Product__r.IM_Unit_of_Measure__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_A_Quote_Item__c/fields/XML_Proposed_Volume__c.field-meta.xml
<CustomField>
    <fullName>XML_Proposed_Volume__c</fullName>
    <label>Proposed Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProjectQuickActionController.cls
public class ProjectQuickActionController {
    @AuraEnabled(cacheable=true)
    public static List<Schedule_A_Quote_Item__c> getScheduleAQuoteItems(Id projectId) {
        pse__Proj__c project = [
            SELECT Deal_Review__c, Deal_Review__r.Schedule_A__c
            FROM pse__Proj__c
            WHERE Id = :projectId
            LIMIT 1
        ];
        if (
            project.Deal_Review__c != null &&
            project.Deal_Review__r.Schedule_A__c != null
        ) {
            return [
                SELECT Id,Name,Product_Name__c, Product_Number__c, Unit_of_Measure__c,
                    Cashview_Cost_Line__c, Cashview_Margin_Line__c, XML_Proposed_Volume__c,
                    Proposed_Price__c, Target_Price__c, Floor_Price__c,
                    Current_Price__c, Current_Volume__c, Line_Revenue__c
                FROM Schedule_A_Quote_Item__c
                WHERE XML_Proposed_Volume__c > 0 AND Schedule_A__c = :project.Deal_Review__r.Schedule_A__c
            ];
        }
        return new List<Schedule_A_Quote_Item__c>();
    }
}