force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>The channel through which the work-item is received</description>
    <inlineHelpText>The channel through which the work-item is received</inlineHelpText>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LiveChatTranscript</fullName>
                <label>Chat</label>
            </value>
            <value>
                <fullName>MessagingSession</fullName>
                <label>Messaging</label>
            </value>
            <value>
                <fullName>VoiceCall</fullName>
                <label>Voice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransferTest.cls
/**
 * 	Class:				TransferTest
 * 
 * 	Author:				Amit Gayal (NeuraFlash LLC)
 * 
 * 	Purpose:			It's the test class for Transfer apex class.
 * 
 * 	Requirements:		IMSLB-30
 * 
 * 	Change History:		
 * 
 * 	Developer					Date				Description
 * ----------------------------------------------------------------------------------------
 */

@isTest
private class TransferTest {

    @isTest
    static void getTransferSObjectInstanceTest(){
        Test.startTest();
        new Transfer();
        new Transfer(new Transfer__c());
        Transfer__c instance = new Transfer().getTransferSObjectInstance();
        Test.stopTest();
        Assert.areEqual('LiveChatTranscript',instance.Channel__c);
    }
}