force-app/main/default/objects/SCVGo_Log__c/SCVGo_Log__c.object-meta.xml
<CustomObject>
    <description>This object will be used for logging any action in SCV Go package.</description>
    <label>SCV Go Log</label>
    <nameField>
        <displayFormat>SGL-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCV Go Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCVGo_Log__c/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <label>Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SCVGo_Log__c/fields/User_Information__c.field-meta.xml
<CustomField>
    <fullName>User_Information__c</fullName>
    <label>User Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SG_Log__e/SG_Log__e.object-meta.xml
<CustomObject>
    <description>This platform event should be fired if you wish to log an action for SCV Go package.</description>
    <label>SCV Go Log Event</label>
    <pluralLabel>SCV Go Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/SG_Log__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Exception Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SG_Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SG_Log__e/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SG_Log__e/fields/User_Information__c.field-meta.xml
<CustomField>
    <fullName>User_Information__c</fullName>
    <label>User Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCVGoEventHandler.cls
/**
 * 	Class:				SCVGoEventHandler
 * 
 * 	Author:				Amit Gayal (NeuraFlash LLC)
 * 
 * 	Purpose:			This class creats record for SCV Go Log object.
 * 
 * 	Requirements:		IMSLB-30
 * 
 * 	Change History:		
 * 
 * 	Developer					Date				Description
 * ----------------------------------------------------------------------------------------
 */
public with sharing class SCVGoEventHandler {

    public static void createLogs(List<SG_Log__e> exceptionsList){
        Schema.DescribeSObjectResult objSchema = SCVGo_Log__c.sObjectType.getDescribe();
        
        if(objSchema.isCreateable()) {
            Map<String, Schema.SObjectField> schemaMap = Schema.SObjectType.SCVGo_Log__c.fields.getMap();
            List<SCVGo_Log__c> logs = new List<SCVGo_Log__c>();
            
            for (SG_Log__e event : exceptionsList) {
                SCVGo_Log__c logRecord = new SCVGo_Log__c();
                    if(schemaMap.get('Message__c').getDescribe().isCreateable()) {
                        logRecord.put('Message__c' , event.Message__c);
                    }
                    if(schemaMap.get('Trace__c').getDescribe().isCreateable()) {
                        logRecord.put('Trace__c' , event.Trace__c);
                    }
                    if(schemaMap.get('Data__c').getDescribe().isCreateable()) {
                        logRecord.put('Data__c' , event.Data__c);
                    }
                    if(schemaMap.get('Type__c').getDescribe().isCreateable()) {
                        logRecord.put('Type__c' , event.Type__c);
                    }
                    if(schemaMap.get('User_Information__c').getDescribe().isCreateable()) {
                        logRecord.put('User_Information__c' , event.User_Information__c);
                    }
                    logs.add(logRecord);
            }
            if(!logs.isEmpty()){
                insert logs;
            }
        }
        
    }
}