force-app/main/default/objects/Case/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <businessProcess>Issues and Tasks</businessProcess>
    <description>A request to modify, adjust, research, or supply customer account information</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/SendTaskDeleteEmail__c/SendTaskDeleteEmail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to send emails when AgedTaskDeletion batch Executes</description>
    <label>SendTaskDeleteEmail</label>
</CustomObject>

force-app/main/default/objects/SendTaskDeleteEmail__c/fields/AgeingDays__c.field-meta.xml
<CustomField>
    <fullName>AgeingDays__c</fullName>
    <description>contains the ageing days which is used in agedTaskDeletion Batch class</description>
    <label>AgeingDays</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SendTaskDeleteEmail__c/fields/Emails__c.field-meta.xml
<CustomField>
    <fullName>Emails__c</fullName>
    <label>Emails</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_AgedTaskDeletion.cls
@isTest
public class Test_AgedTaskDeletion {
    @isTest static void testDeleteTaskmethod(){
      /*  SendTaskDeleteEmail__c setting=new SendTaskDeleteEmail__c();
         setting.Name = 'Emaillist';
         setting.Emails__C = 'praneelkumar.patalay.prtnr@ironmountain.com';
        setting.AgeingDays__c = -1;
         insert setting;        
        Task tsk = new Task();
        tsk.status = 'Not Started';
        tsk.Due_Date__c=null;
        tsk.Subject='TestClass1';
        tsk.Description='Call Next day';
        insert tsk; 
        Test.startTest();
        AgedTaskDeletion atd = new AgedTaskDeletion();
        database.executeBatch(atd);
        Test.stopTest();*/
        //task error method
        SendTaskDeleteEmail__c cs=new SendTaskDeleteEmail__c();
         cs.Name = 'Emaillist';
         cs.Emails__C = 'praneelkumar.patalay.prtnr@ironmountain.com';
        cs.AgeingDays__c = -1;
         insert cs;
        Id CaseTypeRId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Case Type').getRecordTypeId();
        Task t = new Task();
        t.status = 'Not Started';
        t.Due_Date__c=null;
        t.Subject='TestClass1';
        t.Description='Call Next day';
        t.Priority='High';
        t.RecordtypeId= CaseTypeRId;
        t.IsRecurrence=false;
        insert t;
        user u=[select id,Name from user where profile.Name='IM_Sales' and isActive=true limit 1];
        system.runAs(u){
        Test.startTest();
        AgedTaskDeletion atds = new AgedTaskDeletion();
        database.executeBatch(atds);
        Test.stopTest();
    }
    
    }
}