force-app/main/default/objects/Case/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <businessProcess>Issues and Tasks</businessProcess>
    <description>A request to modify, adjust, research, or supply customer account information</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Case_Action__c/Case_Action__c.object-meta.xml
<CustomObject>
    <label>Case Action</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Case Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Action__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case #</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Actions</relationshipLabel>
    <relationshipName>Case_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Field_History__c/Case_Field_History__c.object-meta.xml
<CustomObject>
    <description>Track when case fields have been updated from the customer form</description>
    <label>Case Field History</label>
    <nameField>
        <displayFormat>CFH-{0000000}</displayFormat>
        <label>Case Field History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Field_History__c/fields/Case_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Case_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Field Histories (Case)</relationshipLabel>
    <relationshipName>Case_Field_Histories1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CX_Survey_Details__c/CX_Survey_Details__c.object-meta.xml
<CustomObject>
    <description>This object is used for Qualtrics to write CX data about respondents to.</description>
    <label>CX Survey Details</label>
    <nameField>
        <displayFormat>CXS-{0000}</displayFormat>
        <label>CX Survey Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CX Survey Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CX_Survey_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CX Survey Details</relationshipLabel>
    <relationshipName>CX_Survey_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestCasesAndRelatedUtil.cls
public class TestCasesAndRelatedUtil {
public static void insertEM( list<Case> lstcases ) {
    integer i=0;
    list<EmailMessage> newEmailMsgs=new list<EmailMessage>();
    for(case c : lstcases){
       
       
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = True;
        email.ToAddress= 'test@xyz.org';
        email.Subject = 'Test email'+(++i);
        email.HtmlBody = 'Test email body'+(++i);
        email.ParentId = c.id;
        email.RelatedToId = c.Id;
        newEmailMsgs.add(email);
    }
     insert newEmailMsgs;          
    }
    public static void insertAttAndContent(list<Case> lstcases) {
    integer i=0;
    list<Attachment> atslst=new list<Attachment>();
    list<ContentVersion> cvs=new list<ContentVersion>();
    list<ContentDocumentLink> cds=new list<ContentDocumentLink>();
    integer count=0;
    for(Case c: lstcases){
        ContentVersion cv = new ContentVersion();
            cv.Title = 'Some document'+(++i);
            cv.PathOnClient = 'some document.txt';
            cv.VersionData = Blob.valueOf('Unit Test content version...');
         cvs.add(cv);
        
    }
    insert cvs;
    for(ContentVersion cv: cvs){
    
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        system.debug('conDocId++++++++++++:'+conDocId);
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = conDocId;
        cdl.LinkedEntityId = lstcases.get(count).id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        cds.add(cdl);
        Attachment att = new Attachment();
        att.ParentId   = lstcases.get(count).id;
        Blob bodyBlob  = Blob.valueOf('Unit Test Attachment Body');
        att.body       = bodyBlob;
        att.Name       = 'attachHarry'+(++i);
        atslst.add(att);
        ++count;
    }
    
    insert cds;
    insert atslst;
}
    public static void insertRelatedRecords(list<Case> lstcases){
        list<Case_Field_History__c> cfhlst=new list<Case_Field_History__c>();
     // Commented as part of 12563
     /* list<SFDC_Bug__c> sblst=new list<SFDC_Bug__c>();
        list<Sales_Tool_Project_Case__c> stpclst=new list<Sales_Tool_Project_Case__c>(); */
        list<CX_Survey_Details__c> csdlst=new list<CX_Survey_Details__c>();
        list<Case_Action__c> calst=new list<Case_Action__c>();
        for(case c: lstcases){
          Case_Field_History__c cfh = new Case_Field_History__c();
            cfh.Case_Lookup__c=c.id;
            cfhlst.add(cfh);
         // Commented as part of 12563
         /* SFDC_Bug__c sb=new SFDC_Bug__c();
            sb.Case__c=c.id;
            sb.Problem__c='Tester class';
            sblst.add(sb); 
            Sales_Tool_Project_Case__c stpc=new Sales_Tool_Project_Case__c();
            stpc.Parent__c=c.id;
            stpclst.add(stpc); */
            CX_Survey_Details__c csd=new CX_Survey_Details__c();
            csd.Case__c=c.id;
            csdlst.add(csd);
            Case_Action__c ca=new Case_Action__c();
            ca.Case__c=c.id;
            calst.add(ca);
            
        }
        insert cfhlst;
     // Commented as part of 12563
     /* insert sblst;
        insert stpclst; */
        insert csdlst;
        insert calst;
           
    }
    public static void insertTask(list<Case> lstcases){
        integer i=0;
    list<Task> tsklst=new list<Task>();
        for(Case c : lstcases){
        Task t         = new Task();
        t.subject      = 'Creating Attachments'+(++i);
        t.Description  = 'The Good, The Bad & The Ugly'+(++i);
        t.Priority     = 'High';
        t.WhatId = c.id;
        tsklst.add(t);
        }
        insert tsklst;
    }
}