force-app/main/default/objects/Case/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>false</active>
    <businessProcess>Issues and Tasks</businessProcess>
    <description>A request to modify, adjust, research, or supply customer account information</description>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/Case_Action__c/Case_Action__c.object-meta.xml
<CustomObject>
    <label>Case Action</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Case Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Action__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case #</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Actions</relationshipLabel>
    <relationshipName>Case_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Resubmitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Deletion_Config__c/Case_Deletion_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Days and recordtypes are configured from this list custom settings and used in DeleteCasesAndRelatedLst batch class</description>
    <label>Case Deletion config</label>
</CustomObject>

force-app/main/default/objects/Case_Deletion_Config__c/fields/Record_types__c.field-meta.xml
<CustomField>
    <fullName>Record_types__c</fullName>
    <label>Record types</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case_Field_History__c/Case_Field_History__c.object-meta.xml
<CustomObject>
    <description>Track when case fields have been updated from the customer form</description>
    <label>Case Field History</label>
    <nameField>
        <displayFormat>CFH-{0000000}</displayFormat>
        <label>Case Field History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Field Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Field_History__c/fields/Case_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Case_Lookup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Field Histories (Case)</relationshipLabel>
    <relationshipName>Case_Field_Histories1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CX_Survey_Details__c/CX_Survey_Details__c.object-meta.xml
<CustomObject>
    <description>This object is used for Qualtrics to write CX data about respondents to.</description>
    <label>CX Survey Details</label>
    <nameField>
        <displayFormat>CXS-{0000}</displayFormat>
        <label>CX Survey Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CX Survey Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CX_Survey_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CX Survey Details</relationshipLabel>
    <relationshipName>CX_Survey_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteCasesAndRelatedLst.cls
/*Modified by: Simranjit Kaur
 *          User Story: #8796 Enable Rolling 7 Day Orders case record type archiving automation
 * 	        Record Type: Global Orders 
 * */
public class DeleteCasesAndRelatedLst implements Database.Batchable<sObject>, Database.Stateful {
public set<Id> caseIds=new set<Id>();
public Date AgeingDate;
public string[] RecordTypeNames;
public string status;
public Case_Deletion_Config__c config;
    
public Case_Deletion_Config__c configGlobal;
public Date AgeingDateGlobal;
public string[] RecordTypeNamesGlobal;
public string statusGlobal;
//Map<string, Case_Deletion_Config__c> config;
Public integer recordsProcessed=0;
    public DeleteCasesAndRelatedLst(){
        //config = Case_Deletion_Config__c.getAll();
        config=new Case_Deletion_Config__c();
        configGlobal=new Case_Deletion_Config__c();
        
        config=Case_Deletion_Config__c.getValues('Greater than 30days');
        AgeingDate=Date.today().addDays(-Integer.valueOf(config.Ageing_Days__c));
        RecordTypeNames=config.Record_types__c.split(',');
        system.debug('Record Type Names are:'+RecordTypeNames);
        status=config.Status__c;
        
        configGlobal=Case_Deletion_Config__c.getValues('Greater than 7days');
        RecordTypeNamesGlobal=configGlobal.Record_types__c.split(',');
        //system.debug('Record Type Names are:'+RecordTypeNamesGlobal);
        //system.debug('Ageing Days are:'+configGlobal.Ageing_Days__c);
        AgeingDateGlobal=Date.today().addDays(-Integer.valueOf(configGlobal.Ageing_Days__c));
        statusGlobal=configGlobal.Status__c;
        
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        //system.debug('++++aging+++++:'+AgeingDate);
        //system.debug('++++++Recordtype Name+++:'+RecordTypeNames);
        //system.debug('++++Status++++'+status);
        //Updated the query for record type Global Orders
        string query='select Id, RecordTypeId,RecordType.Name,createdDate from Case where (createdDate<=:AgeingDate and status=:status and RecordType.Name IN:RecordTypeNames) OR (createdDate<=:AgeingDateGlobal and status=:statusGlobal and RecordType.Name IN:RecordTypeNamesGlobal)';    
            
        //string query='select Id, RecordTypeId,RecordType.Name,createdDate from Case where createdDate<=:AgeingDate and status=:status and RecordType.Name=\'IME SC Case\'' ;
        //string query='select Id, RecordTypeId,RecordType.Name,createdDate from Case where createdDate<=:AgeingDate and status=:status and RecordType.Name IN (\'IME SC Case\',\'NAS General Support Case\')' ;
        return Database.getQueryLocator(query); 
    }
    public void execute(Database.BatchableContext bc, List<Case> CaseLst){
        Set<Id> idsToGetContentLinkIds = new Set<Id>();
        for(Case c : CaseLst){
            system.debug('+++record type name in execute method+++'+c.RecordType.Name);
            caseIds.add(c.Id);
            idsToGetContentLinkIds.add(c.Id);
        }
        if(caseIds.size()>0 && !caseIds.isEmpty()){
            system.debug('the size of the records are:'+caseIds.size());
            Set<Id> contDocumentId = new set<Id>();
            Set<Id> emailMsgIds = new Set<Id>();
            
            try{    
                for(EmailMessage emailId : [SELECT Id FROM EmailMessage WHERE RelatedToId IN :caseIds]){
                    idsToGetContentLinkIds.add(emailId.Id);
                }
               for(ContentDocumentLink cid : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN : idsToGetContentLinkIds]){
                   // system.debug('cLinkid '+cid);
                    contDocumentId.add(cid.ContentDocumentId);
                }
           		//system.debug('idsToGetContentLinkIds '+idsToGetContentLinkIds);
                //system.debug('contDocumentId'+contDocumentId);
      DELETE [SELECT Id FROM ContentDocument where id IN :contDocumentId];
       	DELETE [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId IN : caseIds];
       
        DELETE [SELECT Id, ParentId, Name FROM Attachment where ParentId IN: caseIds];
        DELETE [SELECT Id, WhoId, WhatId, Subject FROM Task where WhatId IN: caseIds];
        DELETE [SELECT Id FROM EmailMessage WHERE RelatedToId IN :caseIds];
        DELETE [Select id from Case_Field_History__c WHERE Case_Lookup__c IN:caseIds];
      
        //Commented as part of #12563
     /* DELETE [Select Id from SFDC_Bug__c WHERE Case__c IN:caseIds];
        DELETE [Select Id from Sales_Tool_Project_Case__c WHERE Parent__c IN:caseIds]; */
        DELETE [SELECT Id FROM SurveyInvitation where Case__c IN:caseIds];
        DELETE [SELECT Id FROM CX_Survey_Details__c WHERE Case__c IN:caseIds];
        DELETE [SELECT Id FROM Case_Action__c WHERE Case__c IN:caseIds];
        DELETE [SELECT Id FROM Case where id IN: caseIds];
            } catch(exception e){
                system.debug('exception occurs in the catch method:'+e.getMessage());
            }
            /*try{
        DELETE [SELECT Id FROM Case where id IN: caseIds];
            }catch(exception e){
              Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
               String[] toAddresses=new String[]{};
	           toAddresses=config.Send_Email_To__c.split(',');
               mail.setToAddresses(toAddresses);
               mail.setSenderDisplayName('Apex error message');
               mail.setSubject('Error from Org : ' + UserInfo.getOrganizationName());
               mail.setPlainTextBody(e.getMessage());
               Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
            } */
        }
    }
    public void finish(Database.BatchableContext bc){
        
    }
}