force-app/main/default/objects/Dashboard_Quick_Links__c/Dashboard_Quick_Links__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Dashboard Quick Links</label>
</CustomObject>

force-app/main/default/objects/Dashboard_Quick_Links__c/fields/Current_Dashboard_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Dashboard_ID__c</fullName>
    <label>Current Dashboard ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dashboard_Quick_Links__c/fields/Link_Label__c.field-meta.xml
<CustomField>
    <fullName>Link_Label__c</fullName>
    <label>Link Label</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DashboardQuickLinkController.cls
public class DashboardQuickLinkController
{
    public String currentDashboardId { get; set; }
    public List<DashboardLink> dashboardLinks { get; set; }

    public void generateDBLinks()
    {
        dashboardLinks = new List<DashboardLink>();
        for( Dashboard_Quick_Links__c quickLink : [ SELECT Id, Link_Label__c, Dashboard_ID__c, Current_Dashboard_ID__c FROM Dashboard_Quick_Links__c ORDER BY Name ASC ] )
        {
            if( quickLink.Current_Dashboard_ID__c.equals(currentDashboardId ))
            {
                dashboardLinks.add( new DashboardLink( quickLink.Link_Label__c, quickLink.Dashboard_ID__c ) );
            }
        }
    }

    public DashboardQuickLinkController() { }

    public class DashboardLink
    {
        public String dashboardName { get; set; }
        public String dashboardId { get; set; }

        public DashboardLink( String dbNameIn, String dbIdIn )
        {
            this.dashboardName = dbNameIn;
            this.dashboardId = dbIdIn;
        }
    }
}