force-app/main/default/objects/QTB_Documents_Send_Lookup_Queue__c/QTB_Documents_Send_Lookup_Queue__c.object-meta.xml
<CustomObject>
    <label>Documents Send Lookup Queue</label>
    <nameField>
        <displayFormat>DOC-{000000}</displayFormat>
        <label>Documents Send Lookup Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Send Lookup Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Documents_Send_Lookup_Queue__c/fields/QTB_Status__c.field-meta.xml
<CustomField>
    <fullName>QTB_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>Sent to Bill Trust</fullName>
                <isActive>false</isActive>
                <label>Sent to Bill Trust</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QTB_DocumentSendLookupTriggerHelper.cls
/*****************************************************************************************************
* Class 		: QTB_DocumentSendLookupTriggerHelper
* Test Class    : QTB_DocumentSendLookupTriggerHelper_Test
* Author		: Virtusa
* Purpose		: This is a helper class for all business logic related to I object
* Requirement	: Gitlab US #20933 -- Stop schedule call and run the logic based on need
* Change History: 01/22/2024
* Developer        Date           Description
* -------------------------------------------------------------------------------------------
*  Virtusa       01/22/2024      Gitlab US #20933 -- Stop schedule call and run the logic based on need
*******************************************************************************************************/
public class QTB_DocumentSendLookupTriggerHelper {
    private static final String CLASSNAME = QTB_DocumentSendLookupTriggerHelper.class.getName();
    
    /***********************************************************************************************************
* Method 	 : process
* Parameters : List<blng__Invoice__c>, Map<Id,blng__Invoice__c>, System.TriggerOperation
* Requirement: this method handle the logic related to Document send lookup object
* Author     : Virtusa
* Description: Generic method to handle all operations on the invoice Records
**************************************************************************************************************/
    public static void process(List<QTB_Documents_Send_Lookup_Queue__c> newItems, Map<Id, QTB_Documents_Send_Lookup_Queue__c> oldMap, System.TriggerOperation operationType)
    {
        try{        
            Set<Id> documentSendLookupQueueIdSet = new Set<Id>();
            if(newItems !=null && !newItems.isEmpty()){
                for(QTB_Documents_Send_Lookup_Queue__c documentSendLookupObj : newItems){
                    if(oldMap !=null && !oldMap.isEmpty() && oldMap.get(documentSendLookupObj.Id).QTB_Status__c != documentSendLookupObj.QTB_Status__c &&
                       documentSendLookupObj.QTB_Status__c == 'Delete')
                    {
                        documentSendLookupQueueIdSet.add(documentSendLookupObj.Id);
                    }
                }
            }            
            if(!documentSendLookupQueueIdSet.isEmpty()){
                Database.executeBatch(new QTB_BatchableDocumentSendDelete());
                //Database.executeBatch(new QTB_BatchableDocumentSendDelete(documentSendLookupQueueIdSet));
            }
        }
        catch(Exception e){
            QTB_ExceptionLogger.enable();
            QTB_ExceptionLogger.createLog(e.getLineNumber(),e.getStackTraceString(),e.getMessage(),e.getTypeName(),CLASSNAME);
        }
    }
}