force-app/main/default/objects/Account/recordTypes/IMGA_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>IMGA_Record_Type</fullName>
    <active>true</active>
    <description>IMGA - Book of Business</description>
    <label>IMGA Record Type</label>
</RecordType>

force-app/main/default/objects/BoB_Coverage__c/BoB_Coverage__c.object-meta.xml
<CustomObject>
    <description>Object used to manage both Primary or Local Book of Business Coverage</description>
    <label>M2 BoB Coverage</label>
    <nameField>
        <label>BoB Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M2 BoB Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoB_Coverage__c/fields/CY_YTD_Amount__c.field-meta.xml
<CustomField>
    <fullName>CY_YTD_Amount__c</fullName>
    <formula>/*CY_Jan__c  +  CY_Feb__c  +  CY_Mar__c  +  CY_Apr__c +  CY_May__c +  CY_Jun__c  + CY_Jul__c +  CY_Aug__c + CY_Sep__c +  CY_Oct__c +  CY_Nov__c +  CY_Dec__c*/ null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CY YTD Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BoB_Coverage__c/fields/M2_YTD_Quota_Summary__c.field-meta.xml
<CustomField>
    <fullName>M2_YTD_Quota_Summary__c</fullName>
    <formula>Num_Of_Quota_Periods__c *  PY_Monthly_Average_M2_Quota__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>M2 YTD Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestBobCoverageContExt.cls
/* Commenting the entire code as part of Gitlab #24446 */
@isTest
private class TestBobCoverageContExt {
/*
    static BobCoverageContExt bobExt;
    static  ApexPages.StandardController controller; 
    static integer amountTotal; 
    
    
    static void setup() {
        RecordType imgaRecordType = [ SELECT Id  FROM RecordType WHERE SObjectType = 'Account' and DeveloperName = 'IMGA_Record_Type' LIMIT 1];
        
        Account testAcc = TestingUtils.createAccounts( 1, false )[0];
        testAcc.RecordTypeId = imgaRecordType.ID;
        insert testAcc;
        
        Bob_Coverage__c bobCoverage = TestingUtils.createBoBCoverages( 1, testAcc.Id, 'TestBoB', 'Test Product', 'United Kingdom', true )[0];
        
        amountTotal = 0;
        list<Bob_Coverage_join__C> bobJoins = new list<Bob_Coverage_join__c>();
        for(integer i = 0; i < 12; i++) {
            bobJoins.add(new Bob_Coverage_Join__c(Invoice_Date__c = date.newinstance(2013, i + 1, 1), amount_total__c = i * 100, bob_coverage__c = bobCoverage.id));
            amountTotal += i * 100;
        }
        insert bobJoins;
        controller = new ApexPages.StandardController(bobCoverage);
        
    }
    
    
    static testMethod void testBobCoverageContExtInit(){
        setup();
        
        Test.startTest();
            bobExt = new BobCoverageContExt(controller);
        Test.stopTest();
        BoB_Coverage__c bob = bobExt.bob;
        
       // System.AssertEquals(bob.CY_YTD_Amount__c - bob.M2_YTD_Quota_Summary__c, bobExt.currentYearSum , 'The current Year Sum is not being calculated correctly');
        System.AssertEquals(12, bobExt.currentYearPercentages.size(), 'The current year percentages need twelve values');

    }
        */
}