force-app/main/default/objects/Metadata_Activation_Settings__c/Metadata_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to disable/enable validation rules, process builders, triggers for users and profiles</description>
    <label>Metadata Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the trigger on the specified SObject</description>
    <inlineHelpText>Check if the trigger needs to be disabled for the specified SObject</inlineHelpText>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>Specify for which object processes should be bypassed</description>
    <inlineHelpText>Specify API names separated by semicolon (&apos;;&apos;) of the SObject for which you want to disable/enable the process builders, workflows, validation rules, triggers</inlineHelpText>
    <label>SObject API Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Usage_Suspense__c/QTB_Usage_Suspense__c.object-meta.xml
<CustomObject>
    <label>Usage Suspense</label>
    <nameField>
        <label>Usage Suspense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usage Suspenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Usage_Suspense__c/fields/QTB_Mediation_Status__c.field-meta.xml
<CustomField>
    <fullName>QTB_Mediation_Status__c</fullName>
    <label>Mediation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Re-rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UsageSuspenseTriggerHandler.cls
/**
 * Class: UsageSuspenseTriggerHandler 
 *
 * Author: Vinutha Iyengar
 *
 * Date Created: 25.08.2020
 *
 * Purpose: UsageSuspenseTriggerHandler is a handler class for all business logic related to QTB_Usage_Suspense__c object
 * 
 */
public class UsageSuspenseTriggerHandler implements ITriggerHandler
{
    public static Boolean isTriggerDisabled = false;
    public static final String objName = 'QTB_Usage_Suspense__c';
    public static final String DELIMITERS = '[;,]';
    
    //Method to disable trigger execution from custom settings - Metadata_Activation_Settings__c
    public Boolean IsDisabled(){ 
        Metadata_Activation_Settings__c custSetting = Metadata_Activation_Settings__c.getInstance();
        if(custSetting!=null && ( (String.isBlank(custSetting.SObject_API_Name__c) && custSetting.Disable_Trigger__c)
                                 || (String.isNotBlank(custSetting.SObject_API_Name__c) && 
                                     custSetting.SObject_API_Name__c.split(DELIMITERS).contains(objName)
                                     && custSetting.Disable_Trigger__c) )){     
                                         return true;
                                     }
        else{ 
          return isTriggerDisabled;
        }
    }
     
    public void BeforeInsert(List<SObject> newItems)
    {
    }
 
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems)
    {   
    }
 
    public void BeforeDelete(Map<Id, SObject> oldItems)
    {  
    }
  
    public void AfterInsert(List<SObject> newItems) 
    {              
    }
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {               
        List<QTB_Usage_Suspense__c> newItemsList = newItems.values();
        List<QTB_Usage_Suspense__c> recordsToDelete = new List<QTB_Usage_Suspense__c>();
        for(QTB_Usage_Suspense__c rec : newItemsList) 
        {
            if(rec.QTB_Mediation_Status__c == 'Processed')
            {
            	recordsToDelete.add(rec);      
            }
        }
        if(recordsToDelete.size()>0)
        {
            QTB_Invoice_Utils.deleteUsageSuspenses();
        }
    }
 
    public void AfterDelete(Map<Id, SObject> oldItems)
    {
    }
 
    public void AfterUndelete(Map<Id, SObject> oldItems) 
    {
    }      
}