force-app/main/default/objects/Metadata_Activation_Settings__c/Metadata_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to disable/enable validation rules, process builders, triggers for users and profiles</description>
    <label>Metadata Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the trigger on the specified SObject</description>
    <inlineHelpText>Check if the trigger needs to be disabled for the specified SObject</inlineHelpText>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>Specify for which object processes should be bypassed</description>
    <inlineHelpText>Specify API names separated by semicolon (&apos;;&apos;) of the SObject for which you want to disable/enable the process builders, workflows, validation rules, triggers</inlineHelpText>
    <label>SObject API Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QTB_UsageTriggerHandler.cls
/*****************************************************************************************************
* Class: QTB_UsageTriggerHandler
* Author: Accenture
* Purpose: This is a handler class for all business logic related to Usage object
* Requirement:
* Change History: 
* Developer     Date           Description
* ------------------------------------------------------------------------------------------- 
*              28/5/2020
*******************************************************************************************************/
public with sharing class QTB_UsageTriggerHandler implements ITriggerHandler{
	private static Boolean isTriggerHandlerDisabled = false;
    private static final String CLASSNAME = QTB_UsageTriggerHandler.class.getName();
    public static final String DELIMITERS = '[;,]';
	public static Boolean throwExplicitException = false;    
    /*****************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: Method is used to disable trigger execution from custom setting- Metadata_Activation_Settings__c
    *****************************************************************************************************************/
    public Boolean isDisabled(){ 
        Boolean isTriggerDisabled=false;
        Metadata_Activation_Settings__c custSetting = Metadata_Activation_Settings__c.getInstance();
        if(custSetting!=null 
        && ((String.isBlank(custSetting.SObject_API_Name__c) && custSetting.Disable_Trigger__c)
            || (String.isNotBlank(custSetting.SObject_API_Name__c) 
                && custSetting.SObject_API_Name__c.split(DELIMITERS).contains(QTB_Constants.SOBJECT_BLNG_USAGE)
                && custSetting.Disable_Trigger__c))){     
        	isTriggerDisabled=true;
        }
        return isTriggerHandlerDisabled || isTriggerDisabled;
    }
    // disable usage trigger using apex
    public static void disable() {
        isTriggerHandlerDisabled = true;
    }
     /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for before insert event on the Usage object.
    ********************************************************************************************************************/
    public void beforeInsert(List<SObject> newItems){
        QTB_UsageHelper.process((List<blng__Usage__c>)newItems,null,Trigger.OperationType);
    }
 
    /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for before update event on the Usage object.
    ********************************************************************************************************************/ 
    public void beforeUpdate(Map<ID,SObject> newItems, Map<ID,SObject> oldItems){
       	Map<ID,blng__Usage__c> newUsageMap = (Map<ID,blng__Usage__c>)newItems;
        Map<ID,blng__Usage__c> oldUsageMap = (Map<ID,blng__Usage__c>)oldItems;
        QTB_UsageHelper.process(newUsageMap.values(),oldUsageMap,Trigger.OperationType);
    }
 
     /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for before delete event on the Usage object.
    ********************************************************************************************************************/
    public void beforeDelete(Map<ID,SObject> oldItems){
        Map<ID,blng__Usage__c> usageMap = (Map<ID,blng__Usage__c>)oldItems;
        QTB_UsageHelper.process(usageMap.values(),null,Trigger.OperationType);
    }
  
    /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for after insert event on the Usage object.
    ********************************************************************************************************************/
    public void AfterInsert(List<SObject> newItems) {
        //#20867 Tiered Rate flag setting 
        QTB_UsageHelper.process((List<blng__Usage__c>)newItems,null,Trigger.OperationType);
    }
 
     /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for after update event on the Usage object.
    ********************************************************************************************************************/
    public void AfterUpdate(Map<ID,SObject> newItems, Map<ID,SObject> oldItems) {
        Map<ID,blng__Usage__c> newUsageMap = (Map<ID,blng__Usage__c>) newItems;
        Map<ID,blng__Usage__c> oldUsageMap = (Map<ID,blng__Usage__c>) oldItems;
        QTB_UsageHelper.process(newUsageMap.values(),oldUsageMap,Trigger.OperationType);
    }
 
     /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for after delete event on the Usage object.
    ********************************************************************************************************************/
    public void afterDelete(Map<ID, SObject> oldItems){
        Map<ID,blng__Usage__c> usageMap = (Map<ID,blng__Usage__c>) oldItems;
        QTB_UsageHelper.process(usageMap.values(),null,Trigger.OperationType);
    }
 
     /*******************************************************************************************************************
    * Author:      Accenture
    * Date:        28-05-2020
    * Parameters:  None
    * Return:      void
    * Description: This method is used to handle business logic for after undelete event on the Usage object.
    ********************************************************************************************************************/
    public void afterUndelete(Map<ID, SObject> newItems){
        Map<ID,blng__Usage__c> newUsageMap = (Map<ID,blng__Usage__c>) newItems;
        QTB_UsageHelper.process(newUsageMap.values(),null,Trigger.OperationType);
    }      
}