force-app/main/default/objects/Account/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <formula>IF(FIND(&apos;/&apos;,SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))&gt;0,LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL),FIND(&apos;/&apos;,SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))-1),SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))</formula>
    <label>Account Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DMS_Owner__c.field-meta.xml
<CustomField>
    <fullName>DMS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#26660_ALM Business Unit Solution Development Executive (SDE). - Set at the Country Parent and cascades down to the Sales Site
#29959 Account: Relabel &quot;ALM SDE(Solution Development Executive)&quot; to &quot;ALM VSE/SE&quot;
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>ALM VSE/SE/AE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountslocG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DnB_Web_Address__c.field-meta.xml
<CustomField>
    <fullName>DnB_Web_Address__c</fullName>
    <formula>DNBConnect__D_B_Connect_Company_Profile__r.organization_website_address_domain_1__c</formula>
    <inlineHelpText>The Internet URL (Uniform Resource Locator) which uniquely identifies the proprietary website of the subject or the website preferred by the subject which gives more information on the subject.</inlineHelpText>
    <label>D&amp;B Web Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enterprise_ISR__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ISR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Ignite: Enterprise Inside Sales Representative</description>
    <inlineHelpText>Enterprise Inside Sales Representative - Set at the Country Parent and cascades down to the Sales Site

#26660 : Account Coverage: Add new fields to Account Coverage Section</inlineHelpText>
    <label>Enterprise ISR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IM_IMGA__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA__c</fullName>
    <description>This formula will  traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;Book of Business/IMGA&quot;.
If there is no such level parent in the hierarchy - will leave field blank</description>
    <formula>/* 
This formula will traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;IM Group (IMGA)&quot;. 
If there is no such level parent in the hierarchy - will leave field blank 
*/ 


/* If No Parent AND this Record Hierarchy level IS NOT IMGA leave blank */ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )!=&apos;IM Group (IMGA)&apos;, &apos;&apos;, 

/*Else If No Parent AND this Record Hierarchy level IS IMGA use Name field from this record*/ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Name, 


/*Else If parent is IMGA-Level, get name from parent*/ 
IF(TEXT( Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Name, 

/*Else If second parent is IMGA-Level, get name from second parent*/ 
IF(TEXT( Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Name, 

/*Else If third parent is IMGA-Level, get name from third parent*/ 
IF(TEXT( Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Name, 

/*Else If fourth parent is IMGA-Level, get name from fourth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Parent.Name, 

/*Else If fifth parent is IMGA-Level, get name from fifth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, 
Parent.Parent.Parent.Parent.Parent.Name, 

/*Else (when reached up six levels, if no IMGA-level parent found - then put blank.*/ 
&apos;&apos; ) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Iron Mtn Grouping (IMGA)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Information_Governance_Rep__c.field-meta.xml
<CustomField>
    <fullName>Information_Governance_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#26452 :Account Coverage: Relabel Primary BDE, Insight Owner and Entertainment Services Owner and Hide other retired &quot;Owner&quot; fields
Digital Business Unit Solution Development Executive (SDE). - Set at the Country Parent and cascades down to the Sales Site
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>DBU SE/AE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3IUw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_BDE__c.field-meta.xml
<CustomField>
    <fullName>Primary_BDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A commercial BDE name may be populated in this field for at risk notification. For account coverage details, please see the BOB Coverage by Rep report.
#26452 : Account Coverage: Relabel Primary BDE, Insight Owner and Entertainment Services Owner and Hide other retired &quot;Owner&quot; fields
Account Owner - Account Executive or Inside Sales Rep. - Set at the Country Parent and cascades down to the Sales Site</inlineHelpText>
    <label>AE/ISR (Account Owner)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RIM_SDE__c.field-meta.xml
<CustomField>
    <fullName>RIM_SDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RIM Solution Development Executive
#34421: Copied from Country Parent
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>RIM SE/AE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RIM_SDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <formula>SUBSTITUTE(Email, LEFT(Email, FIND(&quot;@&quot;, Email)), NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Is_Sales_Site__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Related Contact)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadToAccountMatching.cls
public without sharing class LeadToAccountMatching implements Queueable
{
    private static final String SALES_SITE_LEVEL = 'Sales (Site)';
    private static final String FUZZY_DUPLICATE_RULE_NAME = 'L2ACompanyNameFuzzyCountry';
    private static Set<Id> excludedCreatorIds = parseExcludedCreatorIds(Label.L2AMatchingExcludedCreatedByUsers);

    public static Boolean updatingLeads = false;

    private final Set<Id> leadIds;

    public LeadToAccountMatching (Set<Id> leadIds)
    {
        this.leadIds = leadIds;
    }

    public static void handleLeadTrigger (List<Lead> triggerList, Map<Id,Lead> oldMap)
    {
        Set<Id> leadIdsToQueue = new Set<Id>();

        for (Lead l : triggerList)
        {
            if (trigger.isInsert ||
                l.Related_Contact__c != oldMap.get(l.Id).Related_Contact__c ||
                l.Company != oldMap.get(l.Id).Company ||
                l.Country != oldMap.get(l.Id).Country ||
                l.Domain__c != oldMap.get(l.Id).Domain__c ||
                l.Email != oldMap.get(l.Id).Email)
            {
                leadIdsToQueue.add(l.Id);
            }
        }

        if (!leadIdsToQueue.isEmpty())
            System.enqueueJob(new LeadToAccountMatching(leadIdsToQueue));
    }

    public void execute (QueueableContext context)
    {
        if (leadIds.isEmpty())
            return;

        Map<Id,Lead> leadsById = new Map<Id,Lead>([
            SELECT Id, Company, Country, Domain__c, Related_Contact__c, Related_Account__c,
                Street, City, State, PostalCode
            FROM Lead
            WHERE Id IN :leadIds
        ]);

        if (leadsById.isEmpty())
            return;

        Set<Id> unresolvedLeadIds = new Set<Id>(leadsById.keySet());

        Map<Id,Account> matchesByLeadId = new Map<Id,Account>();

        matchRelatedContactAccounts(
            leadsById,
            unresolvedLeadIds,
            matchesByLeadId
        );

        matchExactNameAndCountry(
            leadsById,
            unresolvedLeadIds,
            matchesByLeadId
        );

        matchFuzzyNameAndCountry(
            leadsById,
            unresolvedLeadIds,
            matchesByLeadId
        );

        matchDomains(
            leadsById,
            unresolvedLeadIds,
            matchesByLeadId
        );

        updateMatchedLeads(leadsById,matchesByLeadId);
    }

    private static void matchRelatedContactAccounts (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<Id,Account> matchesByLeadId)
    {
        Set<Id> contactIds = new Set<Id>();

        for (Id leadId : unresolvedLeadIds)
        {
            Id contactId = leadsById.get(leadId).Related_Contact__c;

            if (contactId != null)
                contactIds.add(contactId);
        }

        if (contactIds.isEmpty())
            return;

        Map<Id,Account> accountsByContactId = new Map<Id,Account>();
        for (Contact relatedContact : [
            SELECT Id, Account.Id, Account.ShippingStreet, Account.ShippingCity,
                Account.ShippingState, Account.ShippingPostalCode, Account.ShippingCountry,
                Account.IM_Hierarchy_Level__c, Account.CreatedById
            FROM Contact
            WHERE Id IN :contactIds
        ])
        {
            if (isQualifyingAccount(relatedContact.Account))
                accountsByContactId.put(relatedContact.Id,relatedContact.Account);
        }

        Set<Id> matchedLeadIds = new Set<Id>();

        for (Id leadId : unresolvedLeadIds)
        {
            Account relatedAccount = accountsByContactId.get(
                leadsById.get(leadId).Related_Contact__c
            );

            if (relatedAccount != null)
            {
                matchesByLeadId.put(leadId,relatedAccount);
                matchedLeadIds.add(leadId);
            }
        }

        unresolvedLeadIds.removeAll(matchedLeadIds);
    }

    private static void matchExactNameAndCountry (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<Id,Account> matchesByLeadId)
    {
        if (unresolvedLeadIds.isEmpty())
            return;

        Set<String> companies = new Set<String>();
        Set<String> countries = new Set<String>();

        for (Id leadId : unresolvedLeadIds)
        {
            Lead leadRecord = leadsById.get(leadId);

            if (String.isNotBlank(leadRecord.Company) && String.isNotBlank(leadRecord.Country))
            {
                companies.add(leadRecord.Company);
                countries.add(leadRecord.Country);
            }
        }

        if (companies.isEmpty() || countries.isEmpty())
            return;

        Map<String,List<Account>> candidatesByNameAndCountry = new Map<String,List<Account>>();

        for (Account candidate : [
            SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode,
                ShippingCountry, Primary_BDE__c, Enterprise_ISR__c, RIM_SDE__c,
                Information_Governance_Rep__c, DMS_Owner__c, IM_IMGA__c, Account_Domain__c,
                DnB_Web_Address__c, CreatedDate
            FROM Account
            WHERE IM_Hierarchy_Level__c = :SALES_SITE_LEVEL
                AND CreatedById NOT IN :excludedCreatorIds
                AND Name IN :companies
                AND ShippingCountry IN :countries
        ])
        {
            addCandidate(
                candidatesByNameAndCountry,
                compoundKey(candidate.Name,candidate.ShippingCountry),
                candidate
            );
        }

        matchFromCandidateMap(
            leadsById,
            unresolvedLeadIds,
            candidatesByNameAndCountry,
            true,
            matchesByLeadId
        );
    }

    private static void matchFuzzyNameAndCountry (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<Id,Account> matchesByLeadId)
    {
        if (unresolvedLeadIds.isEmpty())
            return;

        Map<Id,Set<Id>> accountIdsByLeadId = new Map<Id,Set<Id>>();

        for (DuplicateRecordSet duplicateSet : [
            SELECT Id, (SELECT RecordId FROM DuplicateRecordItems)
            FROM DuplicateRecordSet
            WHERE DuplicateRule.DeveloperName = :FUZZY_DUPLICATE_RULE_NAME
                AND Id IN (
                    SELECT DuplicateRecordSetId
                    FROM DuplicateRecordItem
                    WHERE RecordId IN :unresolvedLeadIds
                )
        ])
        {
            Set<Id> leadIdsInSet = new Set<Id>();
            Set<Id> accountIdsInSet = new Set<Id>();

            for (DuplicateRecordItem item : duplicateSet.DuplicateRecordItems)
            {
                if (unresolvedLeadIds.contains(item.RecordId))
                    leadIdsInSet.add(item.RecordId);
                else if (item.RecordId.getSObjectType() == Account.SObjectType)
                    accountIdsInSet.add(item.RecordId);
            }

            if (accountIdsInSet.isEmpty())
                continue;

            for (Id leadId : leadIdsInSet)
            {
                if (!accountIdsByLeadId.containsKey(leadId))
                    accountIdsByLeadId.put(leadId,new Set<Id>());

                accountIdsByLeadId.get(leadId).addAll(accountIdsInSet);
            }
        }

        if (!accountIdsByLeadId.isEmpty())
        {
            matchFuzzyCandidateAccounts(
                leadsById,
                unresolvedLeadIds,
                matchesByLeadId,
                accountIdsByLeadId
            );
        }
    }

    @TestVisible
    private static void matchFuzzyCandidateAccounts (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<Id,Account> matchesByLeadId, Map<Id,Set<Id>> accountIdsByLeadId)
    {
        Set<Id> candidateAccountIds = new Set<Id>();

        for (Set<Id> accountIds : accountIdsByLeadId.values())
            candidateAccountIds.addAll(accountIds);

        Map<Id,Account> qualifyingAccountsById = new Map<Id,Account>([
            SELECT Id, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode,
                ShippingCountry, Primary_BDE__c, Enterprise_ISR__c, RIM_SDE__c,
                Information_Governance_Rep__c, DMS_Owner__c, IM_IMGA__c, Account_Domain__c,
                DnB_Web_Address__c, CreatedDate
            FROM Account
            WHERE Id IN :candidateAccountIds
                AND IM_Hierarchy_Level__c = :SALES_SITE_LEVEL
                AND CreatedById NOT IN :excludedCreatorIds
        ]);

        Set<Id> matchedLeadIds = new Set<Id>();

        for (Id leadId : accountIdsByLeadId.keySet())
        {
            List<Account> candidates = new List<Account>();

            for (Id accountId : accountIdsByLeadId.get(leadId))
            {
                if (qualifyingAccountsById.containsKey(accountId))
                    candidates.add(qualifyingAccountsById.get(accountId));
            }

            Account bestMatch = chooseBestAccount(leadsById.get(leadId),candidates);

            if (bestMatch != null)
            {
                matchesByLeadId.put(leadId,bestMatch);
                matchedLeadIds.add(leadId);
            }
        }

        unresolvedLeadIds.removeAll(matchedLeadIds);
    }

    private static void matchDomains (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<Id,Account> matchesByLeadId)
    {
        if (unresolvedLeadIds.isEmpty())
            return;

        Set<String> leadDomains = new Set<String>();

        for (Id leadId : unresolvedLeadIds)
        {
            String domain = leadsById.get(leadId).Domain__c;

            if (String.isNotBlank(domain))
                leadDomains.add(domain);
        }

        if (leadDomains.isEmpty())
            return;

        Map<String,List<Account>> candidatesByDomain = new Map<String,List<Account>>();

        for (Account candidate : [
            SELECT Id, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode,
                ShippingCountry, Primary_BDE__c, Enterprise_ISR__c, RIM_SDE__c,
                Information_Governance_Rep__c, DMS_Owner__c, IM_IMGA__c, Account_Domain__c,
                DnB_Web_Address__c, CreatedDate
            FROM Account
            WHERE IM_Hierarchy_Level__c = :SALES_SITE_LEVEL
                AND CreatedById NOT IN :excludedCreatorIds
                AND (Account_Domain__c IN :leadDomains OR DnB_Web_Address__c IN :leadDomains)
        ])
        {
            Set<String> candidateDomains = new Set<String>{
                normalize(candidate.Account_Domain__c),
                normalize(candidate.DnB_Web_Address__c)
            };

            candidateDomains.remove(null);

            for (String candidateDomain : candidateDomains)
                addCandidate(candidatesByDomain,candidateDomain,candidate);
        }

        matchFromCandidateMap(
            leadsById,
            unresolvedLeadIds,
            candidatesByDomain,
            false,
            matchesByLeadId
        );
    }

    private static void matchFromCandidateMap (Map<Id,Lead> leadsById, Set<Id> unresolvedLeadIds, Map<String,List<Account>> candidatesByKey, Boolean useNameAndCountryKey, Map<Id,Account> matchesByLeadId)
    {
        Set<Id> matchedLeadIds = new Set<Id>();

        for (Id leadId : unresolvedLeadIds)
        {
            Lead leadRecord = leadsById.get(leadId);

            Account bestMatch = chooseBestAccount(
                leadRecord,
                candidatesByKey.get(
                    useNameAndCountryKey
                    ? compoundKey(leadRecord.Company,leadRecord.Country)
                    : normalize(leadRecord.Domain__c)
                )
            );

            if (bestMatch != null)
            {
                matchesByLeadId.put(leadId,bestMatch);
                matchedLeadIds.add(leadId);
            }
        }

        unresolvedLeadIds.removeAll(matchedLeadIds);
    }

    @TestVisible
    private static Account chooseBestAccount (Lead leadRecord, List<Account> candidates)
    {
        if (candidates == null || candidates.isEmpty())
            return null;

        Account bestMatch;

        for (Account candidate : candidates)
        {
            if (bestMatch == null || isBetterMatch(leadRecord,candidate,bestMatch))
                bestMatch = candidate;
        }

        return bestMatch;
    }

    private static Boolean isBetterMatch (Lead leadRecord, Account candidate, Account currentBest)
    {
        Boolean candidateHasCoverage = hasActiveSalesCoverage(candidate);

        if (candidateHasCoverage != hasActiveSalesCoverage(currentBest))
            return candidateHasCoverage;

        Boolean candidateHasImga = String.isNotBlank(candidate.IM_IMGA__c);

        if (candidateHasImga != String.isNotBlank(currentBest.IM_IMGA__c))
            return candidateHasImga;

        Integer candidateDomainRank = domainRank(
            leadRecord.Domain__c,
            candidate.Account_Domain__c,
            candidate.DnB_Web_Address__c
        );

        Integer bestDomainRank = domainRank(
            leadRecord.Domain__c,
            currentBest.Account_Domain__c,
            currentBest.DnB_Web_Address__c
        );

        if (candidateDomainRank != bestDomainRank)
            return candidateDomainRank < bestDomainRank;

        if (candidate.CreatedDate != currentBest.CreatedDate)
            return candidate.CreatedDate < currentBest.CreatedDate;

        return false;
    }

    private static Boolean hasActiveSalesCoverage (Account accountRecord)
    {
        return accountRecord.Primary_BDE__c != null
            || accountRecord.Enterprise_ISR__c != null
            || accountRecord.RIM_SDE__c != null
            || accountRecord.Information_Governance_Rep__c != null
            || accountRecord.DMS_Owner__c != null;
    }

    @TestVisible
    private static Integer domainRank (String leadDomain, String accountDomain, String dnbWebAddress)
    {
        String normalizedLeadDomain = normalize(leadDomain);

        if (normalizedLeadDomain != null && normalizedLeadDomain == normalize(accountDomain))
            return 1;

        if (normalizedLeadDomain != null && normalizedLeadDomain == normalize(dnbWebAddress))
            return 2;

        return 3;
    }

    private static Boolean isQualifyingAccount (Account accountRecord)
    {
        return accountRecord != null &&
            accountRecord.IM_Hierarchy_Level__c == SALES_SITE_LEVEL &&
            !excludedCreatorIds.contains(accountRecord.CreatedById);
    }

    @TestVisible
    private static Set<Id> parseExcludedCreatorIds (String labelValue)
    {
        Set<Id> excludedCreatorIds = new Set<Id>();

        if (String.isBlank(labelValue))
            return excludedCreatorIds;

        for (String rawValue : labelValue.split(','))
        {
            String candidateValue = rawValue.trim();

            if (!String.isBlank(candidateValue))
            {
                try
                {
                    Id candidateId = (Id)candidateValue;

                    if (candidateId.getSObjectType() == User.SObjectType)
                        excludedCreatorIds.add(candidateId);
                }
                catch (Exception invalidId){}
            }
        }

        return excludedCreatorIds;
    }

    private static void addCandidate (Map<String,List<Account>> candidatesByKey, String key, Account candidate)
    {
        if (!candidatesByKey.containsKey(key))
            candidatesByKey.put(key,new List<Account>());

        candidatesByKey.get(key).add(candidate);
    }

    private static String compoundKey (String firstValue, String secondValue)
    {
        String firstKey = normalize(firstValue);
        String secondKey = normalize(secondValue);

        return firstKey != null && secondKey != null ? firstKey + '|' + secondKey : null;
    }

    private static String normalize (String value)
    {
        return String.isNotBlank(value) ? value.trim().toLowerCase() : null;
    }

    private static void updateMatchedLeads (Map<Id,Lead> leadsById, Map<Id,Account> matchesByLeadId)
    {
        List<Lead> leadsToUpdate = new List<Lead>();

        for (Id leadId : matchesByLeadId.keySet())
        {
            Lead l = leadsById.get(leadId);
            Account match = matchesByLeadId.get(leadId);

            if (l.Related_Account__c == match.Id
                && l.Street == match.ShippingStreet
                && l.City == match.ShippingCity
                && l.State == match.ShippingState
                && l.PostalCode == match.ShippingPostalCode
                && l.Country == match.ShippingCountry)
            {
                continue;
            }

            leadsToUpdate.add(new Lead(
                Id = leadId,
                Related_Account__c = match.Id,
                Street = match.ShippingStreet,
                City = match.ShippingCity,
                State = match.ShippingState,
                PostalCode = match.ShippingPostalCode,
                Country = match.ShippingCountry
            ));
        }

        if (!leadsToUpdate.isEmpty())
        {
            updatingLeads = true;
            try { update leadsToUpdate; }
            finally { updatingLeads = false; }
        }
    }
}