force-app/main/default/objects/Account/fields/Account_Domain__c.field-meta.xml
<CustomField>
    <fullName>Account_Domain__c</fullName>
    <formula>IF(FIND(&apos;/&apos;,SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))&gt;0,LEFT(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL),FIND(&apos;/&apos;,SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))-1),SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Website, &apos;http://&apos;, NULL), &apos;https://&apos;, NULL), &apos;www.&apos;, NULL))</formula>
    <label>Account Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DnB_Web_Address__c.field-meta.xml
<CustomField>
    <fullName>DnB_Web_Address__c</fullName>
    <formula>DNBConnect__D_B_Connect_Company_Profile__r.organization_website_address_domain_1__c</formula>
    <inlineHelpText>The Internet URL (Uniform Resource Locator) which uniquely identifies the proprietary website of the subject or the website preferred by the subject which gives more information on the subject.</inlineHelpText>
    <label>D&amp;B Web Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IM_IMGA__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA__c</fullName>
    <description>This formula will  traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;Book of Business/IMGA&quot;.
If there is no such level parent in the hierarchy - will leave field blank</description>
    <formula>/* 
This formula will traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;IM Group (IMGA)&quot;. 
If there is no such level parent in the hierarchy - will leave field blank 
*/ 


/* If No Parent AND this Record Hierarchy level IS NOT IMGA leave blank */ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )!=&apos;IM Group (IMGA)&apos;, &apos;&apos;, 

/*Else If No Parent AND this Record Hierarchy level IS IMGA use Name field from this record*/ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Name, 


/*Else If parent is IMGA-Level, get name from parent*/ 
IF(TEXT( Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Name, 

/*Else If second parent is IMGA-Level, get name from second parent*/ 
IF(TEXT( Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Name, 

/*Else If third parent is IMGA-Level, get name from third parent*/ 
IF(TEXT( Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Name, 

/*Else If fourth parent is IMGA-Level, get name from fourth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Parent.Name, 

/*Else If fifth parent is IMGA-Level, get name from fifth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, 
Parent.Parent.Parent.Parent.Parent.Name, 

/*Else (when reached up six levels, if no IMGA-level parent found - then put blank.*/ 
&apos;&apos; ) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Iron Mtn Grouping (IMGA)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_BDE__c.field-meta.xml
<CustomField>
    <fullName>Primary_BDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A commercial BDE name may be populated in this field for at risk notification. For account coverage details, please see the BOB Coverage by Rep report.
#26452 : Account Coverage: Relabel Primary BDE, Insight Owner and Entertainment Services Owner and Hide other retired &quot;Owner&quot; fields
Account Owner - Account Executive or Inside Sales Rep. - Set at the Country Parent and cascades down to the Sales Site</inlineHelpText>
    <label>AE/ISR (Account Owner)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <formula>SUBSTITUTE(Email, LEFT(Email, FIND(&quot;@&quot;, Email)), NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Is_Sales_Site__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Related Contact)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RelatedAccountMatchingComplete__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccountMatchingComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Becomes checked when the process by which Related_Account__c is evaluated and populated completes, whether a match was found or not.</description>
    <label>Related Account Matching Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadToAccountMatching_test.cls
@isTest
private class LeadToAccountMatching_test
{
    private static final String SALES_SITE_LEVEL = 'Sales (Site)';
    private static final String COUNTRY_US = 'United States';

    @TestSetup
    static void createApprovedCountries()
    {
        List<IM_Country__c> countries = new List<IM_Country__c>{
            new IM_Country__c(Name = COUNTRY_US,Active__c = true),
            new IM_Country__c(Name = 'Canada',Active__c = true)
        };

        insert countries;

        insert new List<IM_Alternative_Country_Name__c>{
            new IM_Alternative_Country_Name__c(
                Alternative_Name__c = COUNTRY_US,
                IM_Country__c = countries[0].Id
            ),
            new IM_Alternative_Country_Name__c(
                Alternative_Name__c = 'Canada',
                IM_Country__c = countries[1].Id
            )
        };
    }

    @isTest
    static void exactMatchPopulatesAccountAndBillingAddress()
    {
        System.runAs(createTestUser('exact'))
        {
            Account exactAccount = createSalesSite('Exact Company',COUNTRY_US);
            exactAccount.BillingStreet = '100 Exact Street';
            exactAccount.BillingCity = 'Boston';
            exactAccount.BillingState = 'Massachusetts';
            exactAccount.BillingPostalCode = '02108';
            update exactAccount;

            Lead leadRecord = newLead('Exact Company',COUNTRY_US,null);

            Test.startTest();
            insert leadRecord;

            System.assertEquals(Limits.getQueueableJobs(),1);
            System.assertEquals(queryMatchedLead(leadRecord.Id).RelatedAccountMatchingComplete__c,false);
            Test.stopTest();

            Lead matchedLead = queryMatchedLead(leadRecord.Id);

            System.assertEquals(matchedLead.Related_Account__c,exactAccount.Id);
            System.assertEquals(matchedLead.Street,exactAccount.BillingStreet);
            System.assertEquals(matchedLead.City,exactAccount.BillingCity);
            System.assertEquals(matchedLead.State,exactAccount.BillingState);
            System.assertEquals(matchedLead.PostalCode,exactAccount.BillingPostalCode);
            System.assertEquals(matchedLead.Country,exactAccount.BillingCountry);
            System.assertEquals(matchedLead.RelatedAccountMatchingComplete__c,true);
        }
    }

    @isTest
    static void relatedContactAccountTakesPriority()
    {
        System.runAs(createTestUser('contact'))
        {
            Account contactAccount = createSalesSite('Contact Account',COUNTRY_US);
            contactAccount.BillingCity = 'Chicago';
            update contactAccount;

            createSalesSite('Lead Company',COUNTRY_US);

            Contact relatedContact = new Contact(
                FirstName = 'Priority',
                LastName = 'Related Contact',
                AccountId = contactAccount.Id
            );

            insert relatedContact;

            Lead leadRecord = newLead('Lead Company',COUNTRY_US,null);
            leadRecord.Related_Contact__c = relatedContact.Id;

            Test.startTest();
            insert leadRecord;
            Test.stopTest();

            Lead matchedLead = queryMatchedLead(leadRecord.Id);

            System.assertEquals(matchedLead.Related_Account__c,contactAccount.Id);
            System.assertEquals(matchedLead.City,'Chicago');
        }
    }

    @isTest
    static void tiebreakersApplyInPriorityOrder()
    {
        User testUser = createTestUser('tie');

        System.assertEquals(
            LeadToAccountMatching.chooseBestAccount(
                leadWithDomain('priority-example.com'),
                new List<Account>{
                    comparisonAccount('No Coverage',null,null,null,null),
                    comparisonAccount('With Coverage',testUser.Id,null,null,null),
                    comparisonAccount(
                        'With IMGA',
                        testUser.Id,
                        'Priority IMGA',
                        'other-example.com',
                        null
                    ),
                    comparisonAccount(
                        'With Domain',
                        testUser.Id,
                        'Priority IMGA',
                        'priority-example.com',
                        null
                    )
                }
            ).Name,
            'With Domain'
        );
    }

    @isTest
    static void earliestCreatedDateBreaksRemainingTie()
    {
        System.runAs(createTestUser('oldest'))
        {
            Account olderAccount = salesSite('Oldest Company',COUNTRY_US);
            Account newerAccount = salesSite('Oldest Company',COUNTRY_US);

            insert new List<Account>{olderAccount,newerAccount};

            Test.setCreatedDate(olderAccount.Id,Datetime.now().addYears(-2));
            Test.setCreatedDate(newerAccount.Id,Datetime.now().addYears(-1));

            Lead leadRecord = newLead('Oldest Company',COUNTRY_US,null);

            Test.startTest();
            insert leadRecord;
            Test.stopTest();

            System.assertEquals(
                queryMatchedLead(leadRecord.Id).Related_Account__c,
                olderAccount.Id
            );
        }
    }

    @isTest
    static void accountDomainFallbackMatchesAndDoesNotRequeueItself()
    {
        System.runAs(createTestUser('domain'))
        {
            Account domainAccount = salesSite('Different Account Name','Canada');
            domainAccount.Website = 'https://www.domain-match-example.com/a-page';
            domainAccount.BillingCity = 'Toronto';
            insert domainAccount;

            Lead leadRecord = newLead(
                'No Name Match',
                COUNTRY_US,
                'alice.smith@domain-match-example.com'
            );

            Test.startTest();
            insert leadRecord;
            Test.stopTest();

            Lead matchedLead = queryMatchedLead(leadRecord.Id);

            System.assertEquals(matchedLead.Related_Account__c,domainAccount.Id);
            System.assertEquals(matchedLead.Country,'Canada');
            System.assertEquals(matchedLead.City,'Toronto');
        }
    }

    @isTest
    static void fuzzyCandidatesAreQualifiedAndSelected()
    {
        System.runAs(createTestUser('fuzzy'))
        {
            Account fuzzyAccount = createSalesSite('Acme Corporation',COUNTRY_US);
            Lead leadRecord = newLead('Acme Corp',COUNTRY_US,null);

            insertWithoutMatching(new List<Lead>{leadRecord});

            Lead queriedLead = [
                SELECT Id, Domain__c
                FROM Lead
                WHERE Id = :leadRecord.Id
            ];

            Set<Id> unresolvedLeadIds = new Set<Id>{queriedLead.Id};
            Map<Id,Account> matchesByLeadId = new Map<Id,Account>();

            Test.startTest();
            LeadToAccountMatching.matchFuzzyCandidateAccounts(
                new Map<Id,Lead>{queriedLead.Id => queriedLead},
                unresolvedLeadIds,
                matchesByLeadId,
                new Map<Id,Set<Id>>{
                    queriedLead.Id => new Set<Id>{fuzzyAccount.Id}
                }
            );

            Test.stopTest();

            System.assertEquals(matchesByLeadId.get(queriedLead.Id).Id,fuzzyAccount.Id);
            System.assertEquals(unresolvedLeadIds.size(),0);
        }
    }

    @isTest
    static void irrelevantUpdateDoesNotQueueAndNoMatchRetainsExistingAccount()
    {
        System.runAs(createTestUser('retain'))
        {
            Account existingAccount = createSalesSite('Existing Account',COUNTRY_US);
            Lead leadRecord = newLead('Original Company',COUNTRY_US,null);
            leadRecord.Related_Account__c = existingAccount.Id;
            insertWithoutMatching(new List<Lead>{leadRecord});

            Test.startTest();
            leadRecord.Title = 'Updated title';
            update leadRecord;

            System.assertEquals(Limits.getQueueableJobs(),0);
            System.assertEquals(queryMatchedLead(leadRecord.Id).RelatedAccountMatchingComplete__c,false);

            leadRecord.Company = 'No Matching Company';
            update leadRecord;

            System.assertEquals(Limits.getQueueableJobs(),1);
            Test.stopTest();

            Lead completedLead = queryMatchedLead(leadRecord.Id);

            System.assertEquals(completedLead.Related_Account__c,existingAccount.Id);
            System.assertEquals(completedLead.RelatedAccountMatchingComplete__c,true);
        }
    }

    @isTest
    static void bulkInsertUsesOneJobAndMatchesEveryLead()
    {
        System.runAs(createTestUser('bulk'))
        {
            createSalesSite('Bulk Company',COUNTRY_US);

            List<Lead> leads = new List<Lead>();

            for (Integer index = 0; index < 200; index++)
                leads.add(newLead('Bulk Company',COUNTRY_US,null));

            Test.startTest();
            insert leads;

            System.assertEquals(Limits.getQueueableJobs(),1);
            Test.stopTest();

            System.assertEquals(
                [
                    SELECT COUNT()
                    FROM Lead
                    WHERE Id IN :new Map<Id,Lead>(leads).keySet()
                        AND Related_Account__r.Name = 'Bulk Company'
                        AND RelatedAccountMatchingComplete__c = true
                    WITH SYSTEM_MODE
                ],
                200
            );
        }
    }

    @isTest
    static void exclusionParsingAndDomainRanksAreDefensive()
    {
        User testUser = createTestUser('parse');

        System.assertEquals(
            LeadToAccountMatching.parseExcludedCreatorIds(
                '  ' + testUser.Id + ', invalid, 001000000000000AAA, , ' + testUser.Id + '  '
            ),
            new Set<Id>{testUser.Id}
        );

        System.assertEquals(LeadToAccountMatching.parseExcludedCreatorIds(null).size(),0);

        System.assertEquals(
            LeadToAccountMatching.domainRank(
                ' Example.COM ',
                'example.com',
                'other.example'
            ),
            1
        );

        System.assertEquals(
            LeadToAccountMatching.domainRank(
                'example.com',
                'other.example',
                'EXAMPLE.COM'
            ),
            2
        );

        System.assertEquals(
            LeadToAccountMatching.domainRank(
                'example.com',
                'other.example',
                null
            ),
            3
        );
    }

    private static User createTestUser (String uniqueValue)
    {
        String uniqueUsername = 'l2a.' + uniqueValue + '.' + Datetime.now().getTime()
            + '@stackology-tests.invalid';
        
        User testUser = new User(
            Alias = uniqueValue.left(8),
            Country = COUNTRY_US,
            Email = uniqueUsername,
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LastName = uniqueValue + ' Matching User',
            LocaleSidKey = 'en_US',
            ProfileId = [
                SELECT Id
                FROM Profile
                WHERE Name = 'System Administrator'
                LIMIT 1
            ].Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = uniqueUsername
        );

        insert testUser;

        return testUser;
    }

    private static Account createSalesSite (String name, String country)
    {
        Account accountRecord = salesSite(name,country);
        insert accountRecord;

        return accountRecord;
    }

    private static Account salesSite (String name, String country)
    {
        return new Account(
            Name = name,
            BillingCountry = country,
            IM_Hierarchy_Level__c = SALES_SITE_LEVEL
        );
    }

    private static Lead newLead (String company, String country, String email)
    {
        return new Lead(
            LastName = company + ' Matching Test',
            Company = company,
            Status = 'New',
            Country = country,
            Email = email
        );
    }

    private static Lead leadWithDomain (String domain)
    {
        return (Lead) JSON.deserialize(
            JSON.serialize(new Map<String,Object>{
                'attributes' => new Map<String,Object>{'type' => 'Lead'},
                'Domain__c' => domain
            }),
            Lead.class
        );
    }

    private static Account comparisonAccount (String name, Id coverageUserId, String imga, String accountDomain, String dnbDomain)
    {
        Map<String,Object> values = new Map<String,Object>{
            'attributes' => new Map<String,Object>{'type' => 'Account'},
            'Name' => name,
            'IM_IMGA__c' => imga,
            'Account_Domain__c' => accountDomain,
            'DnB_Web_Address__c' => dnbDomain
        };
        
        if (coverageUserId != null)
            values.put('Primary_BDE__c',coverageUserId);

        return (Account) JSON.deserialize(JSON.serialize(values),Account.class);
    }

    private static void insertWithoutMatching (List<Lead> leads)
    {
        LeadToAccountMatching.updatingLeads = true;

        try
        {
            insert leads;
        }
        finally
        {
            LeadToAccountMatching.updatingLeads = false;
        }
    }

    private static Lead queryMatchedLead (Id leadId)
    {
        return [
            SELECT Related_Account__c, RelatedAccountMatchingComplete__c,
                Street, City, State, PostalCode, Country
            FROM Lead
            WHERE Id = :leadId
            WITH SYSTEM_MODE
        ];
    }
}