force-app/main/default/objects/Account/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment (Picklist)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>#N/A</fullName>
                <isActive>false</isActive>
                <label>#N/A</label>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>01J8000000Ghy97</fullName>
                <isActive>false</isActive>
                <label>01J8000000Ghy97</label>
            </value>
            <value>
                <fullName>a3i80000001IPBr</fullName>
                <isActive>false</isActive>
                <label>a3i80000001IPBr</label>
            </value>
            <value>
                <fullName>CDA - Unassigned</fullName>
                <isActive>false</isActive>
                <label>CDA - Unassigned</label>
            </value>
            <value>
                <fullName>CDA-Unassigned</fullName>
                <isActive>false</isActive>
                <label>CDA-Unassigned</label>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Commercial Canada</fullName>
                <isActive>false</isActive>
                <label>Commercial Canada</label>
            </value>
            <value>
                <fullName>Commercial - Canada</fullName>
                <isActive>false</isActive>
                <label>Commercial - Canada</label>
            </value>
            <value>
                <fullName>Commercial East</fullName>
                <isActive>false</isActive>
                <label>Commercial East</label>
            </value>
            <value>
                <fullName>Commercial - East</fullName>
                <isActive>false</isActive>
                <label>Commercial - East</label>
            </value>
            <value>
                <fullName>Commercial West</fullName>
                <isActive>false</isActive>
                <label>Commercial West</label>
            </value>
            <value>
                <fullName>Commercial - West</fullName>
                <isActive>false</isActive>
                <label>Commercial - West</label>
            </value>
            <value>
                <fullName>Coverage 1</fullName>
            </value>
            <value>
                <fullName>Coverage 2</fullName>
            </value>
            <value>
                <fullName>Coverage 3</fullName>
            </value>
            <value>
                <fullName>Coverage 4</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Enterprise Canada</fullName>
            </value>
            <value>
                <fullName>Enterprise East</fullName>
            </value>
            <value>
                <fullName>Enterprise West</fullName>
            </value>
            <value>
                <fullName>Generalist</fullName>
            </value>
            <value>
                <fullName>Global Industries</fullName>
                <isActive>false</isActive>
                <label>GISV</label>
            </value>
            <value>
                <fullName>GISV</fullName>
            </value>
            <value>
                <fullName>GLEAM</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Government - Canada</fullName>
                <isActive>false</isActive>
                <label>Government - Canada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_segment_lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_segment_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Sub-Segment lookup TO BE DELETED</label>
    <referenceTo>Account_Sub_Segment__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Sub_Segment__c</fullName>
    <label>Account Sub-Segment (Picklist)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Segment</fullName>
            </value>
            <value>
                <fullName>APAC-ANZ</fullName>
            </value>
            <value>
                <fullName>APAC-SEA</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>CCD</fullName>
            </value>
            <value>
                <fullName>Channels</fullName>
            </value>
            <value>
                <fullName>Crozier Fine Arts (CFA)</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>EISR</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Enterprise Canada</fullName>
            </value>
            <value>
                <fullName>Enterprise East</fullName>
            </value>
            <value>
                <fullName>Enterprise West</fullName>
            </value>
            <value>
                <fullName>Entertainment Services (IMES)</fullName>
            </value>
            <value>
                <fullName>Federal – Canada</fullName>
                <label>Federal Canada</label>
            </value>
            <value>
                <fullName>Federal-US</fullName>
            </value>
            <value>
                <fullName>Financial Service- Canada</fullName>
                <label>Financial Service Canada</label>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Fulfillment Services</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Healthcare/ Life Sciences – Canada</fullName>
            </value>
            <value>
                <fullName>HLS</fullName>
            </value>
            <value>
                <fullName>INS</fullName>
            </value>
            <value>
                <fullName>IPB</fullName>
            </value>
            <value>
                <fullName>IPRO</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>Large Commercial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Legal – Canada</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Sub_Segment__c/Account_Sub_Segment__c.object-meta.xml
<CustomObject>
    <label>Account Sub-Segment</label>
    <nameField>
        <label>Account Sub Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sub-Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Sub_Segment__c/fields/Account_Segment__c.field-meta.xml
<CustomField>
    <fullName>Account_Segment__c</fullName>
    <label>Account Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAccountSegementServices.cls
@isTest
public with sharing class TestAccountSegementServices {
	public static String testAcctSegmentName = 'Commercial';
	static Map<Id, String> acctSegmentIdToName = new Map<Id, String>();

	static void setupAccountSegments(){
        //28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		/*UnitTest.addData(TestingUtils.createAccountSegments('test', 10, true)).tag('Account Segments');
		for(Account_Sub_Segment__c acctSegment : (List<Account_Sub_Segment__c>) UnitTest.get('Account Segments').getList()){
			acctSegmentIdToName.put(acctSegment.Id, acctSegment.Name);
		}*/
	}

	static testMethod void testFilterAccountsWithPopulatedAcctSegmentLookup(){
        //28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		//Account_Sub_Segment__c testAcctSegment = TestingUtils.createAccountSegments('test', 1, true)[0];
		List<Account> accounts = TestingUtils.createAccounts( 10, false );
        //28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		/*UnitTest.addData(accounts)
				.divide(2)
				.part('Accounts to pass')
				.part('Accounts to fail');
		
		UnitTest.get('Accounts to pass').property('Account_Segment_lookup__c').assign(testAcctSegment.Id);
		UnitTest.get(Account.SObjectType).dummyInsert();*/
		
		Test.startTest();
			List<Account> actualAccounts = AccountSegmentServices.filterAccountsWithChangedAcctSegmentLookup(accounts, null);
		Test.stopTest();
		//28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		/*UnitTest.analyze('Accounts to pass').assertEquivalence(actualAccounts, 
						'accounts with the Account_Segment_lookup__c populated should be filtered');*/
	}

	static testMethod void testFilterAccountsWithChangedAcctSegmentLookup(){
        //28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		/*Account_Sub_Segment__c testAcctSegment = TestingUtils.createAccountSegments('test', 1, true)[0];
		List<Account> accounts = TestingUtils.createAccounts( 10, false );
		UnitTest.addData(accounts)
				.tag('Accounts')
				.divide(2)
				.part('Accounts to pass')
				.part('Accounts to fail');
		UnitTest.get(Account.SObjectType).dummyInsert();
		List<Account> oldAccounts = UnitTest.get('Accounts').getList().deepClone(true);

		UnitTest.get('Accounts to pass').property('Account_Segment_lookup__c').assign(testAcctSegment.Id);
		
		List<Account> newAccounts = UnitTest.get('Accounts').getList();*/
		
		Test.startTest();
        //28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
			//List<Account> actualAccounts = AccountSegmentServices.filterAccountsWithChangedAcctSegmentLookup(newAccounts, new Map<Id, Account>(oldAccounts));*/
		Test.stopTest();
		//28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
		/*UnitTest.analyze('Accounts to pass').assertEquivalence(actualAccounts, 
						'accounts with the Account_Sub_Segment__c changed should be filtered');*/
	}
    
	//28556- Account: Decommission Old Account Segment/Sub-Segment Lookup fields and related Formula fields
	/*static testMethod void testGenerateAccountSubSegmentMap(){
		List<String> listOfTestSegments = new List<String>{'a','b','c','d','e'};
		UnitTest.addData(TestingUtils.createAccountSegments('test', 10, false))
				.tag('account segments');
		UnitTest.get('account segments').property('Account_Segment__c').assignFrom(listOfTestSegments);
		UnitTest.get('account segments').insertAll();
		UnitTest.addData(TestingUtils.createAccounts( 10, false )).tag('accounts')
				.property('Account_Segment_lookup__c')
				.assignFrom('account segments');
		UnitTest.get(Account.SObjectType).dummyInsert();

		Test.startTest();
		  	Map<Id, Account_Sub_Segment__c> actualMap = AccountSegmentServices.generateAccountSubSegmentMap(UnitTest.get('accounts').getList());
		Test.stopTest();
		Map<Id, Account_Sub_Segment__c> expectedMap = new Map<Id, Account_Sub_Segment__c>();
		for(Account_Sub_Segment__c acctSegment : (List<Account_Sub_Segment__c>) UnitTest.get('account segments').getList()){
			expectedMap.put(acctSegment.Id, acctSegment);
		}
		System.assertEquals(expectedMap.keySet(), actualMap.keySet(), 'The expected Account_Sub_Segment__c Ids were not returned');
		for(Id acctSegmentId : actualMap.keySet()) {
			System.assertNotEquals(null, expectedMap.get(acctSegmentId));
			System.assertNotEquals(null, actualMap.get(acctSegmentId));
			System.assertEquals(expectedMap.get(acctSegmentId).Name, actualMap.get(acctSegmentId).Name,
				'The incorrect name value was mapped to an Account Sub Segment Id');
			System.assertEquals(expectedMap.get(acctSegmentId).Account_Segment__c, actualMap.get(acctSegmentId).Account_Segment__c,
				'The incorrect name value was mapped to an Account Sub Segment Id');
		}
	}
	
	static testMethod void testAccountSegmentTriggerOnInsert(){
		setupAccountSegments();
		UnitTest.addData(TestingUtils.createAccounts( 10, false ))
				.tag('Accounts').divide(2)
				.part('accounts with account segment lookup prepopulated')
				.part('accounts without account segment lookup prepopulated');

		UnitTest.get('accounts with account segment lookup prepopulated')
				.property('Account_Segment_lookup__c').assignFrom('Account Segments');
		
		Test.startTest();
			UnitTest.get(Account.SObjectType).InsertAll();
		Test.stopTest();
		
		List<Account> actualAccounts = [SELECT Account_Sub_Segment__c, Account_Segment_lookup__c FROM Account];
						
		for(Account acct : actualAccounts){
			if(UnitTest.analyze('accounts with account segment lookup prepopulated').hasId(acct.Id)){
				System.assertEquals(acctSegmentIdToName.get(acct.Account_Segment_lookup__c), acct.Account_Sub_Segment__c, 
					'Account_Sub_Segment__c field on accounts should be populated with the accountSegment name associated to the correct account segment');
			}else if(UnitTest.analyze('accounts without account segment lookup prepopulated').hasId(acct.Id)){
				System.assertEquals(null, acct.Account_Sub_Segment__c, 
					'accounts that dont have the Account_Segment_lookup__c populated should have Account_Sub_Segment__c as blank');
			}
		}
    }

    static testMethod void testAccountSegmentTriggerOnUpdate(){
    	setupAccountSegments();
    	UnitTest.addData(TestingUtils.createAccounts( 10, false ))
				.tag('Accounts').divide(2)
				.part('Accounts to get updated')
				.part('Accounts not to get updated');
		insert UnitTest.get(Account.SObjectType).getList();

		List<Account> oldAccounts = UnitTest.get('Accounts').getList().deepClone(true);
					
		UnitTest.get('Accounts to get updated')
				.property('Account_Segment_lookup__c').assignFrom('Account Segments');

		List<Account> newAccounts = UnitTest.get('Accounts').getList();

		Test.startTest();
			update UnitTest.get(Account.SObjectType).getList();
		Test.stopTest();

		Set<String> accountSegmentNamesOnAccounts = Pluck.strings('Name', (List<Account_Sub_Segment__c>) UnitTest.get('Account Segments').getList());
		List<Account> actualAccounts = [SELECT Id, Account_Sub_Segment__c, Account_Segment_lookup__c FROM Account];

		for(Account acct : actualAccounts){
			if(UnitTest.analyze('Accounts to get updated').hasId(acct.Id)){
				System.assertEquals(acctSegmentIdToName.get(acct.Account_Segment_lookup__c), acct.Account_Sub_Segment__c, 
					'Account_Sub_Segment__c field on accounts should be populated with the accountSegment name associated to the correct account segment');
			}else if(UnitTest.analyze('Accounts not to get updated').hasId(acct.Id)){
				System.assertEquals(null, acct.Account_Sub_Segment__c, 
					'accounts that dont have the Account_Segment_lookup__c field changed should not get updated');
			}
		}
    }*/
}