force-app/main/default/objects/Account/fields/AMD__c.field-meta.xml
<CustomField>
    <fullName>AMD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Managing Director
#34421: Data is copied from Country Parent
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>CP (Client Partner)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AMD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DMS_Owner__c.field-meta.xml
<CustomField>
    <fullName>DMS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#26660_ALM Business Unit Solution Development Executive (SDE). - Set at the Country Parent and cascades down to the Sales Site
#29959 Account: Relabel &quot;ALM SDE(Solution Development Executive)&quot; to &quot;ALM VSE/SE&quot;
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>ALM VSE/SE/AE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountslocG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enterprise_ISR__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ISR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Ignite: Enterprise Inside Sales Representative</description>
    <inlineHelpText>Enterprise Inside Sales Representative - Set at the Country Parent and cascades down to the Sales Site

#26660 : Account Coverage: Add new fields to Account Coverage Section</inlineHelpText>
    <label>Enterprise ISR</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account__c.field-meta.xml
<CustomField>
    <fullName>Global_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to flag an account as a global account that users can read and report on.</description>
    <label>Global Industries</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_Director__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As per case 14975976, label Global Account Director changed to Global Account Representative

#26231: Global Account Representative.  - Set at the IMGA and cascades down to the Country Parent &amp; Sales Site</description>
    <label>Global Account Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMcP3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_IMGA_Owner__c.field-meta.xml
<CustomField>
    <fullName>Global_IMGA_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#26231: Global Managing Director (MD). - Set at the IMGA and cascades down to the Country Parent &amp; Sales Site</description>
    <label>Global Managing Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Designation__c.field-meta.xml
<CustomField>
    <fullName>Program_Designation__c</fullName>
    <label>Program Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Global Account</fullName>
            </value>
            <value>
                <fullName>Strategic Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RIM_SDE__c.field-meta.xml
<CustomField>
    <fullName>RIM_SDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RIM Solution Development Executive
#34421: Copied from Country Parent
#35890- Update Account Coverage field labels according to new GTM strategy</description>
    <label>RIM SE/AE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RIM_SDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Solution_Executive__c.field-meta.xml
<CustomField>
    <fullName>Solution_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Solution Executive partners with sellers when/if RIM is being sold. SEs are auto added to Opp Split overlay as they will collect incentives from all RIM deals in their region</description>
    <label>Solution Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tele_CDE__c.field-meta.xml
<CustomField>
    <fullName>Tele_CDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#26660_Customer Success Manager (CSM). - Set at the Country Parent and cascades down to the Sales Site</description>
    <label>Customer Success Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsqNqG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Servicing_Region__c.field-meta.xml
<CustomField>
    <fullName>IM_Servicing_Region__c</fullName>
    <description>The IM servicing region related to the opportunity</description>
    <label>Servicing District/Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aberdeen</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahemdabad</fullName>
            </value>
            <value>
                <fullName>Aix</fullName>
            </value>
            <value>
                <fullName>Albuquerque</fullName>
            </value>
            <value>
                <fullName>Alphen</fullName>
            </value>
            <value>
                <fullName>Asheville</fullName>
            </value>
            <value>
                <fullName>Aston</fullName>
            </value>
            <value>
                <fullName>Athens</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Baltimore / Washington</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Barranquilla</fullName>
            </value>
            <value>
                <fullName>Basildon</fullName>
            </value>
            <value>
                <fullName>Baton Rouge</fullName>
            </value>
            <value>
                <fullName>Belfast</fullName>
            </value>
            <value>
                <fullName>Belfast - Northern Ireland</fullName>
            </value>
            <value>
                <fullName>Berlin</fullName>
            </value>
            <value>
                <fullName>Bhondsi</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bhubhneswar</fullName>
            </value>
            <value>
                <fullName>Bilbao</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Birmingham (UK)</fullName>
            </value>
            <value>
                <fullName>Bochum</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IME_Reason_Won__c.field-meta.xml
<CustomField>
    <fullName>IME_Reason_Won__c</fullName>
    <label>Reason Won</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Benchmarking</fullName>
            </value>
            <value>
                <fullName>Decision Location</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Relationship Strength</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Service Expectation</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>Technical Fit</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Most_Recent__c</fullName>
    <inlineHelpText>For new opportunities on existing customers, add the most recent source of the lead</inlineHelpText>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <inlineHelpText>The operational source system the customer ID is managed through</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SKP Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>Other Europe</fullName>
            </value>
            <value>
                <fullName>SB IMLA</fullName>
            </value>
            <value>
                <fullName>SKP IMLA</fullName>
            </value>
            <value>
                <fullName>Other IMLA</fullName>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>SKP IMAP</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SRMS IMAP</fullName>
            </value>
            <value>
                <fullName>Tape Guard IMAP</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>SB IMAP</fullName>
            </value>
            <value>
                <fullName>TRSQL</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TOBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SyncChildOppTeamsAndSplitsTest.cls
@isTest
private class SyncChildOppTeamsAndSplitsTest {
    
    @testSetup
    static void setupData() {
        AccountTriggerHandler.skipTriggerExecutionTestClass = true;
        OpportunityTriggerHandler.skipTriggerExecutionTestClass = true;
        
        // FIX: Create 5 distinct users to prevent Salesforce's "1 OTM per User per Opp" conflict limit
        List<User> users = TestingUtil.createUsers(5, true);
        
        // 2. Create IM Country (required by Opportunity in your org)
        IM_Country__c cntry = TestingUtil.createIMCountry();
        
        // 3. Create Account with distinct users for each role
        Account acc = new Account(
            Name = 'Test Sync Account',
            BillingCountry = 'United States',
            Solution_Executive__c = users[0].Id,  // User 1
            Enterprise_ISR__c = users[1].Id,      // User 2
            AMD__c = users[2].Id,                 // User 3
            RIM_SDE__c = users[3].Id              // User 4
        );
        insert acc;
        
        // 4. Create Opportunity manually
        Opportunity opp = new Opportunity(
            Name = 'test',
            AccountId = acc.Id,
            Source_System__c = 'test SKP Europe',
            Billing_Country__c = cntry.Id,
            Lead_Source_Most_Recent__c = 'x',
            StageName = '1 - Qualification',
            IM_Servicing_Region__c ='London',
            IME_Reason_Won__c = 'Benchmarking',
            IM_Booked_Date__c = System.today(),
            CloseDate = System.today(),
            Amount = 30000
        );
        insert opp;

        // 5. Create Product & Line Item (RIM BU)
        Product2 prod = new Product2(Name = 'RIM Product', IsActive = true);
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(), 
            Product2Id = prod.Id, 
            UnitPrice = 100, 
            IsActive = true
        );
        insert pbe;

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id, 
            PricebookEntryId = pbe.Id, 
            Quantity = 1, 
            TotalPrice = 100, 
            Product_Business_Unit__c = 'RIM'
        );
        insert oli;
    }

   @isTest
    static void testAccountFlowContext_InsertAndUpdate() {
        Account acc = [
            SELECT Id, Solution_Executive__c, Program_Designation__c, Global_Account__c, 
                   Global_IMGA_Owner__c, AMD__c, Enterprise_ISR__c, Tele_CDE__c, 
                   Global_Account_Director__c, DMS_Owner__c, RIM_SDE__c, 
                   Information_Governance_Rep__c, Primary_Local_Market_Rep_1__c 
            FROM Account LIMIT 1
        ];
        
        // Retrieve a fresh user to act as our replacement
        User userNewGAR = [
            SELECT Id FROM User 
            WHERE Id NOT IN (:acc.Global_Account_Director__c, :acc.Enterprise_ISR__c, :acc.AMD__c, :acc.RIM_SDE__c) 
            AND Alias LIKE 'ztest%' LIMIT 1
        ];
        
        // 1. INITIAL SYNC
        SyncChildOppTeamsAndSplits.SyncRequest req1 = new SyncChildOppTeamsAndSplits.SyncRequest();
        req1.accountRecord = acc;
        
        Test.startTest();
        SyncChildOppTeamsAndSplits.syncTeamsAndSplits(new List<SyncChildOppTeamsAndSplits.SyncRequest>{req1});
        
        // 2. UPDATE SYNC 
        acc.Global_Account_Director__c = userNewGAR.Id; // Change dynamic GAR
        acc.Enterprise_ISR__c = null;                   // Clear dynamic EISR
        acc.AMD__c = userNewGAR.Id;                     // Attempt to change static CP (should be ignored)
        
        SyncChildOppTeamsAndSplits.SyncRequest req2 = new SyncChildOppTeamsAndSplits.SyncRequest();
        req2.accountRecord = acc;
        
        SyncChildOppTeamsAndSplits.syncTeamsAndSplits(new List<SyncChildOppTeamsAndSplits.SyncRequest>{req2});
        Test.stopTest();
        
        // Verify GAR changed, EISR deleted, CP remained original user
        List<OpportunityTeamMember> updatedOtms = [SELECT TeamMemberRole, UserId FROM OpportunityTeamMember];
        Boolean garUpdated = false;
        Boolean cpRemained = false;
        
        for(OpportunityTeamMember otm : updatedOtms) {
            // Check GAR (Global Account Director)
            if(otm.TeamMemberRole == 'GAR' && otm.UserId == userNewGAR.Id) {
                garUpdated = true;
            }
            // Check CP (AMD)
            if(otm.TeamMemberRole == 'AMD' && otm.UserId != userNewGAR.Id) {
                cpRemained = true;
            }
            // Ensure EISR is gone
            if(otm.TeamMemberRole == 'Enterprise ISR') {
                System.assert(false, 'Enterprise ISR should have been deleted');
            }
        }
        
        System.assert(garUpdated, 'GAR should have updated to the new user');
        System.assert(cpRemained, 'Static CP (AMD) should NOT have updated');
    }

    @isTest
    static void testOppProductBeforeDeleteContext() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        OpportunityLineItem oli = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        
        Account acc = [
            SELECT Id, Solution_Executive__c, Program_Designation__c, Global_Account__c, 
                   Global_IMGA_Owner__c, AMD__c, Enterprise_ISR__c, Tele_CDE__c, 
                   Global_Account_Director__c, DMS_Owner__c, RIM_SDE__c, 
                   Information_Governance_Rep__c, Primary_Local_Market_Rep_1__c 
            FROM Account LIMIT 1
        ];
        
        // Initial sync to create the RIM role
        SyncChildOppTeamsAndSplits.SyncRequest initReq = new SyncChildOppTeamsAndSplits.SyncRequest();
        initReq.accountRecord = acc;
        SyncChildOppTeamsAndSplits.syncTeamsAndSplits(new List<SyncChildOppTeamsAndSplits.SyncRequest>{initReq});

        // SIMULATE PRODUCT DELETION
        SyncChildOppTeamsAndSplits.SyncRequest delReq = new SyncChildOppTeamsAndSplits.SyncRequest();
        delReq.oppId = opp.Id;
        delReq.deletedOliId = oli.Id; // Simulate the Before Delete Flow sending this OLI ID
        
        Test.startTest();
        SyncChildOppTeamsAndSplits.syncTeamsAndSplits(new List<SyncChildOppTeamsAndSplits.SyncRequest>{delReq});
        Test.stopTest();
        
        // Verify RIM role was deleted because the product is ignored in the query
        Integer rimRoles = [SELECT COUNT() FROM OpportunityTeamMember WHERE TeamMemberRole = 'RIM SE/AE'];
        System.assertEquals(0, rimRoles, 'RIM role should be deleted when last RIM product is removed');
    }
}