force-app/main/default/objects/Account/fields/Bill_To_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Site_Number__c</fullName>
    <label>Billing Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Legal_Entity_Country__c.field-meta.xml
<CustomField>
    <fullName>QTB_Legal_Entity_Country__c</fullName>
    <description>#SFCPQBLG-43 - its shows the legal entity&apos;s country of contract legal entity</description>
    <label>Legal Entity Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__BillingCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Bill_To_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Site_Number__c</fullName>
    <label>Bill To Site Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer_ID__r.IM_Customer_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IM_Market__c.field-meta.xml
<CustomField>
    <fullName>IM_Market__c</fullName>
    <formula>IF(AND(ISBLANK(Customer_ID__c), ISBLANK(AccountId)), &quot;Unassigned&quot;,
IF(AND(!ISBLANK(Customer_ID__c), !ISBLANK(Customer_ID__r.IM_District_Branch_Id__c)),Customer_ID__r.IM_District_Branch_Id__c,
IF(AND(!ISBLANK(AccountId), !ISBLANK(Account.QTB_Customer_District__c)),Account.QTB_Customer_District__c,&quot;Unassigned&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <formula>IF (AND(ISBlank(Customer_ID__c), ISBLANK(AccountId)), &quot;Unassigned&quot; ,
IF (AND(!ISBlank(Customer_ID__c), !ISBLANK(Customer_ID__r.Owning_District_Id__c)), Customer_ID__r.Owning_District_Id__r.Name,
IF (AND(!ISBlank(AccountId), !ISBLANK(Account.QTB_Market__c)),Account.QTB_Market__r.Name,
IF (OR(AND(!ISBlank(Customer_ID__c), ISBLANK(Customer_ID__r.Owning_District_Id__c)),
AND(!ISBlank(AccountId),ISBlank(Account.QTB_Market__c))),&quot;Unassigned&quot;,&quot;IME District&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Market Name; District Name; Branch Name; Service Location</inlineHelpText>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>QTB_Case_Number__c</fullName>
    <description>This is used to store the case number from the SMS.
Story No. - 20447</description>
    <label>QTB_Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_Service_Market_ID__c.field-meta.xml
<CustomField>
    <fullName>QTB_Service_Market_ID__c</fullName>
    <label>Service Market ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Completion_Date__c</fullName>
    <inlineHelpText>Date Service actually began for customer</inlineHelpText>
    <label>Service Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Schedule_Date__c</fullName>
    <inlineHelpText>Date Service to begin for the customer</inlineHelpText>
    <label>Service Schedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SITAD_Disposition_Type__c.field-meta.xml
<CustomField>
    <fullName>SITAD_Disposition_Type__c</fullName>
    <label>SITAD Disposition Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offsite Media Destruction - Bulk</fullName>
            </value>
            <value>
                <fullName>Offsite Media Destruction - Itemized Tapes</fullName>
            </value>
            <value>
                <fullName>Offsite Media Destruction - Itemized Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Bulk Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Bulk Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Hard Drives SSD</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Hard Drives Optical</fullName>
            </value>
            <value>
                <fullName>Onsite Degaussing</fullName>
            </value>
            <value>
                <fullName>Onsite Erasure</fullName>
            </value>
            <value>
                <fullName>eWaste Recycling Bulk (Scrap)</fullName>
            </value>
            <value>
                <fullName>IT Asset Audit Recycle</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing</fullName>
            </value>
            <value>
                <fullName>IT Asset Audit Recycle - Scan on Site</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Destroy Drives</fullName>
            </value>
            <value>
                <fullName>Standard Run</fullName>
            </value>
            <value>
                <fullName>Dedicated Run</fullName>
            </value>
            <value>
                <fullName>Shipping Tapes/Plastics</fullName>
            </value>
            <value>
                <fullName>Shipping Electronics or Mixed Material</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Medium IT Asset</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Scan on Site</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Bulk Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Bulk Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Destruction - Mobilization/Minimum Fee</fullName>
            </value>
            <value>
                <fullName>Remote Box - Box with Shipment Only</fullName>
            </value>
            <value>
                <fullName>Remote Box - Audit Remarket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Owning_District_Id__c.field-meta.xml
<CustomField>
    <fullName>Owning_District_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owning District Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Market__c.InActive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Owning District</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Owning_District_Id__c.field-meta.xml
<CustomField>
    <fullName>Owning_District_Id__c</fullName>
    <externalId>true</externalId>
    <label>Owning District Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/caseObjSITADJSONClass.cls
/******************************************************************************************************************************************
 * Class: caseObjSITADJSONClass
 * 
 * Change History:     11/07/2023
 * Developer           Date                Description
 * ------------------------------------------------------------------------------------------- 
 * Renuka Prasad       11/07/2023          Story #19589 - Changes to pass Billing Account Legal Entity for Country field for SMS Case Sync
 ******************************************************************************************************************************************/
public class caseObjSITADJSONClass{
    public cls_account account;
    public caseObjSITADJSONClass(Case Cas){
        this.account = new cls_account(Cas);
    }
    public class cls_account{
        public string customerAccountID;
        public string customerAccountName;
        //public string salesType;
        public string caseNumber;
        //public string serviceOrderDate;
        public string serviceScheduleDate;
        public string serviceCompletionDate;
        public string districtId; 
        public string marketName;
        public string salesRep;
        public cls_serviceAddress serviceAddress;
        public cls_serviceContact serviceContact;
        public List<dispositionObj> dispositionType;
        public cls_account(Case Cas){   
            //this.customerAccountID = Cas.Customer_ID__c;
            this.customerAccountId = Cas.Bill_To_Site_Number__c;//Cas.Customer_ID__r.name;
            this.customerAccountName = Cas.Account.Name;//Cas.Customer_Name__c;
            if(Cas.QTB_Case_Number__c != null){
                this.caseNumber = Cas.QTB_Case_Number__c;
            }else{
                this.caseNumber = Cas.CaseNumber;
            }
            
            this.serviceScheduleDate = string.ValueOf(Cas.Service_Schedule_Date__c);
            this.serviceCompletionDate = string.ValueOf(Cas.Service_Completion_Date__c);
            this.districtId = Cas.IM_Market__c;
            this.marketName = Cas.Market_Name__c;
            this.salesRep = Cas.Owner.name;//'Ed Fabian';
            this.serviceAddress = new cls_serviceAddress(Cas);
            this.serviceContact = new cls_serviceContact(Cas);
            this.dispositionType = new List<dispositionObj>();
            // This is for Multi Location when we get the Market from SMS(Program)
            if(String.isNotBlank(cas.QTB_Service_Market_ID__c)){
                this.districtId = cas.QTB_Service_Market_ID__c;
                //Get the respective Market Name
                List<Market__c> marIdList = [select Id,Name from Market__c where Owning_District_Id__c=:this.districtId];
                if(!marIdList.IsEmpty()){
                    this.marketName = marIdList[0].Name;
                } 
            }
            List<String> dispostionTypes = new List<string>();
            if(Cas.SITAD_Disposition_Type__c != null)
            dispostionTypes =cas.SITAD_Disposition_Type__c.split(';');
            
            for (String dispostionType : dispostionTypes){
                if(dispostionType!= null){
                    dispositionType.add(new dispositionObj(dispostionType));
                }            
            }    
        }
    }
    public class cls_serviceAddress{
        public cls_address address;
        public cls_serviceAddress(Case Ca){
            this.address = new cls_address(Ca);
        }
    }
    public class cls_address{
        public string street;
        public string city;
        public string state;
        public string postalCode;
        public string country;
        public cls_address(Case Cas){
            this.street = cas.Address__c;
            this.city = cas.City__c;
            this.state = cas.State__c;
            this.postalCode = cas.Zip__c;
            this.country = cas.Account.QTB_Legal_Entity_Country__c; //#19589 - Changes to pass Billing Account Legal Entity for Country field for SMS Case Sync
        }
    }
    public class cls_serviceContact{
        public string name;
        public string phoneNumber;
        public string emailAddress;
        public cls_serviceContact(Case caCon){
            this.name = caCon.Owner.Name;
            this.phoneNumber = caCon.Owner.Phone;
            this.emailAddress = caCon.Owner.Email;
        }
    }
    
   
    public class dispositionObj {
        public string dispositionValue;
        
        public dispositionObj(string disposition){
            this.dispositionValue = disposition;
        }
    }
   
}