force-app/main/default/objects/Account/fields/Bill_To_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Site_Number__c</fullName>
    <label>Billing Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Legal_Entity_Country__c.field-meta.xml
<CustomField>
    <fullName>QTB_Legal_Entity_Country__c</fullName>
    <description>#SFCPQBLG-43 - its shows the legal entity&apos;s country of contract legal entity</description>
    <label>Legal Entity Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__BillingCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Bill_To_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Site_Number__c</fullName>
    <label>Bill To Site Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Billing_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Email__c</fullName>
    <label>Billing Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Contact_Name__c</fullName>
    <label>Case Contact Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia / New Zealand</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>Customer_ID__r.IM_Customer_Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IM_Market__c.field-meta.xml
<CustomField>
    <fullName>IM_Market__c</fullName>
    <formula>IF(AND(ISBLANK(Customer_ID__c), ISBLANK(AccountId)), &quot;Unassigned&quot;,
IF(AND(!ISBLANK(Customer_ID__c), !ISBLANK(Customer_ID__r.IM_District_Branch_Id__c)),Customer_ID__r.IM_District_Branch_Id__c,
IF(AND(!ISBLANK(AccountId), !ISBLANK(Account.QTB_Customer_District__c)),Account.QTB_Customer_District__c,&quot;Unassigned&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <formula>IF (AND(ISBlank(Customer_ID__c), ISBLANK(AccountId)), &quot;Unassigned&quot; ,
IF (AND(!ISBlank(Customer_ID__c), !ISBLANK(Customer_ID__r.Owning_District_Id__c)), Customer_ID__r.Owning_District_Id__r.Name,
IF (AND(!ISBlank(AccountId), !ISBLANK(Account.QTB_Market__c)),Account.QTB_Market__r.Name,
IF (OR(AND(!ISBlank(Customer_ID__c), ISBLANK(Customer_ID__r.Owning_District_Id__c)),
AND(!ISBlank(AccountId),ISBlank(Account.QTB_Market__c))),&quot;Unassigned&quot;,&quot;IME District&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Market Name; District Name; Branch Name; Service Location</inlineHelpText>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>QTB_Case_Number__c</fullName>
    <description>This is used to store the case number from the SMS.
Story No. - 20447</description>
    <label>QTB_Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_Service_Market_ID__c.field-meta.xml
<CustomField>
    <fullName>QTB_Service_Market_ID__c</fullName>
    <label>Service Market ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_SITAD_Integration_Flag__c.field-meta.xml
<CustomField>
    <fullName>QTB_SITAD_Integration_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag is for checking whether this Case is Synced with SITAD system or not</description>
    <inlineHelpText>Indicator for SITAD sync</inlineHelpText>
    <label>SITAD Integration Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/QTB_SMS_Order_Details__c.field-meta.xml
<CustomField>
    <fullName>QTB_SMS_Order_Details__c</fullName>
    <description>Story - 19480
This field is used to display the SMS order details.</description>
    <label>SMS Order Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Completion_Date__c</fullName>
    <inlineHelpText>Date Service actually began for customer</inlineHelpText>
    <label>Service Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Order_Date__c</fullName>
    <inlineHelpText>Date Service order was created</inlineHelpText>
    <label>Initial Service Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Schedule_Date__c</fullName>
    <inlineHelpText>Date Service to begin for the customer</inlineHelpText>
    <label>Service Schedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SITAD_Disposition_Type__c.field-meta.xml
<CustomField>
    <fullName>SITAD_Disposition_Type__c</fullName>
    <label>SITAD Disposition Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offsite Media Destruction - Bulk</fullName>
            </value>
            <value>
                <fullName>Offsite Media Destruction - Itemized Tapes</fullName>
            </value>
            <value>
                <fullName>Offsite Media Destruction - Itemized Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Bulk Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Bulk Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Hard Drives SSD</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Itemized Hard Drives Optical</fullName>
            </value>
            <value>
                <fullName>Onsite Degaussing</fullName>
            </value>
            <value>
                <fullName>Onsite Erasure</fullName>
            </value>
            <value>
                <fullName>eWaste Recycling Bulk (Scrap)</fullName>
            </value>
            <value>
                <fullName>IT Asset Audit Recycle</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing</fullName>
            </value>
            <value>
                <fullName>IT Asset Audit Recycle - Scan on Site</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Destroy Drives</fullName>
            </value>
            <value>
                <fullName>Standard Run</fullName>
            </value>
            <value>
                <fullName>Dedicated Run</fullName>
            </value>
            <value>
                <fullName>Shipping Tapes/Plastics</fullName>
            </value>
            <value>
                <fullName>Shipping Electronics or Mixed Material</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Medium IT Asset</fullName>
            </value>
            <value>
                <fullName>IT Asset Remarketing - Scan on Site</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Bulk Tapes</fullName>
            </value>
            <value>
                <fullName>Onsite Shred - Bulk Hard Drives</fullName>
            </value>
            <value>
                <fullName>Onsite Destruction - Mobilization/Minimum Fee</fullName>
            </value>
            <value>
                <fullName>Remote Box - Box with Shipment Only</fullName>
            </value>
            <value>
                <fullName>Remote Box - Audit Remarket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Customer_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS_Customer_Sync_Date__c</fullName>
    <label>SMS Customer Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SMS_Order_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS_Order_Sync_Date__c</fullName>
    <label>SMS Order Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/SITAD_Flag__c.field-meta.xml
<CustomField>
    <fullName>SITAD_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag is for checking whether this Customer Account is Synced with SITAD system or not</description>
    <inlineHelpText>Indicator for SITAD sync</inlineHelpText>
    <label>SITAD Integration Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SITAD_Integration_Details__c/SITAD_Integration_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SITAD Integration Details</label>
</CustomObject>

force-app/main/default/objects/SITAD_Integration_Details__c/fields/Authorization_Head__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Head__c</fullName>
    <label>Authorization Head</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SITAD_Integration_Details__c/fields/caseObj_Endoint__c.field-meta.xml
<CustomField>
    <fullName>caseObj_Endoint__c</fullName>
    <label>caseObj Endoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SITAD_Integration_Details__c/fields/Token_endpoint__c.field-meta.xml
<CustomField>
    <fullName>Token_endpoint__c</fullName>
    <label>Token endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SKP_Sync_Error__c/SKP_Sync_Error__c.object-meta.xml
<CustomObject>
    <label>Sync Error</label>
    <nameField>
        <displayFormat>SKPErr-{0000000}</displayFormat>
        <label>SKP Sync Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Errors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SKP_Sync_Error__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sync Errors</relationshipLabel>
    <relationshipName>SKP_Sync_Errors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SKP_Sync_Error__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SITADIntegration_Lightning.cls
/**
     * Created By: Revathy Saminathan on 21-Feb-2020
     *          -- for the Sync to SMS button functionality to lightning compantability
     *          -- Case # 13188385 
     *          -- Related Visualforce Page : SITADIntegration_Lightning
     * Change History :
     *       Removed the fields (CDM_Global_Ultimate_ID__c,CDM_Global_Ultimate_Name__c) dependency as part of #16051
**/
global class SITADIntegration_Lightning {
    public static string caseObjJsonString;
    public static string customerAccJsonString;
    public static List<SKP_Sync_Error__c> SMSError = new List<SKP_Sync_Error__c>();
    public static List<SKP_Sync_Error__c> SMSCaseError;
    public static boolean calloutException=false;
    // Added by Revathy Saminathan
    public static String caseId{get; set;}
    public Case currentCaseRecored{get; set;} 
    public Id cs;
    private ApexPages.StandardController sctrl; 
    //Checking for Environment or SandBox
    public static Boolean runningInASandbox {
        get{
            if (runningInASandbox == null) {
                runningInASandbox = [SELECT Id, IsSandbox FROM Organization LIMIT 1].IsSandbox;
            }
            return runningInASandbox;
        } set;
    }
    
    //Getting Value From Custom Setting
    public static SITAD_Integration_Details__c sitadDetails{
        get{
            if(sitadDetails == null){
                string sandboxType = runningInASandbox ? 'Sandbox' : 'Production' ;
                sitadDetails = SITAD_Integration_Details__c.getInstance(sandboxType);
            }
            return sitadDetails;
        }
        set;
    }  
    public SITADIntegration_Lightning(ApexPages.StandardController controller)
    {
        this.cs = controller.getRecord().id;
        this.sctrl = controller;
        caseId = ApexPages.currentPage().getParameters().get('id'); 
    }
    public void sysnToSMS()
    {
        currentCaseRecored = [Select Id,Recordtype.name,CaseNumber,Billing_Contact_Email__c,SMS_Customer_Sync_Date__c,SMS_Order_Sync_Date__c from Case where Id =: this.cs];
        System.debug('Current Case Record Detail>>>>>>>'+currentCaseRecored);
        if(currentCaseRecored.Billing_Contact_Email__c == null && 
          (currentCaseRecored.recordtype.name =='NCSP: DP New Customer Setup'|| currentCaseRecored.recordtype.name =='NCSP: Upsell') ){
              Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Please add Billing contact email on Case before sending it to SMS'));

        }
        if(currentCaseRecored.SMS_Order_Sync_Date__c == Null)
        {
            try
            {
                String syncToSMS = callSMSSync(this.cs);


                Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,syncToSMS)); 
            }
            catch(exception e){
                  Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Something went worng. Please try after some time'+e));
            }
        }
        else if(currentCaseRecored.SMS_Order_Sync_Date__c != Null){
            Apexpages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Case is already Synced')); 
        }
    }
    
    //WebServices Method Called from "Sync To SMS" button for Create
    public static string callSMSSync(id caseId){
        String finalSecurityToken = SITADHelper.checkOAuthSecurityToken(sitadDetails.Token_endpoint__c,sitadDetails.Client_Id__c,sitadDetails.Client_Secret__c,sitadDetails.Authorization_Head__c);
        boolean caseExistError = false;
        SMSError.clear();   
         
        if(finalSecurityToken != null){
            System.debug('>>insideif'+caseId); 
            case caseDetails =[SELECT QTB_Case_Number__c,QTB_SITAD_Integration_Flag__c, SMS_Order_Sync_Date__c, Owner.Name, Owner.Phone, Owner.Email,SITAD_Disposition_Type__c, IM_Market__c, Owner.id, Market_Name__c, Service_Order_Date__c,Service_Schedule_Date__c, Service_Completion_Date__c, CaseNumber, Customer_Name__c, Account.Id,Account.Name,  Address__c,City__c,  State__c, Zip__c, Country__c, Case_Contact_Name__c, Contact.Phone, Contact.Email,Bill_To_Site_Number__c,QTB_SMS_Order_Details__c,QTB_Service_Market_ID__c,Account.QTB_Legal_Entity_Country__c FROM Case WHERE id=:caseId];
            System.debug('>>querycasedetails'+caseDetails.QTB_SITAD_Integration_Flag__c);
            if(caseDetails.QTB_SITAD_Integration_Flag__c == false){
                //Replaced caseDetails.Customer_ID__r.SITAD_Flag__c with caseDetails.QTB_SITAD_Integration_Flag__c as per #20941
                //Adding the Case - Bill To Site Number condition also to avoid the Error for SITAD.
                if(caseDetails.Bill_To_Site_Number__c == null || caseDetails.IM_Market__c == null){
                    System.debug('>>Bill_To_Site_Number__c'+caseDetails.Bill_To_Site_Number__c);
                    return 'Bill To Site Number/Disctrict cannot be blank';
                }
                else{
                    callCaseSMSSync(caseDetails, finalSecurityToken);// Commented this code #16080,20686 
                    if(calloutException){   
                        createSyncError(caseDetails.id, 'Case-Exception', 'calloutException');  
                        insertSyncError();  
                        updateCaseFields(caseDetails,false);                     
                        return 'Something went wrong. Please try after some time';
                        //return 'Synced to SITAD successfully';
                    }
                    if(SMSError.size()>0){
                        if(SMSError.size()==1){
                            insertSyncError();
                            //updateCaseFields(caseDetails,true);
                            return 'Case sync was not successful! Please check sync errors for details.';
                        }
                        else{
                            for(SKP_Sync_Error__c errr :SMSError){
                                if(errr.Error_Description__c.contains('Case already exists'))
                                caseExistError=true;                                
                            }
                            if(caseExistError == false){
                                insertSyncError();
                                updateCaseFields(caseDetails,false);
                                return 'Case sync was not successful! Please check sync errors for details.';
                            }
                        }
                    }  
                    updateCaseFields(caseDetails,true);
                }
            }
            return 'Synced to SITAD successfully';
        }
        else{
            return 'There was some problem with sync. Please try again later.';
        }
    }
    
    public static void updateCaseFields(case caseDetails, boolean caseSynced){        
        //Update Sync Date in Case     
        if(caseSynced){                                  
            //Updating the SITAD Integration Flag
            caseDetails.QTB_SITAD_Integration_Flag__c = true; //Setting caseDetails.QTB_SITAD_Integration_Flag__c to TRUE as per #20941
        	caseDetails.SMS_Order_Sync_Date__c = System.now();
        }
        update caseDetails; 
    }
    
    //WebServices Method for create Order // Commented this code #16080,20686 
    webService static void callCaseSMSSync(Case ca, string finalSecurityToken){
        Http httpCase = new Http();
        HTTPResponse caseResponse;
        HttpRequest caseRequest = new HttpRequest();
        try{            
            caseObjJsonString = JSON.serialize(new caseObjSITADJSONClass(ca));
            system.debug('## Case Obj Json String Insert Req==='+caseObjJsonString);
            string BasicAuthorization = 'Bearer'+' '+finalSecurityToken;
            /* Changes related to 20447*/
            //Start
            if(String.isBlank(ca.QTB_Case_Number__c)){
                caseRequest = SITADHelper.OAuthbuildRequest(sitadDetails.caseObj_Endoint__c,'POST',BasicAuthorization,caseObjJsonString); 
            }else{
                caseRequest = SITADHelper.OAuthbuildRequest(sitadDetails.caseObj_Endoint__c,'PUT',BasicAuthorization,caseObjJsonString); 
            }
            //Stop
            caseRequest.setTimeout(20000); 
            caseResponse  = httpCase.send(caseRequest); 
            System.debug('>>caseRequest'+caseRequest);
            string caseResponseBody = caseResponse.getBody();
            System.debug('caseResponseBody>>'+caseResponseBody);
            if(String.isNotBlank(caseResponseBody)){
                if(caseResponseBody.contains('Errors')){ 
                    caseObjSITADErrorResponse cusRes = (caseObjSITADErrorResponse)json.deserialize(caseResponseBody,caseObjSITADErrorResponse.class);
                    //insert Error message
                    createSyncError(ca.id, cusRes.Errors[0].Code, cusRes.Errors[0].Message);
                }else{
                    caseObjSITADJsonResponse cusRes = (caseObjSITADJsonResponse)Json.deserialize(caseResponseBody,caseObjSITADJsonResponse.class);
                } 
        	}
        }catch (Exception e){
            calloutException= true;
           
            System.debug('Order callout exception==Something went worng. Please try after some time'+e.getMessage()+e.getLineNumber());
        }
    }  
    public static void createSyncError(id casId, string ErrorCode, string ErrorDesc){
        SKP_Sync_Error__c SyncErr = new SKP_Sync_Error__c();
        SyncErr.Case__c = casId;
        SyncErr.Destination_System__c = 'SMS';
        SyncErr.Error_Code__c = ErrorCode;
        SyncErr.Error_Description__c = ErrorDesc;
        SMSError.add(SyncErr);
    }
    
    public static void insertSyncError(){        
        insert SMSError;
    }
    
    public pagereference cancel(){
        PageReference cancel = sctrl.cancel();
        return cancel;
    }   
}