force-app/main/default/objects/Account/fields/D_B_DUNS__c.field-meta.xml
<CustomField>
    <fullName>D_B_DUNS__c</fullName>
    <label>D&amp;B DUNS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMGA_Owner__c.field-meta.xml
<CustomField>
    <fullName>IMGA_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IMGA Owner To be Deleted</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsVymL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Competitor object that captures competitive information around IM competitors.</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Settings__c/Country_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Custom Settings</label>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/IM_Functional_Area__c.field-meta.xml
<CustomField>
    <fullName>IM_Functional_Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Archives</fullName>
            </value>
            <value>
                <fullName>Compliance Management</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Library</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Purchasing</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>IM_Lead_Source_Most_Recent__c</fullName>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound call</fullName>
                <label>Inbound Call</label>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>IM_Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-Suspect</fullName>
                <default>true</default>
                <label>0-Suspect</label>
            </value>
            <value>
                <fullName>1-Inquiry</fullName>
            </value>
            <value>
                <fullName>2-Marketing Qual</fullName>
            </value>
            <value>
                <fullName>3-Sales Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <formula>TEXT( Owner_Details__r.Sales_Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Competitor__c/Lead_Competitor__c.object-meta.xml
<CustomObject>
    <description>Joining object between lead and competitor</description>
    <label>Lead Competitor</label>
    <nameField>
        <displayFormat>LC-{000}</displayFormat>
        <label>Lead Competitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Competitor__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Lead Competitors</relationshipLabel>
    <relationshipName>Lead_Competitors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead_Competitor__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Competitors</relationshipLabel>
    <relationshipName>Lead_Competitors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Competitor__c/fields/Lead_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner_Email__c</fullName>
    <label>Lead Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/classes/Test_LeadCompetitorObject.cls
/** 
 *Author: Srinivasa Rao Mandalapu
 *Date: 12/13/2012
 *Comments: Test class for LeadCompetitorObject Trigger under Lead_Competitor__c.
 */
@isTest(SeeAllData=true)
private class Test_LeadCompetitorObject {
	
	public static String PopulateLeadOwnerEmail=null;
	
    static testMethod void TestPopulateLeadOwnerEmail() {
        List<Trigger_Activation_Settings__c> customsettings = Trigger_Activation_Settings__c.getall().values();
		List<Trigger_Activation_Settings__c> updatesettings = new List<Trigger_Activation_Settings__c>();
		for(Trigger_Activation_Settings__c cs : customsettings){
			if(cs.Object__c == 'Lead_Competitor__c') {
				cs.Value__c='True';
				updatesettings.add(cs);
			}
		}
		update updatesettings;
		
        // TO DO: implement unit test
        //Create a test user who belongs to 'North America' Sales Division.
        list<Profile> p1 = [SELECT Id FROM Profile WHERE Name like 'Standard User'];
        
        User u1 = new User();
        u1.FirstName = 'fName';
        u1.LastName = 'lName';
        u1.Email = 'Test@mail.com';
        u1.Username = 'Test9090909@mail.com';
        u1.Alias ='Test909';
        u1.CommunityNickname = 't909';
        u1.TimeZoneSidKey ='America/New_York';
        u1.LocaleSidKey = 'en_US';
        u1.EmailEncodingKey = 'UTF-8';
        u1.ProfileId = p1[0].id;
        u1.LanguageLocaleKey = 'en_US';
        u1.Country = 'United Kingdom';
        u1.Sales_Division__c = 'Europe';
        insert u1;
               
        IM_Country__c testCountry = new IM_Country__c(Name='United Kingdom');
        insert testCountry;
        IM_Alternative_Country_Name__c country = new IM_Alternative_Country_Name__c(IM_Country__c = testCountry.Id, 
                                                                                    Alternative_Name__c='United Kingdom');
        insert country;
        Country_Settings__c setting = new Country_Settings__c();
        setting.Name = 'United Kingdom';
        setting.object_name__c = 'Account';
        insert setting;
        
        Account A = new Account(name='AccountPratapTestMethod'+system.now(), 
                                  BillingCountry='United Kingdom', 
                                IMGA_Owner__c = u1.id, D_B_DUNS__c ='Test');
        insert A;
               
        //Create a new Lead
        Lead led1 = new Lead();
        led1.FirstName = 'led1fname';
        led1.LastName = 'led1lname';
        led1.Status = 'Open'; 
        led1.IM_Lead_Source_Most_Recent__c = 'Email'; 
        led1.IM_Lead_Stage__c = '1-Inquiry';
        led1.Company = 'Account4UnitTest';
        led1.Email = 'testemail@email.com';
        led1.Street = '745 Atlantic Ave';
        led1.City = 'London';
        led1.State = 'London';
        led1.PostalCode = 'SE1 2TT';
		led1.IM_Functional_Area__c = 'x';
		led1.OwnerId = u1.Id;
        insert led1;
        
        //Create a new Competitor.
        Competitor__c comp = new Competitor__c();
        comp.Name = 'Test Comp';
        insert comp;
        
        //Create a new Lead Competitor.
        Lead_Competitor__c leadComp = new Lead_Competitor__c();
        leadComp.Lead__c = led1.Id;
        leadComp.Competitor__c = comp.Id;
        leadComp.Lead_Owner_Email__c = led1.Owner.Email;
        insert leadComp;
    }    
}