force-app/main/default/objects/Account/fields/IM_DUNS_NBR__c.field-meta.xml
<CustomField>
    <fullName>IM_DUNS_NBR__c</fullName>
    <label>Site (Company) DUNS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IM_Sales_Segment__c.field-meta.xml
<CustomField>
    <fullName>IM_Sales_Segment__c</fullName>
    <label>Sales Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Mid Market</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CDM_Utility.cls
/****************************** 
   Developer Name    : Madhu Paladugu
   
   Date              : 10/18/13
   
   Company Name      : CloudFountain Inc.
   
   Purpose           : This class is used as test utility for CDM_Utility class. 
   
   Dependents        : Apex Class  : CDM_Utility 
   
   Case Number       : 01733573
                                  
 ********************************/ 

@isTest//(seeAllData=true)
public class Test_CDM_Utility{
 /*   
    public static TestMethod void doTest(){
          
        IM_Country__c c = new IM_Country__c(name='United States');
        insert c;
        
        //create dummy account
        Account a=new Account(Name='test',type='Customer',BillingCountry='United States',IM_Sales_Segment__c='Channel',BillingStreet='683 c',BillingCity='Boston',BillingState='MA',BillingPostalCode='02120',IM_DUNS_NBR__c='test');
        insert a;
        
        List<Account> AccountList=new List<Account>();
        AccountList.add(a);
        String message='Test';
        
        //cal methods for test coverage
        CDM_Utility.feedRegularPost(message,AccountList);
        CDM_Utility.feedCSVfilePost(message,AccountList);
    }
*/
}