force-app/main/default/objects/Account/fields/IM_Enterprise_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>IM_Enterprise_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enterprise Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IM_IMGA__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA__c</fullName>
    <description>This formula will  traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;Book of Business/IMGA&quot;.
If there is no such level parent in the hierarchy - will leave field blank</description>
    <formula>/* 
This formula will traverse the Account hierarchy from (including) current record all the way to the top (up to 6 levels) and will display the Name of the parent Account where IM_HIerarchy_Level__c field is &quot;IM Group (IMGA)&quot;. 
If there is no such level parent in the hierarchy - will leave field blank 
*/ 


/* If No Parent AND this Record Hierarchy level IS NOT IMGA leave blank */ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )!=&apos;IM Group (IMGA)&apos;, &apos;&apos;, 

/*Else If No Parent AND this Record Hierarchy level IS IMGA use Name field from this record*/ 
IF (LEN(ParentId)==0 &amp;&amp; TEXT( IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Name, 


/*Else If parent is IMGA-Level, get name from parent*/ 
IF(TEXT( Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Name, 

/*Else If second parent is IMGA-Level, get name from second parent*/ 
IF(TEXT( Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Name, 

/*Else If third parent is IMGA-Level, get name from third parent*/ 
IF(TEXT( Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Name, 

/*Else If fourth parent is IMGA-Level, get name from fourth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, Parent.Parent.Parent.Parent.Name, 

/*Else If fifth parent is IMGA-Level, get name from fifth parent*/ 
IF(TEXT( Parent.Parent.Parent.Parent.Parent.IM_Hierarchy_Level__c )==&apos;IM Group (IMGA)&apos;, 
Parent.Parent.Parent.Parent.Parent.Name, 

/*Else (when reached up six levels, if no IMGA-level parent found - then put blank.*/ 
&apos;&apos; ) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Iron Mtn Grouping (IMGA)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IM_IMGA_Indexed__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA_Indexed__c</fullName>
    <description>Indexed IMGA field used for reporting. Populated by background process by copying values from the calculated formula field IM_IMGA</description>
    <inlineHelpText>Indexed IMGA field used for reporting. Populated by background process by copying values from the calculated formula field &quot;Iron Mtn Grouping (IMGA)&quot;</inlineHelpText>
    <label>IM Group (IMGA)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Effective_Date__c</fullName>
    <label>Contract Effective Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Contract_Signed__c</fullName>
    <inlineHelpText>Effective date of Customer Signature</inlineHelpText>
    <label>Date Contract Signed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Paperwork_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Paperwork_Received__c</fullName>
    <inlineHelpText>Date contract or internal paperwork (Dept Adds) received</inlineHelpText>
    <label>Date Paperwork Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Department Add</fullName>
            </value>
            <value>
                <fullName>New Service Line</fullName>
            </value>
            <value>
                <fullName>New Deal</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Service_line__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Service_line__c</fullName>
    <label>NCSP Service Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accutrac</fullName>
            </value>
            <value>
                <fullName>CDR</fullName>
            </value>
            <value>
                <fullName>Cloud Archive</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Data Center</fullName>
            </value>
            <value>
                <fullName>DB&amp;R</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>DRCMI</fullName>
            </value>
            <value>
                <fullName>eVault</fullName>
                <label>EVault</label>
            </value>
            <value>
                <fullName>Geological Core</fullName>
            </value>
            <value>
                <fullName>Iron Cloud</fullName>
            </value>
            <value>
                <fullName>Live Vault</fullName>
            </value>
            <value>
                <fullName>One Time Shred</fullName>
            </value>
            <value>
                <fullName>RM</fullName>
            </value>
            <value>
                <fullName>RM/Shred</fullName>
            </value>
            <value>
                <fullName>RM Pathology</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>SKP Shell</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Vault Climate Control</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Upsell_Type__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Upsell_Type__c</fullName>
    <label>NCSP Upsell Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NCSP_Service_line__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cloud Archive</fullName>
            </value>
            <value>
                <fullName>CloudBlue</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>DRCMI</fullName>
            </value>
            <value>
                <fullName>EMC</fullName>
            </value>
            <value>
                <fullName>Evault</fullName>
            </value>
            <value>
                <fullName>Internal ITAD</fullName>
            </value>
            <value>
                <fullName>Inventory Transfer</fullName>
            </value>
            <value>
                <fullName>Library Move</fullName>
            </value>
            <value>
                <fullName>Live Vault</fullName>
            </value>
            <value>
                <fullName>Media Destruction</fullName>
            </value>
            <value>
                <fullName>OTO</fullName>
            </value>
            <value>
                <fullName>Paper Destruction</fullName>
            </value>
            <value>
                <fullName>Program</fullName>
            </value>
            <value>
                <fullName>Service Frequency</fullName>
            </value>
            <value>
                <fullName>SITAD Closure</fullName>
            </value>
            <value>
                <fullName>Storage Increase</fullName>
            </value>
            <value>
                <fullName>Supply Increase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Non_Standard__c.field-meta.xml
<CustomField>
    <fullName>Non_Standard__c</fullName>
    <label>Non Standard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Customer_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>IM_Customer_Account_Name__c</fullName>
    <description>Descriptive name of Customer account from external (Billing) system</description>
    <inlineHelpText>Descriptive name of Customer account from external (Billing) system</inlineHelpText>
    <label>Customer Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_IMGA__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA__c</fullName>
    <formula>IM_Account__r.IM_IMGA_Indexed__c</formula>
    <label>IMGA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Status__c.field-meta.xml
<CustomField>
    <fullName>IM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Original_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>IM_Original_Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Deal</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Framework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Original_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>IM_Original_Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Security__c/Opportunity_Security__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Security Field Settings</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Security__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of Field to use in Oppty Sharing Logic</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Security__c/fields/Visibility_Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Access_Level__c</fullName>
    <description>R for Read
W for Write</description>
    <label>Visibility Access Level</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/OpportunityProductSelection__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to take product class and product line names in to apex class while adding product</description>
    <label>OpportunityProductSelection</label>
</CustomObject>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Class_Name__c</fullName>
    <label>Product Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RenewalOppWizardCtrl2lightning.cls
@isTest
public class Test_RenewalOppWizardCtrl2lightning {
    
    private static final String IMGA = 'IM_UCB';
    private static final String  DEAL_TYPE = 'DEAL TYPE';
    private static final String  SERVICE_LINE1 = 'SERVICE LINE1';
    private static final String  SERVICE_LINE2 = 'SERVICE LINE2';
    private static final String  UPSELL_TYPE1 = 'UPSELL TYPE1';
    private static final String  UPSELL_TYPE2 = 'UPSELL TYPE2';
    
    private static final String  TEST_CUSTOMER_ACCOUNT = 'Search String Customer Account';
    private static final String  ACTIVE = 'Active';
    
    private static Opportunity testOpportunity;
    private static Account testAccount;
    private static void setupCustomSettings()
    {
        TestingUtils.setupCountryCustomSettings(true);
        setupOpportunitySecuritySettings();
        OpportunityProductSelection__c oppprodsel = new OpportunityProductSelection__c();	
        oppprodsel.Name = 'CloudSolutionsProduct';	
        oppprodsel.Product_Class_Name__c = 'Data Backup and Recovery';	
        oppprodsel.Product_Line_Name__c = 'Cloud Solutions';              	
        insert oppprodsel; 	
        
    }
    
     private static void setupOpportunitySecuritySettings()
    {
       List<Opportunity_Security__c> settings = new List<Opportunity_Security__c>();
        //settings.add(new Opportunity_Security__c(Name='Enterprise Account Executive', Field_Name__c = 'IM_Enterprise_Account_Executive__c', Object_Name__c = 'Account', Visibility_Access_Level__c = 'W') );
        settings.add(new Opportunity_Security__c(Name='Enterprise Account Manager', Field_Name__c = 'IM_Enterprise_Account_Manager__c', Object_Name__c = 'Account', Visibility_Access_Level__c = 'R') );
      //  settings.add(new Opportunity_Security__c(Name='Inside Sales – RM', Field_Name__c = 'physical_isr__c', Object_Name__c = 'Postal_Code', Visibility_Access_Level__c = 'W') );
        settings.add(new Opportunity_Security__c(Name='Original Lead Owner', Field_Name__c = 'IM_Original_Lead_Owner__c', Object_Name__c = 'Opportunity', Visibility_Access_Level__c = 'W') );
     /*   settings.add(new Opportunity_Security__c(Name='Physical Hybrid', Field_Name__c = 'physical_hybrid__c', Object_Name__c = 'Postal_Code', Visibility_Access_Level__c = 'W') );
        settings.add(new Opportunity_Security__c(Name='Physical RM', Field_Name__c = 'physical_rm__c', Object_Name__c = 'Postal_Code', Visibility_Access_Level__c = 'W') );
        settings.add(new Opportunity_Security__c(Name='Physical – DB&R', Field_Name__c = 'physical_dp__c', Object_Name__c = 'Postal_Code', Visibility_Access_Level__c = 'W') );
*/
            
                insert settings;
          
    }
    
    static void setupOpportunity()
    {
        setupCustomSettings();
        testAccount = TestingUtils.createAccounts(1, false)[0];
        testAccount.IM_IMGA_Indexed__c = IMGA;
        insert testAccount;
        testOpportunity = TestingUtils.createOpportunity('testOpp', testAccount.Id, true);
        List<IM_Customer_Account__c> custAccountsToInsert = new List<IM_Customer_Account__c>();
        IM_Customer_Account__c custAcc1 = TestingUtils.createCustomerAccount(testAccount.Id, false);
        custAccountsToInsert.add(custAcc1);
        IM_Customer_Account__c custAcc2 =TestingUtils.createCustomerAccount(testAccount.Id, false);
        custAcc2.IM_Status__c = ACTIVE;
        custAcc2.name = TEST_CUSTOMER_ACCOUNT;
        custAccountsToInsert.add(custAcc2);
        insert custAccountsToInsert;
    }
    
    static void setupCaseInputOnStep1(RenewalOppWizardCtrl2lightning controller)
    {
        controller.ctrlCaseWith1stServLine.Deal_Type__c = DEAL_TYPE;
        controller.ctrlCaseWith1stServLine.Non_Standard__c = 'true'; 
        controller.ctrlCaseWith1stServLine.NCSP_Service_line__c = SERVICE_LINE1; 
        controller.ctrlCaseWith1stServLine.NCSP_Upsell_Type__c = UPSELL_TYPE1; 
        controller.ctrlCaseWith2ndServLine.NCSP_Service_line__c = SERVICE_LINE2; 
        controller.ctrlCaseWith2ndServLine.NCSP_Upsell_Type__c = UPSELL_TYPE2; 
        controller.ctrlCaseWith1stServLine.Date_Contract_Signed__c = System.today();
        controller.ctrlCaseWith1stServLine.Date_Paperwork_Received__c = System.today();
        controller.ctrlCaseWith1stServLine.Contract_Effective_Date__c = System.today();
    }
    
    private static RenewalOppWizardCtrl2lightning setupController ( Pagereference currentPage ){
        Test.setCurrentPage( currentPage );
        Apexpages.currentPage().getParameters().put( RenewalOppWizardCtrl2lightning.OPP_ID_PARAM, testOpportunity.Id );
        return new RenewalOppWizardCtrl2lightning();
    }
    static testMethod void testConstructor()
    {
        setupOpportunity();
        test.startTest();
        RenewalOppWizardCtrl2lightning controller =  setupController ( Page.renewalOppWizard2_step1_Lightning);
        test.stopTest();
        
        System.assert( !Apexpages.hasMessages() , 'There should be no messages');
        System.assertEquals(testOpportunity.Id ,controller.opportunityId ,'Opportunity Id parameter should have properly retrieved from URL ');
        System.assertEquals(testAccount.Id, controller.accountId ,'Opportunity Id parameter should have properly retrieved from URL ');
        System.assertEquals(IMGA ,controller.imga ,'Opportunity Id parameter should have properly retrieved from URL ');
        System.assert( !controller.showSearchResults , 'The show search Result Flag should be defaulted to false');
        System.assert( !controller.showListOfAttachments , 'The show list of attachment Fag should be defaulted to false');
        
    }
    static testMethod void testPrevious()
    {
        final PageReference EXPECTED_PREVIOUS = Page.Renewaloppwizard2_step2_Lightning;
        setupOpportunity();
        RenewalOppWizardCtrl2lightning ctr = setupController( EXPECTED_PREVIOUS );
        Test.startTest();
        ctr.redirectToStep3();
        PageReference actualPrev = ctr.previous();
        Test.stopTest();
        System.assertEquals(EXPECTED_PREVIOUS , actualPrev, 'The user should be redirected to the previous page');
    }

    static testMethod void testStep3createCases()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        setupCaseInputOnStep1(controller);
        Test.startTest();
        PageReference resultPageRef =  controller.redirectToStep2();
        controller.nextForSetCon();
        controller.previousForSetCon();
        controller.last();
        controller.first();
        controller.cancelForSetCon();
        
        controller.createCase();
        Test.stopTest();
        List<IM_Customer_Account__c> existingImgaCustAccounts = [Select Id, Name,IM_Customer_Account_Name__c,IM_Account__c,IM_Account__r.name,IM_Status__c FROM IM_Customer_Account__c where IM_IMGA__c=:IMGA And IM_Status__c = 'Active' Order By Name limit 1000];
        System.assertEquals(existingImgaCustAccounts.size() ,controller.imgaCustomerAccountWrappers.size(),' IMGA Customer Account Section should show all the Active Customer Accounts with matching IMGA ');
       
        List<Apexpages.Message> msgs = ApexPages.getMessages();
		for(Apexpages.Message msg:msgs){
            system.debug('mmmmmm '+msg.getDetail());
        }

        
        System.assert(!Apexpages.hasMessages(), 'There should be no messages');
       // System.assertEquals(Page.renewalOppWizard2_step2.getUrl(), resultPageRef.getUrl());
        
        List<Case> insertedCases=  [Select id,Deal_Type__c,Setup_Type__c,Non_Standard__c,Date_Contract_Signed__c,Date_Paperwork_Received__c,Contract_Effective_Date__c from Case where NCSP_Opportunity__c=:testOpportunity.id and accountId =:testAccount.id];
        System.assertEquals(2, insertedCases.size(), 'Two cases should have been inserted');
        Case case1 = insertedCases[0];
        Case case2 = insertedCases[1];
        System.assertEquals(case1.Deal_Type__c ,case2.Deal_Type__c ,'Case values not properly cloned');
        System.assertEquals(case1.Setup_Type__c ,case2.Setup_Type__c ,'Case values not properly cloned');
        System.assertEquals(case1.Non_Standard__c ,case2.Non_Standard__c ,'Case values not properly cloned');
        System.assertEquals(case1.Date_Contract_Signed__c ,case2.Date_Contract_Signed__c  ,'Case values not properly cloned');
        System.assertEquals(case1.Date_Paperwork_Received__c ,case2.Date_Paperwork_Received__c ,'Case values not properly cloned');
        System.assertEquals(case1.Contract_Effective_Date__c ,case2.Contract_Effective_Date__c ,'Case values not properly cloned');
  }
    static testMethod void testCancel()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        setupCaseInputOnStep1(controller);
        Test.startTest();
        PageReference cancelPageRef = controller.cancel();
        Test.stopTest();
        System.assertEquals('/' + controller.opportunityId , cancelPageRef.getUrl());
    }
    static testMethod void testStep2SearchCaseCustomerAccount()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        setupCaseInputOnStep1(controller);
        
        controller.redirectToStep2();
        Test.startTest();
        controller.searchText = 'Search';
        controller.search();
        Test.stopTest();
        system.assertEquals(1, controller.searchCustomerAccountWrappers.size(), 'Search should have returned matching customer accounts');
    }
    static testMethod void testStep3uploadAttachment()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        controller.attachment.ParentId = controller.opportunityId; // the record the file is attached to
        controller.attachment.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        controller.attachment.description ='Unit Test Attachment Description';
        controller.attachment.body=bodyBlob;
        test.startTest();
        controller.upload();
        test.stopTest();
        System.assert(true,controller.showListOfAttachments);
        List<Attachment> attachments = [Select id from Attachment];
        System.assertEquals(1,attachments.size());
    }
    
     static testMethod void testStep3createCaseWith2ndServiceLineBlank()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        setupCaseInputOnStep1(controller);
        controller.ctrlCaseWith2ndServLine.NCSP_Service_line__c = '';
        controller.ctrlCaseWith2ndServLine.NCSP_Upsell_Type__c = '';
        controller.redirectToStep2();
        controller.imgaCustomerAccountWrappers[0].checked = true;
        test.startTest();
        Pagereference step2PageRef = controller.redirectToStep3();
        controller.createCase();
        Pagereference step3PageRef = controller.redirectToCase();
        test.stopTest();
      //  System.assertEquals(Page.Renewaloppwizard2_step3_Lightning.getUrl(), step2PageRef.getUrl());
        System.assertEquals('/'+controller.casesToBeInserted[0].id, step3PageRef.getUrl());
        System.assertEquals(1,controller.caseCustomerAccountsToBeInserted.size());
        List<Case_Customer_Account__c> insertedCaseCustAccounts = [Select Id from Case_Customer_Account__c];
        System.assertEquals(1,insertedCaseCustAccounts.size());
    }
    static testMethod void testStep3createCaseWith2ndServiceLinePopulated()
    {
        setupOpportunity();
        RenewalOppWizardCtrl2lightning controller = setupController( Page.renewalOppWizard2_step1_Lightning );
        setupCaseInputOnStep1(controller);
        controller.redirectToStep2();
        controller.imgaCustomerAccountWrappers[0].checked = true;
        test.startTest();
        Pagereference step2PageRef = controller.redirectToStep3();
        controller.createCase();
        Pagereference step3PageRef = controller.redirectToCase();
        test.stopTest();
       // System.assertEquals(Page.Renewaloppwizard2_step3_Lightning.getUrl(), step2PageRef.getUrl());
        System.assertEquals('/'+controller.casesToBeInserted[0].id, step3PageRef.getUrl());
        System.assertEquals(2,controller.caseCustomerAccountsToBeInserted.size());
        List<Case_Customer_Account__c> insertedCaseCustAccounts = [Select Id from Case_Customer_Account__c];
        System.assertEquals(2,insertedCaseCustAccounts.size());
    }

}