force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Competitor object that captures competitive information around IM competitors.</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/Iron_Mountain_Storage_Profile__c.object-meta.xml
<CustomObject>
    <label>Iron Mountain Storage Profile</label>
    <nameField>
        <displayFormat>IMSP - {00000}</displayFormat>
        <label>Iron Mountain Storage Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iron Mountain Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Iron Mountain Storage Profiles</relationshipLabel>
    <relationshipName>Iron_Mountain_Storage_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_Cube__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_Cube__c</fullName>
    <inlineHelpText>Total CF of customer storage volume with IM (total for all accounts in this IMGA).</inlineHelpText>
    <label>Existing IM Storage Volume - Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_DB_R_Container__c</fullName>
    <inlineHelpText>Shows the quantity Iron Mountain has sold to this customer</inlineHelpText>
    <label>Existing IM Storage Volume - DPUs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_Tape__c</fullName>
    <inlineHelpText>Shows the quantity Iron Mountain has sold to this customer</inlineHelpText>
    <label>Existing IM Storage Volume - Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_Cube__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_Cube__c</fullName>
    <inlineHelpText>This is the total amount of records storage (in CF) the customer has/needs regardless of location (at customer site, competitors, etc.)</inlineHelpText>
    <label>Overall Customer Storage Volume-Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_DB_R_Container__c</fullName>
    <inlineHelpText>Enter the profiled customer need.</inlineHelpText>
    <label>Overall Storage Volume - DPUs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_Tape__c</fullName>
    <inlineHelpText>Enter the profiled customer need.</inlineHelpText>
    <label>Overall Customer Storage Volume – Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_Cube__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_Cube__c</fullName>
    <formula>Profiled_Quantity_Cube__c -(IM_Quantity_Cube__c + Competitor_Quantity_Cube__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The difference between the total amount of overall customer storage volume and what storage volume IM has (It’s calculated for you).</inlineHelpText>
    <label>Potential New Storage Volume - Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_DB_R_Container__c</fullName>
    <formula>Profiled_Quantity_DB_R_Container__c -( IM_Quantity_DB_R_Container__c + Competitor_Quantity_DB_R_Container__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Potential New Storage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_Tape__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_Tape__c</fullName>
    <formula>Profiled_Quantity_Tape__c -( IM_Quantity_Tape__c +  Competitor_Quantity_Tape__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Potential New Storage Volume - Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/Storage_Profile__c.object-meta.xml
<CustomObject>
    <description>Object used to capture which vendor controls existing cube and tape at an account</description>
    <label>Competitor Storage Profile</label>
    <nameField>
        <displayFormat>StorageProfile-{0000}</displayFormat>
        <label>Storage Profile Name (cust-vendor-type)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Profile__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>IMGA Account record</description>
    <label>Customer</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Storage Profile records can only be associated to an IMGA record</errorMessage>
        <filterItems>
            <field>Account.IM_Hierarchy_Level__c</field>
            <operation>equals</operation>
            <value>IM Group (IMGA)</value>
        </filterItems>
        <infoMessage>Storage Profile records can only be associated to an IMGA record</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Storage_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Iron_Mountain_Storage_Profile__c.field-meta.xml
<CustomField>
    <fullName>Iron_Mountain_Storage_Profile__c</fullName>
    <label>Iron Mountain Storage Profile</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Iron_Mountain_Storage_Profile__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Iron_Mountain_Storage_Profile__c</referenceTo>
    <relationshipLabel>Competitor Storage Profiles</relationshipLabel>
    <relationshipName>Storage_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Enter the total number of cube, tapes or DB&amp;R containers serviced by this vendor</inlineHelpText>
    <label>Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Tape__c</fullName>
    <label>Quantity (Tape)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Competitors table</description>
    <inlineHelpText>Search for the competitor&apos;s name. If Iron Mountain owns this storage business search for Iron Mountain. If this is un-vended search for InHouse</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipName>Storage_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestStorageProfilePageCont.cls
@isTest
private class TestStorageProfilePageCont 
{
	static final Integer NUM_OF_IM_STORAGE_PROFILES = 2;
    	

    
    static Account IMGA_Account;
    static List<Iron_Mountain_Storage_Profile__c> testIMStorageProfiles;
    static List<Competitor__c> testCompetitors;
    static List<Storage_Profile__c> testStorageProfiles;
    
	static StorageProfilePageCont setupPage( Account testAccount )
	{
		ApexPages.StandardController sc = new ApexPages.StandardController ( testAccount );
		StorageProfilePageCont spCont = new StorageProfilePageCont();
		spCont.accountID = testAccount.id;
		spCont.returnID = testAccount.id;
    	return spCont;
	}
	
	static void setup()
	{
		setup(true);
	}
	
	static void setup( boolean createProfilesAndCompetitors )
	{
		IMGA_Account = Testingutils.createAccounts( 1, false )[0];
    	IMGA_Account.RecordTypeId = Testingutils.IMGA_ACCOUNT_RECORD_TYPE.Id;
    	IMGA_Account.IM_Hierarchy_Level__c = 'IM Group (IMGA)';	
    	insert IMGA_Account;
    	
    	if( createProfilesAndCompetitors )
    	{
	    	testIMStorageProfiles = TestingUtils.createIronMountainStorageProfiles( NUM_OF_IM_STORAGE_PROFILES, IMGA_Account.Id, 0, 0, 0,  true );
	    	testCompetitors = TestingUtils.createCompetitors( NUM_OF_IM_STORAGE_PROFILES, 'Test Comp', true );
	    	testStorageProfiles = new List<Storage_Profile__c>();
	    	
	    	for( Integer i = 0; i < NUM_OF_IM_STORAGE_PROFILES; i++ )
	    	{
	    		testStorageProfiles.add( TestingUtils.createStorageProfile( testIMStorageProfiles[i].Id, IMGA_Account.Id, testCompetitors[i].Id, 0, 0, 0, false ) );
	    	}
	    	insert testStorageProfiles;
    	}
	}
	
	static testMethod void testSaveNegativeTapeWhitespace()
	{
		final Integer SAMPLE_QUANTITY = 50;
		
		setup();
    	setupPage( IMGA_Account );
    	
		StorageProfilePageCont controller = setupPage( IMGA_Account );
		
    	for( Iron_Mountain_Storage_Profile__c aIMStorageProfile : controller.ironMountainStorageProfileMap.values() )
    	{
    		aIMStorageProfile.Profiled_Quantity_Tape__c = SAMPLE_QUANTITY;
    		aIMStorageProfile.IM_Quantity_Tape__c = SAMPLE_QUANTITY;
    		
    		Storage_Profile__c relatedStorageProfile = aIMStorageProfile.Storage_Profiles__r[0];
    		relatedStorageProfile.Quantity_Tape__c = 1;
    	}
    	
    	Test.startTest();
    		controller.save();
    	Test.stopTest();
    	
    	System.assert(ApexPages.hasMessages(),'There should be an error');
    	System.assert(TestingUtils.pageMessageContains(System.Label.Negative_Whitespace_Alert),'We expect to show a warning message when the whitespace calculates to less than 0');		
	}

	static testMethod void testViewPageWithEmptyProfile()
	{
		final boolean createProfileAndCompetitors = false;
		
		setup( createProfileAndCompetitors );
    	
    	Test.startTest();
    		StorageProfilePageCont controller = setupPage( IMGA_Account );
    	Test.stopTest();
    	
    	System.assert(!controller.atLeastOneIronMountainStorageProfile,'There should be no profiles');
    	System.assertEquals(IMGA_Account.ID, controller.emptyIronMountainStorageProfile[0].Account__c,'The blank profile should be tied to the correct account');
    	
    	String expectedPage = Page.StorageProfileNew.getUrl();
    	String expectedRetUrl = 'retURL=%2F' + IMGA_Account.Id;
    	String expectedAcctParam = StorageProfileContExt.ACCOUNT_ID_PARAM+'=' + IMGA_Account.Id;
    	
    	System.assertEquals(IMGA_Account.ID, controller.emptyIronMountainStorageProfile[0].Account__c,'The blank profile should be tied to the correct account');
    	System.assert(controller.createNewCompetitorProfile.contains( expectedPage ),'The correct page should be referenced');
    	System.assert(controller.createNewCompetitorProfile.contains( expectedRetUrl ),'The correct return id should be in the page reference');
    	System.assert(controller.createNewCompetitorProfile.contains( expectedAcctParam ),'The correct accountid should be in the page reference');
    	
	}

	static testMethod void testSaveNewProfilePageWithEmptyProfile()
	{
		testSaveProfilePage( true );
	}	
	
	static testMethod void testSaveProfilePageWithEmptyProfile()
	{
		testSaveProfilePage( false );
	}
		
	static void testSaveProfilePage( boolean saveNew )
	{
		final boolean createProfileAndCompetitors = false;
		
		setup( createProfileAndCompetitors );
    	
    	Test.startTest();
    		StorageProfilePageCont controller = setupPage( IMGA_Account );
    		
    		if( saveNew )
    			controller.saveNewProfile();
    		else
    			controller.save();
    			
    	Test.stopTest();
    	
    	List<Iron_Mountain_Storage_Profile__c>profilesCreated = [Select Id, Account__c from Iron_Mountain_Storage_Profile__c];
    	
    	System.assertEquals(1, profilesCreated.size(), 'The Empty profile should have been created' );
    	System.assertEquals(profilesCreated[0].Id, controller.ironProfileID, 'The Empty profile should have been created and saved in the controllers variable' );
	}
	
    static testMethod void testSave()
    {
	    final Decimal PROFILE_TAPE_QUANTITY = 100;
	    final Decimal PROFILE_CUBE_QUANTITY = 200;
	    final Decimal PROFILE_DBnR_QUANTITY = 300;
	    final Decimal IM_TAPE_QUANTITY = 40;
	    final Decimal IM_CUBE_QUANTITY = 50;
	    final Decimal IM_DBnR_QUANTITY = 60;
	    	
	    final Decimal SP_QUANTITY = 60;
    
    	setup();
    	setupPage( IMGA_Account );
    	
		StorageProfilePageCont controller = setupPage( IMGA_Account );
		
    	for( Iron_Mountain_Storage_Profile__c aIMStorageProfile : controller.ironMountainStorageProfileMap.values() )
    	{
    		aIMStorageProfile.Profiled_Quantity_Tape__c = PROFILE_TAPE_QUANTITY;
    		aIMStorageProfile.Profiled_Quantity_Cube__c = PROFILE_CUBE_QUANTITY;
    		aIMStorageProfile.Profiled_Quantity_DB_R_Container__c = PROFILE_DBnR_QUANTITY;
    		aIMStorageProfile.IM_Quantity_Tape__c = IM_TAPE_QUANTITY;
    		aIMStorageProfile.IM_Quantity_Cube__c = IM_CUBE_QUANTITY;
    		aIMStorageProfile.IM_Quantity_DB_R_Container__c = IM_DBnR_QUANTITY;
    		
    		Storage_Profile__c relatedStorageProfile = aIMStorageProfile.Storage_Profiles__r[0];
    		relatedStorageProfile.Quantity__c = SP_QUANTITY;
    	}
    	 
    	Test.startTest();
			controller.save();
		Test.stopTest();
		
		System.assertEquals( testIMStorageProfiles.size(), controller.ironMountainStorageProfileMap.size(), 'The ironMountainStorageProfileMap in the controller should have all the imStorageProfiles related to the account' );
    	System.assert( controller.ironMountainStorageProfileMap.keySet().containsAll( Pluck.ids( testIMStorageProfiles ) ), 'All the expected im storage profiles should be included in the map' );
    	System.assert( Pluck.ids( testIMStorageProfiles ).containsAll( controller.ironMountainStorageProfileMap.keySet() ), 'Only the expected im storage profiles should be included in the map' );
    	
    	for( Iron_Mountain_Storage_Profile__c aIMStorageProfile : controller.ironMountainStorageProfileMap.values() )
    	{
			System.assertEquals( 1, aIMStorageProfile.Storage_Profiles__r.size(), 'The ironMountainStorageProfileMap in the controller should have exepcted number of StorageProfiles related to the imstorageProfile' );
    	}
    	
		Map<Id, Iron_Mountain_Storage_Profile__c> actualMap = new Map<Id, Iron_Mountain_Storage_Profile__c> ( 
													[ SELECT Whitespace_Tape__c, Whitespace_DB_R_Container__c, Whitespace_Cube__c, Profiled_Quantity_Tape__c, 
													Profiled_Quantity_DB_R_Container__c, Profiled_Quantity_Cube__c, Name, IM_Quantity_Tape__c, IM_Quantity_DB_R_Container__c, IM_Quantity_Cube__c, 
													( SELECT Name, Quantity__c FROM Storage_Profiles__r ) 
													FROM Iron_Mountain_Storage_Profile__c WHERE Id IN : testIMStorageProfiles ] );
													
		System.assertEquals( testIMStorageProfiles.size(), actualMap.size(), 'The actual map should have all the expected imStorageProfiles' );
		
		for( Iron_Mountain_Storage_Profile__c aIMStorageProfile : actualMap.values() )
		{
			System.assertEquals( PROFILE_TAPE_QUANTITY, aIMStorageProfile.Profiled_Quantity_Tape__c, 'All the fields modified on the page should get updated with their respective values' );
			System.assertEquals( PROFILE_CUBE_QUANTITY, aIMStorageProfile.Profiled_Quantity_Cube__c, 'All the fields modified on the page should get updated with their respective values' );
			System.assertEquals( PROFILE_DBnR_QUANTITY, aIMStorageProfile.Profiled_Quantity_DB_R_Container__c, 'All the fields modified on the page should get updated with their respective values' );
			System.assertEquals( IM_TAPE_QUANTITY, aIMStorageProfile.IM_Quantity_Tape__c, 'All the fields modified on the page should get updated with their respective values' );
			System.assertEquals( IM_CUBE_QUANTITY, aIMStorageProfile.IM_Quantity_Cube__c, 'All the fields modified on the page should get updated with their respective values' );
			System.assertEquals( IM_DBnR_QUANTITY, aIMStorageProfile.IM_Quantity_DB_R_Container__c, 'All the fields modified on the page should get updated with their respective values' );
			
			Storage_Profile__c actualStorageProfile = aIMStorageProfile.Storage_Profiles__r[0];
			System.assertEquals( SP_QUANTITY, actualStorageProfile.Quantity__c, 'All the fields modified on the page should get updated with their respective values' );
		}												
		
    }
    
}