force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/Iron_Mountain_Storage_Profile__c.object-meta.xml
<CustomObject>
    <label>Iron Mountain Storage Profile</label>
    <nameField>
        <displayFormat>IMSP - {00000}</displayFormat>
        <label>Iron Mountain Storage Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iron Mountain Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Profile__c/Storage_Profile__c.object-meta.xml
<CustomObject>
    <description>Object used to capture which vendor controls existing cube and tape at an account</description>
    <label>Competitor Storage Profile</label>
    <nameField>
        <displayFormat>StorageProfile-{0000}</displayFormat>
        <label>Storage Profile Name (cust-vendor-type)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Profile__c/fields/Iron_Mountain_Storage_Profile__c.field-meta.xml
<CustomField>
    <fullName>Iron_Mountain_Storage_Profile__c</fullName>
    <label>Iron Mountain Storage Profile</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Iron_Mountain_Storage_Profile__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Iron_Mountain_Storage_Profile__c</referenceTo>
    <relationshipLabel>Competitor Storage Profiles</relationshipLabel>
    <relationshipName>Storage_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestStorageProfileControllerExtension.cls
@isTest
private class TestStorageProfileControllerExtension {

    static testMethod void PageCancelWithIM_Profile()
    {
    	
		Account IMGA_Account = Testingutils.createAccounts( 1, false )[0];
		IMGA_Account.RecordTypeId = Testingutils.IMGA_ACCOUNT_RECORD_TYPE.Id;
    	IMGA_Account.IM_Hierarchy_Level__c = 'IM Group (IMGA)';	
    	insert IMGA_Account;
    	
		Iron_Mountain_Storage_Profile__c testIMStorageProfile = TestingUtils.createIronMountainStorageProfiles( 1, IMGA_Account.Id, 0, 0, 0,  true )[0];
    	
    	Storage_Profile__c testStorageProfile =  new Storage_Profile__c(); 
    	
    	PageReference storageProfileCreationPage = Page.StorageProfileNew;
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.ACCOUNT_ID_PARAM, IMGA_Account.Id);
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.IM_PROFILE_ID_PARAM, testIMStorageProfile.Id);
		
    	Test.setCurrentPageReference( storageProfileCreationPage );
		
		ApexPages.StandardController sc = new ApexPages.StandardController ( testStorageProfile );
		
		Test.startTest();
			StorageProfileContExt spExt = new storageProfileContExt( sc );
			spExt.cancel();
		Test.stopTest();
		
		List<Iron_Mountain_Storage_Profile__c> testIMStorageProfiles = [Select id 
												 						from Iron_Mountain_Storage_Profile__c ];
		
		System.assertEquals(1, testIMStorageProfiles.size(), 'A storage profile should not have been deleted');
		
	}

	static testMethod void PageSaveWithOutIM_Profile()
    {
    	
		Account IMGA_Account = Testingutils.createAccounts( 1, false )[0];
		IMGA_Account.RecordTypeId = Testingutils.IMGA_ACCOUNT_RECORD_TYPE.Id;
    	IMGA_Account.IM_Hierarchy_Level__c = 'IM Group (IMGA)';	
    	insert IMGA_Account;
    	
    	Iron_Mountain_Storage_Profile__c testIMStorageProfile = TestingUtils.createIronMountainStorageProfiles( 1, IMGA_Account.Id, 0, 0, 0,  true )[0];
    	Storage_Profile__c testStorageProfile =  new Storage_Profile__c(); 
    	
    	PageReference storageProfileCreationPage = Page.StorageProfileNew;
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.ACCOUNT_ID_PARAM, IMGA_Account.Id);
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.IM_PROFILE_ID_PARAM, testIMStorageProfile.Id);
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.NEW_IM_PROFILE_ID, 'true');
    	 
    	Test.setCurrentPageReference( storageProfileCreationPage );
		
		ApexPages.StandardController sc = new ApexPages.StandardController ( testStorageProfile );
		
		Test.startTest();
			StorageProfileContExt spExt = new storageProfileContExt( sc );
			spExt.cancel();
		Test.stopTest();
		
		List<Iron_Mountain_Storage_Profile__c> testIMStorageProfiles = [Select id
												 						from Iron_Mountain_Storage_Profile__c ];
		
		System.assertEquals(0, testIMStorageProfiles.size(), 'A storage profile should have been deleted');
		
	}

	static testMethod void PageSaveWithOutIM_ProfileERROR()
    {
    	
		Account IMGA_Account = Testingutils.createAccounts( 1, false )[0];
		IMGA_Account.RecordTypeId = Testingutils.IMGA_ACCOUNT_RECORD_TYPE.Id;
    	IMGA_Account.IM_Hierarchy_Level__c = 'IM Group (IMGA)';	
    	insert IMGA_Account;
    	
    	Iron_Mountain_Storage_Profile__c testIMStorageProfile = TestingUtils.createIronMountainStorageProfiles( 1, IMGA_Account.Id, 0, 0, 0,  true )[0];
    	Storage_Profile__c testStorageProfile =  new Storage_Profile__c(); 
    	
    	PageReference storageProfileCreationPage = Page.StorageProfileNew;
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.ACCOUNT_ID_PARAM, IMGA_Account.Id);
		storageProfileCreationPage.getParameters().put(StorageProfileContExt.NEW_IM_PROFILE_ID, 'true');
    	 
    	Test.setCurrentPageReference( storageProfileCreationPage );
		
		ApexPages.StandardController sc = new ApexPages.StandardController ( testStorageProfile );
		
		Test.startTest();
			StorageProfileContExt spExt = new storageProfileContExt( sc );
			spExt.cancel();
		Test.stopTest();
		
		List<Iron_Mountain_Storage_Profile__c> testIMStorageProfiles = [Select id
												 						from Iron_Mountain_Storage_Profile__c ];
		
		System.assert(TestingUtils.pageMessageContains( StorageProfileContExt.ERROR ), 'If an error occurs, it should be displayed on the page');
		
	}
	
    
}