force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Australia / New Zealand</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Code__c/Country_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store Country Codes based on Country Names</description>
    <label>Country Code</label>
</CustomObject>

force-app/main/default/objects/Country_Settings__c/Country_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Custom Settings</label>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Most_Recent__c</fullName>
    <inlineHelpText>For new opportunities on existing customers, add the most recent source of the lead</inlineHelpText>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Renewal_Date__c</fullName>
    <label>Service Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Stage_Progression_Dates__c/Quote_Stage_Progression_Dates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To do the stage progression on NA Renewal quotes</description>
    <label>Quote Stage Progression Dates</label>
</CustomObject>

force-app/main/default/objects/Quote_Stage_Progression_Dates__c/fields/Next_Progression_Stage__c.field-meta.xml
<CustomField>
    <fullName>Next_Progression_Stage__c</fullName>
    <label>Next Progression Stage</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Stage_Progression_Dates__c/fields/Progression_Date__c.field-meta.xml
<CustomField>
    <fullName>Progression_Date__c</fullName>
    <inlineHelpText>Date for the stage progression</inlineHelpText>
    <label>Progression Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_Q2W_Quote_Stage_Progre_BatchJob.cls
/****************************** 
   Developer Name    : Madhu Paladugu
   
   Date              : 7/3/2013
   
   Company Name      : CloudFountain Inc.
   
   Purpose           : Test Utility Class. 
   
   Dependents        : Apex Class: Q2W_Quote_Stage_Progre_BatchJob,Q2W_Quote_Stage_Progre_Scheduler
   
   Case Number       : 00222919
   ********
   
   Modifications on 18/09/2014 by Sandhya Ramesh:
    Added Lead_Source_Most_Recent__c to Opp insert, 
    Added Stage__c and Proposed_Service_Discount__c.
   All test methods passed.
                                   
 ********************************/ 
 
 @isTest
 public class Test_Q2W_Quote_Stage_Progre_BatchJob{
     
     static testMethod void doTest(){
         

        
        // Create test Country Data with more robust approach
        IM_Country__c mainName = new IM_Country__c();
        mainName.Name = 'United States';
        //mainName.Country_Code__c = 'US'; // Add a country code if required
        insert mainName;
        
        // Alternative Country Name
        IM_Alternative_Country_Name__c country = new IM_Alternative_Country_Name__c();
        country.IM_Country__c = mainName.Id;
        country.Alternative_Name__c = 'United States';
        insert country;
        
        // Country Settings
        Country_Settings__c setting = new Country_Settings__c();
        setting.Name = 'United States';
        setting.object_name__c = 'Account';
        insert setting;
        
        // Create Test Account with minimal required fields
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.BillingCountry = 'United States';
        testAccount.BillingState = 'NY';
        testAccount.BillingPostalCode = '10001';
        testAccount.IM_Hierarchy_Level__c = 'Sales (Site)';
        insert testAccount;
        
          RecordType renewalOppRT = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'NA Renewal' LIMIT 1];
     
        // Custom Setting Preparation
        Quote_Stage_Progression_Dates__c custData = new Quote_Stage_Progression_Dates__c();
        custData.Name = 'Test Custom Setting';
        custData.Next_Progression_Stage__c = 'Test Stage';
        custData.Progression_Date__c = Date.Today();
        insert custData;
        
        // Create Opportunity
        // 
     
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.AccountId = testAccount.Id;
        opp.CloseDate = System.today().addMonths(3);
        opp.StageName = '1 - Qualification';
        opp.RecordTypeId = renewalOppRT.Id;
        //opp.Type = 'Renewal';
        opp.Lead_Source_Most_Recent__c = 'Email';
        opp.Billing_Country__c = mainName.Id;
        
        // Insert Opportunity
        insert opp;
         
          //insert Quote 
          //Quote Q=new Quote(Name='Test Quote',opportunityId=opp.id,Service_Renewal_Date__c=System.today().addMonths(3));
          Quote Q=new Quote(Name='Test Quote',opportunityId=opp.id,Stage__c='1 - Under Review', Proposed_Service_Discount__c=0);
          Insert Q;
         
          //sync opportunity and quote
          opp.SyncedQuoteId = Q.Id;
          update opp;
          
          Test.startTest();
              Q2W_Quote_Stage_Progre_Scheduler InstanceofClass = new Q2W_Quote_Stage_Progre_Scheduler();
              String sch = '0 0 20 * * ?';
              system.schedule('Stage Progression', sch, InstanceofClass);
              Q2W_Quote_Stage_Progre_BatchJob job=new Q2W_Quote_Stage_Progre_BatchJob('test stage');
              Database.executeBatch(job);
          Test.stopTest(); 
          
     }
 }