force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Acct_Plan__c/SFDC_Acct_Plan__c.object-meta.xml
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Acct_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>R00N60000001PRP8EAO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test_AccountPlan.cls
@isTest(seeAllData= true)
public class test_AccountPlan {
public static testMethod Void doTest(){
    Id IMGARecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMGA Record Type').getRecordTypeId();
    Id StdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard Account').getRecordTypeId();
    Id GlobalRecordTypeId = Schema.SObjectType.SFDC_Acct_Plan__c.getRecordTypeInfosByName().get('Global Account Plan').getRecordTypeId();
    Id INTLRecordTypeId = Schema.SObjectType.SFDC_Acct_Plan__c.getRecordTypeInfosByName().get('INTL Account Plan').getRecordTypeId();
    
    
    Account IMGAAccount = new Account(Name='Test Account',
                                      IM_Hierarchy_Level__c = 'IM Group (IMGA)', RecordTypeId=IMGARecordTypeId);
    insert IMGAAccount;
    
    Account IMGAAccount1 = new Account(Name='Test Account2',
                                      IM_Hierarchy_Level__c = 'IM Group (IMGA)', RecordTypeId=IMGARecordTypeId);
    insert IMGAAccount1;
    
    Account StdAccount = new Account(Name='Test Account1',
                                      IM_Hierarchy_Level__c = 'Country Parent', ParentId=IMGAAccount.Id,
                                     RecordTypeId=StdRecordTypeId);
    
    insert StdAccount;
    
    SFDC_Acct_Plan__c acctPlan = new SFDC_Acct_Plan__c();
    acctPlan.RecordTypeId = GlobalRecordTypeId;
    acctPlan.Name = 'Test account plan for global account';
    acctPlan.Account__c = IMGAAccount.Id;
    insert acctPlan;
    
    
    SFDC_Acct_Plan__c acctPlan1 = new SFDC_Acct_Plan__c();
    acctPlan1.RecordTypeId = INTLRecordTypeId;
    acctPlan1.Name = 'Test account plan for INTL account';
    acctPlan1.Account__c = StdAccount.Id;
    insert acctPlan1;
    
    SFDC_Acct_Plan__c accPlan = new SFDC_Acct_Plan__c();
        accPlan.RecordTypeId = GlobalRecordTypeId;
        accPlan.Name = 'Test account plan for global account';
        accPlan.Account__c = IMGAAccount1.Id;
        insert accPlan;
        
        
    try{
        SFDC_Acct_Plan__c acctPlan2 = new SFDC_Acct_Plan__c();
        acctPlan2.RecordTypeId = GlobalRecordTypeId;
        acctPlan2.Name = 'Test account plan for global accounts';
        acctPlan2.Account__c = IMGAAccount1.Id;
        insert acctPlan2;
    }
        catch(Exception e) {}
     try{   
        accPlan.Account__c = IMGAAccount.id;
        update accPlan; }
        catch(Exception e) {}


}
}