force-app/main/default/objects/Account/fields/IM_Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>IM_Hierarchy_Level__c</fullName>
    <label>Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Group (IMGA)</fullName>
            </value>
            <value>
                <fullName>Country Parent</fullName>
            </value>
            <value>
                <fullName>Sales (Site)</fullName>
            </value>
            <value>
                <fullName>Operational Account</fullName>
            </value>
            <value>
                <fullName>Billing Account</fullName>
            </value>
            <value>
                <fullName>0018000000ZR7LQ</fullName>
                <isActive>false</isActive>
                <label>0018000000ZR7LQ</label>
            </value>
            <value>
                <fullName>0018000000ZV4Ql</fullName>
                <isActive>false</isActive>
                <label>0018000000ZV4Ql</label>
            </value>
            <value>
                <fullName>0018000000ZVci2</fullName>
                <isActive>false</isActive>
                <label>0018000000ZVci2</label>
            </value>
            <value>
                <fullName>0018000000ZYH6f</fullName>
                <isActive>false</isActive>
                <label>0018000000ZYH6f</label>
            </value>
            <value>
                <fullName>Book of Business/IMGA</fullName>
                <isActive>false</isActive>
                <label>Book of Business/IMGA</label>
            </value>
            <value>
                <fullName>Contry Parent</fullName>
                <isActive>false</isActive>
                <label>Contry Parent</label>
            </value>
            <value>
                <fullName>Country HQ</fullName>
                <isActive>false</isActive>
                <label>Country HQ</label>
            </value>
            <value>
                <fullName>County Parent</fullName>
                <isActive>false</isActive>
                <label>County Parent</label>
            </value>
            <value>
                <fullName>Coutnry Parent</fullName>
                <isActive>false</isActive>
                <label>Coutnry Parent</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Parent</fullName>
                <isActive>false</isActive>
                <label>Customer Parent</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUN</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUN</label>
            </value>
            <value>
                <fullName>Domestic Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Domestic Ultimate DUNS</label>
            </value>
            <value>
                <fullName>Global Ultimate DUNS</fullName>
                <isActive>false</isActive>
                <label>Global Ultimate DUNS</label>
            </value>
            <value>
                <fullName>IMGA</fullName>
                <isActive>false</isActive>
                <label>IMGA</label>
            </value>
            <value>
                <fullName>Operational Accounts</fullName>
                <isActive>false</isActive>
                <label>Operational Accounts</label>
            </value>
            <value>
                <fullName>Parent</fullName>
                <isActive>false</isActive>
                <label>Parent</label>
            </value>
            <value>
                <fullName>Parent (HQ)</fullName>
                <isActive>false</isActive>
                <label>Parent (HQ)</label>
            </value>
            <value>
                <fullName>Parent Account</fullName>
                <isActive>false</isActive>
                <label>Parent Account</label>
            </value>
            <value>
                <fullName>Parent Country</fullName>
                <isActive>false</isActive>
                <label>Parent Country</label>
            </value>
            <value>
                <fullName>Parent HQ</fullName>
                <isActive>false</isActive>
                <label>Parent HQ</label>
            </value>
            <value>
                <fullName>Parent Site</fullName>
                <isActive>false</isActive>
                <label>Parent Site</label>
            </value>
            <value>
                <fullName>Parent/HQ DUNS</fullName>
                <isActive>false</isActive>
                <label>Parent/HQ DUNS</label>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <isActive>false</isActive>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>SALES</fullName>
                <isActive>false</isActive>
                <label>SALES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/Management_Account_Plan_Review__c.object-meta.xml
<CustomObject>
    <label>Management Account Plan Review</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Management Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Management Account Plan Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Account_Plan__c</fullName>
    <description>This is the account plan the MR is directly related to</description>
    <label>Account Plan</label>
    <referenceTo>SFDC_Acct_Plan__c</referenceTo>
    <relationshipLabel>Management Account Plan Reviews</relationshipLabel>
    <relationshipName>Management_Account_Plan_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Account_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Account_Strategy__c</fullName>
    <description>Is this a clear statement of WHAT you are going to do to achieve the plan?
1.	This is the big picture strategy for the entire account and should not be more than a few sentences. 

2.	Example: Our account strategy is do what is necessary to win the unvended Company XYZ’s Contractor File initiative with an Iron Mountain agreement that allows us to amend and affiliate all existing accounts. Also, focus all of our sales resources on adding new affiliates resulting in naming IRM as their vendor much the way we have directed NAO to use Company XYZ.</description>
    <inlineHelpText>Is this a clear statement of WHAT you are going to do to achieve the plan?</inlineHelpText>
    <label>Account Strategy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Completeness__c.field-meta.xml
<CustomField>
    <fullName>Completeness__c</fullName>
    <description>Are all elements of your account plan filled out?</description>
    <inlineHelpText>Are all elements of your account plan filled out?</inlineHelpText>
    <label>Completeness</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Customer_Challenges__c.field-meta.xml
<CustomField>
    <fullName>Customer_Challenges__c</fullName>
    <description>What are your customer’s primary challenges that Iron Mountain can solve? What obstacles are in your way, and what is the plan for overcoming them?
1.	Industry  Challenges/How Iron Mountain can solve/How to teach for differentiation (Challenger)
2.	Company Challenges/How Iron Mountain can solve/How to teach for differentiation (Challenger)</description>
    <inlineHelpText>What are your customer’s primary challenges that IM can solve? What obstacles are in your way, and what is the plan for overcoming them?
Industry &amp; Company Challenges/How can you teach for Iron Mountain’s differentiators?</inlineHelpText>
    <label>Customer Challenges</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Customer_Narrative__c.field-meta.xml
<CustomField>
    <fullName>Customer_Narrative__c</fullName>
    <description>Is this a sound interpretation of data and customer knowledge?
1.	The customer narrative should take all of the data (internal and external) that exists on the account and interpret it. Examples of items to cover include new leadership, market expansion, international growth, trigger events (real estate moves, M&amp;A, regulations impacting their industry), high level opportunities for the account based on exiting internal data. It should tell you what it means and why it is important to you. It may be different based on the maturity of the account, but this is an overall interpretation of the current state of the account and should not include anything copied and pasted from the company’s website.</description>
    <inlineHelpText>Is this a sound interpretation of data and customer knowledge? Is it written out, and NOT copy and pasted?</inlineHelpText>
    <label>Customer Narrative</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Objectives__c.field-meta.xml
<CustomField>
    <fullName>Objectives__c</fullName>
    <description>Are they clearly actionable for HOW you achieve the account strategy, with owners and dates?
1.	These should be higher level objectives that are broad, such as “getting into the C-Suite” with indications of HOW you are going to do this. Since there are no more strategic and tactical objectives (just “objectives,”) each of these can be longer and include the tactics of how you will achieve the objective. Each objective needs to be actionable.
2.	Each objective should be tied to a specific service line in which you are trying to gain more business.</description>
    <inlineHelpText>Are they clearly actionable for HOW you achieve the account strategy, with owners and dates?</inlineHelpText>
    <label>Objectives</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Organizational_Heat_Map_Key_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Organizational_Heat_Map_Key_Contacts__c</fullName>
    <description>Is it completed with all relevant names and titles?
1.	This should be completed with the names of who you call on currently, who you are trying to gain access to, relationship to the people you know, how you evaluate the relationship that currently exists, and what service line they are associated with (if applicable). *Note* This is under development and may be able to be accomplished using the “Key Contacts” button.
2.	Challenger: For each name, identify what is important to them on both a functional role (what they are measured by) and/or personal level.
3.	Challenger: For each name, describe how are you providing insight (aka “teaching”) to each of these individuals. How are they looped into the larger strategic plan to close gaps in areas you do not have coverage?</description>
    <inlineHelpText>Is it completed with all relevant names and titles?</inlineHelpText>
    <label>Key Contacts</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Management_Account_Plan_Review__c/fields/Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Management_Account_Plan_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Acct_Plan__c/SFDC_Acct_Plan__c.object-meta.xml
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Acct_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>R00N60000001PRP8EAO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Acct_Plan__c/fields/Customer_Narrative__c.field-meta.xml
<CustomField>
    <fullName>Customer_Narrative__c</fullName>
    <inlineHelpText>Use all data (internal and external) that exists on the account and interpret it. Examples: new leadership, market expansion, international growth, trigger events. Explain what it means and why it is important to you. Do not copy and paste from website.</inlineHelpText>
    <label>Customer Narrative</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Test_PopulateApprovalStatusOnAcctPlan.cls
/************************************************************************
** CLIENT
**   Iron Mountain
**
** MODULE
**   Test_PopulateApprovalStatusOnAcctPlan (Test Class)
**
** PURPOSE
**   Code Coverage for 'PopulateApprovalStatusOnAcctPlan' trigger on 'Management Account Plan Review' Object.
**
** CHANGE LOG
**   [[Version; Date; Author; Project/Case; Description]]
**   v1.0; 10/1/2013; Srinivasa Rao/Randstad; Stamp of "approval" on Account Plan (Case # 01758327); Initial release
**
************************************************************************/
@isTest
public class Test_PopulateApprovalStatusOnAcctPlan {

    //Commenting code as part of #24270
   /* static testMethod void myUnitTest() {
        
        //Retrieving Admin Profile
        Profile p = [select id from profile where name='System Administrator' LIMIT 1];
        
        //Retrieving 'IMNA Account Plan' Record Type Id
        RecordType RT = [Select Id From RecordType Where SObjectType= :'SFDC_Acct_Plan__c' AND Name = :'IMNA Account Plan' LIMIT 1];
        
        //Create User
        User u = new user(alias = 'smand99', username='srinu.mandalapu99@IM.com', email='srinu.mandalapu99@IM.com', lastname='mandalapu99',
                          emailencodingkey='UTF-8', languagelocalekey='en_US', localesidkey='en_US', profileid = p.Id, 
                          timezonesidkey='America/New_York' , country='USA');
        insert u;                         
        
        //create Account
        Account act = new Account();
        act.Name='TestAccount';
        act.IM_Hierarchy_Level__c='Country Parent';
        insert act;
        
        //Create Account Plan
        SFDC_Acct_Plan__c actpln = new SFDC_Acct_Plan__c();
        actpln.Name='IMNAAccountPlan';
        actpln.Account__c=act.Id;
        actpln.RecordTypeId=RT.Id;
        insert actpln;
        
        //Create Management Account Plan Review
        Management_Account_Plan_Review__c mapr = new Management_Account_Plan_Review__c();
        mapr.Reviewed_By__c=u.Id;
        mapr.Account_Plan__c=actpln.Id;
        mapr.Completed_Date__c=System.Today();        
        mapr.Customer_Narrative__c='Not Started';
        mapr.Customer_Challenges__c='In Progress';
        mapr.Organizational_Heat_Map_Key_Contacts__c='Completed';
        mapr.Account_Strategy__c='Not Started';
        mapr.Objectives__c='In Progress';
        mapr.Completeness__c='Completed';
        insert mapr;
        
        //Verify that the Approval_Status__c field is populated on the AccountPlan.        
        List<SFDC_Acct_Plan__c> insertedStatus = [Select Id, Approval_Status__c From SFDC_Acct_Plan__c Where Id = :actpln.Id];
        System.assertEquals('Not Approved', insertedStatus[0].Approval_Status__c);
        
        //Update Management Account Plan Review
        mapr.Reviewed_By__c=u.Id;
        mapr.Account_Plan__c=actpln.Id;
        mapr.Completed_Date__c=System.Today();        
        mapr.Customer_Narrative__c='Completed';
        mapr.Customer_Challenges__c='Completed';
        mapr.Organizational_Heat_Map_Key_Contacts__c='Completed';
        mapr.Account_Strategy__c='Completed';
        mapr.Objectives__c='Completed';
        mapr.Completeness__c='Completed';
        update mapr;
        
        //Verify that the Approval_Status__c field was updated in the database.        
        List<SFDC_Acct_Plan__c> updatedStatus = [Select Id, Approval_Status__c From SFDC_Acct_Plan__c Where Id = :actpln.Id];
        System.assertEquals('Approved', updatedStatus[0].Approval_Status__c);

    } */
}