force-app/main/default/objects/Account/fields/Originating_Org__c.field-meta.xml
<CustomField>
    <fullName>Originating_Org__c</fullName>
    <label>Originating Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>Data Center LLC</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Review__c/Deal_Review__c.object-meta.xml
<CustomObject>
    <label>Deal Review</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Deal Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Review__c/fields/ACV_Annual_Contract_Value__c.field-meta.xml
<CustomField>
    <fullName>ACV_Annual_Contract_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ACV (Annual Contract Value)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <label>Primary Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Digital Solutions</fullName>
            </value>
            <value>
                <fullName>DM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>DM Cloud Solutions</fullName>
            </value>
            <value>
                <fullName>DM SITAD</fullName>
            </value>
            <value>
                <fullName>DM Tape Vaulting</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>Fixed Asset Management</fullName>
            </value>
            <value>
                <fullName>Information Governance</fullName>
            </value>
            <value>
                <fullName>Insight</fullName>
                <label>InSight</label>
            </value>
            <value>
                <fullName>ITRenew Contracted Sales Only</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
            <value>
                <fullName>RM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>RM Secure Storage</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
            </value>
            <value>
                <fullName>Secure Shredding</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
            </value>
            <value>
                <fullName>Sierra26</fullName>
            </value>
            <value>
                <fullName>SMB Packages</fullName>
            </value>
            <value>
                <fullName>Special Projects - Data Management</fullName>
            </value>
            <value>
                <fullName>Special Projects - International</fullName>
            </value>
            <value>
                <fullName>Special Projects - Records Management &amp; Shred</fullName>
            </value>
            <value>
                <fullName>SBS Pallet Storage</fullName>
                <label>W&amp;L Pallet Storage</label>
            </value>
            <value>
                <fullName>Warehouse and Logistics</fullName>
            </value>
            <value>
                <fullName>Regency Technologies - Contracted Sales Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Review__c/fields/Total_Cashview_Margin_Percent__c.field-meta.xml
<CustomField>
    <fullName>Total_Cashview_Margin_Percent__c</fullName>
    <label>Total Cashview Margin %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/LGK__Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LGK__Transaction__c/fields/Deal_Review__c.field-meta.xml
<CustomField>
    <fullName>Deal_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Review</label>
    <referenceTo>Deal_Review__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__AccountId__c.field-meta.xml
<CustomField>
    <fullName>LGK__AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.account.id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>AccountTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>LGK__OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.opportunity.id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>OpportunityTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__Pricebook2Id__c.field-meta.xml
<CustomField>
    <fullName>LGK__Pricebook2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.pricebook.id</description>
    <label>Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>PricebookTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Since the Opportunity is now locked for Sales Profiles at Stages 6 and 7, sales still needs to update field “Up-Sell Detail” in stages 6 and 7 to log billing details. This allows them to communicate to Commissions via this field. “Up-sell Detail” Chatter Action allows bypassing the validation and is able to only update this field.[Case# 02497355].</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Originating_Org__c.field-meta.xml
<CustomField>
    <fullName>Originating_Org__c</fullName>
    <label>Originating Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>Data Center LLC</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
                <default>true</default>
                <label>Core</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <label>Primary Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clean Start</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Data Restoration &amp; Migration</fullName>
            </value>
            <value>
                <fullName>Digital Solutions</fullName>
                <isActive>false</isActive>
                <label>Digital Solutions</label>
            </value>
            <value>
                <fullName>Digitization</fullName>
            </value>
            <value>
                <fullName>DM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>DM Cloud Solutions</fullName>
                <isActive>false</isActive>
                <label>DM Cloud Solutions</label>
            </value>
            <value>
                <fullName>DM SITAD</fullName>
            </value>
            <value>
                <fullName>DM Tape Vaulting</fullName>
            </value>
            <value>
                <fullName>DXP (InSight)</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>Fixed Asset Management</fullName>
                <isActive>false</isActive>
                <label>Fixed Asset Management</label>
            </value>
            <value>
                <fullName>Incubation</fullName>
                <isActive>false</isActive>
                <label>Incubation</label>
            </value>
            <value>
                <fullName>Information Governance</fullName>
            </value>
            <value>
                <fullName>ITRenew Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>ITRenew Contracted Sales Only</label>
            </value>
            <value>
                <fullName>MAS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Professional Staffing</fullName>
            </value>
            <value>
                <fullName>Records Management - Paper document storage</fullName>
                <isActive>false</isActive>
                <label>Records Management - Paper document storage</label>
            </value>
            <value>
                <fullName>Regency Technologies - Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>Regency Technologies - Contracted Sales Only</label>
            </value>
            <value>
                <fullName>RM (All other service lines)</fullName>
                <isActive>false</isActive>
                <label>RM (All other service lines)</label>
            </value>
            <value>
                <fullName>RM Secure Storage</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
                <isActive>false</isActive>
                <label>Scan</label>
            </value>
            <value>
                <fullName>Secure Shredding</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
                <isActive>false</isActive>
                <label>Shred</label>
            </value>
            <value>
                <fullName>Sierra26</fullName>
                <isActive>false</isActive>
                <label>Sierra26</label>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>Smart Suite</fullName>
            </value>
            <value>
                <fullName>SMB Packages</fullName>
                <isActive>false</isActive>
                <label>SMB Packages</label>
            </value>
            <value>
                <fullName>Special Projects - Data Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitForApprovalEndpointTest.cls
@isTest
private class SubmitForApprovalEndpointTest {

    @testSetup
    static void setupTestData() {
        // --- BYPASS THE ACCOUNT TRIGGER ---
        // This prevents AccountHelper OpportunityHelper and the Country Validation from firing during the test
        AccountTriggerHandler.skipTriggerExecutionTestClass = true;
        OpportunityTriggerHandler.skipTriggerExecutionTestClass = true;



        // Query the Profile
        Profile im_sales_Profile = [SELECT Id FROM Profile WHERE Name = 'IM_Sales' LIMIT 1];
        
        // Create the Test User
        User IM_Sales_User = new User(
            FirstName = 'Test',
            LastName = 'Admin',
            Alias = 'tadmin',
            Email = 'testadmin_' + DateTime.now().getTime() + '@example.com',
            Username = 'testadmin_' + DateTime.now().getTime() + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = im_sales_Profile.Id,
            Country = 'United States'
        );

        insert IM_Sales_User;


        List<PermissionSetGroup> psgList = [SELECT Id FROM PermissionSetGroup WHERE DeveloperName = 'Sales_Operations_Business_Partner_PSG' LIMIT 1];
        
        if (!psgList.isEmpty()) {
            PermissionSetAssignment psgAssignment = new PermissionSetAssignment(
                AssigneeId = IM_Sales_User.Id,
                PermissionSetGroupId = psgList[0].Id 
            );
            insert psgAssignment;
            
 
            Test.calculatePermissionSetGroup(psgList[0].Id); 
        }

        //Query the Permission Set from 
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Logik_Custom_CPQ_PS' LIMIT 1];
        
        //Assign the Permission Set to the newly created User
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = IM_Sales_User.Id,
            PermissionSetId = ps.Id
        );
        insert psa;


        System.runAs(IM_Sales_User) {
            
        // 1. Create a Test Account
        Account testAcc = new Account(Name = 'Test Account');
        insert testAcc;

        // 2. Get the Standard Pricebook ID for the test context
        Id standardPricebookId = Test.getStandardPricebookId();

        IM_Country__c imContry = new  IM_Country__c(
        Name = 'United States',
        Originating_Org__c = 'Core',
        Region__c = 'North America',
        CurrencyIsoCode = 'USD',
        Active__c = true
        );

        insert imContry;


        Schema.DescribeFieldResult fieldResult = Opportunity.Primary_Product_Line__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        String validProductLine = ple[0].getValue();

        // 3. Create a Test Opportunity and associate the Pricebook
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAcc.Id,
            Pricebook2Id = standardPricebookId,
            StageName = '1 - Qualification',
            CloseDate = System.today().addDays(30),
            Primary_Product_Line__c = validProductLine,
            //Primary_Product_Line__c = 'SITAD',
            Billing_Country__c = imContry.id,
            Bypass_Validation__c = true
        );
        insert testOpp;

        // 4. Create the Logik Transaction with all required relationship fields
        LGK__Transaction__c testTrans = new LGK__Transaction__c(
            LGK__AccountId__c = testAcc.Id,
            LGK__OpportunityId__c = testOpp.Id,
            LGK__Pricebook2Id__c = standardPricebookId
        );
        insert testTrans;
        }
    }

    /*@isTest
    static void testGenerateDealReviewRecordsSuccess() {
        // Fetch the test records created in the setup phase
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        LGK__Transaction__c trans = [SELECT Id FROM LGK__Transaction__c LIMIT 1];

        // Construct the payload matching what the endpoint expects
        Map<String, Object> jsonMap = new Map<String, Object>{
            'opportunityId' => opp.Id,
            'accountId' => acc.Id,
            'transactionId' => trans.Id,
            'ACV' => '50000',
            'cashviewMargin' => '12.5'
        };

        // Configure the REST context to simulate an incoming HTTP POST request
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/submitForApproval/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(jsonMap));
        
        RestContext.request = req;
        RestContext.response = res;

        // Invoke the endpoint method
        Test.startTest();
        Map<String, String> response = SubmitForApprovalEndpoint.generateDealReviewRecords();
        Test.stopTest();

        // System Assertions to verify behavioral accuracy
        System.assertNotEquals(null, response, 'The response structure should not be null.');
        System.assert(response.containsKey('dealReviewId'), 'The response map must contain the dealReviewId.');
        
        Id dealReviewId = (Id) response.get('dealReviewId');
        
        // Assert that Deal_Review__c was correctly generated and values parsed
        Deal_Review__c createdReview = [SELECT Id, ACV_Annual_Contract_Value__c, Total_Cashview_Margin_Percent__c 
                                        FROM Deal_Review__c 
                                        WHERE Id = :dealReviewId];
                                        
        System.assertEquals(50000, createdReview.ACV_Annual_Contract_Value__c, 'ACV numeric parsing failed.');
        System.assertEquals(12.5, createdReview.Total_Cashview_Margin_Percent__c, 'Cashview Margin numeric parsing failed.');

        // Assert that the transaction record was successfully updated with the reference
        LGK__Transaction__c updatedTrans = [SELECT Id, Deal_Review__c FROM LGK__Transaction__c WHERE Id = :trans.Id];
        System.assertEquals(dealReviewId, updatedTrans.Deal_Review__c, 'Transaction failed to establish lookup relation with the Deal Review.');
    }*/

    @isTest
    static void testGenerateDealReviewRecordsWithFallbackValues() {

        User IM_Sales_User = [SELECT Id FROM User WHERE Alias = 'tadmin' LIMIT 1];

        System.runAs(IM_Sales_User) {

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        LGK__Transaction__c trans = [SELECT Id FROM LGK__Transaction__c LIMIT 1];

        // Simulate fallback payload logic (blank and 'undefined' string variables)
        Map<String, Object> jsonMap = new Map<String, Object>{
            'opportunityId' => opp.Id,
            'accountId' => acc.Id,
            'transactionId' => trans.Id,
            'ACV' => 'undefined',
            'cashviewMargin' => ''
        };

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/submitForApproval/';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(JSON.serialize(jsonMap));
        
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Map<String, String> response = SubmitForApprovalEndpoint.generateDealReviewRecords();
        Test.stopTest();

        // Verify that the endpoint handled fallback conditions gracefully by setting defaults to 1
        Id dealReviewId = (Id) response.get('dealReviewId');
        Deal_Review__c createdReview = [SELECT Id, ACV_Annual_Contract_Value__c, Total_Cashview_Margin_Percent__c 
                                        FROM Deal_Review__c 
                                        WHERE Id = :dealReviewId];
                                        
        System.assertEquals(1, createdReview.ACV_Annual_Contract_Value__c, 'ACV should default to fallback value 1.');
        System.assertEquals(1, createdReview.Total_Cashview_Margin_Percent__c, 'Cashview Margin should default to fallback value 1.');
    }
    }
}