force-app/main/default/objects/Account/fields/Originating_Org__c.field-meta.xml
<CustomField>
    <fullName>Originating_Org__c</fullName>
    <label>Originating Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>Data Center LLC</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/LGK__Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__AccountId__c.field-meta.xml
<CustomField>
    <fullName>LGK__AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.account.id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>AccountTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>LGK__OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.opportunity.id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>OpportunityTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__Transaction__c/fields/LGK__Pricebook2Id__c.field-meta.xml
<CustomField>
    <fullName>LGK__Pricebook2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>txn.pricebook.id</description>
    <label>Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>PricebookTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LGK__TransactionLine__c/LGK__TransactionLine__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{00000}</displayFormat>
        <label>Transaction Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LGK__TransactionLine__c/fields/LGK__ConfigurationId__c.field-meta.xml
<CustomField>
    <fullName>LGK__ConfigurationId__c</fullName>
    <description>txn.line.configuration.id</description>
    <externalId>true</externalId>
    <label>Configuration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LGK__TransactionLine__c/fields/LGK__TransactionId__c.field-meta.xml
<CustomField>
    <fullName>LGK__TransactionId__c</fullName>
    <label>Transaction</label>
    <referenceTo>LGK__Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>TransactionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Since the Opportunity is now locked for Sales Profiles at Stages 6 and 7, sales still needs to update field “Up-Sell Detail” in stages 6 and 7 to log billing details. This allows them to communicate to Commissions via this field. “Up-sell Detail” Chatter Action allows bypassing the validation and is able to only update this field.[Case# 02497355].</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Originating_Org__c.field-meta.xml
<CustomField>
    <fullName>Originating_Org__c</fullName>
    <label>Originating Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>Crozier</fullName>
            </value>
            <value>
                <fullName>Data Center LLC</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
                <default>true</default>
                <label>Core</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <label>Primary Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clean Start</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Data Restoration &amp; Migration</fullName>
            </value>
            <value>
                <fullName>Digital Solutions</fullName>
                <isActive>false</isActive>
                <label>Digital Solutions</label>
            </value>
            <value>
                <fullName>Digitization</fullName>
            </value>
            <value>
                <fullName>DM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>DM Cloud Solutions</fullName>
                <isActive>false</isActive>
                <label>DM Cloud Solutions</label>
            </value>
            <value>
                <fullName>DM SITAD</fullName>
            </value>
            <value>
                <fullName>DM Tape Vaulting</fullName>
            </value>
            <value>
                <fullName>DXP (InSight)</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>Fixed Asset Management</fullName>
                <isActive>false</isActive>
                <label>Fixed Asset Management</label>
            </value>
            <value>
                <fullName>Incubation</fullName>
                <isActive>false</isActive>
                <label>Incubation</label>
            </value>
            <value>
                <fullName>Information Governance</fullName>
            </value>
            <value>
                <fullName>ITRenew Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>ITRenew Contracted Sales Only</label>
            </value>
            <value>
                <fullName>MAS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Professional Staffing</fullName>
            </value>
            <value>
                <fullName>Records Management - Paper document storage</fullName>
                <isActive>false</isActive>
                <label>Records Management - Paper document storage</label>
            </value>
            <value>
                <fullName>Regency Technologies - Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>Regency Technologies - Contracted Sales Only</label>
            </value>
            <value>
                <fullName>RM (All other service lines)</fullName>
                <isActive>false</isActive>
                <label>RM (All other service lines)</label>
            </value>
            <value>
                <fullName>RM Secure Storage</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
                <isActive>false</isActive>
                <label>Scan</label>
            </value>
            <value>
                <fullName>Secure Shredding</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
                <isActive>false</isActive>
                <label>Shred</label>
            </value>
            <value>
                <fullName>Sierra26</fullName>
                <isActive>false</isActive>
                <label>Sierra26</label>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>Smart Suite</fullName>
            </value>
            <value>
                <fullName>SMB Packages</fullName>
                <isActive>false</isActive>
                <label>SMB Packages</label>
            </value>
            <value>
                <fullName>Special Projects - Data Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CleanupConfigLineItemsBatchTest.cls
@isTest
private class CleanupConfigLineItemsBatchTest {

    @testSetup
    static void setupTestData() {
        

        // --- BYPASS THE ACCOUNT TRIGGER ---
        // This prevents AccountHelper OpportunityHelper and the Country Validation from firing during the test
        AccountTriggerHandler.skipTriggerExecutionTestClass = true;
        OpportunityTriggerHandler.skipTriggerExecutionTestClass = true;

        // Query the Profile
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'IM_Custom Sys Admin' LIMIT 1];
        
        // Create the Test User
        User testAdminUser = new User(
            FirstName = 'Test',
            LastName = 'Admin',
            Alias = 'tadmin',
            Email = 'testadmin_' + DateTime.now().getTime() + '@example.com',
            Username = 'testadmin_' + DateTime.now().getTime() + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = adminProfile.Id,
            Country = 'United States'
        );

        insert testAdminUser;

        //Query the Permission Set from 
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Sales_Operations_Business_Partner_PSG' LIMIT 1];
        
        //Assign the Permission Set to the newly created User
        PermissionSetAssignment psa = new PermissionSetAssignment(
            AssigneeId = testAdminUser.Id,
            PermissionSetId = ps.Id
        );
        insert psa;


        System.runAs(testAdminUser) {

        // 1. Create a Test Account
        Account testAcc = new Account(Name = 'Test Account');
        insert testAcc;

        // 2. Get the Standard Pricebook ID for the test context
        Id standardPricebookId = Test.getStandardPricebookId();

        IM_Country__c imContry = new  IM_Country__c(
        Name = 'United States',
        Originating_Org__c = 'Core',
        Region__c = 'North America',
        CurrencyIsoCode = 'USD',
        Active__c = true
        );

        insert imContry;


        Schema.DescribeFieldResult fieldResult = Opportunity.Primary_Product_Line__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        String validProductLine = ple[0].getValue();

        // 3. Create a Test Opportunity and associate the Pricebook
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAcc.Id,
            Pricebook2Id = standardPricebookId,
            //StageName = 'Prospecting', //1 - Qualification
            StageName = '1 - Qualification', //1 - Qualification
            CloseDate = System.today().addDays(30),
            //Primary_Product_Line__c = 'SITAD',
            Primary_Product_Line__c = validProductLine,
            Billing_Country__c = imContry.id,
            Bypass_Validation__c = true
        );
        insert testOpp;

        // 4. Create the Logik Transaction with all required relationship fields
        LGK__Transaction__c testTrans = new LGK__Transaction__c(
            LGK__AccountId__c = testAcc.Id,
            LGK__OpportunityId__c = testOpp.Id,
            LGK__Pricebook2Id__c = standardPricebookId
        );
        insert testTrans;


        List<LGK__TransactionLine__c> testTxLines = new List<LGK__TransactionLine__c>();
        
        testTxLines.add(new LGK__TransactionLine__c(
            LGK__ConfigurationId__c = 'CONFIG-VALID-123',
            LGK__TransactionId__c = testTrans.Id
        ));
        insert testTxLines;


        List<LGK__ConfigurationLineItem__c> testConfigs = new List<LGK__ConfigurationLineItem__c>();
        
        // Escenario A: VALID CONFIG, CONFIG LINES EXIST SHOULD BE NOT DELETED
        testConfigs.add(new LGK__ConfigurationLineItem__c(
            LGK__ConfigurationId__c = 'CONFIG-VALID-123'
        ));
        
        // Escenario B: INVALID CONFIG, CONFIG LINES EXIST SHOULD BE  DELETED
        testConfigs.add(new LGK__ConfigurationLineItem__c(
            LGK__ConfigurationId__c = 'CONFIG-ORPHAN-456'
        ));
        
        // Escenario C: NULL, CONFIG LINES EXIST SHOULD BE DELETED
        testConfigs.add(new LGK__ConfigurationLineItem__c(
            LGK__ConfigurationId__c = null
        ));
        
        insert testConfigs;
        }
    }

    @isTest
    static void testBatchExecution() {

        User testAdminUser = [SELECT Id FROM User WHERE Alias = 'tadmin' LIMIT 1];

        System.runAs(testAdminUser) {

        // Verificar que los 3 registros se crearon correctamente antes del proceso
        Assert.areEqual(3, [SELECT COUNT() FROM LGK__ConfigurationLineItem__c], 'Debería haber 3 registros iniciales.');

        // Test.startTest() y Test.stopTest() fuerzan a que el proceso asíncrono (Batch)
        // se ejecute de manera síncrona dentro del contexto de la prueba.
        Test.startTest();
        CleanupConfigLineItemsBatch batchJob = new CleanupConfigLineItemsBatch();
        Database.executeBatch(batchJob, 200);
        Test.stopTest();

        // --- VERIFICACIÓN DE RESULTADOS ---
        
        // El huérfano y el nulo deben haber sido eliminados. Solo debe quedar 1 registro.
        List<LGK__ConfigurationLineItem__c> remainingConfigs = [
            SELECT Id, LGK__ConfigurationId__c 
            FROM LGK__ConfigurationLineItem__c
        ];
        
        Assert.areEqual(1, remainingConfigs.size(), 'Solo debería haber quedado 1 registro tras la limpieza.');
        Assert.areEqual('CONFIG-VALID-123', remainingConfigs[0].LGK__ConfigurationId__c, 'El registro restante debe ser el que tiene una transacción activa.');
        }
    }

    @isTest
    static void testSchedulableExecution() {
        User testAdminUser = [SELECT Id FROM User WHERE Alias = 'tadmin' LIMIT 1];

        System.runAs(testAdminUser) {

        String cronExp = '0 0 0 * * ?';
        
        Test.startTest();
        // Programar el Job
        String jobId = System.schedule(
            'Test Daily Cleanup Job', 
            cronExp, 
            new CleanupConfigLineItemsBatch()
        );
        Test.stopTest();

        // Verificar que el Job quedó correctamente en la cola de Salesforce
        CronTrigger ct = [
            SELECT Id, CronExpression, TimesTriggered, State 
            FROM CronTrigger 
            WHERE Id = :jobId
        ];
        
        Assert.areEqual(cronExp, ct.CronExpression, 'La expresión Cron debe coincidir con la configurada.');
        Assert.areEqual('WAITING', ct.State, 'El Job programado debe estar en estado de espera (WAITING).');
        }
    }
}