force-app/main/default/objects/Account/fields/Primary_BDE__c.field-meta.xml
<CustomField>
    <fullName>Primary_BDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A commercial BDE name may be populated in this field for at risk notification. For account coverage details, please see the BOB Coverage by Rep report.
#26452 : Account Coverage: Relabel Primary BDE, Insight Owner and Entertainment Services Owner and Hide other retired &quot;Owner&quot; fields
Account Owner - Account Executive or Inside Sales Rep. - Set at the Country Parent and cascades down to the Sales Site</inlineHelpText>
    <label>AE/ISR (Account Owner)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_CDE__c.field-meta.xml
<CustomField>
    <fullName>Primary_CDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A commercial CDE name may be populated in this field for at risk notification. For account coverage details, please see the BOB Coverage by Rep report.</inlineHelpText>
    <label>Primary CDE To be Deleted</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts11</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Settings__c/Country_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Custom Settings</label>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/IM_Alternative_Country_Name__c.object-meta.xml
<CustomObject>
    <label>Alternative Country Name</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>IM Alternative Country Name Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternative Country Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/Alternative_Name__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Name__c</fullName>
    <label>Alternative Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Alternative_Country_Name__c/fields/IM_Country__c.field-meta.xml
<CustomField>
    <fullName>IM_Country__c</fullName>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Alternative Country Names</relationshipLabel>
    <relationshipName>Alternative_Country_Names</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Original_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>IM_Original_Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Original_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>IM_Original_Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QTB_Billing_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>QTB_Billing_Country_Name__c</fullName>
    <description>#SFCPQBLG-955 Country name selected in the Billing Country field</description>
    <formula>Billing_Country__r.Name</formula>
    <inlineHelpText>Billing Country Name</inlineHelpText>
    <label>Billing Country Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Sales_Billing_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Billing_Estimate__c</fullName>
    <description>Sum of all the Sales Billing Estimates for this opportunity</description>
    <label>Total Sales Billing Estimate</label>
    <summarizedField>Sales_Revenue_Forecast__c.Sales_Billing_Estimate__c</summarizedField>
    <summaryForeignKey>Sales_Revenue_Forecast__c.Forecast_Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Standard_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Standard_Opportunity_Process</businessProcess>
    <description>IRM Standard Opportunity. Full 8-stage lifecycle. Includes Setup stage used by child/sub-Opportunities under a Framework Parent contract.</description>
    <label>Standard Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Security__c/Opportunity_Security__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Opportunity Security Field Settings</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Security__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Name of Field to use in Oppty Sharing Logic</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Security__c/fields/Visibility_Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Visibility_Access_Level__c</fullName>
    <description>R for Read
W for Write</description>
    <label>Visibility Access Level</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/OpportunityProductSelection__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to take product class and product line names in to apex class while adding product</description>
    <label>OpportunityProductSelection</label>
</CustomObject>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Class_Name__c</fullName>
    <label>Product Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Revenue_Forecast__c/Sales_Revenue_Forecast__c.object-meta.xml
<CustomObject>
    <description>Sales Revenue Forecast object which is tied to an Oppty for O2R</description>
    <label>Sales Billing Forecast</label>
    <nameField>
        <label>Billing Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Billing Forecast</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Revenue_Forecast__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <description>Opportunity tied to the Revenue</description>
    <label>Forecast Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Billing Forecast</relationshipLabel>
    <relationshipName>Revenue_Forecast</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Revenue_Forecast__c/fields/Sales_Billing_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Sales_Billing_Estimate__c</fullName>
    <label>Sales Billing Estimate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SVStatus__c/SVStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for checking the SVStatus field values</description>
    <label>SVStatus</label>
</CustomObject>

force-app/main/default/classes/VR_PRISM_TestSupport.cls
/**
 * Shared test-support utilities for the VR_PRISM_* validation-rule test classes.
 * Not itself a test class - each *_Test class calls these from its own @TestSetup /
 * test methods (Apex @TestSetup cannot be inherited or shared directly across classes).
 *
 * setupCommonTestData() exists because inserting ANY Opportunity in this org's test
 * context runs into automation (Touch Level calc, sharing, SVStatus) that NPEs without
 * this scaffolding - it has nothing to do with the VR_PRISM rules themselves, but every
 * one of the 61 new test classes needs it just to get an insert to succeed at all.
 */
@isTest
public class VR_PRISM_TestSupport {
  public static void setupCommonTestData() {
    insert new SVStatus__c(
      Name = 'SVStatusPassed',
      Amount__c = 0,
      SetupOwnerId = UserInfo.getOrganizationId()
    );
    insert new Country_Settings__c(
      Name = 'United States',
      Object_Name__c = 'Opportunity',
      SetupOwnerId = UserInfo.getOrganizationId()
    );
    insert new List<Opportunity_Security__c>{
      new Opportunity_Security__c(
        Name = 'Primary CDE',
        Field_Name__c = 'Primary_CDE__c',
        Object_Name__c = 'Account',
        Visibility_Access_Level__c = 'R',
        SetupOwnerId = UserInfo.getOrganizationId()
      ),
      new Opportunity_Security__c(
        Name = 'Original Lead Owner',
        Field_Name__c = 'IM_Original_Lead_Owner__c',
        Object_Name__c = 'Opportunity',
        Visibility_Access_Level__c = 'W',
        SetupOwnerId = UserInfo.getOrganizationId()
      ),
      new Opportunity_Security__c(
        Name = 'Primary BDE',
        Field_Name__c = 'Primary_BDE__c',
        Object_Name__c = 'Account',
        Visibility_Access_Level__c = 'W',
        SetupOwnerId = UserInfo.getOrganizationId()
      )
    };
    insert new OpportunityProductSelection__c(
      Name = 'CloudSolutionsProduct',
      Product_Class_Name__c = 'Cloud',
      Product_Line_Name__c = 'Cloud Solutions'
    );

    IM_Country__c testCountry = new IM_Country__c(
      Name = 'United States',
      Active__c = true,
      Region__c = 'North America'
    );
    insert testCountry;
    insert new IM_Alternative_Country_Name__c(
      IM_Country__c = testCountry.Id,
      Alternative_Name__c = 'United States'
    );
    // Second country, outside North America, for rules that gate on a non-NA Region
    // (e.g. VR_PRISM_Qual_UpSell_Oracle_Acct_ID). QTB_Billing_Country_Name__c and
    // Region__c on Opportunity are both formulas off Billing_Country__c - not directly
    // writeable - so tests set Billing_Country__c to one of these two records instead.
    insert new IM_Country__c(
      Name = 'Ireland',
      Active__c = true,
      Region__c = 'Europe'
    );

    Account testAccount = new Account(
      Name = 'VR_PRISM Test Account',
      BillingCountry = 'United States',
      BillingState = 'NY',
      BillingPostalCode = '11209'
    );
    insert testAccount;

    // IM_Account__c is Master-Detail to Account, so it's required.
    insert new IM_Customer_Account__c(
      Name = 'VR-PRISM-TEST-001',
      IM_Account__c = testAccount.Id
    );
  }

  public static Id getAccountId() {
    return [SELECT Id FROM Account WHERE Name = 'VR_PRISM Test Account' LIMIT 1]
    .Id;
  }

  public static Id getCustomerAccountId() {
    return [
      SELECT Id
      FROM IM_Customer_Account__c
      WHERE Name = 'VR-PRISM-TEST-001'
      LIMIT 1
    ]
    .Id;
  }

  public static Id getUnitedStatesCountryId() {
    return [SELECT Id FROM IM_Country__c WHERE Name = 'United States' LIMIT 1]
    .Id;
  }

  public static Id getIrelandCountryId() {
    return [SELECT Id FROM IM_Country__c WHERE Name = 'Ireland' LIMIT 1].Id;
  }

  /**
   * Minimally-valid Opportunity for exercising a single VR_PRISM rule. All BU flags
   * default false and Amount defaults low (1000) so BU-gated / amount-threshold rules
   * don't fire unless a test deliberately overrides them. Callers set whatever
   * additional fields their specific rule cares about (PPL, country, target field, ...)
   * on the returned record before insert.
   */
  public static Opportunity baseOpp(
    String stage,
    Id recordTypeId,
    String type
  ) {
    return new Opportunity(
      Name = 'VR PRISM Test Opportunity',
      AccountId = getAccountId(),
      RecordTypeId = recordTypeId,
      Type = type,
      StageName = stage,
      CloseDate = Date.today().addDays(30),
      Pricebook2Id = Test.getStandardPricebookId(),
      Amount = 1000,
      ALM_BU__c = false,
      RIM_BU__c = false,
      MAS_BU__c = false,
      Digital_BU__c = false,
      W_L_BU__c = false
    );
  }

  // Standard_Opportunity is the default record type used by tests that don't care
  // which of the two (Standard vs Framework Parent) applies.
  public static Id stdRecordTypeId() {
    return App_Constants.STD_OPPORTUNITY_RECTYPE_ID;
  }

  public static Id frameworkParentRecordTypeId() {
    return App_Constants.FRAMEWORK_PARENT_OPPORTUNITY_RECTYPE_ID;
  }

  // One-time (per test run) Sales Revenue Forecast child record, needed only by the
  // VR_PRISM_Neg_Sales_Billing_Estimate positive test: Total_Sales_Billing_Estimate__c
  // is a roll-up summary field on Opportunity and cannot be set directly via DML.
  public static void addSalesRevenueForecast(
    Id opportunityId,
    Decimal estimate
  ) {
    insert new Sales_Revenue_Forecast__c(
      Name = 'VR PRISM Test Forecast',
      Forecast_Opportunity__c = opportunityId,
      Sales_Billing_Estimate__c = estimate
    );
  }

  // For the 3 VR_PRISM_Lock_All_Fields_When_{Booked,Closed,Setup} rules, which are
  // additionally gated on $Profile.Name = 'Sales & Account Management' - there is no
  // way to test that branch except by actually running the DML as a user with that
  // profile (custom permissions/profile checks in formulas can't be toggled directly
  // in a test context). Creates (once) and returns a user with that profile.
  public static User getSalesAccountManagementUser() {
    List<User> existing = [
      SELECT Id
      FROM User
      WHERE Username = 'vr.prism.sam.testuser@irmdev.test.invalid'
      LIMIT 1
    ];
    if (!existing.isEmpty()) {
      return existing[0];
    }
    Profile p = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Sales & Account Management'
      LIMIT 1
    ];
    User u = new User(
      FirstName = 'VR PRISM',
      LastName = 'Sales AM Test User',
      Alias = 'vrpsam',
      Email = 'vr.prism.sam.testuser@irmdev.test.invalid',
      Username = 'vr.prism.sam.testuser@irmdev.test.invalid',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/New_York',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
    );
    insert u;
    return u;
  }
}