force-app/main/default/objects/Account/fields/QTB_Legal_Entity_Country__c.field-meta.xml
<CustomField>
    <fullName>QTB_Legal_Entity_Country__c</fullName>
    <description>#SFCPQBLG-43 - its shows the legal entity&apos;s country of contract legal entity</description>
    <label>Legal Entity Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__BillingCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Source_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>QTB_Source_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#AS-8 Created for storing Sales Opportunity value on Billing Account</description>
    <label>Source Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts (SourceOpportunity)</relationshipLabel>
    <relationshipName>Accounts_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/AlternativeNames__c.field-meta.xml
<CustomField>
    <fullName>AlternativeNames__c</fullName>
    <label>Alternative Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Iso31662Code__c.field-meta.xml
<CustomField>
    <fullName>Iso31662Code__c</fullName>
    <description>2 Digit ISO country Code</description>
    <label>ISO 3166-2 Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Iso31663Code__c.field-meta.xml
<CustomField>
    <fullName>Iso31663Code__c</fullName>
    <description>3 Digit ISO Country Code</description>
    <label>ISO 3166-3 Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <label>Primary Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clean Start</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Data Restoration &amp; Migration</fullName>
            </value>
            <value>
                <fullName>Digital Solutions</fullName>
                <isActive>false</isActive>
                <label>Digital Solutions</label>
            </value>
            <value>
                <fullName>Digitization</fullName>
            </value>
            <value>
                <fullName>DM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>DM Cloud Solutions</fullName>
                <isActive>false</isActive>
                <label>DM Cloud Solutions</label>
            </value>
            <value>
                <fullName>DM SITAD</fullName>
            </value>
            <value>
                <fullName>DM Tape Vaulting</fullName>
            </value>
            <value>
                <fullName>DXP (InSight)</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>Fixed Asset Management</fullName>
                <isActive>false</isActive>
                <label>Fixed Asset Management</label>
            </value>
            <value>
                <fullName>Incubation</fullName>
                <isActive>false</isActive>
                <label>Incubation</label>
            </value>
            <value>
                <fullName>Information Governance</fullName>
            </value>
            <value>
                <fullName>ITRenew Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>ITRenew Contracted Sales Only</label>
            </value>
            <value>
                <fullName>MAS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Professional Staffing</fullName>
            </value>
            <value>
                <fullName>Records Management - Paper document storage</fullName>
                <isActive>false</isActive>
                <label>Records Management - Paper document storage</label>
            </value>
            <value>
                <fullName>Regency Technologies - Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>Regency Technologies - Contracted Sales Only</label>
            </value>
            <value>
                <fullName>RM (All other service lines)</fullName>
                <isActive>false</isActive>
                <label>RM (All other service lines)</label>
            </value>
            <value>
                <fullName>RM Secure Storage</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
                <isActive>false</isActive>
                <label>Scan</label>
            </value>
            <value>
                <fullName>Secure Shredding</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
                <isActive>false</isActive>
                <label>Shred</label>
            </value>
            <value>
                <fullName>Sierra26</fullName>
                <isActive>false</isActive>
                <label>Sierra26</label>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>Smart Suite</fullName>
            </value>
            <value>
                <fullName>SMB Packages</fullName>
                <isActive>false</isActive>
                <label>SMB Packages</label>
            </value>
            <value>
                <fullName>Special Projects - Data Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Promotion__c/QTB_Promotion__c.object-meta.xml
<CustomObject>
    <description>#GITLAB-367: To capture the promotions</description>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Promotion__c/fields/QTB_Promo_Description__c.field-meta.xml
<CustomField>
    <fullName>QTB_Promo_Description__c</fullName>
    <description>#Gitlab:411-To show the Promo Description</description>
    <label>Promotion Description</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Promotion__c/fields/QTB_Promo_Term__c.field-meta.xml
<CustomField>
    <fullName>QTB_Promo_Term__c</fullName>
    <description>#GITLAB: 376 --&gt; to store the promotional term</description>
    <label>Promotion Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QTB_Promotion__c/fields/QTB_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>QTB_Quote_Type__c</fullName>
    <description>#GITLAB:376 --&gt; to store the quote type</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
                <label>Up sell</label>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
                <label>Cross Sell</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QTB_Quote_Promotion__c/QTB_Quote_Promotion__c.object-meta.xml
<CustomObject>
    <description>#GITLAB: 376 --&gt; to store the quote promotions</description>
    <label>Quote Promotion</label>
    <nameField>
        <label>Quote Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Quote_Promotion__c/fields/QTB_Promo_Description__c.field-meta.xml
<CustomField>
    <fullName>QTB_Promo_Description__c</fullName>
    <description>Gitlab#378 - to store Promotion Description from Promotions</description>
    <label>Promotion Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Quote_Promotion__c/fields/QTB_Promo_Term__c.field-meta.xml
<CustomField>
    <fullName>QTB_Promo_Term__c</fullName>
    <description>Gitlab#378 - to store Promo Term from Promotions</description>
    <label>Promotion Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QTB_Quote_Promotion__c/fields/QTB_Promotion_Name__c.field-meta.xml
<CustomField>
    <fullName>QTB_Promotion_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#GITLAB:376 -&gt; to store the promotion that applied on the quote</description>
    <label>Promotion Name</label>
    <referenceTo>QTB_Promotion__c</referenceTo>
    <relationshipLabel>Quote Promotions</relationshipLabel>
    <relationshipName>Quote_Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QTB_Quote_Promotion__c/fields/QTB_Quote__c.field-meta.xml
<CustomField>
    <fullName>QTB_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#GITLAB:376 --&gt; to store the Quote information</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Promotions</relationshipLabel>
    <relationshipName>Quote_Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QTB_OrderHelper_Test.cls
/*****************************************************************************************************
* Class: QTB_OrderHelper_Test
* Author: Accenture
* Purpose: This is a test class for QTB_OrderHelper
* Change History: 6/1/2020
* Developer     Date           Description
* -------------------------------------------------------------------------------------------
* Accenture
*******************************************************************************************************/
@isTest(seealldata=false)
private with sharing class QTB_OrderHelper_Test {
    @TestSetup
    static void createData() {
        List<User> userList = QTB_TestDataFactory.usrMethdLst(1);
        
       
    System.runAs(userList[0]) 
    {
            List<account> accountList = QTB_TestDataFactory.createAccounts(1);
            accountList[0].BillingCountry = 'India';
            accountList[0].QTB_Legal_Entity_Country__c = 'India';
            update accountList;
       System.debug('DEBUGLOG --> accountList:'+accountList); 
      blng__BillingRule__c billingRule = QTB_TestDataFactory.createBillingRule( 'Yes' );
      blng__RevenueRecognitionRule__c revenueRule = QTB_TestDataFactory.createRevenueRecognitionRule( 'Yes' );
            blng__TaxRule__c taxRule = QTB_TestDataFactory.createTaxRule('Yes');
            
            List<product2> product = QTB_TestDataFactory.createProducts(1);
            product[0].blng__BillingRule__c = billingRule.id;
            product[0].blng__RevenueRecognitionRule__c = revenueRule.id;
            product[0].blng__TaxRule__c = taxRule.id;
            database.update(product);
            
            Id pricebookId = Test.getStandardPricebookId();
      PricebookEntry standardPrice = QTB_TestDataFactory.createPricebookEntry( product[0] );
            
            // Update the pricebook of opportunity
            //   List<opportunity> oppList = QTB_TestDataFactory.createOpps(accountList);
            //IM Country
            IM_Country__c im = new IM_Country__c();
            im.Name = 'United States';
            im.CurrencyIsoCode = 'USD';
            im.Region__c = 'North America';
            im.AlternativeNames__c = 'United States';
            im.Iso31662Code__c ='US';
            im.Iso31663Code__c ='USA'; 
            im.Active__c = true;
            insert im;
        System.debug('DEBUGLOG --> Im  :'+im);
            list<opportunity> oppList =new list<opportunity>();
            for (Integer i = 0; i < accountList.size(); i++) {
                oppList.add(
                    new Opportunity(
                        Name = 'Test' + i,
                        AccountId = accountList[i].Id,
                        CloseDate = Date.today(),
                        StageName = '1 - Qualification',
                        RecordTypeId = QTB_Utils.OPP_SALES_RECTYPEID,
                        Amount = 500,
                        Billing_Country__c =im.id
                        //Primary_Product_Line__c = 'Data Management'
                    )
                );
            }
                System.debug('DEBUGLOG --> oppList  :'+oppList);

      if (!oppList.isEmpty()) 
      {
         Database.SaveResult[] srList = Database.insert(oppList, false);

        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('DEBUGLOG --> Successfully inserted Opportunity. Opp ID: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors())
                {
                    System.debug('DEBUGLOG --> The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }  
            }
      
            oppList[0].Pricebook2Id = pricebookId;
            database.update(oppList);
            
            List<SBQQ__Quote__c> quoteList = QTB_TestDataFactory.createCPQQuotes(
        						1, oppList[0].id, accountList[0].id, true, null  );
            quoteList[0].SBQQ__PriceBook__c = pricebookId;
            quoteList[0].SBQQ__StartDate__c = System.Today();
            database.update(quoteList);
            QTB_Promotion__c promo = new QTB_Promotion__c();
            promo.Name = 'test promo';
            promo.QTB_Quote_Type__c = 'Quote';
            promo.QTB_Promo_Description__c = 'test data';
            promo.QTB_Promo_Term__c = 2;
            try{
                insert promo;
            }
            catch(Exception e){
                
            }
            
            QTB_Quote_Promotion__c quotePromo = new QTB_Quote_Promotion__c();
            quotePromo.name = 'test QuotePromotion';
            quotePromo.QTB_Promotion_Name__c = promo.id;
            quotePromo.qtb_quote__c = quoteList[0].id;
            quotePromo.QTB_Promo_Term__c = 2;
            insert quotePromo;
            
            List<SBQQ__QuoteLineGroup__c> quoteGroupList = QTB_TestDataFactory.createCPQQuoteLineGroups(
        1, quoteList[0].id, accountList[0].id );
            List<SBQQ__QuoteLine__c> quoteLinesList = QTB_TestDataFactory.createCPQQuoteLines(
        1,quoteList[0].id, quoteGroupList[0].id, product[0].id );
            SBQQ.Triggercontrol.Disable();
            
        Test.startTest();
            List<account> accountList2 = QTB_TestDataFactory.createAccounts(
       							 1, accountList[0], null, 'Billing Account'  );
            accountList2[0].QTB_Source_Opportunity__c = oppList[0].id;
            
            update accountList2[0];
        
      
            List<Order> orderList1 = QTB_TestDataFactory.createCPQOrders(
        						1, quoteList[0].Id, accountList[0].id );
            orderList1[0].blng__BillingAccount__c = accountList2[0].id;
     //  orderList1[0].blng__BillingAccount__c = accountList3.id;
            orderList1[0].RecordTypeId = QTB_Utils.ORDER_SALES_RECTYPEID;
            orderList1[0].SBQQ__PriceCalcStatus__c = 'Not Needed';
            
            try{
                database.update(orderList1);
            }
            catch(Exception e){
            }
            orderList1[0].RecordTypeId = QTB_Utils.ORDER_BILL_RECTYPEID;
            
            try{
                database.update(orderList1);
            }
            catch(Exception e){
                
            }
            List<Order> orderList2 = QTB_TestDataFactory.createBillingOrders( 1, quoteList[0].Id,  accountList[0].id );
             // Team san-diego >>Start
            List<Order> orderList3 = QTB_TestDataFactory.createBillingOrders( 1, quotelist[0].Id, accountList2[0].id );
            orderList3[0].QTB_Hold_Contracting__c=true;
              try{
                    Database.update(orderList3[0]); 
            }
            catch(Exception e){
                System.debug('orderList3 update1 : '+e.getMessage());
            }
            orderList3[0].EffectiveDate = Date.today().adddays(-3);
            orderList3[0].blng__InvoiceBatch__c='US-SBS-1st-EOM';
            orderList3[0].RecordTypeId=QTB_Utils.ORDER_BILL_RECTYPEID;
            orderList3[0].QTB_Legal_Entity_Country__c='United States';
            orderList3[0].QTB_OrderCategory__c='Ad-Hoc';
            orderList3[0].QTB_Hold_Contracting__c=false;
            
                try{
                Database.update(orderList3[0]); 
            }
            catch(Exception e){
                System.debug('orderList3 : '+e.getMessage());
            }
            // Team san-diego >>end
            List<OrderItem> orderItemList = QTB_TestDataFactory.createCPQOrderItems(
        orderList1[0].Id, product[0].Id, quoteLinesList, standardPrice );
            
            //  orderList1[0].Status = 'Activated';
            //  update orderList1[0]; 
            Test.stopTest();
            system.assert(orderItemList[0].SBQQ__ChargeType__c == 'One-Time');
        }
    }
    
    // cover catch
    static testMethod void testmethod5() {
        List<User> userList = QTB_TestDataFactory.usrMethdLst(2);
        Test.startTest();
        System.runAs(userList[1]) {
            QTB_OrderTriggerHandler.throwExplicitException = true;
            QTB_OrderTriggerHandler handler = new QTB_OrderTriggerHandler();
            handler.AfterDelete(null);
            handler.BeforeDelete(null);
            handler.AfterUndelete(null);
            try {   
                handler.AfterUpdate(null, null);
            }
            catch (NullPointerException e) {
                System.assertEquals('System.NullPointerException', e.getTypeName());
            }
            QTB_TestDataFactory.createBypassSetting(QTB_Constants.SOBJECT_ORDER);
            handler.IsDisabled();
            Test.stopTest();
        }
    }
    static testmethod void testmethod6() {
        try {
            List<order> ordLST = [SELECT id,Status,RecordTypeId,OrderNumber,SBQQ__PriceCalcStatus__c from order];
            system.debug('New order List'+ordLST);
            Test.startTest();
            QTB_OrderTriggerHandler.throwExplicitException = true;
            QTB_OrderHelper.countryClone(null, null);
            Test.stopTest();
        } catch (NullPointerException e) {
            System.assertEquals('System.NullPointerException', e.getTypeName());
        }
    }
    static testMethod void testmethod7() {
        try {
            Test.startTest();
            QTB_OrderTriggerHandler.throwExplicitException = true;
            QTB_OrderHelper.updateOnActivationOrder(null, null);
            Test.stopTest();
        } catch (NullPointerException e) {
            System.assertEquals('System.NullPointerException', e.getTypeName());
        }
    }
    static testMethod void testmethod8() {
        try {
            Test.startTest();
            QTB_OrderTriggerHandler.throwExplicitException = true;
            QTB_OrderHelper.setOrderTypeValue(null, null, null);
            Test.stopTest();
        } catch (NullPointerException e) {
            System.assertEquals('System.NullPointerException', e.getTypeName());
        }
    }
    static testMethod void testmethod9() {
        try {
            Test.startTest();
            
            QTB_OrderTriggerHandler.throwExplicitException = true;
            
            QTB_OrderHelper.billingPromotions(null, null);
            Test.stopTest();
        } catch (NullPointerException e) {
            System.assertEquals('System.NullPointerException', e.getTypeName());
        }
    }
}