force-app/main/default/objects/Account/fields/QTB_Bill_Cycle_Day__c.field-meta.xml
<CustomField>
    <fullName>QTB_Bill_Cycle_Day__c</fullName>
    <description>#SFCPQBLG-727: Field to Store Bill Cycle Day for a Billing Account.</description>
    <label>Bill Cycle Day</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Bill_Forward_Type__c.field-meta.xml
<CustomField>
    <fullName>QTB_Bill_Forward_Type__c</fullName>
    <label>Bill Forward Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Arrears</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Billing_Account_Invoice_Name__c.field-meta.xml
<CustomField>
    <fullName>QTB_Billing_Account_Invoice_Name__c</fullName>
    <description>#SFCPQBLG-648 Clone of Billing Account Name without any prefix</description>
    <label>Billing Account Invoice Name</label>
    <length>249</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>QTB_Billing_Frequency__c</fullName>
    <description>QTB-2--  to store billing frequency and bill product on which frequency</description>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Invoice Plan</fullName>
                <isActive>false</isActive>
                <label>Invoice Plan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Contract_Entity__c.field-meta.xml
<CustomField>
    <fullName>QTB_Contract_Entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>#QTB-44a Contracted Legal Entity Lookup.</description>
    <label>Contract Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>blng__LegalEntity__c.blng__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>blng__LegalEntity__c</referenceTo>
    <relationshipLabel>Accounts (Contract Legal Entity)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Create_Parent_Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>QTB_Create_Parent_Billing_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SFCPQBLG-68-&gt;To be marked to create parent billing account when billing account is created through flow</description>
    <label>Create Parent Billing Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/QTB_Legal_Entity_Country__c.field-meta.xml
<CustomField>
    <fullName>QTB_Legal_Entity_Country__c</fullName>
    <description>#SFCPQBLG-43 - its shows the legal entity&apos;s country of contract legal entity</description>
    <label>Legal Entity Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__BillingCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_ReBill_InvoiceSchedulerValidation__c/Credit_ReBill_InvoiceSchedulerValidation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Gitlab US #9256 Credit &amp; Rebill  -- validation to avoid multiple creation on invoice scheduler on same time.</description>
    <label>Credit ReBill InvoiceSchedulerValidation</label>
</CustomObject>

force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/AlternativeNames__c.field-meta.xml
<CustomField>
    <fullName>AlternativeNames__c</fullName>
    <label>Alternative Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Iso31662Code__c.field-meta.xml
<CustomField>
    <fullName>Iso31662Code__c</fullName>
    <description>2 Digit ISO country Code</description>
    <label>ISO 3166-2 Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Iso31663Code__c.field-meta.xml
<CustomField>
    <fullName>Iso31663Code__c</fullName>
    <description>3 Digit ISO Country Code</description>
    <label>ISO 3166-3 Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/Metadata_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to disable/enable validation rules, process builders, triggers for users and profiles</description>
    <label>Metadata Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/Disable_PB__c.field-meta.xml
<CustomField>
    <fullName>Disable_PB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable Processes for users and profile</description>
    <inlineHelpText>Check if you want Process Builder to be disabled for the SObject</inlineHelpText>
    <label>Disable Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/Disable_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable the trigger on the specified SObject</description>
    <inlineHelpText>Check if the trigger needs to be disabled for the specified SObject</inlineHelpText>
    <label>Disable Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/Disable_VR__c.field-meta.xml
<CustomField>
    <fullName>Disable_VR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable validation rules for the specified object</description>
    <inlineHelpText>Check if validation rules should be disabled for the SObject</inlineHelpText>
    <label>Disable Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Activation_Settings__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>Specify for which object processes should be bypassed</description>
    <inlineHelpText>Specify API names separated by semicolon (&apos;;&apos;) of the SObject for which you want to disable/enable the process builders, workflows, validation rules, triggers</inlineHelpText>
    <label>SObject API Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Billing_Countries__c/QTB_Billing_Countries__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This has Used in billing account creation Flow.</description>
    <label>Billing Countries</label>
</CustomObject>

force-app/main/default/objects/QTB_Billing_Countries__c/fields/Legal_entity_country__c.field-meta.xml
<CustomField>
    <fullName>Legal_entity_country__c</fullName>
    <label>Legal Entity Country</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QTB_orderUpdateForUSDelete_Test.cls
/*****************************************************************************************************
 * Class: QTB_orderUpdateForUSDelete_Test
 * Author: Virtusa
 * Purpose: This is a test class for QTB_orderUpdateForUSDelete
 *******************************************************************************************************/
@isTest(seealldata=false)
public class QTB_orderUpdateForUSDelete_Test {
  @TestSetup
  static void createData() {
    List<User> userList = QTB_TestDataFactory.usrMethdLst(1);
    System.runAs(userList[0]) {
      //Test.startTest();
        Metadata_Activation_Settings__c custSetting = new Metadata_Activation_Settings__c();
        custSetting.SObject_API_Name__c = 'blng__Invoice__c;Account;AccountContactRelation;blng__UsageSummary__c;OrderItem;blng__InvoiceLine__c;blng__CreditNote__c;Product2;blng__CreditNoteLine__c;blng__Usage__c';
        custSetting.Disable_VR__c = true;
        custSetting.Disable_PB__c = true;
        custSetting.Disable_Trigger__c = true;
        // custSetting.SetupOwnerId = UserInfo.getOrganizationId();
        insert custSetting;
        
        Credit_ReBill_InvoiceSchedulerValidation__c invSchCust = new Credit_ReBill_InvoiceSchedulerValidation__c();
        invSchCust.Name = 'Finland';
        invSchCust.isRunning__c = false;
        insert invSchCust;
        
        QTB_Billing_Countries__c BillingCountries = new QTB_Billing_Countries__c();
        BillingCountries.Name = 'Singapore';
        BillingCountries.Legal_entity_country__c = 'Singapore' ;
        insert BillingCountries;
        
        //List<User> userList = QTB_TestDataFactory.usrMethdLst(1);
        blng__BillingRule__c billingRule = QTB_TestDataFactory.createBillingRule('Yes');
        blng__RevenueRecognitionRule__c revenueRule = QTB_TestDataFactory.createRevenueRecognitionRule('Yes');
        blng__TaxRule__c taxRule = QTB_TestDataFactory.createTaxRule('Yes');
        
        //Product
        List<product2> product = QTB_TestDataFactory.createProducts(1);
        product[0].blng__BillingRule__c = billingRule.id;
        product[0].blng__RevenueRecognitionRule__c = revenueRule.id;
        product[0].blng__TaxRule__c = taxRule.id;
        database.update(product);
        
        //Pricebook
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = QTB_TestDataFactory.createPricebookEntry(product[0]);
        
        //Account
        List<Account> accountList = new List<Account>();
        ID StandardrecordId = QTB_Utils.ACCOUNT_STANDARD_RECTYPEID;
        Id recordTypeValue = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing Account').getRecordTypeId();   
        for (Integer i = 0; i < 10; i++) {
            Account a = new Account();
            a.Name = (a.Name == null ? 'Test' : a.Name) + i;
            a.Phone = 'Test' + String.valueOf(Crypto.getRandomInteger());
            a.RecordTypeId = recordTypeValue;
            a.QTB_Create_Parent_Billing_Account__c = true;
            a.Name = 'Test Account';
            a.BillingCountry = 'Singapore';
            a.BillingPostalCode = '11209';
            a.BillingState = 'TN';
            a.Registration_Number__c = 'Reg';
            a.ShippingCountry = 'Singapore';
            a.QTB_Legal_Entity_Country__c='Singapore';
            if(i == 0){
                a.QTB_Legal_Entity_Country__c='United States';
                a.QTB_Bill_Cycle_Day__c = 'United States-DM-1st-EOM Manual';
            }
            if(i == 1){
                a.QTB_Bill_Forward_Type__c = 'Arrears';
                a.QTB_Billing_Frequency__c = 'Monthly';  
            }
            if(i == 2){
                a.QTB_Bill_Forward_Type__c = 'Advance';
                a.QTB_Billing_Frequency__c = 'Monthly';  
            }
            if(i == 3){
                a.QTB_Bill_Forward_Type__c = 'Arrears';
                a.QTB_Billing_Frequency__c = 'Quarterly';  
            }
            if(i == 4){
                a.QTB_Bill_Forward_Type__c = 'Advance';
                a.QTB_Billing_Frequency__c = 'Quarterly';  
            }
            if(i == 5){
                a.QTB_Bill_Forward_Type__c = 'Arrears';
                a.QTB_Billing_Frequency__c = 'Semiannual';  
            }
            if(i == 6){
                a.QTB_Bill_Forward_Type__c = 'Advance';
                a.QTB_Billing_Frequency__c = 'Semiannual';  
            }
            if(i == 7){
                a.QTB_Bill_Forward_Type__c = 'Arrears';
                a.QTB_Billing_Frequency__c = 'Annual';  
            }
            if(i == 8){
                a.QTB_Bill_Forward_Type__c = 'Advance';
                a.QTB_Billing_Frequency__c = 'Annual';  
            }
            if(i == 8){
                a.QTB_Bill_Forward_Type__c = '';
                a.QTB_Billing_Frequency__c = '';  
            }
            accountList.add(a);
        }
        
        if (!accountList.isEmpty()) {
            insert accountList;
        }
      

          blng__LegalEntity__c Indiaentity = QTB_TestDataFactory.createLegalEntity(
          'India'
          );
         
        List<Account> standardAccountList = QTB_TestDataFactory.createAccounts(1,'Standard Account');
        accountList[0].QTB_Legal_Entity_Country__c='India';
        accountList[0].QTB_Billing_Account_Invoice_Name__c = 'Standard Account';
        accountList[0].ShippingCountry = 'India';
        accountList[0].QTB_Contract_Entity__c = Indiaentity.Id;
        update accountList;
        update standardAccountList; 
   
        
        IM_Country__c im = new IM_Country__c();
        im.Name = 'United States';
        im.CurrencyIsoCode = 'USD';
        im.Region__c = 'North America';
        im.AlternativeNames__c = 'United States';
        im.Iso31662Code__c ='US';
        im.Iso31663Code__c ='USA';    
        im.Active__c = true;
        insert im;
        //Account
          Account a = new Account();
            a.Name = 'testdata123';
            a.Phone = 'Test' + String.valueOf(Crypto.getRandomInteger());
            a.RecordTypeId = recordTypeValue;
            a.QTB_Create_Parent_Billing_Account__c = true;
            a.Name = 'Test Account';
            a.BillingCountry = 'Singapore';
            a.BillingPostalCode = '11209';
            a.BillingState = 'TN';
            a.Registration_Number__c = 'Reg';
            a.ShippingCountry = 'Singapore';
            a.QTB_Legal_Entity_Country__c='Singapore';
         insert a;
       
        List<Opportunity> oppList = new List<Opportunity>();
        
        Opportunity insOpp = new Opportunity();
        insOpp.name = 'testOpp';
        insOpp.AccountId = standardAccountList[0].id;
        insOpp.CloseDate = Date.today();
        insOpp.StageName = '1 - Qualification';
        insOpp.RecordTypeId = QTB_Utils.OPP_SALES_RECTYPEID;
        insOpp.Amount = 500;
        insOpp.Pricebook2Id=pricebookId;
        oppList.add(insOpp);
        insert oppList;
        SBQQ.TriggerControl.disable();
        List<Order> orderList3 = QTB_TestDataFactory.createCPQOrders(1,null,accountList[0].id);
        orderList3[0].recordtypeid = QTB_Utils.ORDER_BILL_RECTYPEID;
        orderList3[0].Usagesummary_deletion_batchRun__c =true;
         update  orderList3;
        List<OrderItem> orderItemList3 = new List<OrderItem>();
            //QTB_TestDataFactory.createCPQOrderItems(orderList3[0].Id,product[0].Id,quoteLinesList,standardPrice);
        try {
      for (Integer i = 0; i < 1; i++) {
        orderItemList3.add(
          new OrderItem(
            OrderId = orderList3[0].Id,
            Quantity = 2.00,
            UnitPrice = 12.00,
            //SBQQ__QuoteLine__c = quoteLines[i].id,
            PricebookEntryId = standardPrice.Id,
            SBQQ__ChargeType__c = 'One-Time',
            product2id = product[0].Id,
            SBQQ__Activated__c = true,
            blng__BillingRule__c = QTB_TestDataFactory.createBillingRule('Yes')
              .id,
            blng__RevenueRecognitionRule__c = QTB_TestDataFactory.createRevenueRecognitionRule(
                'Yes'
              )
              .id,
            blng__TaxRule__c = QTB_TestDataFactory.createTaxRule('Yes').id,
              blng__HoldBilling__c = 'Yes'
          )
        );
      }
      if (!orderItemList3.isEmpty()) {
        insert orderItemList3;
      }
    } catch (Exception e) {
    }
             
        blng__UsageSummary__c usage = new blng__UsageSummary__c();
        usage.blng__SummaryEndDate__c = DATE.newInstance(2021, 06, 30);
        usage.blng__SummaryStartDate__c = DATE.newInstance(2021,06, 01);
        usage.blng__MatchingId__c = '1234';
        usage.blng__Status__c = 'New';
        usage.QTB_Legal_Entity_Country__c = 'Singapore';
        usage.blng__UnitOfMeasure__c = '';
        usage.blng__OrderProduct__c = orderItemList3[0].id;
        usage.CurrencyIsoCode ='SGD';
        insert usage;      
        id cid = UserInfo.getUserId();
       
    }
  }
  //cover catch
  static testMethod void testMethod2() {
    List<User> userList = QTB_TestDataFactory.usrMethdLst(2);
    System.runAs(userList[1]) {
      Test.startTest();
      id cid = UserInfo.getUserId();  
      List<Order> orderList = [select id from Order limit 1];
      QTB_orderUpdateForUSDelete obj = new QTB_orderUpdateForUSDelete(orderList[0].Id);
      obj.throwExplicitException = true;
      database.executeBatch(obj);
      Test.stopTest();
     
    }
    
  } 

  static testMethod void testMethod3() {
    List<User> userList = QTB_TestDataFactory.usrMethdLst(2);
    System.runAs(userList[1]) {
      Test.startTest();
      id cid = UserInfo.getUserId();  
      List<Order> orderList = [select id from Order limit 1];
      QTB_orderUpdateForUSDelete obj = new QTB_orderUpdateForUSDelete();
      database.executeBatch(obj);
      Test.stopTest();
     
    }
} 
  
    
  

}