force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Current_Year_Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Total_Revenue__c</fullName>
    <description>Invoiced revenue from all business lines for the current calendar year.</description>
    <formula>Current_Year_DBR_Revenue__c + Current_Year_DMS_Revenue__c + Current_Year_Other_Revenue__c + Current_Year_RM_Revenue__c +  Current_Year_Shred_Revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Invoiced revenue from all business lines for the current calendar year.</inlineHelpText>
    <label>Current Year Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_IMGA__c.field-meta.xml
<CustomField>
    <fullName>IM_IMGA__c</fullName>
    <formula>IM_Account__r.IM_IMGA_Indexed__c</formula>
    <label>IMGA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Overall_At_Risk_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_At_Risk_Score__c</fullName>
    <description>This is the overall at-risk score across all three product lines.</description>
    <inlineHelpText>This is the overall at-risk score across all three product lines on a scale of 0-10.</inlineHelpText>
    <label>Overall At Risk Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>Other NA</fullName>
            </value>
            <value>
                <fullName>SB NA</fullName>
            </value>
            <value>
                <fullName>SKP NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerAccountServices.cls
/***************************************************************************************************
Class    :  CustomerAccountServices.cls
Developer:  Mickey Murphy, Blue Wolf Group LLC
Created  :  June 25, 2013
Modified :  July 25, 2013
Objective:  This class provides methods to service IM_Customer_Account__c collections.

***************************************************************************************************/

public with sharing class CustomerAccountServices
{
    //  public methods listed in alphabetical order
    public static Integer getCountOfRedCids ( String imga )
    {
        return [ select count() from im_customer_account__c
                  where   overall_at_risk_score__c = 10 
                    and ( source_system__c IN ('SB NA', 'SKP NA', 'Other NA'))
                    and   im_imga__c = :imga ];

    }   //  getCountofRedCIDs ()

    public static Double getTotalGreenRevenue ( String imga )
    {
        Double totalGreenRevenue = 0;   
        String query = 'select sum(current_year_total_revenue__c) greenTotal'
                     + ' from im_customer_account__c'
                     + ' where overall_at_risk_score__c < ' + 7
                     + ' and ( source_system__c = \'SB NA\''
                     + ' or    source_system__c = \'SKP NA\' )'
                     + ' and   im_imga__c = \'' + imga + '\'';

        System.debug (Logginglevel.INFO, 'getTotalGreenRevenue () query:  ' + query);

        List <AggregateResult> results = getResultsByQuery (query);
        totalGreenRevenue = (Double) results [0].get ('greenTotal');

        System.debug (Logginglevel.INFO, 'totalGreenRevenue:  ' + totalGreenRevenue);

        return totalGreenRevenue;

    }   //  getTotalGreenRevenue ()     
        
    public static Double getTotalRedRevenue ( String imga )
    {
        Double totalRedRevenue = 0;   
        String query = 'select sum(current_year_total_revenue__c) redTotal'
                     + ' from im_customer_account__c'
                     + ' where overall_at_risk_score__c = ' + 10
                     + ' and ( source_system__c = \'SB NA\''
                     + ' or    source_system__c = \'SKP NA\' )'
                     + ' and   im_imga__c = \'' + imga + '\'';

        System.debug (Logginglevel.INFO, 'getTotalRedRevenue () query:  ' + query);

        List <AggregateResult> results = getResultsByQuery (query);
        totalRedRevenue = (Double) results [0].get ('redTotal');

        System.debug (Logginglevel.INFO, 'totalRedRevenue:  ' + totalRedRevenue);

        return totalRedRevenue;

    }   //  getTotalRedRevenue () 

    public static Double getTotalRevenue ( String field, String imga )
    {
        Double totalRevenue = 0;   
        String query = 'select sum(' + field + ') fieldTotal'
                     + ' from im_customer_account__c'
                     + ' where ( source_system__c = \'SB NA\''
                     + ' or      source_system__c = \'SKP NA\' )'
                     + ' and     im_imga__c = \'' + imga + '\'';

        System.debug (Logginglevel.INFO, 'getTotalRevenue () query:  ' + query);

        List <AggregateResult> results = getResultsByQuery (query);
        totalRevenue = (Double) results [0].get ('fieldTotal');

        System.debug (Logginglevel.INFO, 'totalRevenue:  ' + totalRevenue);

        return totalRevenue;

    }   //  getTotalRevenue () 

    public static Double getTotalYellowRevenue ( String imga )
    {
        Double totalYellowRevenue = 0;   
        String query = 'select sum(current_year_total_revenue__c) yellowTotal'
                     + ' from im_customer_account__c'
                     + ' where overall_at_risk_score__c > ' + 6
                     + ' and overall_at_risk_score__c < ' + 10
                     + ' and ( source_system__c = \'SB NA\''
                     + ' or    source_system__c = \'SKP NA\' )'
                     + ' and   im_imga__c = \'' + imga + '\'';

        System.debug (Logginglevel.INFO, 'getTotalYellowRevenue () query:  ' + query);

        List <AggregateResult> results = getResultsByQuery (query);
        totalYellowRevenue = (Double) results [0].get ('yellowTotal');

        System.debug (Logginglevel.INFO, 'totalYellowRevenue:  ' + totalYellowRevenue);

        return totalYellowRevenue;

    }   //  getTotalRedRevenue ()

    //  private methods listed in alphabetical order
    private static List <AggregateResult> getResultsByQuery ( String query )
    {
        List <AggregateResult> results = new List <AggregateResult> ();

        results = Database.query (query);

        return results;

    }   //  getResultsByQuery ()

}