force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/AlternativeNames__c.field-meta.xml
<CustomField>
    <fullName>AlternativeNames__c</fullName>
    <label>Alternative Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Since the Opportunity is now locked for Sales Profiles at Stages 6 and 7, sales still needs to update field “Up-Sell Detail” in stages 6 and 7 to log billing details. This allows them to communicate to Commissions via this field. “Up-sell Detail” Chatter Action allows bypassing the validation and is able to only update this field.[Case# 02497355].</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Skip_Quote_Primary_Validation__c/Skip_Quote_Primary_Validation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Skip the Quote Primary Checkbox Validation Rule for IME Custom Sys Admi</description>
    <label>Skip Quote Primary VR</label>
</CustomObject>

force-app/main/default/objects/Skip_Quote_Primary_Validation__c/fields/ByPass_Validation__c.field-meta.xml
<CustomField>
    <fullName>ByPass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest(seeAllData = TRUE)
public class QuoteTriggerHandlerTest {
    
    static testMethod void handlerTestMethod(){
        
        Skip_Quote_Primary_Validation__c testCustomSetting = new Skip_Quote_Primary_Validation__c();
        Profile imCustomAdminProfile = [Select Id from Profile where Name ='IM_Custom Sys Admin'];
        
        IM_Country__c country=new IM_Country__c(Name='United States',AlternativeNames__c='USA');
         insert country;
        
        Account A = new Account(name='Account4TestMethod'+system.now(), BillingStreet='test',BillingState='MA',BillingCity='Boston',BillingCountry='United States');
        insert A;
        
        RecordType r=new RecordType();
         r=[select id from RecordType where name='Standard Opportunity'];
        
        Opportunity opp = new Opportunity();
        opp.AccountId = A.Id;
        opp.Name = 'Test Handler Opp';
        opp.IM_Booked_Date__c = System.today().addMonths(3);
        opp.StageName = '1 - Qualification';
        opp.CloseDate = Date.today();
        opp.Type = 'New Deal';
        opp.RecordTypeId = r.Id;
        
        insert opp;
        
        Quote q1 = new Quote();
        q1.Name = 'To1';
        q1.Status = 'Accepted';
        q1.Primary__c = True;
        q1.OpportunityId = opp.Id;
        
        
        Quote q2 = new Quote();
        q2.Name = 'To2';
        q2.Status = 'Draft'; 
        q2.Primary__c = false;
        q2.OpportunityId = opp.Id;
        
        Quote q3 = new Quote();
        q3.Name = 'To3';
        q3.Status = 'Approved';
        q3.Primary__c = false;
        q3.OpportunityId = opp.Id;
        
        List<Quote> cList = new List<Quote>(); 
        cList.add(q1);
        List<Quote> cList2 = new List<Quote>();
        cList2.add(q2);
        cList2.add(q3);
        insert cList;
        insert cList2;
        
        
        test.startTest();
         
        testCustomSetting.ByPass_Validation__c = TRUE;
        testCustomSetting.SetupOwnerId = imCustomAdminProfile.Id;
        //insert testCustomSetting;
        q2.status='Accepted';
        update q2;
        QuoteTriggerHandler.QuoteValidation(cList);
        test.stopTest();
        
    }

}