force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Iso31662Code__c.field-meta.xml
<CustomField>
    <fullName>Iso31662Code__c</fullName>
    <description>2 Digit ISO country Code</description>
    <label>ISO 3166-2 Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Primary_Product_Line__c</fullName>
    <label>Primary Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clean Start</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Data Restoration &amp; Migration</fullName>
            </value>
            <value>
                <fullName>Digital Solutions</fullName>
                <isActive>false</isActive>
                <label>Digital Solutions</label>
            </value>
            <value>
                <fullName>Digitization</fullName>
            </value>
            <value>
                <fullName>DM (All other service lines)</fullName>
            </value>
            <value>
                <fullName>DM Cloud Solutions</fullName>
                <isActive>false</isActive>
                <label>DM Cloud Solutions</label>
            </value>
            <value>
                <fullName>DM SITAD</fullName>
            </value>
            <value>
                <fullName>DM Tape Vaulting</fullName>
            </value>
            <value>
                <fullName>DXP (InSight)</fullName>
            </value>
            <value>
                <fullName>Entertainment Services</fullName>
            </value>
            <value>
                <fullName>Fixed Asset Management</fullName>
                <isActive>false</isActive>
                <label>Fixed Asset Management</label>
            </value>
            <value>
                <fullName>Incubation</fullName>
                <isActive>false</isActive>
                <label>Incubation</label>
            </value>
            <value>
                <fullName>Information Governance</fullName>
            </value>
            <value>
                <fullName>ITRenew Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>ITRenew Contracted Sales Only</label>
            </value>
            <value>
                <fullName>MAS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Professional Staffing</fullName>
            </value>
            <value>
                <fullName>Records Management - Paper document storage</fullName>
                <isActive>false</isActive>
                <label>Records Management - Paper document storage</label>
            </value>
            <value>
                <fullName>Regency Technologies - Contracted Sales Only</fullName>
                <isActive>false</isActive>
                <label>Regency Technologies - Contracted Sales Only</label>
            </value>
            <value>
                <fullName>RM (All other service lines)</fullName>
                <isActive>false</isActive>
                <label>RM (All other service lines)</label>
            </value>
            <value>
                <fullName>RM Secure Storage</fullName>
            </value>
            <value>
                <fullName>Scan</fullName>
                <isActive>false</isActive>
                <label>Scan</label>
            </value>
            <value>
                <fullName>Secure Shredding</fullName>
            </value>
            <value>
                <fullName>Shred</fullName>
                <isActive>false</isActive>
                <label>Shred</label>
            </value>
            <value>
                <fullName>Sierra26</fullName>
                <isActive>false</isActive>
                <label>Sierra26</label>
            </value>
            <value>
                <fullName>SITAD</fullName>
            </value>
            <value>
                <fullName>Smart Suite</fullName>
            </value>
            <value>
                <fullName>SMB Packages</fullName>
                <isActive>false</isActive>
                <label>SMB Packages</label>
            </value>
            <value>
                <fullName>Special Projects - Data Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QTB_Deferred_Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>QTB_Deferred_Renewal_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>#OM-6 Created for Deferred Renewal Opportuntiy</description>
    <label>Deferred renewal opportunity?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/QTB_Original_Quote__c.field-meta.xml
<CustomField>
    <fullName>QTB_Original_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#SFCPQBLG-162: To carry original sales quote to subsequent renewed opportunities</description>
    <label>Original Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities (Original Quote)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/QTB_Bill_Code_Product_Lookup__c.object-meta.xml
<CustomObject>
    <label>Bill Code Product Lookup</label>
    <nameField>
        <label>Bill Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Code Product Lookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Active__c.field-meta.xml
<CustomField>
    <fullName>QTB_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Country__c.field-meta.xml
<CustomField>
    <fullName>QTB_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IM Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Bill Code Product Lookup</relationshipLabel>
    <relationshipName>QTB_Bill_Code_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Pricing_Bill_Code__c.field-meta.xml
<CustomField>
    <fullName>QTB_Pricing_Bill_Code__c</fullName>
    <label>Pricing Bill Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Primary__c.field-meta.xml
<CustomField>
    <fullName>QTB_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Product2__c.field-meta.xml
<CustomField>
    <fullName>QTB_Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bill Code Product Lookup</relationshipLabel>
    <relationshipName>QTB_Bill_Code_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QTB_Bill_Code_Product_Lookup__c/fields/QTB_Source_Bill_Code__c.field-meta.xml
<CustomField>
    <fullName>QTB_Source_Bill_Code__c</fullName>
    <label>Source Bill Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Customer_Billing_Account_Lookup__c/QTB_Customer_Billing_Account_Lookup__c.object-meta.xml
<CustomObject>
    <label>Customer Billing Account Lookup</label>
    <nameField>
        <displayFormat>CBA - {000000000}</displayFormat>
        <label>QTB Customer Billing Account Lookup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Billing Account Lookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QTB_Customer_Billing_Account_Lookup__c/fields/QTB_Compound_Key__c.field-meta.xml
<CustomField>
    <fullName>QTB_Compound_Key__c</fullName>
    <label>Compound Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Customer_Billing_Account_Lookup__c/fields/QTB_Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>QTB_Customer_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipName>QTB_Customer_Billing_Account_Lookup</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QTB_Customer_Billing_Account_Lookup__c/fields/QTB_Pricefx_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>QTB_Pricefx_Customer_ID__c</fullName>
    <label>PriceFX Customer ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QTB_Customer_Billing_Account_Lookup__c/fields/QTB_Quote__c.field-meta.xml
<CustomField>
    <fullName>QTB_Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SBQQ__Quote__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Quote, Sales Quote - Approved, Sales Quote - In Review</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Customer Billing Account Lookup</relationshipLabel>
    <relationshipName>Customer_Billing_Account_Lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QTB_RenewalUpliftBatch_Test.cls
/*****************************************************************************************************
* Class: QTB_RenewalUpliftBatch_Test
* Author: Accenture
* Purpose: Test Class for QTB_RenewalUpliftBatch
* Change History: 6/19/2020
* Developer     Date           Description
* ------------------------------------------------------------------------------------------- 
* Accenture   6/10/2020
*******************************************************************************************************/
@isTest(seeAllData=false)
private with sharing class QTB_RenewalUpliftBatch_Test {
    @testSetup static void setup() {
        List<Account> accList = QTB_TestDataFactory.createAccounts(1, 'Standard Account');
        accList[0].name = 'Account for Renewal Uplift';
        database.update(accList);
        
        blng__BillingRule__c billingRule = QTB_TestDataFactory.createBillingRule('Yes');
        blng__RevenueRecognitionRule__c revenueRule= QTB_TestDataFactory.createRevenueRecognitionRule('Yes');
        blng__TaxRule__c taxRule = QTB_TestDataFactory.createTaxRule('Yes');
        
        List<product2> product=QTB_TestDataFactory.createProducts(1);
        product[0].blng__BillingRule__c=billingRule.id;
        product[0].blng__RevenueRecognitionRule__c =revenueRule.id;
        product[0].blng__TaxRule__c =taxRule.id;
        database.update(product); 
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = QTB_TestDataFactory.createPricebookEntry(product[0]);
        
        IM_Country__c country = new IM_Country__c(Name = 'United States',Iso31662Code__c='US');
        database.insert(country);
               
        List<Opportunity> oppList = QTB_TestDataFactory.createOpps(accList);
        oppList[0].Pricebook2Id =pricebookId;
        oppList[0].billing_country__c = country.id;
        oppList[0].recordTypeId = QTB_Utils.OPP_SALES_RECTYPEID;
        oppList[0].Primary_Product_Line__c ='Records Management';
        
        List<SBQQ__Quote__c> quoteList = QTB_TestDataFactory.createCPQQuotes(1,oppList[0].id,accList[0].id,true,null);
        quoteList[0].SBQQ__PriceBook__c=pricebookId;
        quoteList[0].SBQQ__StartDate__c = System.Today();
        quoteList[0].SBQQ__Status__c ='Draft';
        
        update quoteList;
        
        List<SBQQ__QuoteLineGroup__c> quoteGroupList = QTB_TestDataFactory.createCPQQuoteLineGroups(1, quoteList[0].id,accList[0].id );
        List<SBQQ__QuoteLine__c> quoteLinesList = QTB_TestDataFactory.createCPQQuoteLines(1,quoteList[0].id,quoteGroupList[0].id,product[0].id );
        quoteList[0].SBQQ__Status__c ='Approved';
        
        update quoteList;
        
        List<Order> orderList = QTB_TestDataFactory.createCPQOrders(1,quoteList[0].id,accList[0].id);
        List<Contract> testContracts = QTB_TestDataFactory.createCPQContracts(1,orderList[0].id,accList[0].id,quoteList[0].id);
        testContracts[0].SBQQ__Quote__c = quoteList[0].id;
        database.update(testContracts);
        Test.startTest();
        List<Opportunity> testRenewalOpp = QTB_TestDataFactory.createCPQOppsNew(accList,'CPQ Sales Opportunity');
        testRenewalOpp[0].SBQQ__RenewedContract__c = testContracts[0].id;
        testRenewalOpp[0].QTB_Deferred_Renewal_Opportunity__c = True;
         testRenewalOpp[0].QTB_Original_Quote__c =quoteList[0].id;
        testRenewalOpp[0].billing_country__c = country.id;
        testRenewalOpp[0].Primary_Product_Line__c ='Records Management';
        database.update(testRenewalOpp);
        
        List<SBQQ__Quote__c> testRenewalQuotes = QTB_TestDataFactory.createRenewalQuotes(1, testRenewalOpp[0].Id, oppList[0].AccountId, false, null);
        
        testRenewalQuotes[0].SBQQ__Opportunity2__c = testRenewalOpp[0].id;
        testRenewalQuotes[0].SBQQ__Status__c = 'Draft';
        database.update(testRenewalQuotes);
        
        List<SBQQ__QuoteLineGroup__c> quoteGroupList4 = QTB_TestDataFactory.createCPQQuoteLineGroups(1, testRenewalQuotes[0].id,accList[0].id );
        List<SBQQ__QuoteLine__c> quoteLinesList4 = QTB_TestDataFactory.createCPQQuoteLines(1,testRenewalQuotes[0].id,quoteGroupList4[0].id,product[0].id );
        quoteLinesList4[0].SBQQ__ListPrice__c =10;
        database.update(quoteLinesList4);
        
        QTB_Bill_Code_Product_Lookup__c  billcode = new QTB_Bill_Code_Product_Lookup__c();
        billcode.QTB_Product2__c =product[0].id;
        billcode.QTB_Active__c= True;
        billcode.QTB_Primary__c= True;
        Billcode.QTB_Pricing_Bill_Code__c='201';
        Billcode.QTB_Country__c =country.id;
        Billcode.QTB_Source_Bill_Code__c='201';
        database.insert(billcode);
        
        IM_Customer_Account__c customerAccount = new IM_Customer_Account__c();
        customerAccount.name = 'test';
        customerAccount.Billing_Country__c=country.id;
        customerAccount.IM_Account__c=accList[0].id;
        database.insert(customerAccount);
        
        List<QTB_Customer_Billing_Account_Lookup__c> customerTableRecords = new List<QTB_Customer_Billing_Account_Lookup__c>();
        QTB_Customer_Billing_Account_Lookup__c customerTable = new QTB_Customer_Billing_Account_Lookup__c();
        customerTable.QTB_Pricefx_Customer_ID__c ='140AI';
        customerTable.QTB_Quote__c =quoteList[0].id;
        customerTable.QTB_Customer_Account__c=customerAccount.id;
        customerTable.QTB_Compound_Key__c='xyz';
        customerTableRecords.add(customerTable);
               
        QTB_Customer_Billing_Account_Lookup__c customerTable2 = new QTB_Customer_Billing_Account_Lookup__c();
        customerTable2.QTB_Pricefx_Customer_ID__c ='142ER';
        customerTable2.QTB_Quote__c =quoteList[0].id;
        customerTable2.QTB_Customer_Account__c=customerAccount.id;
        customerTable2.QTB_Compound_Key__c='test';
        customerTableRecords.add(customerTable2);
        database.insert(customerTableRecords);
        
        Test.stopTest();
        
    }
    
    static testmethod void test() { 
        Test.startTest();
        set<ID> contrIDset = new set<ID>();
        list<Account> accountList = [select id,name from account  limit 1];
        for(Contract con :[select id,name,AccountID from contract where AccountID =:accountList[0].id])
        {
            contrIDset.add(con.Id);
        }       
        QTB_RenewalUpliftBatch obj = new QTB_RenewalUpliftBatch(contrIDset);
        Test.setMock(HttpCalloutMock.class, new QTB_MockPricefxCalloutRenewal());
        DataBase.executeBatch(obj);
        Test.stopTest(); 
        System.assert(accountList.size()>0);
    }
    
    
}