force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>MENAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account_Number__c</fullName>
    <inlineHelpText>The customer account ID as setup in the billing system. SKP, ARCVMS etc</inlineHelpText>
    <label>Customer ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Commit_to_Forecast__c.field-meta.xml
<CustomField>
    <fullName>IM_Commit_to_Forecast__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Forecast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Servicing_Region__c.field-meta.xml
<CustomField>
    <fullName>IM_Servicing_Region__c</fullName>
    <description>The IM servicing region related to the opportunity</description>
    <label>Servicing District/Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aberdeen</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahemdabad</fullName>
            </value>
            <value>
                <fullName>Aix</fullName>
            </value>
            <value>
                <fullName>Albuquerque</fullName>
            </value>
            <value>
                <fullName>Alphen</fullName>
            </value>
            <value>
                <fullName>Asheville</fullName>
            </value>
            <value>
                <fullName>Aston</fullName>
            </value>
            <value>
                <fullName>Athens</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Baltimore / Washington</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Barranquilla</fullName>
            </value>
            <value>
                <fullName>Basildon</fullName>
            </value>
            <value>
                <fullName>Baton Rouge</fullName>
            </value>
            <value>
                <fullName>Belfast</fullName>
            </value>
            <value>
                <fullName>Belfast - Northern Ireland</fullName>
            </value>
            <value>
                <fullName>Berlin</fullName>
            </value>
            <value>
                <fullName>Bhondsi</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bhubhneswar</fullName>
            </value>
            <value>
                <fullName>Bilbao</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Birmingham (UK)</fullName>
            </value>
            <value>
                <fullName>Bochum</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Stage_5_Entered_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Stage_5_Entered_Date__c</fullName>
    <label>Stage 5 Entered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IME_Reason_Won__c.field-meta.xml
<CustomField>
    <fullName>IME_Reason_Won__c</fullName>
    <label>Reason Won</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Benchmarking</fullName>
            </value>
            <value>
                <fullName>Decision Location</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Relationship Strength</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Service Expectation</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>Technical Fit</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Most_Recent__c</fullName>
    <inlineHelpText>For new opportunities on existing customers, add the most recent source of the lead</inlineHelpText>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>#13083 : Opportunity| Clusters: Create new fields on IM Country &amp; Opportunity to include Regions, Clusters, Sub Clusters</description>
    <formula>TEXT(Billing_Country__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <inlineHelpText>The operational source system the customer ID is managed through</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SKP Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>Other Europe</fullName>
            </value>
            <value>
                <fullName>SB IMLA</fullName>
            </value>
            <value>
                <fullName>SKP IMLA</fullName>
            </value>
            <value>
                <fullName>Other IMLA</fullName>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>SKP IMAP</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SRMS IMAP</fullName>
            </value>
            <value>
                <fullName>Tape Guard IMAP</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>SB IMAP</fullName>
            </value>
            <value>
                <fullName>TRSQL</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TOBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Activation_Settings__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_IMEOpportunityCustAcctTrg.cls
@isTest(seeAlldata = true)
private class Test_IMEOpportunityCustAcctTrg {
  
// #16283 Commenting out the code as its main class(IME_OpportunityCustAcctTrg) is Inactive 
  
  static testMethod void runTest() 
  { 
       /* List<Trigger_Activation_Settings__c> customsettings = Trigger_Activation_Settings__c.getall().values();
        List<Trigger_Activation_Settings__c> updatesettings = new List<Trigger_Activation_Settings__c>();
        for(Trigger_Activation_Settings__c cs : customsettings){
            if(cs.Trigger__c == 'createcustomeraccounts'){
            	cs.Value__c='True';
            }
            updatesettings.add(cs);
        }
        update updatesettings;
        
        Profile p = [Select id from profile where name = 'IME_Contracts'];
        IM_Country__c cntry = CountryNameTranslator.getOrCreateTestCountry
                                                    ( (new IM_Country__c(name = 'United Kingdom',
                                                                         Region__c = 'Europe')));
        
        User u = new User(alias = 'hasrole', email='userwithrole@roletest1.com'
                              ,emailencodingkey='UTF-8'
                              , lastname='Testing', languagelocalekey='en_US'
                              , localesidkey='en_US', profileid = p.id
                              , timezonesidkey='America/Los_Angeles'
                              , username='userwithrole@testorg.com'
                              , Country = 'United Kingdom');
        
        insert u;
        RecordType EUOppType = [select id from RecordType
                              where name = 'IME standard opportunity'
                                and sObjectType = 'Opportunity'];
                                
           
       account a = new Account(name='x');
       insert a;
   
        Product2 product = 
        new Product2(
        Secondary_Product_Allowed__c=true, 
        Name='test', 
        CurrencyIsoCode='GBP', 
        IsActive=true);
        insert product;
        
      //Create the opportunity
       Opportunity o = new Opportunity(name = 'c'
                                      ,AccountId = a.id
                                      ,Source_System__c = 'SKP Europe'
                                      ,Billing_Country__c = cntry.id 
                                      ,Lead_Source_Most_Recent__c = 'x'
                                      //,StageName = '7 - Closed'
                                      ,StageName = '5 - Signed/PO in'
                                      //,Customer_Account_Number__c = System.now().format()
                                      ,RecordTypeId = EUOppType.Id
                                      ,IM_Servicing_Region__c ='London'
                                          ,IM_Commit_to_Forecast__c = true
                                          ,IM_Stage_5_Entered_Date__c  = System.today()
                                      ,CloseDate = System.today()+10
                                      ,IME_Reason_Won__c = 'Price'
                                      ,CurrencyIsoCode='GBP'
                                      );
                                             
        insert o;
        
               
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        PricebookEntry pbe = new PricebookEntry(
          Pricebook2Id = standardPB.Id, 
          Product2Id = product.Id, 
          UnitPrice = 1, 
          IsActive = true,
          CurrencyIsoCode='GBP', 
          UseStandardPrice = false);
  
  insert pbe;
  
        //PricebookEntry pbe = [select id from PricebookEntry where CurrencyIsoCode='GBP' and IsActive= true   limit 1];
        
      //  Select o.PricebookEntryId, o.OpportunityId From OpportunityLineItem o
        
        OpportunityLineItem oli = new OpportunityLineItem(
        PricebookEntryId= pbe.id,
        OpportunityId=o.id,
        Quantity=1,
        TotalPrice=1
        );
        
        insert oli;
         test.startTest();
        o.Customer_Account_Number__c = System.now().format();
        o.StageName = '7 - Closed';
         update o;
        
       
        
       // o.Customer_Account_Number__c = System.now().format()
        o.Customer_Account_Number__c = null;
          
        update o;
           
        o.Customer_Account_Number__c = System.now().format();
        try{
            update o;
        }
        catch(Exception e)
        {
            
        }
         
       test.stopTest(); 
       
    } */
 
  }
}