force-app/main/default/objects/IM_Country__c/IM_Country__c.object-meta.xml
<CustomObject>
    <description>custom object used to store the country name, ISO country code for reference in fields, validation rules, apex classes and triggers</description>
    <label>IM Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IM Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>ISO Code should be required</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>IM_Country__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Servicing_Region__c.field-meta.xml
<CustomField>
    <fullName>IM_Servicing_Region__c</fullName>
    <description>The IM servicing region related to the opportunity</description>
    <label>Servicing District/Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aberdeen</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahemdabad</fullName>
            </value>
            <value>
                <fullName>Aix</fullName>
            </value>
            <value>
                <fullName>Albuquerque</fullName>
            </value>
            <value>
                <fullName>Alphen</fullName>
            </value>
            <value>
                <fullName>Asheville</fullName>
            </value>
            <value>
                <fullName>Aston</fullName>
            </value>
            <value>
                <fullName>Athens</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Baltimore / Washington</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Barranquilla</fullName>
            </value>
            <value>
                <fullName>Basildon</fullName>
            </value>
            <value>
                <fullName>Baton Rouge</fullName>
            </value>
            <value>
                <fullName>Belfast</fullName>
            </value>
            <value>
                <fullName>Belfast - Northern Ireland</fullName>
            </value>
            <value>
                <fullName>Berlin</fullName>
            </value>
            <value>
                <fullName>Bhondsi</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bhubhneswar</fullName>
            </value>
            <value>
                <fullName>Bilbao</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Birmingham (UK)</fullName>
            </value>
            <value>
                <fullName>Bochum</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Most_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Most_Recent__c</fullName>
    <inlineHelpText>For new opportunities on existing customers, add the most recent source of the lead</inlineHelpText>
    <label>Lead Source - Most Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>6sense</fullName>
            </value>
            <value>
                <fullName>Channel / Partners</fullName>
            </value>
            <value>
                <fullName>Content Syndication</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>List Purchased</fullName>
                <label>List Purchase</label>
            </value>
            <value>
                <fullName>Live Event</fullName>
            </value>
            <value>
                <fullName>Online Event</fullName>
            </value>
            <value>
                <fullName>Other / Unknown</fullName>
            </value>
            <value>
                <fullName>Paid Media</fullName>
            </value>
            <value>
                <fullName>Parent - Integrated / Cross Channel</fullName>
            </value>
            <value>
                <fullName>Sales Generated</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Telemarketing</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <inlineHelpText>The operational source system the customer ID is managed through</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SKP Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>Other Europe</fullName>
            </value>
            <value>
                <fullName>SB IMLA</fullName>
            </value>
            <value>
                <fullName>SKP IMLA</fullName>
            </value>
            <value>
                <fullName>Other IMLA</fullName>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>SKP IMAP</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SRMS IMAP</fullName>
            </value>
            <value>
                <fullName>Tape Guard IMAP</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>SB IMAP</fullName>
            </value>
            <value>
                <fullName>TRSQL</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TOBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Coach_Activity__c/Sales_Coach_Activity__c.object-meta.xml
<CustomObject>
    <label>Sales Coach Activity</label>
    <nameField>
        <displayFormat>SCAN-{000000}</displayFormat>
        <label>Sales Coach Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Coach Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Coach_Activity__c/fields/Activity_Details__c.field-meta.xml
<CustomField>
    <fullName>Activity_Details__c</fullName>
    <label>Activity Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Activity__c/fields/Ordering_Number__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Number__c</fullName>
    <label>Ordering Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Activity__c/fields/Sales_Coach_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sales_Coach_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Coach Stage</label>
    <referenceTo>Sales_Coach_Stage__c</referenceTo>
    <relationshipLabel>Sales Coach Activities</relationshipLabel>
    <relationshipName>Sales_Coach_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section__c/Sales_Coach_Section__c.object-meta.xml
<CustomObject>
    <label>Sales Coach Section</label>
    <nameField>
        <displayFormat>SCS-{0000}</displayFormat>
        <label>Sales Coach Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Coach Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Coach_Section__c/fields/Sales_Coach_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sales_Coach_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Coach Stage</label>
    <referenceTo>Sales_Coach_Stage__c</referenceTo>
    <relationshipLabel>Sales Coach Sections</relationshipLabel>
    <relationshipName>Sales_Coach_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section__c/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section__c/fields/Section_Width__c.field-meta.xml
<CustomField>
    <fullName>Section_Width__c</fullName>
    <label>Section Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section_Item__c/Sales_Coach_Section_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Coach Section Item</label>
    <nameField>
        <displayFormat>SCSI-{0000}</displayFormat>
        <label>Sales Coach Section Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Coach Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Coach_Section_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section_Item__c/fields/Link_to_Content__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Content__c</fullName>
    <label>Link to Content</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section_Item__c/fields/Sales_Coach_Section__c.field-meta.xml
<CustomField>
    <fullName>Sales_Coach_Section__c</fullName>
    <label>Sales Coach Section</label>
    <referenceTo>Sales_Coach_Section__c</referenceTo>
    <relationshipLabel>Sales Coach Section Items</relationshipLabel>
    <relationshipName>Sales_Coach_Section_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Section_Item__c/fields/Section_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Section_Ordering__c</fullName>
    <label>Section Ordering</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Stage__c/Sales_Coach_Stage__c.object-meta.xml
<CustomObject>
    <label>Sales Coach Stage</label>
    <nameField>
        <label>Sales Coach Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Coach Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Coach_Stage__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Coach_Stage__c/fields/Buyer_Stage__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Stage__c</fullName>
    <label>Stage Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestingUtil.cls
@isTest
public with sharing class TestingUtil {
  public String opId;
  public String scsId;
  public String scsecId;
  public String scsecItemId;
  public String actId;
  static Integer offSet = 0;

  public TestingUtil(){
    opId = makeTestableOp();
    scsId = makeSalesCoachStage();
    scsecId = makeSalesCoachSections();
    scsecItemId = makeSecItem();
    actId = makeActivities();
    ApexPages.currentPage().getParameters().put('id', this.opId);
  }
 //CloseDate formerly First Bill Date, Booked Date is now First Bill Date.
  private String makeTestableOp(){
    Opportunity op = new Opportunity();
    op.Name='testOpName';
    op.IM_Booked_Date__c = Date.today();
    op.StageName='1 - Qualification';
    op.Lead_Source_Most_Recent__c = 'Email';
    insert op;
    return op.Id;
  }
  
  private String makeSalesCoachStage(){
    Sales_Coach_Stage__c scs = new Sales_Coach_Stage__c();
    scs.Name='testStage';
    scs.Buyer_Stage__c='testBuyStage';
    scs.Active__c=true;
    insert scs;
    return scs.Id;
  }
  
  private String makeSalesCoachSections(){
    Sales_Coach_Section__c scsec =  new Sales_Coach_Section__c();
    scsec.Section_Ordering__c =1.0;
    scsec.Section_Name__c='testSection';
    scsec.Sales_Coach_Stage__c=scsId;
    scsec.Section_Width__c=33.0;
    insert scsec;
    return scsec.Id;
  }
  
  private String makeSecItem(){
    Sales_Coach_Section_Item__c secItem = new Sales_Coach_Section_Item__c();
    secItem.Section_Ordering__c=1.0;
    secItem.Sales_Coach_Section__c=scsecId;
    secItem.Link_to_Content__c='http://www.google.com';
    secItem.Item_Name__c='testItem';
    secItem.Display__c=true;
    secItem.Products__c='';
    insert secItem;
    return secItem.Id;
  }
  
  private String makeActivities(){
    Sales_Coach_Activity__c sca = new Sales_Coach_Activity__c();
    sca.Sales_Coach_Stage__c=scsId;
    sca.Ordering_Number__c=1.0;
    sca.Activity_Details__c='testActivity';
    insert sca;
    return sca.Id;
  }
  
  public static IM_Country__c createIMCountry()
  {
    IM_Country__c cntry = new IM_Country__c(Name = 'Test Country');
    insert cntry;
    
    return cntry;
  }
  
  public static Opportunity createOpportunity()
  {
    IM_Country__c cntry = createIMCountry();
     
      Account testAccount = new Account();
      testAccount.Name = 'TestAccount';
      insert testAccount;
    
    //CloseDate formerly First Bill Date, Booked Date is now First Bill Date.  
    Opportunity opp = new Opportunity(
                                      name = 'test'
                                      ,Source_System__c = 'test SKP Europe'
                                      ,Billing_Country__c = cntry.id 
                                      ,Lead_Source_Most_Recent__c = 'x'
                                      ,StageName = '1 - Qualification'
                                      ,IM_Servicing_Region__c ='London'
                                      ,IME_Reason_Won__c = 'Benchmarking'
                                      ,AccountId = testAccount.Id   
                                      ,IM_Booked_Date__c = System.today(),
                                       CloseDate = System.today()
                                      );
    insert opp;

    return opp;
  }
  
  public static Pricebook2 createPricebook2()
  {
    Pricebook2 pr = new Pricebook2(Name = 'North America');
    insert pr;
    
    return pr;
  }
  
  public static List<User> createUsers(Integer howMany, Boolean doInsert)
  {
    Profile p = [Select id from profile where name = 'IM_Custom Sys Admin'];

    List<User> allUsers = new List<User>();
    
    for(Integer i = 0; i < howMany; i++)
    {
      offset++;
      User us = new User(alias = 'ztest'+offset, email='p'+offset+'@malkosus.com'
                         ,emailencodingkey='UTF-8'
                         , firstname='Fir'+offset
                         , lastname='Tes'+offset, languagelocalekey='en_US'
                         , localesidkey='en_US', profileid = p.id
                         , timezonesidkey='America/Los_Angeles'
                         , username='tet'+offset+'@malkosus.com'
                         ,isActive=true
                         , Country = 'United Kingdom');
      allUsers.add(us);
    }
    
    if(doInsert)
    insert allUsers;

    return allUsers;
  }
  
  public static User createUser()
  {
    Profile p = [Select id from profile where name = 'IM_Custom Sys Admin'];

    User us = new User(alias = 'hasrole', email='ptkachenko@malkosus.com'
                       ,emailencodingkey='UTF-8'
                       , lastname='Testing', languagelocalekey='en_US'
                       , localesidkey='en_US', profileid = p.id
                       , timezonesidkey='America/Los_Angeles'
                       , username='test@malkosus.com'
                       , Country = 'United Kingdom');
    insert us;

    return us;
  }
  
  public static Schedule_A__c createScheduleA(ID Id, User u)
  {
    Schedule_A__c sc = new Schedule_A__c(Approver_1__c = u.Id, Opportunity__c = Id, IsMaster__c = true, Reference__c = 'Testing File');

    insert sc;

    return sc;
  }
  
  public static Schedule_A__c createScheduleA(Boolean IsTemplate)
  {
    Schedule_A__c sc = new Schedule_A__c(IsTemplate__c = IsTemplate, IsMaster__c = true, Reference__c = 'Testing File');
    sc.Approver_1__c = UserInfo.getUserID();
    insert sc;

    return sc;
  }

  public static Schedule_A_Quote_Item__c createScheduleAQuoteItem(ID Id)
  {
    //#30912 PA Model LINES field clean up
    Schedule_A_Quote_Item__c sq = new Schedule_A_Quote_Item__c(Schedule_A__c = Id/*, Offering_Type__c = 'TEST_TYPE'*/);

    insert sq;

    return sq;
  }
  
  public static Quote createQuote()
  {
      
    Opportunity opp = createOpportunity();
    Quote quote = new Quote();
    quote.Name  = 'Test Quote';
    quote.OpportunityId  = opp.id;
    
    insert quote;

    return quote;
  } 
}