force-app/main/default/objects/Billing_Territory__c/Billing_Territory__c.object-meta.xml
<CustomObject>
    <label>Billing Territory</label>
    <nameField>
        <label>Billing Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Dashboard_Component_Assignment__c/Territory_Dashboard_Component_Assignment__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Territory Dashboard Component Assignment</label>
</CustomObject>

force-app/main/default/objects/Territory_Dashboard_Component_Assignment__c/fields/DashboardId__c.field-meta.xml
<CustomField>
    <fullName>DashboardId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>DashboardId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Territory_Dashboard_Component_Assignment__c/fields/Territory_Region__c.field-meta.xml
<CustomField>
    <fullName>Territory_Region__c</fullName>
    <inlineHelpText>select either &quot;Territory&quot; or &quot;Region&quot;</inlineHelpText>
    <label>Territory/Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory_Dashboard_Component_Assignment__c/fields/TerritoryNames__c.field-meta.xml
<CustomField>
    <fullName>TerritoryNames__c</fullName>
    <description>Territories to be considered in dashboard component for a specific dashboard</description>
    <inlineHelpText>Please delimit territory names with a comma(&apos;,&apos;).</inlineHelpText>
    <label>TerritoryNames</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DashboardTerritoryLookup.cls
public class DashboardTerritoryLookup {
	
	public final static String REGION = 'Region';
	public final static String TERRITORY = 'Territory';
	@TestVisible static String INVALID_CUSTOM_SETTING_TERRITORY_NAME = 'There is an invalid territory or region name being used in the custom setting Territory Dashboard Component Assignment.';
	@TestVisible static String INVALID_DASHBOARD_ERROR = 'An invalid dashboard id used on Net Cube Growth Component dashboard.';
	
	public Set<String> territoryNames {get; set;}
	public Set<String> regionNames {get; set;}
	private Set<String> validDashboards {get; set;}
	
	public String dashboardId { 
		get; 
		set {
			dashboardId = value;
			refreshDashboardFromCS();
		} 
	} 
	
	public DashboardTerritoryLookup() {
		refreshDashboardFromCS();
	}
	public DashboardTerritoryLookup(String dashId) {
		dashboardId = dashId;
	}
	
	public void refreshDashboardFromCS()
	{
		validDashboards = new Set<String>();
		territoryNames = new Set<String>();
		regionNames = new Set<String>();
		for (Territory_Dashboard_Component_Assignment__c cs : Territory_Dashboard_Component_Assignment__c.getAll().values() ){
			validDashboards.add(cs.DashboardId__c);
			if (cs.DashboardId__c == dashboardId){
				for (String terrtitory : cs.TerritoryNames__c.split(',')){
					if (!String.isBlank(terrtitory)){
						if (cs.Territory_Region__c == REGION){
							regionNames.add(terrtitory.trim());
						}
						else if (cs.Territory_Region__c == TERRITORY){
							territoryNames.add(terrtitory.trim());
						}
					}
				}
			}
		}
	}
	
	public Boolean isValidDashboardId() {
		return validDashboards.contains(dashboardId);
	}
	
	public List<Billing_Territory__c> getBillingTerritoryIds(){
		List<Billing_Territory__c> allTerritories = new List<Billing_Territory__c>();
		allTerritories.addAll(getTerritories());
		allTerritories.addAll(getRegions());
		return allTerritories;
		
	}
	
	@testVisible private List<Billing_Territory__c> getRegions(){
		
		List<Billing_Territory__c> billingTerritories = [Select Id, Name, Region__c From Billing_Territory__c Where Region__c in :regionNames];
		if (billingTerritories.size() != regionNames.size()){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, INVALID_CUSTOM_SETTING_TERRITORY_NAME));
		}
		return billingTerritories;
	}
	
	
	@testVisible private List<Billing_Territory__c> getTerritories() {
		
		List<Billing_Territory__c> billingTerritories = [Select Id, Name, Region__c From Billing_Territory__c Where Name in :territoryNames];
		if (billingTerritories.size() != territoryNames.size()){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, INVALID_CUSTOM_SETTING_TERRITORY_NAME));
		}
		return billingTerritories;
	}

}