force-app/main/default/objects/Batch_Setting__c/Batch_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for the BatchInboundStorageAssignment process</description>
    <label>Batch Settings</label>
</CustomObject>

force-app/main/default/objects/Batch_Setting__c/fields/Cut_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Cut_Off_Date__c</fullName>
    <defaultValue>DATE(2014,02,01)</defaultValue>
    <description>Do not match any inbound storage records to Opportunities that have a First Billed Date (aka CloseDate) &lt;= Feb 2014</description>
    <label>Cut Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Batch_Setting__c/fields/Email_List__c.field-meta.xml
<CustomField>
    <fullName>Email_List__c</fullName>
    <label>Email List</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>5-7 alphanumeric characters</inlineHelpText>
    <label>Customer ID</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NCSP_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the opportunity that created this NCSP case for on boarding. Populated by an Apex trigger when the case is created</description>
    <label>NCSP Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (NCSP Opportunity)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/New_Department_ID__c.field-meta.xml
<CustomField>
    <fullName>New_Department_ID__c</fullName>
    <description>New Department ID added to this Customer ID. This ID will be used to create a Department in SKP and will be fed back into Salesforce as a Department record.</description>
    <inlineHelpText>New Department ID added to this Customer ID</inlineHelpText>
    <label>New Department ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/New_Division_ID__c.field-meta.xml
<CustomField>
    <fullName>New_Division_ID__c</fullName>
    <description>New Division ID added to this Customer ID. This ID will be used to create a Department in SKP and will be fed back into Salesforce as a Division record.</description>
    <inlineHelpText>New Division ID added to this Customer ID</inlineHelpText>
    <label>New Division ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source Opportunity that triggered this Support Engagement Case.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal &amp; Post Sale Support Cases</relationshipLabel>
    <relationshipName>Support_Engagement_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Storage__c/Inbound_Storage__c.object-meta.xml
<CustomObject>
    <label>Inbound Storage</label>
    <nameField>
        <displayFormat>STOR-{00000000}</displayFormat>
        <label>New Storage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Storage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Storage__c/fields/Associated_to_Opportunity_Date__c.field-meta.xml
<CustomField>
    <fullName>Associated_to_Opportunity_Date__c</fullName>
    <description>Date/Time that the inbound storage record was initially associated to a Sale.</description>
    <inlineHelpText>Date/Time that the inbound storage record was initially associated to a Sale.</inlineHelpText>
    <label>Associated to Opportunity Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Association_to_Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Association_to_Opportunity_Status__c</fullName>
    <description>Status of the association between the inbound storage record and the booked sale, managed by the commissions team.</description>
    <inlineHelpText>Status of the association between the inbound storage record and the booked sale.</inlineHelpText>
    <label>Association to Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unmatched</fullName>
                <default>true</default>
                <label>Unmatched</label>
            </value>
            <value>
                <fullName>Matched - Approved</fullName>
            </value>
            <value>
                <fullName>Matched - Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <label>Customer Account</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipName>New_Storage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Dept_ID_del__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID_del__c</fullName>
    <label>Dept. ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Div_ID_del__c.field-meta.xml
<CustomField>
    <fullName>Div_ID_del__c</fullName>
    <label>Div. ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Opportunity which produced the new storage</description>
    <inlineHelpText>Link to the Opportunity which produced the new storage</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>New_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Storage_Date__c.field-meta.xml
<CustomField>
    <fullName>Storage_Date__c</fullName>
    <label>Storage Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage_Error__c/Inbound_Storage_Error__c.object-meta.xml
<CustomObject>
    <label>Inbound Storage Errors</label>
    <nameField>
        <label>Inbound Storage Errors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inbound Storage Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Storage_Error__c/fields/Inbound_Storage__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Storage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inbound Storage</label>
    <referenceTo>Inbound_Storage__c</referenceTo>
    <relationshipLabel>Inbound Storage Errors</relationshipLabel>
    <relationshipName>Inbound_Storage_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commissionable_Window_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Commissionable_Window_Close_Date__c</fullName>
    <description>Value of Commissionable_Window__c Months past First Bill Date (Closedate)
CloseDate formerly First Bill Date, Booked Date is now First Bill Date.</description>
    <formula>DATE(
year(IM_Booked_Date__c)
+ floor((month(IM_Booked_Date__c) + Commissionable_Window__c)/12) + if(and(month(IM_Booked_Date__c)=12,Commissionable_Window__c&gt;=12),-1,0)
,
if( mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ) = 0, 12 , mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ))
,
min( 
day(IM_Booked_Date__c),
case(
max( mod( month(IM_Booked_Date__c) + Commissionable_Window__c , 12 ) , 1),
9,30,
4,30,
6,30,
11,30,
2,28,
31
)
)
)</formula>
    <label>Commissionable Window Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Bill_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Bill_Booked_Date__c</fullName>
    <description>CloseDate formerly First Bill Date, Booked Date is now First Bill Date.</description>
    <formula>if( Sales_Segment__c = &quot;Digital&quot;,  CloseDate ,  IM_Booked_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Bill / Booked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchInboundStorageAssignment.cls
/* Commenting the entire code as part of Gitlab #24448 */
global class BatchInboundStorageAssignment{
    public BatchInboundStorageAssignment(){
        
    }
}
/*
global class BatchInboundStorageAssignment implements Database.Batchable<sObject> {
    global String query; 
    global String type;
    global String status_matched; 
    global String status_unmatched; 

    global BatchInboundStorageAssignment(String query){
        this.query = query;
    }

    global Database.queryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    //delete this 
    //[SELECT Id,Dept_ID_del__c,Div_ID_del__c,IM_Customer_Account__r.Id FROM Inbound_Storage__c ]
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        String currentCommissionYear = System.Label.Current_Commission_Year;
        Boolean caught_error = false;
        Map<Id,List<Inbound_Storage__c>> acctids_storageLst = new Map<Id,List<Inbound_Storage__c>>(); 
        //map to hold acct to cases data: account Id -> case list 
        Map<Id,List<Case>> acctid_caseLst = new Map<Id,List<Case>>();
        List<Inbound_Storage__c> inbslSTforDMLOpperation = new List<Inbound_Storage__c>();
        Batch_Setting__c settings = Batch_Setting__c.getInstance('Inbound Assignment');
        Date cutOffDate = settings.Cut_Off_Date__c;
        try{
            for(SObject s : scope){
                Inbound_Storage__c in_storage = (Inbound_Storage__c)s;
                //map customer accts to inbound storage for final opp assignment and status 
                if(!acctids_storageLst.containsKey(in_storage.Customer_Account__r.Id)){
                    List<Inbound_Storage__c> ibnsLSt = new List<Inbound_Storage__c>();
                    ibnsLSt.add(in_storage);
                    acctids_storageLst.put(in_storage.Customer_Account__r.Id, ibnsLSt);
                }else{
                    acctids_storageLst.get(in_storage.Customer_Account__r.Id).add(in_storage);
                }
            }
            //create map acctid_caseLst with empty caseLst to make sure all account in the map has a list to avoid NPE
            for(Id acctId: acctids_storageLst.keySet()){
                acctid_caseLst.put(acctId,new List<Case>());
            }
            //find all the new customer setup cases for each customer accts, via the record type name
            for(Case c : [SELECT NCSP_Opportunity__r.Id
                                 ,NCSP_Opportunity__r.Type
                                 ,New_Division_ID__c
                                 ,New_Department_ID__c 
                                 ,NCSP_Opportunity__r.First_Bill_Booked_Date__c
                                 ,NCSP_Opportunity__r.Commissionable_Window_Close_Date__c
                                 ,NCSP_Opportunity__r.CloseDate
                                 ,Customer_ID__r.Id
                           FROM Case 
                           WHERE Customer_ID__c IN :acctids_storageLst.keySet() 
                             AND NCSP_Opportunity__c != null 
                             AND NCSP_Opportunity__r.CloseDate >= :cutOffDate
                             AND (RecordType.Name = 'NCSP: SKP New Customer Setup' OR RecordType.Name = 'NCSP: SKP Department Add Only' OR RecordType.Name = 'NCSP: Upsell')]){
                //add case into the map: acctid_caseLst
                acctid_caseLst.get(c.Customer_ID__r.Id).add(c);
            }
            for(Id acctId : acctids_storageLst.keySet()){
                //first check if we have 0 cases - if not, we start looking for the opp
                if(acctid_caseLst.get(acctId)!=null && acctid_caseLst.get(acctId).size() != 0){
                    //if only one, that's the opp and continue
                    if(acctid_caseLst.get(acctId).size() == 1){
                        for(Inbound_Storage__c ibns : acctids_storageLst.get(acctId)){
                            if((acctid_caseLst.get(acctId).get(0).NCSP_Opportunity__r.CloseDate < ibns.Storage_Date__c 
                                || acctid_caseLst.get(acctId).get(0).NCSP_Opportunity__r.CloseDate.monthsBetween(ibns.Storage_Date__c)==0)
                                && ibns.Storage_Date__c < acctid_caseLst.get(acctId).get(0).NCSP_Opportunity__r.Commissionable_Window_Close_Date__c){
                                ibns.Opportunity__c = acctid_caseLst.get(acctId).get(0).NCSP_Opportunity__r.Id; 
                                ibns.Association_to_Opportunity_Status__c = getStatus(acctid_caseLst.get(acctId).get(0).NCSP_Opportunity__r.Type);
                                //set the associated date 
                                ibns.Associated_to_Opportunity_Date__c = Datetime.now();
                                continue;
                            }
                            else{
                                ibns.Association_to_Opportunity_Status__c = 'Unmatched';
                            }
                        }
                    }
                    //otherwise we start paring down the list 
                    else{
                        for(Inbound_Storage__c ibns : acctids_storageLst.get(acctId)){
                            InboundStorageAssignment inbound_assignment = new InboundStorageAssignment(acctid_caseLst.get(acctId),ibns); 
                            InboundStorageAssignment.OppStack match = inbound_assignment.getMatch(); 
                            if(match != null){
                                ibns.Opportunity__c = match.opp; 
                                ibns.Association_to_Opportunity_Status__c = getStatus(match.type); 
                                //set the associated date 
                                ibns.Associated_to_Opportunity_Date__c = Datetime.now();
                            }
                            else{
                                ibns.Association_to_Opportunity_Status__c = 'Unmatched';
                            }
                        }
                    }
                }
                //if it's 0 we set it to unmatched 
                else{
                    for(Inbound_Storage__c ibns : acctids_storageLst.get(acctId)){
                        ibns.Association_to_Opportunity_Status__c = 'Unmatched';
                    }
                }

            }
        }
        catch(Exception e){
            caught_error = true;
            Inbound_Storage_Error__c err = new Inbound_Storage_Error__c(Name = 'Inbound Assignment - ' + String.valueOf(Date.today())
                                                                        ,Type__c = e.getTypeName()
                                                                        ,Message__c = e.getMessage()
                                                                        ,Stack_Trace__c = e.getStackTraceString()
                                                                        ,Line_Number__c = e.getLineNumber()
                                                                        );
            insert err; 
        }
        if(!caught_error){
            for(List<Inbound_Storage__c> inbsLst : acctids_storageLst.values()){
                inbslSTforDMLOpperation.addAll(inbsLst);
            }
            List<Database.SaveResult> res = Database.update(inbslSTforDMLOpperation,false);
            List<Inbound_Storage_Error__c> errs = new List<Inbound_Storage_Error__c>(); 

            for(Database.SaveResult sr : res){
                if(!sr.isSuccess()){
                    for(Database.Error e : sr.getErrors()){
                        Inbound_Storage_Error__c err = new Inbound_Storage_Error__c(Name = 'Inbound Assignment - ' + String.valueOf(Date.today())
                                                                                    ,Message__c = e.getMessage()
                                                                                    ,Inbound_Storage__c = sr.getId());
                        errs.add(err);
                    }
                }
            }

            if(!errs.isEmpty()){
                insert errs; 
            }
        }  
    }

    public static String getStatus(String type){
        if(type == 'New Deal'){
            return 'Matched - Approved';
        }
        else{
            return 'Matched - Pending';
        }
    }
    global void finish(Database.BatchableContext bc){
        Batch_Setting__c settings = Batch_Setting__c.getInstance('Inbound Assignment');
        AsyncApexJob apex_job = [SELECT CompletedDate,TotalJobItems,NumberOfErrors FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = settings.Email_List__c.split(',');
        //String[] toAddresses = new String[] {'drahl@bluewolfgroup.com'};
        mail.setToAddresses(toAddresses);
        mail.setReplyTo('noreply@wherever.com');
        mail.setSenderDisplayName('Salesforce');
        mail.setSubject('Inbound Storage Assignment Completed');
        mail.setPlainTextBody('Completed Date: ' + apex_job.CompletedDate + '\nNumber of Errors: ' + apex_job.NumberOfErrors + '\nTotal Batches: ' + apex_job.TotalJobItems);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}*/