force-app/main/default/objects/Call_Experience__c/Call_Experience__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the IVR greetings and queue routings for Service Cloud Voice with Amazon Connect</description>
    <label>Call Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Experience__c/fields/DTMF_Option__c.field-meta.xml
<CustomField>
    <fullName>DTMF_Option__c</fullName>
    <inlineHelpText>DTMF Option used for language selection. If the Multi-Lingual checkbox is not selected, it will default the DTMF Option to 1.</inlineHelpText>
    <label>DTMF Option</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Used_in_Multi_Lingual_Setup__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Emergency_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Prompt__c</fullName>
    <description>Prompt that will be played when &quot;is Emergency?&quot; is set to true.</description>
    <inlineHelpText>Prompt that will be played when &quot;is Emergency?&quot; is set to true.</inlineHelpText>
    <label>Emergency Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Greeting_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Greeting_Prompt__c</fullName>
    <description>Optional greeting.</description>
    <inlineHelpText>Optional greeting prompt. Place some text if you want to play any message (Text To Speech) after the language selection in IVR.</inlineHelpText>
    <label>Greeting Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Immediate_Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Immediate_Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If you want to skip the IVR experience when a customer calls in and directly transfer the call to a queue or a phone number, then store the Call Transfer record in this field.</description>
    <inlineHelpText>Skip IVR experience and transfer call to</inlineHelpText>
    <label>Immediate Transfer To</label>
    <referenceTo>Transfer__c</referenceTo>
    <relationshipLabel>Call Experiences</relationshipLabel>
    <relationshipName>Call_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the record is inactive, then it will not be considered for customization of the IVR experience by Amazon Connect flows.</description>
    <inlineHelpText>Identifies if the record is used in IVR experience customization</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language for this Call Experience.</description>
    <inlineHelpText>Language for this Call Experience.</inlineHelpText>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>English (Singaporean)</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>Mandarin</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Bahasa Indonesia</fullName>
            </value>
            <value>
                <fullName>Thai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Language_Setup__c.field-meta.xml
<CustomField>
    <fullName>Language_Setup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Language Setup</label>
    <referenceTo>Language_Setup__c</referenceTo>
    <relationshipLabel>Call Experiences</relationshipLabel>
    <relationshipName>Call_Experiences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Menu_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Menu_Prompt__c</fullName>
    <description>Message played after greeting if immediate transfer is unchecked.</description>
    <inlineHelpText>Message played after greeting if immediate transfer is unchecked. (Text to Speech)</inlineHelpText>
    <label>Menu Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Menu_Prompt_ARN__c.field-meta.xml
<CustomField>
    <fullName>Menu_Prompt_ARN__c</fullName>
    <description>You can save a text message for Menu Prompt OR select the ARN of a prompt stored in Amazon Connect instance.</description>
    <inlineHelpText>Amazon Connect Prompt ARN if you want use Amazon Connect resources</inlineHelpText>
    <label>Menu Prompt ARN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Off_hours_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Off_hours_Prompt__c</fullName>
    <description>Prompt to speak if caller contact outside the business hours.</description>
    <inlineHelpText>Prompt to speak if caller contact outside the business hours.</inlineHelpText>
    <label>Off-hours Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Primary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone_Number__c</fullName>
    <formula>Language_Setup__r.Primary_Phone_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Experience__c/fields/Working_Hours__c.field-meta.xml
<CustomField>
    <fullName>Working_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the Business Hours for an IVR experience.</description>
    <inlineHelpText>Business Hours attached to a phone number experience</inlineHelpText>
    <label>Working Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipLabel>Call Experiences</relationshipLabel>
    <relationshipName>Call_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Language_Setup__c/Language_Setup__c.object-meta.xml
<CustomObject>
    <label>Language Setup</label>
    <nameField>
        <label>Language Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language_Setup__c/fields/Initial_Greeting_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Initial_Greeting_Prompt__c</fullName>
    <description>The initial Greeting played for the dialed number.</description>
    <inlineHelpText>The initial Greeting that will be played before the language selection menu.</inlineHelpText>
    <label>Initial Greeting Prompt</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Language_Setup__c/fields/Primary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone_Number__c</fullName>
    <description>TFN or DID for this Language Setup.</description>
    <inlineHelpText>TFN or DID for this Language Setup.</inlineHelpText>
    <label>Primary Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>The channel through which the work-item is received</description>
    <inlineHelpText>The channel through which the work-item is received</inlineHelpText>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LiveChatTranscript</fullName>
                <label>Chat</label>
            </value>
            <value>
                <fullName>MessagingSession</fullName>
                <label>Messaging</label>
            </value>
            <value>
                <fullName>VoiceCall</fullName>
                <label>Voice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Transfer_Destination__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Destination__c</fullName>
    <description>This field stores the ID of the Salesforce Queue (in case of Queue Transfer) OR the phone number (in case of External Transfer).</description>
    <inlineHelpText>18-digit Salesforce Voice Call Queue ID or the phone number to transfer to</inlineHelpText>
    <label>Transfer Destination</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Transfer_Label__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Label__c</fullName>
    <description>This field stores the Name of the Salesforce Queue (in case of Queue Transfer) OR the text identifier (in case of External Transfer); ex: Voice Call Queue OR Agent X DID number.</description>
    <inlineHelpText>User-friendly text to identify the transfer destination</inlineHelpText>
    <label>Transfer Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>You can transfer the call to a phone number OR to a queue.</description>
    <inlineHelpText>Type of transfer to perform</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queue Transfer</fullName>
            </value>
            <value>
                <fullName>External Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallExperienceTest.cls
/**
 * 	Class:				CallExperienceTest
 * 
 * 	Author:				Amit Gayal (NeuraFlash LLC)
 * 
 * 	Purpose:			It's the test class for CallExperience apex class.
 * 
 * 	Requirements:		IMSLB-30
 * 
 * 	Change History:		
 * 
 * 	Developer					Date				Description
 * ----------------------------------------------------------------------------------------
 */
@isTest
public class CallExperienceTest {
    @isTest 
    static void CallExperienceTest1 () {
        Transfer__c it = new Transfer__c();
        it.Transfer_Destination__c = '344';
        it.Transfer_Label__c = '544';
        it.Type__c ='Queue Transfer';
        it.Channel__c = 'LiveChatTranscript';
        insert it;
        
        Language_Setup__c ls = new Language_Setup__c();
        ls.Primary_Phone_Number__c = '+12345678901';
        ls.Initial_Greeting_Prompt__c = 'test data';
        ls.Name = 'Test Setup';
        insert ls;
        
        Call_Experience__c ce = new Call_Experience__c();
        ce.Language_Setup__c = ls.id;
        ce.Language__c = 'English';
        ce.DTMF_Option__c = '1';
        ce.Is_Active__c = true;
        ce.Emergency_Prompt__c = '222';
        ce.Greeting_Prompt__c = 'HELLO';
        ce.Menu_Prompt__c = '12345';
        ce.Menu_Prompt_ARN__c = '123456';
        ce.Off_hours_Prompt__c ='8-6';
        ce.Working_Hours__c = null;
        ce.Immediate_Transfer_To__c = it.Id;
        insert ce;
        
        CallExperience cl = new CallExperience(ce.id);
        Assert.isTrue(cl != null);
        
    }
    @isTest 
    static void CallExperienceTest2 () {
        Transfer__c it = new Transfer__c();
        it.Transfer_Destination__c = '344';
        it.Transfer_Label__c = '544';
        it.Type__c ='Queue Transfer';
        it.Channel__c = 'LiveChatTranscript';
        insert it;
        
        Language_Setup__c ls = new Language_Setup__c();
        ls.Primary_Phone_Number__c = '+12345678901';
        ls.Initial_Greeting_Prompt__c = 'test data';
        ls.Name = 'Test Setup';
        insert ls;
        
        Call_Experience__c ce = new Call_Experience__c();
        ce.Language_Setup__c = ls.id;
        ce.Language__c = 'English';
        ce.DTMF_Option__c = '1';
        ce.Is_Active__c = true;
        ce.Emergency_Prompt__c = '222';
        ce.Greeting_Prompt__c = 'HELLO';
        ce.Menu_Prompt__c = '12345';
        ce.Menu_Prompt_ARN__c = '123456';
        ce.Off_hours_Prompt__c ='8-6';
        ce.Working_Hours__c = null;
        ce.Immediate_Transfer_To__c = it.Id;
        insert ce;
        
        CallExperience cl = new CallExperience();
        Assert.isTrue(cl != null);
        
    }
}