force-app/main/default/objects/Call_Experience__c/Call_Experience__c.object-meta.xml
<CustomObject>
    <description>This object is used to manage the IVR greetings and queue routings for Service Cloud Voice with Amazon Connect</description>
    <label>Call Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Experience__c/fields/Contact_Flow_ARN__c.field-meta.xml
<CustomField>
    <fullName>Contact_Flow_ARN__c</fullName>
    <label>Contact Flow ARN</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/Menu_Option__c.object-meta.xml
<CustomObject>
    <label>Menu Option</label>
    <nameField>
        <label>Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menu Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Menu_Option__c/fields/Call_Experience__c.field-meta.xml
<CustomField>
    <fullName>Call_Experience__c</fullName>
    <description>Parent Call experience for this menu option</description>
    <inlineHelpText>Parent Call experience for this menu option</inlineHelpText>
    <label>Call Experience</label>
    <referenceTo>Call_Experience__c</referenceTo>
    <relationshipLabel>Menu Options</relationshipLabel>
    <relationshipName>Menu_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Contact_Flow_ARN__c.field-meta.xml
<CustomField>
    <fullName>Contact_Flow_ARN__c</fullName>
    <description>In case type of Menu Option is Amazon Connect Flow, this field stores the ARN for the contact flow.</description>
    <inlineHelpText>Contact flow ARN to which the current contact will be transferred</inlineHelpText>
    <label>Contact Flow ARN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Parent_Menu__c.field-meta.xml
<CustomField>
    <fullName>Parent_Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent menu option record.</description>
    <inlineHelpText>Parent Menu</inlineHelpText>
    <label>Parent Menu</label>
    <referenceTo>Menu_Option__c</referenceTo>
    <relationshipLabel>Sub-menu</relationshipLabel>
    <relationshipName>Sub_Menu</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Self_service_Message__c.field-meta.xml
<CustomField>
    <fullName>Self_service_Message__c</fullName>
    <description>In case menu option type is &apos;Self-service Message&apos;, then this field should store the text for the message.</description>
    <inlineHelpText>Self-service message text</inlineHelpText>
    <label>Self-service Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Sub_menu_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Sub_menu_Prompt__c</fullName>
    <description>If the type is &apos;Sub-menu&apos;, then provide the prompt for next menu selection.</description>
    <inlineHelpText>Menu prompt for next menu selection</inlineHelpText>
    <label>Sub-menu Prompt</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the menu option type is &apos;Call Transfer&apos;, then this field must store the Call Transfer record ID where the call will be transferred.</description>
    <inlineHelpText>Call Transfer record where you want to transfer the call</inlineHelpText>
    <label>Transfer To</label>
    <referenceTo>Transfer__c</referenceTo>
    <relationshipLabel>Menu Options</relationshipLabel>
    <relationshipName>Menu_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Stores the type of the menu option</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amazon Contact Flow</fullName>
            </value>
            <value>
                <fullName>Call Transfer</fullName>
            </value>
            <value>
                <fullName>Self-Service Message</fullName>
            </value>
            <value>
                <fullName>Sub-menu</fullName>
            </value>
            <value>
                <fullName>Menu Loop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Menu_Option__c/fields/User_Choice__c.field-meta.xml
<CustomField>
    <fullName>User_Choice__c</fullName>
    <description>This field differentiates between user inputs. The values can be 0-9, * and #. It only address the DTMF input.</description>
    <inlineHelpText>DTMF input received from user (0-9,*,#)</inlineHelpText>
    <label>User Choice</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>*</fullName>
            </value>
            <value>
                <fullName>#</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <label>Transfer</label>
    <nameField>
        <label>Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Callback_Confirmation_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Callback_Confirmation_Prompt__c</fullName>
    <description>Prompt to play when you want the user to confirm the callback number.</description>
    <inlineHelpText>Prompt to play when you want the user to confirm the callback number.</inlineHelpText>
    <label>Callback Confirmation Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Callback_End_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Callback_End_Prompt__c</fullName>
    <description>Prompt to play when ending the callback flow.</description>
    <inlineHelpText>Prompt to play when ending the callback flow.</inlineHelpText>
    <label>Callback End Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Callback_Menu_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Callback_Menu_Prompt__c</fullName>
    <description>Prompt to play while presenting menu options to the user.</description>
    <inlineHelpText>Prompt to play while presenting menu options to the user.</inlineHelpText>
    <label>Callback Menu Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Callback_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Callback_Prompt__c</fullName>
    <description>Message to present to the customer before offering the callback.</description>
    <inlineHelpText>Message to present to the customer before offering the callback.</inlineHelpText>
    <label>Callback Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Callback_Threshold_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Callback_Threshold_In_Minutes__c</fullName>
    <description>Minutes (post start of the Business Day OR before end of the Business Day) that will be considered as off-hours</description>
    <inlineHelpText>Minutes (post start of the Business Day OR before end of the Business Day) that will be considered as off-hours</inlineHelpText>
    <label>Callback Threshold (In Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Different_Callback_Number_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Different_Callback_Number_Prompt__c</fullName>
    <description>Prompt to play when the user wants to receive the callback at a separate number.</description>
    <inlineHelpText>Prompt to play when the user wants to receive the callback at a separate number.</inlineHelpText>
    <label>Different Callback Number Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Invalid_Number_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Invalid_Number_Prompt__c</fullName>
    <description>Prompt to play when user entered an invalid number.</description>
    <inlineHelpText>Prompt to play when user entered an invalid number.</inlineHelpText>
    <label>Invalid Number Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Offer_Callback__c.field-meta.xml
<CustomField>
    <fullName>Offer_Callback__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select if callback is available for this transfer</description>
    <inlineHelpText>Select if callback is available for this transfer</inlineHelpText>
    <label>Offer Callback?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Transfer_Destination__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Destination__c</fullName>
    <description>This field stores the ID of the Salesforce Queue (in case of Queue Transfer) OR the phone number (in case of External Transfer).</description>
    <inlineHelpText>18-digit Salesforce Voice Call Queue ID or the phone number to transfer to</inlineHelpText>
    <label>Transfer Destination</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Transfer_Label__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Label__c</fullName>
    <description>This field stores the Name of the Salesforce Queue (in case of Queue Transfer) OR the text identifier (in case of External Transfer); ex: Voice Call Queue OR Agent X DID number.</description>
    <inlineHelpText>User-friendly text to identify the transfer destination</inlineHelpText>
    <label>Transfer Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Transfer_Message__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Message__c</fullName>
    <defaultValue>&apos;Please wait while we are transferring you...&apos;</defaultValue>
    <description>If you want to play a message before performing the call transfer to a queue OR the external phone number.</description>
    <inlineHelpText>Text message played by Amazon Connect flow before transferring to Transfer Destination</inlineHelpText>
    <label>Transfer Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>You can transfer the call to a phone number OR to a queue.</description>
    <inlineHelpText>Type of transfer to perform</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queue Transfer</fullName>
            </value>
            <value>
                <fullName>External Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MenuOption.cls
/**
 * 	Class:				MenuOption
 * 
 * 	Author:				Amit Gayal (NeuraFlash LLC)
 * 
 * 	Purpose:			This class handles the creation and conversion for Menu Option object instances.
 * 
 * 	Requirements:		IMSLB-30
 * 
 * 	Change History:		
 * 
 * 	Developer					Date				Description
 * ----------------------------------------------------------------------------------------
 */
public class MenuOption {
    @AuraEnabled
    public String menuOptionId;
    @AuraEnabled
    public String callExperienceId;
    @AuraEnabled
    public String callExperienceName;
    @AuraEnabled
    public String contactFlowToInvoke;
    @AuraEnabled
    public String parentMenuOptionId;
    @AuraEnabled
    public String parentMenuOptionName;
    @AuraEnabled
    public String selfServiceMessage;
    @AuraEnabled
    public String subMenuPrompt;
    @AuraEnabled
    public String menuOptionType;
    @AuraEnabled
    public String menuName;
    @AuraEnabled
    public String menuUserChoice;

    //Attributes related to Transfer
    public String transferDestination {get; private set;}
    @AuraEnabled
    public String transferId {get; private set;}
    @AuraEnabled
    public String transferLabel {get; private set;}
    public String transferMessage {get; private set;}
    public String transferName {get; private set;}
    public String transferType {get; private set;}
    public Boolean transferOfferCallback {get; private set;}
    public String transferCallbackPrompt {get; private set;}
    public String transferCallbackMenuPrompt {get; private set;}
    public String transferDifferentCallbackNumberPrompt {get; private set;}
    public String transferInvalidNumberPrompt {get; private set;}
    public String transferCallbackConfirmationPrompt {get; private set;}
    public String transferCallbackEndPrompt {get; private set;}
    public Integer transferCallbackThreshold {get; private set;}

    
    public MenuOption(Menu_Option__c inputOption){
        this.setAttributes(inputOption);
    }
    
    public Menu_Option__c getMenuOptionObjectInstance(){
        Menu_Option__c outputOption = new Menu_Option__c();
        outputOption.Id = this.menuOptionId;
        outputOption.Call_Experience__c = this.callExperienceId;
        outputOption.Contact_Flow_ARN__c = this.contactFlowToInvoke;
        outputOption.Parent_Menu__c = this.parentMenuOptionId;
        outputOption.Name = this.menuName;
        outputOption.Self_service_Message__c = this.selfServiceMessage;
        outputOption.Type__c = this.menuOptionType;
        outputOption.User_Choice__c = this.menuUserChoice;
        outputOption.Sub_menu_Prompt__c = this.subMenuPrompt;
        outputOption.Transfer_To__c = this.transferId;
        return outputOption;
    }

    public MenuOption(String callExperienceId, String parentMenuId, String userSelection){
        List<Menu_Option__c> relatedCallExperiences = [SELECT Id, Name, Call_Experience__c, Call_Experience__r.Name, Parent_Menu__c, Parent_Menu__r.Name, Contact_Flow_ARN__c, Self_service_Message__c, Sub_menu_Prompt__c, Type__c, User_Choice__c, Transfer_To__c, Transfer_To__r.Transfer_Destination__c, Transfer_To__r.Transfer_Label__c, Transfer_To__r.Transfer_Message__c, Transfer_To__r.Name, Transfer_To__r.Type__c, Transfer_To__r.Offer_Callback__c, Transfer_To__r.Callback_Prompt__c, Transfer_To__r.Callback_Menu_Prompt__c, Transfer_To__r.Different_Callback_Number_Prompt__c, Transfer_To__r.Invalid_Number_Prompt__c, Transfer_To__r.Callback_Confirmation_Prompt__c, Transfer_To__r.Callback_End_Prompt__c, Transfer_To__r.Callback_Threshold_In_Minutes__c FROM Menu_Option__c WHERE Call_Experience__c =: callExperienceId AND Parent_Menu__c =: parentMenuId AND User_Choice__c =: userSelection];
        if(relatedCallExperiences != null && !relatedCallExperiences.isEmpty()){
            this.setAttributes(relatedCallExperiences[0]);
        }
    }
    
	@TestVisible
    private void setAttributes(Menu_Option__c inputMenuOption){
        this.menuOptionId = inputMenuOption.Id;
        this.callExperienceId = inputMenuOption.Call_Experience__c;
        this.callExperienceName = inputMenuOption.Call_Experience__r.Name;
        this.contactFlowToInvoke = inputMenuOption.Contact_Flow_ARN__c;
        this.parentMenuOptionId = inputMenuOption.Parent_Menu__c;
        this.parentMenuOptionName = inputMenuOption.Parent_Menu__r.Name;
        this.menuName = inputMenuOption.Name;
        this.selfServiceMessage = inputMenuOption.Self_service_Message__c;
        this.menuOptionType = inputMenuOption.Type__c;
        this.menuUserChoice = inputMenuOption.User_Choice__c;
        this.subMenuPrompt = inputMenuOption.Sub_menu_Prompt__c;

        this.transferDestination = inputMenuOption.Transfer_To__r.Transfer_Destination__c;
        this.transferId = inputMenuOption.Transfer_To__c;
        this.transferLabel = inputMenuOption.Transfer_To__r.Transfer_Label__c;
        this.transferMessage = inputMenuOption.Transfer_To__r.Transfer_Message__c;
        this.transferName = inputMenuOption.Transfer_To__r.Name;
        this.transferType = inputMenuOption.Transfer_To__r.Type__c;
        this.transferOfferCallback = inputMenuOption.Transfer_To__r.Offer_Callback__c;
        this.transferCallbackPrompt = inputMenuOption.Transfer_To__r.Callback_Prompt__c;
        this.transferCallbackMenuPrompt = inputMenuOption.Transfer_To__r.Callback_Menu_Prompt__c;
        this.transferDifferentCallbackNumberPrompt = inputMenuOption.Transfer_To__r.Different_Callback_Number_Prompt__c;
        this.transferInvalidNumberPrompt = inputMenuOption.Transfer_To__r.Invalid_Number_Prompt__c;
        this.transferCallbackConfirmationPrompt = inputMenuOption.Transfer_To__r.Callback_Confirmation_Prompt__c;
        this.transferCallbackEndPrompt = inputMenuOption.Transfer_To__r.Callback_End_Prompt__c;
        this.transferCallbackThreshold = (Integer) inputMenuOption.Transfer_To__r.Callback_Threshold_In_Minutes__c;
    }
}