force-app/main/default/objects/GuestArticleVote__c/GuestArticleVote__c.object-meta.xml
<CustomObject>
    <label>GuestArticleVote</label>
    <nameField>
        <displayFormat>KnowledgeFeedback-{0000}</displayFormat>
        <label>GuestArticleVote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GuestArticleVote</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GuestArticleVote__c/fields/GuestUserId__c.field-meta.xml
<CustomField>
    <fullName>GuestUserId__c</fullName>
    <label>GuestUserId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GuestArticleVote__c/fields/IsUpvoted__c.field-meta.xml
<CustomField>
    <fullName>IsUpvoted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upvoted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GuestArticleVote__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>GuestArticleVote</relationshipLabel>
    <relationshipName>GuestArticleVote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <label>Knowledge</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/GuestArticleVoteController.cls
public without sharing class GuestArticleVoteController {
    @AuraEnabled
    public static Boolean existsVoteResult(String articleVersionId, String guestUserId){
        
        Knowledge__kav knObj=  [select Id,UrlName from Knowledge__kav where urlname=:articleVersionId limit 1];
            
        Integer voteCount = [
            SELECT COUNT()
            FROM GuestArticleVote__c
            WHERE Knowledge__c = :knObj.id AND GuestUserId__c = :guestUserId
        ];
        system.debug('voteCount'+voteCount);
        return (voteCount > 0);
    }

    @AuraEnabled
    public static void vote(String articleVersionId, String guestUserId, Boolean isUpvoted){
        Knowledge__kav knObj=  [select Id,UrlName from Knowledge__kav where urlname=:articleVersionId limit 1];
		System.debug('Kav List---'+knObj);
        insert new GuestArticleVote__c(
            Knowledge__c  = knObj.Id,
            GuestUserId__c = guestUserId,
            IsUpvoted__c = isUpvoted
        );
    }
}