force-app/main/default/objects/Prospecting_Batch__c/Prospecting_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Prospecting Batch</label>
</CustomObject>

force-app/main/default/objects/Prospecting_Batch__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <inlineHelpText>The desired number of records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_End__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_End__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job ends.</inlineHelpText>
    <label>Last Batch End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_Start__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Start__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job starts.</inlineHelpText>
    <label>Last Batch Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Status__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job runs.</inlineHelpText>
    <label>Last Batch Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Count__c</fullName>
    <label>Last Run Count</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/User_Filter__c.field-meta.xml
<CustomField>
    <fullName>User_Filter__c</fullName>
    <inlineHelpText>This should be an exact WHERE clause segment for a query on the User object.  e.g.:
IsActive=true AND Role_Type__c LIKE &apos;Sales%&apos;</inlineHelpText>
    <label>User Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospecting_Entry__c/Prospecting_Entry__c.object-meta.xml
<CustomObject>
    <description>Allows for commercial BDEs to log their hours of prospecting each week.</description>
    <label>Prospecting Entry</label>
    <nameField>
        <label>Prospecting Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospecting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestProspectingEntryCreationBatch.cls
/* Commenting the entire code as part of Gitlab #24448 */
@isTest
public with sharing class TestProspectingEntryCreationBatch {
/*
	private static Prospecting_Batch__c setting;
	private static User[] users = new User[]{};
	private static String ident;

	static {
		ident = String.valueOf(System.currentTimeMillis()).substring(9,13);
		setting = new Prospecting_Batch__c(
			Batch_Size__c = 100,
			User_Filter__c = 'Email LIKE \'%'+ident+'%\''
		);
		insert setting;
		for(Integer i=0; i<5; i++){
			users.add(TestingUtils.createUser(ident+i,false));
		}
		insert users;
	}

	@isTest private static void testSchedulable(){
		Test.startTest();
		System.schedule('ProspectingEntryCreationBatch','0 0 13 * * ?', new ProspectingEntryCreationBatch());
		Test.stopTest();
	}

	@isTest private static void testBatchable(){
		Test.startTest();
		Database.executeBatch(new ProspectingEntryCreationBatch(), Integer.valueOf(setting.Batch_Size__c));
		Test.stopTest();
		system.assertEquals(5,[SELECT Id FROM Prospecting_Entry__c].size());
		setting = [SELECT Id, Last_Batch_Start__c, Last_Batch_End__c, Last_Batch_Status__c, Last_Run_Count__c FROM Prospecting_Batch__c ORDER BY LastModifiedDate DESC LIMIT 1];
		system.assertNotEquals(null,setting.Last_Batch_Start__c);
		system.assertNotEquals(null,setting.Last_Batch_End__c);
		system.assertEquals('Complete',setting.Last_Batch_Status__c);
		system.assertEquals(5, setting.Last_Run_Count__c);
	}

	@isTest private static void testBatchable_WhileAlreadyRunning(){
		setting.Last_Batch_Status__c = 'Started';
		update setting;
		try{
			Test.startTest();
			Database.executeBatch(new ProspectingEntryCreationBatch(), Integer.valueOf(setting.Batch_Size__c));
			Test.stopTest();
			system.assert(false,'should have thrown an exception');
		}catch(Exception e){
			system.debug(e);
			system.assert(e.getMessage().contains('already be in progress'));
		}
	}
*/
}