force-app/main/default/objects/Prospecting_Batch__c/Prospecting_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Prospecting Batch</label>
</CustomObject>

force-app/main/default/objects/Prospecting_Batch__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <inlineHelpText>The desired number of records per batch.</inlineHelpText>
    <label>Batch Size</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_End__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_End__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job ends.</inlineHelpText>
    <label>Last Batch End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_Start__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Start__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job starts.</inlineHelpText>
    <label>Last Batch Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Batch_Status__c</fullName>
    <inlineHelpText>Do not edit.  This will be updated every time the batch job runs.</inlineHelpText>
    <label>Last Batch Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/Last_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Count__c</fullName>
    <label>Last Run Count</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prospecting_Batch__c/fields/User_Filter__c.field-meta.xml
<CustomField>
    <fullName>User_Filter__c</fullName>
    <inlineHelpText>This should be an exact WHERE clause segment for a query on the User object.  e.g.:
IsActive=true AND Role_Type__c LIKE &apos;Sales%&apos;</inlineHelpText>
    <label>User Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProspectingEntryCreationBatch.cls
/* Commenting the entire code as part of Gitlab #24448 */
global with sharing class ProspectingEntryCreationBatch{
    public ProspectingEntryCreationBatch(){
        
    }
}
/*global with sharing class ProspectingEntryCreationBatch implements Schedulable, Database.Stateful, Database.Batchable<sObject> {
	
	String query;

	global class BatchException extends Exception {}

	global Prospecting_Batch__c settings;
	global Integer count;
	global Date nextMonday;
	
	global ProspectingEntryCreationBatch(){
		settings = [SELECT 
						Id, 
						Batch_Size__c,
						Last_Batch_End__c,
						Last_Batch_Start__c,
						Last_Batch_Status__c,
						Last_Run_Count__c,
						User_Filter__c
					FROM Prospecting_Batch__c 
					LIMIT 1];
		Date d = Date.today();
		Date epoch = Date.valueOf('1900-01-07');
		while(Math.mod(epoch.daysBetween(d), 7) != 1){
			d+=1;
		}
		nextMonday = d;
		count = 0;
	}

	global void execute(SchedulableContext SC){
		Database.executeBatch(new ProspectingEntryCreationBatch(), Integer.valueOf(settings.Batch_Size__c));
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		if(settings.Last_Batch_Status__c=='Started' || settings.Last_Batch_Status__c=='In Progress'){
			throw new BatchException('This batch appears to already be in progress.  If you believe this is an error, update the Prospecting Batch custom setting.');
		}
		query = 'SELECT Id, Name FROM User';
		if(settings.User_Filter__c != null){
			query += ' WHERE '+settings.User_Filter__c;
		}
		settings.Last_Batch_Start__c = System.now();
		settings.Last_Batch_Status__c = 'Started';
		update settings;
		system.debug(query);
		system.debug(settings);
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<User> scope) {
   		system.debug(scope);
   		if(settings.Last_Batch_Status__c=='Started'){
   			settings.Last_Batch_Status__c = 'In Progress';
   			update settings;
   		}
   		count += ProspectingEntryService.batchCreateWeeklyEntryRecords(nextMonday, scope);
	}
	
	global void finish(Database.BatchableContext BC) {
		settings.Last_Batch_End__c = System.now();
		settings.Last_Batch_Status__c = 'Complete';
		settings.Last_Run_Count__c = count;
		update settings;
	}

}*/