force-app/main/default/objects/Lead/fields/batch_Email_Formula__c.field-meta.xml
<CustomField>
    <fullName>batch_Email_Formula__c</fullName>
    <formula>IF( ISNULL(StageComparisonDate__c),null, StageComparisonDate__c + 12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>batch Email Formula</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/batch_field_check__c.field-meta.xml
<CustomField>
    <fullName>batch_field_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>delete_batch field check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/batch_Field_Update__c.field-meta.xml
<CustomField>
    <fullName>batch_Field_Update__c</fullName>
    <formula>IF(  ISNULL(StageComparisonDate__c ), Null, StageComparisonDate__c +15)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>batch Field Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IM_Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>IM_Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0-Suspect</fullName>
                <default>true</default>
                <label>0-Suspect</label>
            </value>
            <value>
                <fullName>1-Inquiry</fullName>
            </value>
            <value>
                <fullName>2-Marketing Qual</fullName>
            </value>
            <value>
                <fullName>3-Sales Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Most_Recent_Sales_Activity__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Sales_Activity__c</fullName>
    <label>Most Recent Sales Activity</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Send_Email_Alert__c.field-meta.xml
<CustomField>
    <fullName>Send_Email_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Email Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/StageComparisonDate__c.field-meta.xml
<CustomField>
    <fullName>StageComparisonDate__c</fullName>
    <description>This field is to store the higher date from IM_Stage_3_Entered_Date__c and Most_Recent_Sales_Activity__c</description>
    <label>StageComparisonDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_IM_NotificationAndFieldUpdateBatch.cls
@isTest(SeeAllData=true)
private class Test_IM_NotificationAndFieldUpdateBatch{
    static testMethod void testIM_NotificationAndFieldUpdateBatch()
    {
       String usrId = UserInfo.getUserId();
        test.startTest();
       
          Lead lead= new Lead();
           lead.Email='valid@ironmountain.com';
           lead.OwnerId=usrId ;
           lead.LastName='Testing';
           lead.Company='Testing Company';
           lead.Status='New';
           lead.IM_Lead_Stage__c = '3-Sales Accepted';
           lead.IM_Stage_3_Entered_Date__c= System.today()-12;
           lead.Send_Email_Alert__c=false;
           lead.StageComparisonDate__c=System.today()-12;
           lead.Send_Email_Alert__c= false;
           lead.IsConverted = false;
           insert lead;
           
           IM_NotificationAndFieldUpdateBatch batchemail= new IM_NotificationAndFieldUpdateBatch();
           batchemail.queryStr = 'SELECT Id , '+
                      'Owner.Email , '+
                      'IM_Lead_Stage__c , '+
                      'IM_Stage_3_Entered_Date__c, '+
                      'Most_Recent_Sales_Activity__c, '+
                      'StageComparisonDate__c, '+
                      'batch_Email_Formula__c, '+
                      'Batch_Field_Update__c, '+
                      'Send_Email_Alert__c, '+
                      'batch_field_check__c '+
                      'FROM Lead '+ 
                      'WHERE StageComparisonDate__c != null '+
                      'AND Id=\''+lead.Id+'\'';
           System.debug('batchemail.queryStr=='+batchemail.queryStr); 
           Database.executeBatch(batchemail);
           
           test.stopTest();  
    }
    
    static testMethod void testIM_NotificationAndFieldUpdateBatch1()
    {
       String usrId = UserInfo.getUserId();
        test.startTest();
       
          Lead lead= new Lead();
           lead.Email='valid@ironmountain.com';
           lead.OwnerId=usrId ;
           lead.LastName='Testing';
           lead.Company='Testing Company';
           lead.Status='New';
           lead.IM_Lead_Stage__c = '3-Sales Accepted';
           lead.IM_Stage_3_Entered_Date__c= System.today()-15;
           lead.Send_Email_Alert__c=false;
           lead.StageComparisonDate__c=System.today()-15;
           lead.Send_Email_Alert__c= false;
           lead.IsConverted = false;
           insert lead;
           
           IM_NotificationAndFieldUpdateBatch batchemail= new IM_NotificationAndFieldUpdateBatch();
           batchemail.queryStr = 'SELECT Id , '+
                      'Owner.Email , '+
                      'IM_Lead_Stage__c , '+
                      'IM_Stage_3_Entered_Date__c, '+
                      'Most_Recent_Sales_Activity__c, '+
                      'StageComparisonDate__c, '+
                      'batch_Email_Formula__c, '+
                      'Batch_Field_Update__c, '+
                      'Send_Email_Alert__c, '+
                      'batch_field_check__c '+
                      'FROM Lead '+ 
                      'WHERE StageComparisonDate__c != null '+
                      'AND Id=\''+lead.Id+'\'';
           System.debug('batchemail.queryStr=='+batchemail.queryStr); 
           Database.executeBatch(batchemail);
           
           test.stopTest();  
    }  
    
     static TestMethod void doTest2(){
       Schedule_NotificationAndFieldUpdateBatch b1=new Schedule_NotificationAndFieldUpdateBatch();
       //Test.starttest();   
       b1.execute(null);
       //Test.stoptest();
    }
    
}