force-app/main/default/objects/Opportunity/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Since the Opportunity is now locked for Sales Profiles at Stages 6 and 7, sales still needs to update field “Up-Sell Detail” in stages 6 and 7 to log billing details. This allows them to communicate to Commissions via this field. “Up-sell Detail” Chatter Action allows bypassing the validation and is able to only update this field.[Case# 02497355].</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_10__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_10__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V13. Customer is openly negotiating terms and conditions.</inlineHelpText>
    <label>Customer Verifier 14</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_11__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_11__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V14. Customer accepted and signed the final contract.</inlineHelpText>
    <label>Customer Verifier 15</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_12__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_12__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Verifier 12</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_13__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_13__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V11. Customer has requested ref. and/or scheduled a tour.</inlineHelpText>
    <label>Customer Verifier 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_14__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_14__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V4. Assessed internal and external competitive options.</inlineHelpText>
    <label>Customer Verifier 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_15__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_15__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V8. Customer is working jointly on approach for solution.</inlineHelpText>
    <label>Customer Verifier 8</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_16__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_16__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V9. Identified &amp; satisfied all forms of customer resistance</inlineHelpText>
    <label>Customer Verifier 9</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_2__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_2__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V1. Compelling event- ID of  a significant  and relevant need.</inlineHelpText>
    <label>Customer Verifier 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_3__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_3__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V6. Customer accepts approach for direction.</inlineHelpText>
    <label>Customer Verifier 6</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_4__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_4__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V2.  Jointly discovered customer goals/problems/needs.</inlineHelpText>
    <label>Customer Verifier 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_5__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_5__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V3.  Decision Process: ID stakeholders/criteria/steps.</inlineHelpText>
    <label>Customer Verifier 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_6__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_6__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V5. Budget: Customer has access to funds.</inlineHelpText>
    <label>Customer Verifier 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_7__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_7__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V10. Customer accepted proposed solution meets their need.</inlineHelpText>
    <label>Customer Verifier 10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_8__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_8__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V7. 3x3: All Stakeholders Goals Problems,Needs are known.</inlineHelpText>
    <label>Customer Verifier 7</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Verifier_9__c.field-meta.xml
<CustomField>
    <fullName>Customer_Verifier_9__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>V12. Customer has given verbal to move forward.</inlineHelpText>
    <label>Customer Verifier 13</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RIM360_1__c.field-meta.xml
<CustomField>
    <fullName>RIM360_1__c</fullName>
    <inlineHelpText>I used RIM360 to uncover sales opportunity</inlineHelpText>
    <label>RIM360:Used to find Opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RIM360_2__c.field-meta.xml
<CustomField>
    <fullName>RIM360_2__c</fullName>
    <inlineHelpText>I delivered a RIM360 Roadmap with a financial business case</inlineHelpText>
    <label>RIM360:Delivered Roadmap &amp; Business Case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RIM360__c/RIM360__c.object-meta.xml
<CustomObject>
    <description>Custom object to track RIM360 engagements related to opportunities.</description>
    <label>RIM360 Tracker</label>
    <nameField>
        <label>RIM360 Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIM360 Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ActivityService.cls
public without sharing class ActivityService {

    private static Map<Id, Opportunity> opps;
    private static Map<Id, Opportunity> oppsToUpdate;
    
    public static void rollUp(sObject source) {
        Opportunity opp = opps.get((Id) source.get('WhatId'));
        if(opp==null) return;
        String customerVerifiers = (String) source.get('Customer_Verifiers__c');
        if(customerVerifiers==null) return;
        // Comment out #16914
        /*Set<String> verifiers = new Set<String>();
        for(String s: customerVerifiers.split(';')){
            verifiers.add(s.trim());
        }
      
        Boolean changed = false;
        if(verifiers.contains('1')){
            if(opp.Customer_Verifier_2__c != true) changed = true;
            opp.Customer_Verifier_2__c = true;
        }
        if(verifiers.contains('2')){
            if(opp.Customer_Verifier_4__c != true) changed = true;
            opp.Customer_Verifier_4__c = true;
        }
        if(verifiers.contains('3')){
            if(opp.Customer_Verifier_5__c != true) changed = true;
            opp.Customer_Verifier_5__c = true;
        }
        if(verifiers.contains('4')){
            if(opp.Customer_Verifier_14__c != true) changed = true;
            opp.Customer_Verifier_14__c = true;
        }
        if(verifiers.contains('5')){
            if(opp.Customer_Verifier_6__c != true) changed = true;
            opp.Customer_Verifier_6__c = true;
        }
        if(verifiers.contains('6')){
            if(opp.Customer_Verifier_3__c != true) changed = true;
            opp.Customer_Verifier_3__c = true;
        }
        if(verifiers.contains('7')){
            if(opp.Customer_Verifier_8__c != true) changed = true;
            opp.Customer_Verifier_8__c = true;
        }
        if(verifiers.contains('8')){
            if(opp.Customer_Verifier_15__c != true) changed = true;
            opp.Customer_Verifier_15__c = true;
        }
        if(verifiers.contains('9')){
            if(opp.Customer_Verifier_16__c != true) changed = true;
            opp.Customer_Verifier_16__c = true;
        }
        if(verifiers.contains('10')){
            if(opp.Customer_Verifier_7__c != true) changed = true;
            opp.Customer_Verifier_7__c = true;
        }
        if(verifiers.contains('11')){
            if(opp.Customer_Verifier_13__c != true) changed = true;
            opp.Customer_Verifier_13__c = true;
        }
        if(verifiers.contains('12')){
            if(opp.Customer_Verifier_12__c != true) changed = true;
            opp.Customer_Verifier_12__c = true;
        }
        if(verifiers.contains('13')){
            if(opp.Customer_Verifier_9__c != true) changed = true;
            opp.Customer_Verifier_9__c = true;
        }
        if(verifiers.contains('14')){
            if(opp.Customer_Verifier_10__c != true) changed = true;
            opp.Customer_Verifier_10__c = true;
        }
        if(verifiers.contains('15')){
            if(opp.Customer_Verifier_11__c != true) changed = true;
            opp.Customer_Verifier_11__c = true;
        }        
        if(changed == true){
            opp.Bypass_Validation__c = true;
            oppsToUpdate.put(opp.Id, opp);
        }*/
    }

     public static void rollUpRimTracker(sObject source) {
        Opportunity opp = opps.get((Id) source.get('WhatId'));
        if(opp==null) return;
        String rimtracker = (String) source.get('RIM360__c');
        if(rimtracker==null) return;
        // Comment out #16914
        /*Set<String> trackers = new Set<String>();
        
        for(String s: rimtracker.split(';')){
            trackers.add(s.trim());
        }
        Boolean changed = false;        
        if(trackers.contains('1')){
           if(opp.RIM360_1__c == null || opp.RIM360_1__c == 'No') changed = true;
            opp.RIM360_1__c = 'Yes';
        }
        if(trackers.contains('2')){
           if(opp.RIM360_2__c == null || opp.RIM360_2__c == 'No') changed = true;
            opp.RIM360_2__c = 'Yes';
        }
         if(trackers.contains('3')){
           if(opp.RIM360_1__c == null || opp.RIM360_1__c == 'Yes') changed = true;
            opp.RIM360_1__c = 'No';
        }
        if(changed == true){
            opp.Bypass_Validation__c = true;
            oppsToUpdate.put(opp.Id, opp);
        }*/
    }  
    public static void rollUp(List<sObject> sourceList) {
        Set<Id> whatIds = new Set<Id>();
        for(sObject o: sourceList){
            whatIds.add((Id) o.get('WhatId'));
        }
        opps = new Map<Id, Opportunity>([
            SELECT 
                Id, 
                Customer_Verifier_2__c,
                Customer_Verifier_3__c,
                Customer_Verifier_4__c,
                Customer_Verifier_5__c,
                Customer_Verifier_6__c,
                Customer_Verifier_7__c,
                Customer_Verifier_8__c,
                Customer_Verifier_9__c,
                Customer_Verifier_10__c,
                Customer_Verifier_11__c,
                Customer_Verifier_12__c,
                Customer_Verifier_13__c,
                Customer_Verifier_14__c,
                Customer_Verifier_15__c,
                Customer_Verifier_16__c,
                RIM360_1__c
               //#16915 RIM360_2__c
            FROM Opportunity
            WHERE Id IN :whatIds
        ]);
        oppsToUpdate = new Map<Id, Opportunity>();
        for(sObject o: sourceList){
            rollUp(o);
            rollUpRimTracker(o);
        }
        update oppsToUpdate.values();
    }

    public static void getContactLevel(List<sObject> sourceList){
        Set<Id> whoIds = new Set<Id>();
        for(sObject o: sourceList){
            whoIds.add((Id) o.get('WhoId'));
        }
        Map<Id, Contact> contacts = new Map<Id, Contact>([
            SELECT
                Id,
                IM_Job_Level__c
            FROM Contact
            WHERE Id IN :whoIds

        ]);
        for(sObject o: sourceList){
            Contact c = contacts.get((Id) o.get('WhoId'));
            if(c==null) continue;
            o.put('Contact_Level__c', c.IM_Job_Level__c);
        }
    }

}