force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Original_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>IM_Original_Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_OppShareInsertBatchClass.cls
/*Author           : Abhay Gupta
  Company          : Patni Computer Systems
  Created Date     : 27-Apr-2011
  Description      : Apex test class to test the coverage of apex batch class Oppshare_insert_batch_class by setting up test data. 

  Author           : Ketan Benegal
  Company          : CloudFountain Inc.
  Modified Date    : 20-Apr-2012
  Case No.         : 00357920
  Description      : Modified to include multiple users and test the security with custom settings value. 
  
  CHANGE LOG       :
  [[Version; Date; Author; Project/Case; Description]]
  v1.0; 2013/05/07; Srinivasa Rao/Randstad; Reviewing code coverage for all components/Case#01367998; Initial release.
*/

@isTest (SeeAllData=true) 
private class Test_OppShareInsertBatchClass
{
    static testMethod void runTest() {
        try{            
            //Setting test data
            List<OpportunityShare> lstOppShare = new List<OpportunityShare>();
            //get user
            List<User> userList = [Select Id from User where IsActive = True limit 5];            
            User u = userList[0];
            
            //create Account
           // Account acc1 = new Account(Name='Testaccount2', BillingPostalCode='11223', BillingCountry='United States',IM_Digital_Sales_Executive__c = u.Id, IM_Enterprise_Account_Executive__c=userList[3].Id); 
			Account acc1 = new Account(Name='Testaccount2', BillingPostalCode='11223', BillingCountry='United States'); 
            insert acc1;
            string accountid = '\''+acc1.id+'\'';
            
            //create Opportunity
            Opportunity opp = new Opportunity(Name = 'testopp',AccountId = acc1.Id,CloseDate = date.today(),IM_Booked_Date__c = date.today(),
                                              IM_Original_Lead_Owner__c = u.Id,StageName = '0 - Pre-Qualification',Type = 'New Deal');
            insert opp;        
            string opprid = '\''+opp.id+'\''; 
            
            //Testing the coverage for execute section.
            Test.startTest();
            
            //get PricebookEntry
            PricebookEntry pb = [Select Id,CurrencyIsoCode from PricebookEntry where Name = 'eLearning' AND CurrencyIsoCode = 'USD' AND isActive=true limit 1]; 
            OpportunityLineItem  opp_product = new OpportunityLineItem (OpportunityId = opp.Id,PricebookEntryId = pb.Id,Quantity = 2,TotalPrice = 2);
            insert opp_product;
              
            //create another Opportunity
            Opportunity opp2 = new Opportunity(Name = 'testopp2',AccountId = acc1.Id,CloseDate = date.today(),IM_Booked_Date__c = date.today(),
                                               IM_Original_Lead_Owner__c = u.Id ,StageName = '0 - Pre-Qualification',Type = 'New Deal');
            insert opp2; 
            Id opp2Id = opp2.Id;       
            string opprid2 = '\''+opp2.id+'\''; 
            OpportunityLineItem  opp_product2 = new OpportunityLineItem (OpportunityId = opp2.Id,PricebookEntryId = pb.Id,Quantity = 2,TotalPrice = 2);
            insert opp_product2;
            
                        
            //calling batch class         
            Oppshare_insert_batch_class job = new Oppshare_insert_batch_class();    
            
            //Passing '20' records to start method, if it was called by test method.
            Id jobId = Database.executeBatch(job,5);
            
               
            
            //Checking the batch job is completed ot not with assert statements and setting Accesslevel on Opportunity
        /*    AsyncApexJob jobActual = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, CreatedBy.Firstname
                                      from AsyncApexJob where Id = :jobId];
            System.assertEquals(jobActual.TotalJobItems, 1);
            System.assertEquals(jobActual.JobItemsProcessed, 1);
            System.assertEquals(jobActual.NumberOfErrors, 0);
            System.assertEquals(jobActual.Status, 'Completed');
            
                       
            if(jobActual.Status == 'Completed'){
                lstOppShare = [select OpportunityAccessLevel, OpportunityId, Id, RowCause, UserOrGroupId FROM OpportunityShare where OpportunityId = :opp2Id and RowCause in ('Team', 'Manual') ];
                for(OpportunityShare opShare : lstOppShare){
                  if((opShare.UserOrGroupId == userList[2].Id) || (opShare.UserOrGroupId == userList[3].Id) || (opShare.UserOrGroupId == userList[4].Id)){
                    System.assertEquals(opShare.OpportunityAccessLevel, 'Edit');
                  }
                }
            }
        */
        Test.stopTest();
        
        }catch(System.Exception e){
            System.debug('Error encountered in Oppshare creation' + e.getmessage());  
        }
          
    }
}