force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Reason_Lost__c.field-meta.xml
<CustomField>
    <fullName>IM_Reason_Lost__c</fullName>
    <label>Reason Lost</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Autopay Refused</fullName>
            </value>
            <value>
                <fullName>Benchmarking</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Competitors Solution</fullName>
            </value>
            <value>
                <fullName>Conflict</fullName>
            </value>
            <value>
                <fullName>Contractual Terms</fullName>
            </value>
            <value>
                <fullName>Decision Location</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>In House</fullName>
            </value>
            <value>
                <fullName>Installed Base</fullName>
            </value>
            <value>
                <fullName>No Clear Business Need</fullName>
            </value>
            <value>
                <fullName>Non Conversion</fullName>
            </value>
            <value>
                <fullName>No Suitable Solution</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Relationship Weakness</fullName>
            </value>
            <value>
                <fullName>Service Perception</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>Technical Fit</fullName>
            </value>
            <value>
                <fullName>Track Record</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
            <value>
                <fullName>Booking Policy Violation</fullName>
            </value>
            <value>
                <fullName>Sales Ops Hygiene</fullName>
            </value>
            <value>
                <fullName>Cancelled after Signing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NCSP_Status__c.field-meta.xml
<CustomField>
    <fullName>NCSP_Status__c</fullName>
    <description>tracks the progress of the NCSP case related to this opportunity. The value is updated by an APEX trigger on the Case.</description>
    <label>NCSP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent to NCSP</fullName>
                <color>#0B6FCE</color>
                <label>Sent to NCSP</label>
            </value>
            <value>
                <fullName>Contract Approved</fullName>
                <color>#E27001</color>
                <label>Contract Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#A845DC</color>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Service Scheduled</fullName>
                <color>#419249</color>
                <label>Service Scheduled</label>
            </value>
            <value>
                <fullName>Service Completed</fullName>
                <color>#CC9933</color>
                <label>Service Completed</label>
            </value>
            <value>
                <fullName>Custom Setup</fullName>
                <color>#33CCFF</color>
                <label>Custom Setup</label>
            </value>
            <value>
                <fullName>Local Market Setup</fullName>
            </value>
            <value>
                <fullName>Special Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Completed_Entered_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Completed_Entered_Date__c</fullName>
    <description>Aligned with the Service Completion Date field on the case. The value is updated by an APEX trigger on the Case.</description>
    <label>Service Completed Entered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_CallingUpdateOppRecords.cls
@isTest(seeAllData=true)
public class Test_CallingUpdateOppRecords {
    static testmethod void test() {
        List<Id> lstOppIdThatChangeStage=new List<Id>();
        List<String> NCSP_StatusList=new List<String>();
        List<String> StageNamelist=new List<String>();
        List<Date> Service_Completed_Entered_DateList=new List<Date>();
        List<String> IM_Reason_LostListl=new List<String>();
        List<Opportunity> optylist = new List<Opportunity>();
        //CloseDate formerly First Bill Date, Booked Date is now First Bill Date.
        Account A = new Account(name='Account4TestMethod'+system.now(), BillingCountry='United States');
        insert A;
        Opportunity opty = new Opportunity(Name='Test',IM_Booked_Date__c=System.today()+10,CloseDate = Date.Today(),NCSP_Status__c='Custom Setup',StageName='1 - Qualification',Service_Completed_Entered_Date__c=System.today(),IM_Reason_Lost__c='Decision Location', AccountId = A.Id);
        optylist.add(opty);
        insert optylist;
        for(Opportunity op: optylist){
            lstOppIdThatChangeStage.add(op.Id);
            NCSP_StatusList.add(op.NCSP_Status__c);
            StageNamelist.add(op.StageName);
            Service_Completed_Entered_DateList.add(op.Service_Completed_Entered_Date__c);
            IM_Reason_LostListl.add(op.IM_Reason_Lost__c);
            
        }
            
        CallingUpdateOppRecords cur = new CallingUpdateOppRecords();
        CallingUpdateOppRecords.doUpdate(lstOppIdThatChangeStage,NCSP_StatusList,StageNamelist,Service_Completed_Entered_DateList,IM_Reason_LostListl);
       
    }
}