force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>IM_Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accelerated Information Consolidation</fullName>
            </value>
            <value>
                <fullName>Backup Care</fullName>
            </value>
            <value>
                <fullName>Cubic Ft</fullName>
            </value>
            <value>
                <fullName>Customer Billable Audits</fullName>
            </value>
            <value>
                <fullName>Data Restoration</fullName>
            </value>
            <value>
                <fullName>DC - Cross Connect</fullName>
            </value>
            <value>
                <fullName>DC - Data Domain Services</fullName>
            </value>
            <value>
                <fullName>DC - Helping Hands</fullName>
            </value>
            <value>
                <fullName>DC - Installation / Implementation</fullName>
            </value>
            <value>
                <fullName>DC - Managed Internet</fullName>
            </value>
            <value>
                <fullName>DC - Network Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Other MRC Service</fullName>
            </value>
            <value>
                <fullName>DC - Rent</fullName>
            </value>
            <value>
                <fullName>DC - Retail Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Special Projects</fullName>
            </value>
            <value>
                <fullName>Destruction</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>EV Up-Sell  - Gigs</fullName>
            </value>
            <value>
                <fullName>EV Up Sell - Seats</fullName>
            </value>
            <value>
                <fullName>IMAGES</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – Carton Level</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – File Level</fullName>
            </value>
            <value>
                <fullName>Inventory Pack/Purge/Shift</fullName>
            </value>
            <value>
                <fullName>Inventory Relocation</fullName>
            </value>
            <value>
                <fullName>Labour Hours</fullName>
            </value>
            <value>
                <fullName>Library Move</fullName>
            </value>
            <value>
                <fullName>Linear Ft</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Shred - Add Bins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Detail__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Detail__c</fullName>
    <inlineHelpText>Enter a detailed description of the Department, Division, or Location that the deal was sold to.  There is no need to put a Contact Name, Company Name, or Revenue Type as this has already been provided in the other fields on the Opportunity.</inlineHelpText>
    <label>Up-Sell Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Quantity__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Quantity__c</fullName>
    <inlineHelpText>Please enter a Quantity.  
Examples:  for cubic ft and linear ft, enter the total amount involved in the up-sell.  For up-sells on rotations (Wkly-Daily, Mthly-Wkly, etc), enter 1.</inlineHelpText>
    <label>Up-Sell Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Sold_To__c</fullName>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Up-Sell Oracle Account ID#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVStatus__c/SVStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for checking the SVStatus field values</description>
    <label>SVStatus</label>
</CustomObject>

force-app/main/default/objects/SVStatus__c/fields/OpptType__c.field-meta.xml
<CustomField>
    <fullName>OpptType__c</fullName>
    <label>OpptType</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVStatus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&apos;6 - Setup&apos;</defaultValue>
    <label>Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Activation_Settings__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SVStatusTrigger_Test.cls
@isTest(seeAllData=false)
private class SVStatusTrigger_Test {
    static testMethod void testInsertOpportunity() {
        
        //insert Account
        Account acc = TestingUtils.createAccounts(1, true)[0];
        
        //insert SV custom setting
        SVStatus__c sv = new SVStatus__c();
            sv.name = 'SVStatusPassed';
            sv.Amount__c = 24000;
            sv.Stage__c = '6 - Setup';
            sv.OpptType__c = 'Up-Sell/Lift,New Deal';
            insert sv;
        
        //insert Trigger Activation Setting
        Trigger_Activation_Settings__c TAS = new Trigger_Activation_Settings__c();
            TAS.Name = 'OpportunitySVStatus';
            TAS.Object__c ='Opportunity';
            TAS.Trigger__c = 'OpportunitySVStatus';
            TAS.Value__c = 'TRUE';
            insert TAS;
        
        //Get record type
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> OppRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtId = OppRecordTypeInfo .get('Standard Opportunity').getRecordTypeId();
        //insert product
        Product2 pdt = TestingUtils.createProduct('TestPdt',true);
        //insert pricebook
        //Pricebook2 priceB = TestingUtils.createPriceBook('TestPriceB',true);
        Id pricebookId = Test.getStandardPricebookId();
        //insert pricebookEntry
        PriceBookEntry pricebEntr = TestingUtils.createPriceBookEntry(pdt.id, pricebookId, true);
        
        //insert Opportunity
        opportunity Opp = TestingUtils.createOpportunity('opp', acc.id, false);
            Opp.Type = 'New Deal';
            Opp.Amount = 22;
            Opp.recordtypeid = rtId;
            Opp.IM_Booked_Date__c = system.today();
            Opp.CloseDate = system.today();  
            Opp.IM_Up_Sell_Quantity__c = 2;
            Opp.IM_Up_Sell_Sold_To__c = '245';
            Opp.IM_Up_Sell_Detail__c = '268';
            Opp.IM_Up_Sell_Detail__c = 'test';
            Opp.IM_Unit_of_Measure__c = 'Backup Care';
        insert Opp;
        //insert Opportunity Line Item
        OpportunityLineItem olItem = TestingUtils.createOLI(pricebEntr.id, Opp.id, true);
        //Update Opportunity            
        Opp.StageName ='6 - Setup';
        update Opp;
    }
}