force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>IM_Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accelerated Information Consolidation</fullName>
            </value>
            <value>
                <fullName>Backup Care</fullName>
            </value>
            <value>
                <fullName>Cubic Ft</fullName>
            </value>
            <value>
                <fullName>Customer Billable Audits</fullName>
            </value>
            <value>
                <fullName>Data Restoration</fullName>
            </value>
            <value>
                <fullName>DC - Cross Connect</fullName>
            </value>
            <value>
                <fullName>DC - Data Domain Services</fullName>
            </value>
            <value>
                <fullName>DC - Helping Hands</fullName>
            </value>
            <value>
                <fullName>DC - Installation / Implementation</fullName>
            </value>
            <value>
                <fullName>DC - Managed Internet</fullName>
            </value>
            <value>
                <fullName>DC - Network Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Other MRC Service</fullName>
            </value>
            <value>
                <fullName>DC - Rent</fullName>
            </value>
            <value>
                <fullName>DC - Retail Circuit</fullName>
            </value>
            <value>
                <fullName>DC - Special Projects</fullName>
            </value>
            <value>
                <fullName>Destruction</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Each</fullName>
            </value>
            <value>
                <fullName>EV Up-Sell  - Gigs</fullName>
            </value>
            <value>
                <fullName>EV Up Sell - Seats</fullName>
            </value>
            <value>
                <fullName>IMAGES</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – Carton Level</fullName>
            </value>
            <value>
                <fullName>Inventory Data Capture – File Level</fullName>
            </value>
            <value>
                <fullName>Inventory Pack/Purge/Shift</fullName>
            </value>
            <value>
                <fullName>Inventory Relocation</fullName>
            </value>
            <value>
                <fullName>Labour Hours</fullName>
            </value>
            <value>
                <fullName>Library Move</fullName>
            </value>
            <value>
                <fullName>Linear Ft</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Shred - Add Bins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Detail__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Detail__c</fullName>
    <inlineHelpText>Enter a detailed description of the Department, Division, or Location that the deal was sold to.  There is no need to put a Contact Name, Company Name, or Revenue Type as this has already been provided in the other fields on the Opportunity.</inlineHelpText>
    <label>Up-Sell Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Quantity__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Quantity__c</fullName>
    <inlineHelpText>Please enter a Quantity.  
Examples:  for cubic ft and linear ft, enter the total amount involved in the up-sell.  For up-sells on rotations (Wkly-Daily, Mthly-Wkly, etc), enter 1.</inlineHelpText>
    <label>Up-Sell Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IM_Up_Sell_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>IM_Up_Sell_Sold_To__c</fullName>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Up-Sell Oracle Account ID#</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upsell_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Customer_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>filtered look up to the customer account table for North America</description>
    <inlineHelpText>Enter the existing Customer Account you are selling to</inlineHelpText>
    <label>Upsell Customer ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 7) OR 4 OR 5 OR 6</booleanFilter>
        <filterItems>
            <field>IM_Customer_Account__c.Source_System__c</field>
            <operation>equals</operation>
            <value>SB NA, SKP NA, Business Central - ITRenew, Archivum CHE, ARCVMS Europe, ONeils Europe, Other Europe, SKP Europe</value>
        </filterItems>
        <filterItems>
            <field>IM_Customer_Account__c.IM_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>IM_Customer_Account__c.IM_Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>DM SITAD</value>
        </filterItems>
        <filterItems>
            <field>$Source.Primary_Product_Line__c</field>
            <operation>equals</operation>
            <value>Secure IT Asset Disposition</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Up-Sell/Lift</value>
        </filterItems>
        <infoMessage>This lookup shows Customer IDs related to the Opportunity’s Account Hierarchy.  The Opportunity and Customer ID Accounts must match unless prepaid OTS deal.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ValidateOnLeadConvert.cls
/*     
Author       : Madhu Paladugu / Srinivasa rao Mandalapu
Created Date : 1/23/2013
Case No.     : 00662466
Description  : Added the logic to check the validation rules(Upsell_Opportunity_Quantity,Upsell_Opportunity_Detail_Rule,Upsell_Opportunity_Unit_of_Measure,UpSell_Sold_To_required_for_UpSell_Opt,Validate_Booked_Date_Early) while converting the lead.
*/  
public Class ValidateOnLeadConvert{
    
    public static Boolean NO_ERROR=false;
    
    public static void doValidate(Opportunity opp){    
        
        Opportunity leadopportunity=opp;
                system.debug(leadopportunity.Upsell_Customer_ID__c+'testing@@');
        if((leadopportunity.StageName == '0 - Pre-Qualification' || leadopportunity.StageName == '1 - Qualification' || leadopportunity.StageName == '2 - Solution Developed' || leadopportunity.StageName == '3 - Solution Agreed' || leadopportunity.StageName == '4 - Negotiate' || leadopportunity.StageName == 'Postponed') && leadopportunity.CloseDate < system.today()){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'Booked Date cannot be a date in the past in early stage opportunities');
            Apexpages.addMessage(errMsg1);          
        }
        else if(leadopportunity.StageName=='5 - Signed/PO in' || leadopportunity.StageName=='6 - Setup' || leadopportunity.StageName=='7 - Closed' || leadopportunity.StageName=='0 - Pre-Qualification' || leadopportunity.StageName==' Lost' || leadopportunity.StageName=='Dead' || leadopportunity.StageName=='Postponed' ){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'Stage should be 1 to 4 only while converting the lead');
            Apexpages.addMessage(errMsg1); 
        }
        
        //CloseDate formerly First Bill Date, Booked Date is now First Bill Date.
        else if(leadopportunity.IM_Booked_Date__c<leadopportunity.CloseDate){
             Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'The First Bill Date must be greater or equal to the Booked Date.');
             Apexpages.addMessage(errMsg1); 
        }      
        else if(leadopportunity.Type=='Up-Sell/Lift' && (leadopportunity.IM_Up_Sell_Quantity__c==null ||leadopportunity.IM_Up_Sell_Quantity__c<=0)){
             Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'If Type is Up-Sell you must fill in the Up-Sell Quantity');
             Apexpages.addMessage(errMsg1); 
                
        }
        /* else if(leadopportunity.Type=='Up-Sell/Lift' && leadopportunity.IM_Up_Sell_Sold_To__c==null){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'If Type is Up-Sell, you must fill in the Up-Sell Oracle Account ID#');
            Apexpages.addMessage(errMsg1); 
        } */

        else if(leadopportunity.Type=='Up-Sell/Lift' && String.isBlank(leadopportunity.Upsell_Customer_ID__c)){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'If Type is Up-Sell, you must fill in the Up-Sell Customer Id');
            Apexpages.addMessage(errMsg1); 
        }
        else if(leadopportunity.Type=='Up-Sell/Lift' && leadopportunity.IM_Up_Sell_Detail__c==null){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'If Type is Up-Sell, you must fill in the Up-Sell Detail');
            Apexpages.addMessage(errMsg1);
        }
        else if(leadopportunity.Type=='Up-Sell/Lift' && leadopportunity.IM_Unit_of_Measure__c==null){
            Apexpages.Message errMsg1 = new Apexpages.Message(ApexPages.Severity.Fatal, 'If Type is Up-Sell you must fill in the Unit of Measure');
            Apexpages.addMessage(errMsg1); 
        }
       
        else{
           NO_ERROR=true;
        }

    }
}