force-app/main/default/objects/Opportunity/fields/IM_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>IM_Booked_Date__c</fullName>
    <label>First Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <formula>TEXT(Owner_Link__r.Sales_Division__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Bundle__c/Product_Bundle__c.object-meta.xml
<CustomObject>
    <label>Product Bundle</label>
    <nameField>
        <label>Product Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Bundle__c/fields/Product_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_ID__c</fullName>
    <description>Please put the ID of the product group associated to this bundle.</description>
    <inlineHelpText>Production value for North America Product Group ID: 01s80000000QlcC</inlineHelpText>
    <label>Product Group ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Bundle__c/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product ID</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Bundles</relationshipLabel>
    <relationshipName>Product_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Activation_Settings__c/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_OpportunityCurrentRevenue_Trigger.cls
@isTest(seeAllData=true)
public class Test_OpportunityCurrentRevenue_Trigger {
   
   static testMethod void myUnitTest() {
      List<Trigger_Activation_Settings__c> customsettings = Trigger_Activation_Settings__c.getall().values();
      List<Trigger_Activation_Settings__c> updatesettings = new List<Trigger_Activation_Settings__c>();
      for(Trigger_Activation_Settings__c cs : customsettings){
          if(cs.Object__c == 'OpportunityLineItem' && cs.Trigger__c == 'maintainOpportunityForecastObject') {
          cs.Value__c='True';
          updatesettings.add(cs);
        }
      }
      update updatesettings;
      system.debug('enetering maintainOpportunityForecastObject---------');
     
        //Preparing mock data for test
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;
        Recordtype r=[select id from recordtype where name='Standard Opportunity' limit 1];
      //  recordtype r=[select id from recordtype where name='NA Renewal' limit 1];
        
        Opportunity testOpp = new Opportunity(Name = 'Test Opportunity', AccountId = testAccount.Id, StageName = '1 - Qualification', IM_Booked_Date__c = Date.Today(), closedate = Date.Today()+1,recordtypeid=r.id);
        insert testOpp;
        
        user u=[select id,Sales_Division__c from user where id=:userInfo.getUserId()];
        u.Sales_Division__c='North America';
        update u;
        
        //Retrieving standard pricebook
        Pricebook2 testStandardPriceBook = [select id from Pricebook2 where IsStandard = true];
        //Creating a Prooduct, PriceBookEntry for it and using these record to generate OpportunityLineItem record.
        RecordType rec=[select id from RecordType where name='IMNA Product' limit 1];
        
        Product2 testProd = new Product2(Name = 'Test Product', IsActive= true, recordTypeId =rec.id);
        insert testProd;
        PriceBookEntry testPriceBookEntry =  new PriceBookEntry(Product2Id = testProd.Id, Pricebook2Id = testStandardPriceBook.Id, UnitPrice = 1, IsActive = true, UseStandardPrice = false);
        insert testPriceBookEntry;
        List<OpportunityLineItem> insLinItems=new  List<OpportunityLineItem>();     
        OpportunityLineItem oppProd = new OpportunityLineItem(Quantity = 12, PricebookEntryId = testPriceBookEntry.Id, OpportunityId = testOpp.Id, unitPrice = 1);
        //insert oppProd;//insert event of Trigger is called.
       OpportunityLineItem oppProd1 = new OpportunityLineItem(Quantity = 12, PricebookEntryId = testPriceBookEntry.Id, OpportunityId = testOpp.Id, unitPrice = 1);
        insLinItems.add(oppProd);
        //insLinItems.add(oppProd1);
         Test.startTest();
        insert insLinItems;
    
         Product_Bundle__c probun = new Product_Bundle__c(
        Product_ID__c=testProd.id,
        Product_Group_ID__c=testPriceBookEntry.Pricebook2Id);
        insert probun;
        //updating OpportunityLineItem record
       
        update oppProd;//Update event of trigger is called
      
       // delete oppProd;//delete event of trigger is called.
       //delete oppProd1;
       
       //insLinItems.add(oppProd);//delete event of trigger is called.
       //insLinItems.add(oppProd1);
   
      delete insLinItems;     
        
       Test.stopTest();
}

}