force-app/main/default/objects/Opportunity/fields/New_Department_or_SKP_Shipto_Address__c.field-meta.xml
<CustomField>
    <fullName>New_Department_or_SKP_Shipto_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the RM opportunity requires the set-up of a new Department or Shipto Address</description>
    <inlineHelpText>Indicates that this RM Opportunity requires the set-up of a new Department or Ship To Address</inlineHelpText>
    <label>RM New Department or Ship To Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Total_Annual_Amount_Test__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Total_Annual_Amount_Test__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is the Total Annual Amount equal to or less than PA Model/SOW/Project Form? In North America this test is only carried out on Opportunities over USD 24k.</inlineHelpText>
    <label>Opportunity Total Annual Amount Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SV_Status__c.field-meta.xml
<CustomField>
    <fullName>SV_Status__c</fullName>
    <inlineHelpText>Queued - ready to test commission eligibility. Passed - commission eligible. Open - action required by Opportunity Owner. Failed - not commission eligible. Withdrawn - at Opportunity Owner’s request. Commission Ineligible - no sales process.</inlineHelpText>
    <label>SV Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Commission Ineligible</fullName>
            </value>
            <value>
                <fullName>Appeal Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upsell_Lift_Sales_Cycle_Length_Test__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Lift_Sales_Cycle_Length_Test__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Test applies to Upsell/Lift Opportunities. Tests the length of time between the Create Date and the Booked Date (minimum 21 days for recurring products; 7 days for only non-recurring products).</inlineHelpText>
    <label>Upsell/Lift Sales Cycle Length Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Standard_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Standard_Opportunity_Process</businessProcess>
    <description>IRM Standard Opportunity. Full 8-stage lifecycle. Includes Setup stage used by child/sub-Opportunities under a Framework Parent contract.</description>
    <label>Standard Opportunity</label>
</RecordType>

force-app/main/default/objects/SVStatus__c/SVStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for checking the SVStatus field values</description>
    <label>SVStatus</label>
</CustomObject>

force-app/main/default/objects/SVStatus__c/fields/OpptType__c.field-meta.xml
<CustomField>
    <fullName>OpptType__c</fullName>
    <label>OpptType</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SVStatus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&apos;6 - Setup&apos;</defaultValue>
    <label>Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SVStatus.cls
/**
* Modified By: Vinutha Iyengar on 20-Jun-2017 
*          -- Set 'Opportunity Total Annual Amount Test' to false when 'SV Status' != 'Passed'
*          -- Case # 06190653

* Modified By: Keerthi Senthilnathan on 14-Aug-2017 
*          -- Set 'Upsell/Lift Sales Cycle Length Test' and 'RM New Department or Ship To Address' to false when 'SV Status' != 'Passed'
*          -- Case # 06190653

* Modified By: Keerthi Senthilnathan on 24-Apr-2018 
*          -- Update 'SV Status' based on the condition
*          -- Case # 07739056

**/
public class SVStatus{
    
    public static void updateSVStatus(List<Opportunity> OppList, Map<id,Opportunity> oldMap,Map<String, Double> currenMap){
        //Id standardRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Standard_Opportunity').getRecordTypeId();
        Id standardRecordTypeId = App_Constants.STD_OPPORTUNITY_RECTYPE_ID;
        Id IMERecordTypeId = App_Constants.IME_STD_OPPORTUNITY_RECTYPE_ID;
        /*currenLst = new List<CurrencyType>();
//get all the Org Currency & conversions
currenLst = [Select Id, ConversionRate, ISOCode  from CurrencyType];
currenMap = new Map<String, Double>();
//put All the currency in the Map
for(CurrencyType objCurren: currenLst)
{
currenMap.put(objCurren.ISOCode , objCurren.ConversionRate);
}*/
        for(Opportunity OppNew : OppList){
            Opportunity Oppold = oldMap.get(OppNew.Id);
            //Get Custom setting values
            SVStatus__c svStsCustom = SVStatus__c.getValues('SVStatusPassed');
            system.debug('$$$$$$$$$$$$$$ Gopi'+svStsCustom);
            //get Redord Types Details 
            if(OppNew.Amount != Oppold.Amount || OppNew.Type != Oppold.Type|| OppNew.RecordtypeId != Oppold.RecordtypeId || OppNew.StageName != Oppold.StageName){
                //if((OppNew.Type == 'Up-Sell/Lift' || OppNew.Type == 'New Deal')&& (OppNew.StageName =='6 - Setup') &&((1/(currenMap.get(OppNew.currencyIsoCode)) * (OppNew.Amount = OppNew.Amount==null?0:OppNew.Amount)) < 24000 ) &&(recordType_Map.get(OppNew.RecordtypeId).Name=='Standard Opportunity')){
                List<string> opptTypes = new List<string>();
                if(svStsCustom.OpptType__c != null){
                    opptTypes = svStsCustom.OpptType__c.split(',');
                }
                //List<string> opptTypes = svStsCustom.OpptType__c.split(',');
                boolean checkTrue = false;
                for(string opType : opptTypes){
                    if((OppNew.Type == opType)&& (OppNew.StageName == svStsCustom.Stage__c) &&((1/(currenMap.get(OppNew.currencyIsoCode)) * (OppNew.Amount = OppNew.Amount==null?0:OppNew.Amount)) < svStsCustom.Amount__c) &&(OppNew.RecordtypeId == standardRecordTypeId)){
                        checkTrue = true;
                        break;
                    }
                }
                if(checkTrue)
                {
                    OppNew.Opportunity_Total_Annual_Amount_Test__c= true;
                }
                else
                {
                    if(OppNew.SV_Status__c != 'Passed'){
                        OppNew.Opportunity_Total_Annual_Amount_Test__c= false;
                        OppNew.Upsell_Lift_Sales_Cycle_Length_Test__c = false;
                        
                    }
                }
            }
            if(OppNew.OwnerId != Oppold.OwnerId)
            {
                if(OppNew.SV_Status__c != 'Passed'){
                    OppNew.Opportunity_Total_Annual_Amount_Test__c= false;
                    OppNew.Upsell_Lift_Sales_Cycle_Length_Test__c = false;
                    
                }
            }
            
            //Update 'SV Status' based on the condition for case#07739056
            
            //(If the opportunity RecordType is equal to Standard opportunity or IME Standard opportunity and opportunity status is equal to passed and any of the filed (Amount or ownerid or Type is equal to New deal or up-sell/Lift) in opportunity is changed then the opportunity status should be updated to Queued)
            if((OppNew.RecordTypeId == standardRecordTypeId || OppNew.RecordTypeId == IMERecordTypeId) && OppNew.SV_Status__c == 'Passed' && (OppNew.Amount != Oppold.Amount || OppNew.OwnerId != Oppold.OwnerId || (OppNew.Type != Oppold.Type && (OppNew.Type == 'New Deal' || OppNew.Type == 'Up-Sell/Lift'))))
            {
                OppNew.SV_Status__c = 'Queued';
                OppNew.Opportunity_Total_Annual_Amount_Test__c= false;
                OppNew.Upsell_Lift_Sales_Cycle_Length_Test__c = false;
                
            }
            
            //(If the opportunity RecordType is equal to Standard opportunity or IME Standard opportunity and opportunity Type is equal to Renewal then the opportunity status should be updated to Blank)
            if((OppNew.RecordTypeId == standardRecordTypeId || OppNew.RecordTypeId == IMERecordTypeId) && OppNew.Type == 'Renewal')
            {
                OppNew.SV_Status__c = '';
            } 
            
            //(If the opportunity RecordType is equal to IME Standard opportunity And Opportunity Type field is equal to 'New Deal' and Opportunity Total Annual Amount Test field checkbox is checked OR all the three Checkbox fields "Opportunity Total Annual Amount Test", "Upsell/Lift Sales Cycle Length Test" and "RM New Department or Ship To Address" is checked and Opportunity 'Type' field is equal to 'Up-Sell/Lift') 
            if(OppNew.RecordTypeId == IMERecordTypeId && (OppNew.Type == 'New Deal' && OppNew.Opportunity_Total_Annual_Amount_Test__c == TRUE) || (OppNew.Opportunity_Total_Annual_Amount_Test__c == TRUE && OppNew.Type == 'Up-Sell/Lift' && OppNew.Upsell_Lift_Sales_Cycle_Length_Test__c == TRUE && OppNew.New_Department_or_SKP_Shipto_Address__c == TRUE))
            {
                OppNew.SV_Status__c = 'Passed';
            }
            
            //(If the opportunity RecordType is equal to Standard opportunity or IME Standard opportunity AND Opportunity 'StageName' is equal to '6 - Setup' AND Opportunity 'SV Status' is equal to NULL AND either Opportunity 'Type' field is equal to 'New Deal' Or 'Up-Sell/Lift')
            if((OppNew.RecordTypeId == standardRecordTypeId || OppNew.RecordTypeId == IMERecordTypeId) && OppNew.StageName == '6 - Setup' && OppNew.SV_Status__c == NULL && (OppNew.Type == 'New Deal' || OppNew.Type == 'Up-Sell/Lift'))
            {
                OppNew.SV_Status__c = 'Queued';
            }
        } 
    }   
}