force-app/main/default/objects/Sales_Support_Request__c/Sales_Support_Request__c.object-meta.xml
<CustomObject>
    <label>Commercial Support Request</label>
    <nameField>
        <label>Request Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Support_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sales Support Team Member</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Factory_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Support_Request__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Factory_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Support_Request_Users__c/Sales_Support_Request_Users__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SalesSupport Request Users</label>
</CustomObject>

force-app/main/default/objects/Sales_Support_Request_Users__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trigger_Activation_Settings__c/Trigger_Activation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Setting is used for turning on and off any particular logic of a trigger for all Objects.</description>
    <label>Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/classes/Test_SalesSupportRequestObject.cls
/*****************************************************************************************************************************
Name : Test_SalesSupportRequestObject 
Created By : Srinivasa Rao Mandalapu
Created Date : 03rd Dec, 201
Usages : Test coverage of SalesSupportRequestTrigger with custom settings logic.
*****************************************************************************************************************************/
@isTest(SeeAllData=true)
private class Test_SalesSupportRequestObject {
    
    public static String SalesSupportRequestTrigger=null;
    
    /*SalesSupportRequestTrigger code coverage for bulkPositive*/
    static testMethod void bulkPositive() {
        List<Trigger_Activation_Settings__c> customsettings = Trigger_Activation_Settings__c.getall().values();
        List<Trigger_Activation_Settings__c> updatesettings = new List<Trigger_Activation_Settings__c>();
        for(Trigger_Activation_Settings__c cs : customsettings){
          if(cs.Object__c == 'Sales_Support_Request__c') {
            cs.Value__c='True';
            updatesettings.add(cs);
          }
        }
        update updatesettings;
        
        // TO DO: implement unit test
        Profile p = [select id from profile where name='Marketing User'];
        // create a user to run the test as
        User u = new User(alias = 'test123', email='test1234@noemail.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = p.Id, country='United States',
            timezonesidkey='America/Los_Angeles', username='12test1234@noemail.com');
        insert u;
         Sales_Support_Request_Users__c custset=new Sales_Support_Request_Users__c();
            custset.Name='test1';
            custset.UserId__c=u.id;
            insert custset;

            Sales_Support_Request__c ssr = new Sales_Support_Request__c(
                Name='testName',
                OwnerId=u.Id,
                Assigned_to__c=u.id
            );
        insert ssr;
        Sales_Support_Request__c ssr1=[select id,Sales_Rep__c from Sales_Support_Request__c where id=:ssr.id];
       
        System.assertEquals (ssr1.Sales_Rep__c , userInfo.getUserId());
        
        ssr1.Sales_Rep__c = u.Id;
        
        System.assertEquals (ssr1.Sales_Rep__c , u.Id);
    }
    
   
}