force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>Competitor object that captures competitive information around IM competitors.</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/Iron_Mountain_Storage_Profile__c.object-meta.xml
<CustomObject>
    <label>Iron Mountain Storage Profile</label>
    <nameField>
        <displayFormat>IMSP - {00000}</displayFormat>
        <label>Iron Mountain Storage Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Iron Mountain Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Iron Mountain Storage Profiles</relationshipLabel>
    <relationshipName>Iron_Mountain_Storage_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_Cube__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_Cube__c</fullName>
    <inlineHelpText>Total CF of customer storage volume with IM (total for all accounts in this IMGA).</inlineHelpText>
    <label>Existing IM Storage Volume - Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_DB_R_Container__c</fullName>
    <inlineHelpText>Shows the quantity Iron Mountain has sold to this customer</inlineHelpText>
    <label>Existing IM Storage Volume - DPUs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/IM_Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>IM_Quantity_Tape__c</fullName>
    <inlineHelpText>Shows the quantity Iron Mountain has sold to this customer</inlineHelpText>
    <label>Existing IM Storage Volume - Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_Cube__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_Cube__c</fullName>
    <inlineHelpText>This is the total amount of records storage (in CF) the customer has/needs regardless of location (at customer site, competitors, etc.)</inlineHelpText>
    <label>Overall Customer Storage Volume-Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_DB_R_Container__c</fullName>
    <inlineHelpText>Enter the profiled customer need.</inlineHelpText>
    <label>Overall Storage Volume - DPUs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Profiled_Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>Profiled_Quantity_Tape__c</fullName>
    <inlineHelpText>Enter the profiled customer need.</inlineHelpText>
    <label>Overall Customer Storage Volume – Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_Cube__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_Cube__c</fullName>
    <formula>Profiled_Quantity_Cube__c -(IM_Quantity_Cube__c + Competitor_Quantity_Cube__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The difference between the total amount of overall customer storage volume and what storage volume IM has (It’s calculated for you).</inlineHelpText>
    <label>Potential New Storage Volume - Cubic Ft</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_DB_R_Container__c</fullName>
    <formula>Profiled_Quantity_DB_R_Container__c -( IM_Quantity_DB_R_Container__c + Competitor_Quantity_DB_R_Container__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Potential New Storage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Iron_Mountain_Storage_Profile__c/fields/Whitespace_Tape__c.field-meta.xml
<CustomField>
    <fullName>Whitespace_Tape__c</fullName>
    <formula>Profiled_Quantity_Tape__c -( IM_Quantity_Tape__c +  Competitor_Quantity_Tape__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Potential New Storage Volume - Tape</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/Storage_Profile__c.object-meta.xml
<CustomObject>
    <description>Object used to capture which vendor controls existing cube and tape at an account</description>
    <label>Competitor Storage Profile</label>
    <nameField>
        <displayFormat>StorageProfile-{0000}</displayFormat>
        <label>Storage Profile Name (cust-vendor-type)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Storage Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Storage_Profile__c/fields/Iron_Mountain_Storage_Profile__c.field-meta.xml
<CustomField>
    <fullName>Iron_Mountain_Storage_Profile__c</fullName>
    <label>Iron Mountain Storage Profile</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Iron_Mountain_Storage_Profile__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Iron_Mountain_Storage_Profile__c</referenceTo>
    <relationshipLabel>Competitor Storage Profiles</relationshipLabel>
    <relationshipName>Storage_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Quantity_Cube__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Cube__c</fullName>
    <label>Quantity (Cube)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Quantity_DB_R_Container__c.field-meta.xml
<CustomField>
    <fullName>Quantity_DB_R_Container__c</fullName>
    <label>Quantity (DB&amp;R Container)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Quantity_Tape__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Tape__c</fullName>
    <label>Quantity (Tape)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Storage_Profile__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Competitors table</description>
    <inlineHelpText>Search for the competitor&apos;s name. If Iron Mountain owns this storage business search for Iron Mountain. If this is un-vended search for InHouse</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipName>Storage_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StorageProfilePageCont.cls
public with sharing class StorageProfilePageCont 
{
	public static final String CUBE = 'Cube';
	public static final String DBnR_CONTAINER = 'DB&R Container';
	public static final String TAPE = 'Tape';
	public ID accountID {get;set;}
	public ID returnID {get;set;}
	public ID ironProfileID {get;set;}

	public StorageProfilePageCont(){
		
	}
	
	public Map<Id, Iron_Mountain_Storage_Profile__c> ironMountainStorageProfileMap
	{
		get
		{
			if( ironMountainStorageProfileMap == NULL )
			{
				ironMountainStorageProfileMap = new Map<Id, Iron_Mountain_Storage_Profile__c> ( 
													[ SELECT Whitespace_Tape__c, Whitespace_DB_R_Container__c, Whitespace_Cube__c, Profiled_Quantity_Tape__c, 
													Profiled_Quantity_DB_R_Container__c, Profiled_Quantity_Cube__c, Name, IM_Quantity_Tape__c, IM_Quantity_DB_R_Container__c, IM_Quantity_Cube__c, 
													( SELECT Name, Quantity_Tape__c, Quantity_DB_R_Container__c, Quantity_Cube__c, Vendor__r.name FROM Storage_Profiles__r order by Vendor__r.name ) 
													FROM Iron_Mountain_Storage_Profile__c WHERE Account__c = :accountID ] );
													
								
			}
			return ironMountainStorageProfileMap;
		}
		public set;
	}
	
	public Boolean atLeastOneIronMountainStorageProfile {
		get {
			return !ironMountainStorageProfileMap.isEmpty();
		}
		private set;
	}
	
	public List<Iron_Mountain_Storage_Profile__c> emptyIronMountainStorageProfile {
		get {
			if( emptyIronMountainStorageProfile == null )
			{
				Iron_Mountain_Storage_Profile__c empty = new Iron_Mountain_Storage_Profile__c(Account__c = accountID);
				emptyIronMountainStorageProfile = new List<Iron_Mountain_Storage_Profile__c>{empty};
			}
			return emptyIronMountainStorageProfile;
		}
		private set;
	}
	
	public list<Iron_Mountain_Storage_Profile__c> ironMountainStorageProfiles
	{
		get 
		{
			return  ironMountainStorageProfileMap.values();
		}
		set;
	}
	
	public String createNewCompetitorProfile
	{
		get 
		{
			if(String.isBlank( createNewCompetitorProfile ))
			{
				PageReference storageProfileCreationPage = Page.StorageProfileNew;
				storageProfileCreationPage.getParameters().put('retURL', '/' + returnID);
				storageProfileCreationPage.getParameters().put(StorageProfileContExt.ACCOUNT_ID_PARAM, accountID);
				
				createNewCompetitorProfile = URL.getSalesforceBaseUrl().toExternalForm() + storageProfileCreationPage.getUrl();
			}
			return  createNewCompetitorProfile;
		}
		set;
	}
	
	public pageReference saveNewProfile() {
		
		try{
			insert emptyIronMountainStorageProfile;	
			ironProfileID = emptyIronMountainStorageProfile[0].Id;
		}
		catch(Exception Ex)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An Error Occurred : ' + Ex.getMessage()));
		}
		
		return null;
	}
	
	public pagereference save() {
		
		if( !atLeastOneIronMountainStorageProfile )
		{
			saveNewProfile();
		}
		else
		{
			Savepoint sp = Database.setSavepoint();
			List<Storage_Profile__C> storageProfiles = new list<Storage_Profile__c>();
			for (Iron_Mountain_Storage_Profile__c imsp : ironMountainStorageProfiles )
				storageProfiles.addAll(imsp.Storage_Profiles__r);
			
			
			try{
				update storageProfiles;
				update ironMountainStorageProfiles;
				
				this.ironMountainStorageProfileMap = NULL;
				
				for (Iron_Mountain_Storage_Profile__c imsp : ironMountainStorageProfiles ){
					if (imsp.Whitespace_Cube__c < 0 || imsp.Whitespace_DB_R_Container__c < 0  || imsp.Whitespace_Tape__c < 0 ){
						ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, System.Label.Negative_Whitespace_Alert));
					}
				}
				
				
				
			} catch (Dmlexception ex) {
				ApexPages.addMessages(ex);
				Database.rollback(sp);
				
				this.ironMountainStorageProfileMap = NULL;
			}
		}	
		//Nulling this out to clear the values on page. 
		
		
		return null;
	}
	

	
	
}