force-app/main/default/objects/Quote_Stage_Progression_Dates__c/Quote_Stage_Progression_Dates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To do the stage progression on NA Renewal quotes</description>
    <label>Quote Stage Progression Dates</label>
</CustomObject>

force-app/main/default/objects/Quote_Stage_Progression_Dates__c/fields/Next_Progression_Stage__c.field-meta.xml
<CustomField>
    <fullName>Next_Progression_Stage__c</fullName>
    <label>Next Progression Stage</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Stage_Progression_Dates__c/fields/Progression_Date__c.field-meta.xml
<CustomField>
    <fullName>Progression_Date__c</fullName>
    <inlineHelpText>Date for the stage progression</inlineHelpText>
    <label>Progression Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Q2W_Quote_Stage_Progre_Scheduler.cls
/****************************** 
   Developer Name    : Madhu Paladugu
   
   Date              : 7/3/2013
   
   Company Name      : CloudFountain Inc.
   
   Purpose           : This class is used for Quote stage progression batch job's scheduler. 
   
   Test Class        : Test_Q2W_Quote_Stage_Progre_BatchJob
   
   Dependents        : Apex Class: Q2W_Quote_Stage_Progre_BatchJob
   
   Case Number       : 00222919
                                  
 ********************************/  

global class  Q2W_Quote_Stage_Progre_Scheduler implements Schedulable{
   
    //execute method with each batch size of 200 records
    Global void execute(SchedulableContext sc){
        
        Quote_Stage_Progression_Dates__c custData;
        try{
            custData=[select Next_Progression_Stage__c,Progression_Date__c from Quote_Stage_Progression_Dates__c where Progression_Date__c = TODAY limit 1]; 
        }
        catch(Exception e){
            system.debug('++++++++do nothing++++++++');
        }
        if(custData!=null){
            system.debug('++++++++++Executing stage progression on +++++++++'+Date.today());
            database.executebatch(new Q2W_Quote_Stage_Progre_BatchJob(custData.Next_Progression_Stage__c),200); 
        }
    }
}