force-app/main/default/objects/Billing_Market__c/Billing_Market__c.object-meta.xml
<CustomObject>
    <description>Object that represents Revenue District or Billing Market from storage bill codes</description>
    <label>Billing Market</label>
    <nameField>
        <label>Billing Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Settings__c/Country_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country Custom Settings</label>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/Inbound_Storage__c.object-meta.xml
<CustomObject>
    <label>Inbound Storage</label>
    <nameField>
        <displayFormat>STOR-{00000000}</displayFormat>
        <label>New Storage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Storage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Storage__c/fields/Association_to_Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Association_to_Opportunity_Status__c</fullName>
    <description>Status of the association between the inbound storage record and the booked sale, managed by the commissions team.</description>
    <inlineHelpText>Status of the association between the inbound storage record and the booked sale.</inlineHelpText>
    <label>Association to Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Unmatched</fullName>
                <default>true</default>
                <label>Unmatched</label>
            </value>
            <value>
                <fullName>Matched - Approved</fullName>
            </value>
            <value>
                <fullName>Matched - Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Cube_District__c.field-meta.xml
<CustomField>
    <fullName>Cube_District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cube District</label>
    <referenceTo>Billing_Market__c</referenceTo>
    <relationshipName>New_Storage</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <label>Customer Account</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipName>New_Storage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Dept_ID_del__c.field-meta.xml
<CustomField>
    <fullName>Dept_ID_del__c</fullName>
    <label>Dept. ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Div_ID_del__c.field-meta.xml
<CustomField>
    <fullName>Div_ID_del__c</fullName>
    <label>Div. ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Opportunity which produced the new storage</description>
    <inlineHelpText>Link to the Opportunity which produced the new storage</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>New_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Storage__c/fields/Storage_Date__c.field-meta.xml
<CustomField>
    <fullName>Storage_Date__c</fullName>
    <label>Storage Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <inlineHelpText>The operational source system the customer ID is managed through</inlineHelpText>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SKP Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>Other Europe</fullName>
            </value>
            <value>
                <fullName>SB IMLA</fullName>
            </value>
            <value>
                <fullName>SKP IMLA</fullName>
            </value>
            <value>
                <fullName>Other IMLA</fullName>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>SKP IMAP</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SRMS IMAP</fullName>
            </value>
            <value>
                <fullName>Tape Guard IMAP</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>SB IMAP</fullName>
            </value>
            <value>
                <fullName>TRSQL</fullName>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TOBAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/OpportunityProductSelection__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to take product class and product line names in to apex class while adding product</description>
    <label>OpportunityProductSelection</label>
</CustomObject>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Class_Name__c</fullName>
    <label>Product Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityProductSelection__c/fields/Product_Line_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Name__c</fullName>
    <label>Product Line Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestInboundStorageTrigger.cls
/*
 * InboundStorageTrigger
 * Handles updating opportunities to roll up their related inbound storages
 *
 * Ver No.     Resource                           Date         Changes
 * -----------------------------------------------------------------------------
 *   1.0       Charlie Xie(Bluewolf)        01/27/2014         Created
 *
 */ 

/*
 * Used (SeeAllData=true) because IM_Customer_Account__c creation keeps crashing in SIT, UAT and Prod.
 * Error: Internal Salesforce Error: 464140916-98261 (-120363337) (-120363337)
 * Root Cause: Unable to use any safe value for the required restricted picklist field 'Source_System__c' on IM_Customer_Account__c.
*/ 
@isTest(SeeAllData=true)
public class TestInboundStorageTrigger {

    private static List<Inbound_Storage__c> createTestInboundStorageRecords(Integer count) {
        List<Inbound_Storage__c> inboundStorages = new List<Inbound_Storage__c>();
		List<Account> accts = TestingUtils.createAccounts(1, true);
        
        List<OpportunityProductSelection__c> oppprodsels = [SELECT Id FROM OpportunityProductSelection__c where Product_Class_Name__c = 'Data Backup and Recovery' and Product_Line_Name__c = 'Cloud Solutions' LIMIT 1];
        List<Country_Settings__c> settings = [SELECT Id FROM Country_Settings__c where Name = 'United States' and object_name__c = 'Account'  LIMIT 1];
        
        if (!oppprodsels.isEmpty()) {
            OpportunityProductSelection__c oppprodsel = oppprodsels[0];
        } else {
            OpportunityProductSelection__c oppprodsel = new OpportunityProductSelection__c();
            oppprodsel.Name = 'CloudSolutionsProduct';
            oppprodsel.Product_Class_Name__c = 'Data Backup and Recovery';
            oppprodsel.Product_Line_Name__c = 'Cloud Solutions';              
            insert oppprodsel; 
        }
        
        if (!settings.isEmpty()) {
            Country_Settings__c setting = settings[0];
        } else {
            Country_Settings__c setting = new Country_Settings__c();
            setting.Name = 'United States';
            setting.object_name__c = 'Account';
            insert setting;  
        }
        Opportunity opps = TestingUtils.createOpportunity('Testopp1',accts[0].Id,true);
        
        IM_Customer_Account__c imca;
        Billing_Market__c billingMarket;
        try {
            imca = [SELECT Id FROM IM_Customer_Account__c LIMIT 1];
            billingMarket = [SELECT Id FROM Billing_Market__c LIMIT 1];
        } catch (QueryException e) {
            System.debug('NO DATA FOUND: At least one IM_Customer_Account__c and Billing_Market__c is required.');
        }
        
        RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'Inbound Storage' LIMIT 1];

        for (Integer i = 0; i < count; i++) {
            inboundStorages.add(new Inbound_Storage__c(
                RecordTypeId = rt.Id,
                Association_To_Opportunity_Status__c = 'Matched - Approved',
                Customer_Account__c = imca.Id,
                Storage_Date__c = Date.today(),
                Div_ID_del__c = 'division ' + i,
                Dept_ID_del__c = 'dept ' + i,
                Cube_District__c = billingMarket.Id
            ));
        }
        return inboundStorages;
    }

    @isTest static void testAfterInsert() {
        List<Inbound_Storage__c> newRecords = createTestInboundStorageRecords(2);

        Test.startTest();
        insert newRecords;
        Test.stopTest();

    }

    @isTest static void testAfterUpdate() {
        List<Inbound_Storage__c> records = createTestInboundStorageRecords(2);
        list<Opportunity> oppid = [Select id from Opportunity where name = 'Testopp1'];
        insert records;

        for (Inbound_Storage__c rec : records) {
            rec.Dept_ID_del__c += ' updated';
            rec.Opportunity__c = oppid[0].id;
            system.debug('This is from test class: ' +rec.Opportunity__c);
        }

        Test.startTest();
        update records;
        Test.stopTest();

    }

    @isTest static void testAfterDelete() {
        List<Inbound_Storage__c> records = createTestInboundStorageRecords(1);
        insert records;

        Test.startTest();
        delete records;
        Test.stopTest();

    }
    
     @isTest static void testAfterUpdate_existinginbound() {
        List<Inbound_Storage__c> records = createTestInboundStorageRecords(2);
        list<Opportunity> oppid = [Select id from Opportunity where name like 'Testopp%'];
        records[0].Opportunity__c = oppid[0].id;
        records[1].Opportunity__c = oppid[0].id;
         
        Test.startTest();
        insert records;
        for (Inbound_Storage__c rec : records) {
            rec.Dept_ID_del__c += ' updated';
        }
         records[0].Opportunity__c = null;
        update records;
        Test.stopTest();

    }

    @isTest static void testBulkOperations() {
        List<Inbound_Storage__c> bulkRecords = createTestInboundStorageRecords(200);

        Test.startTest();
        insert bulkRecords;

        for (Inbound_Storage__c rec : bulkRecords) {
            rec.Dept_ID_del__c += ' bulk update';
        }
        update bulkRecords;

        delete bulkRecords;
        Test.stopTest();
    }
}