force-app/main/default/objects/Billing_Market__c/Billing_Market__c.object-meta.xml
<CustomObject>
    <description>Object that represents Revenue District or Billing Market from storage bill codes</description>
    <label>Billing Market</label>
    <nameField>
        <label>Billing Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Market__c/fields/Parent_Billing_Market__c.field-meta.xml
<CustomField>
    <fullName>Parent_Billing_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Billing Market that the Billing Market on this record belongs to.</description>
    <label>Parent Billing Market</label>
    <referenceTo>Parent_Billing_Market__c</referenceTo>
    <relationshipLabel>Billing Markets</relationshipLabel>
    <relationshipName>Billing_Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/Billings__c.object-meta.xml
<CustomObject>
    <description>Object used to receive billing transactions</description>
    <label>Billings</label>
    <nameField>
        <displayFormat>B-{000000000}</displayFormat>
        <label>Billings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billings__c/fields/Billing_Market__c.field-meta.xml
<CustomField>
    <fullName>Billing_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Market should be populated for storage related bill codes and represents the Revenue District as opposed to the Owning District</description>
    <label>Billing Market</label>
    <referenceTo>Billing_Market__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Billing_Period__c.field-meta.xml
<CustomField>
    <fullName>Billing_Period__c</fullName>
    <formula>MONTH (Invoice_Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Country_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Country_Coverage__c</fullName>
    <description>this value is pulled from the Parent Billing Market</description>
    <formula>TEXT( Billing_Market__r.Parent_Billing_Market__r.Country_Coverage__c )</formula>
    <label>Country Coverage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <label>Customer Account</label>
    <referenceTo>IM_Customer_Account__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/IMGA_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>IMGA_Name_Formula__c</fullName>
    <description>Returns the indexed IMGA Name on the Account linked to the Customer Account</description>
    <formula>Customer_Account__r.IM_Account__r.IM_IMGA_Indexed__c</formula>
    <label>IMGA Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Include_in_M4_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Include_in_M4_Coverage__c</fullName>
    <formula>IF(
Bill_Code__r.Include_in_M4_Coverage__c = TRUE,
&quot;Include&quot;,
&quot;Exclude&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Include in M4 Coverage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/M4_CY_YTD_Q1_Q2__c.field-meta.xml
<CustomField>
    <fullName>M4_CY_YTD_Q1_Q2__c</fullName>
    <formula>AND( 
MONTH(Invoice_Date__c) &lt;= VALUE(null),
MONTH(Invoice_Date__c) &gt;= 1,
MONTH(Invoice_Date__c) &lt;= 6,
YEAR(Invoice_Date__c) = VALUE($Label.Current_Commission_Year),
Bill_Code__r.Include_in_M4_Coverage__c  = true
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>M4 CY YTD Q1 Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Parent_Billing_Market__c.field-meta.xml
<CustomField>
    <fullName>Parent_Billing_Market__c</fullName>
    <description>this value is pulled from the Parent Billing Market</description>
    <formula>Billing_Market__r.Parent_Billing_Market__r.Name</formula>
    <label>Parent Billing Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Product_Class__c.field-meta.xml
<CustomField>
    <fullName>Product_Class__c</fullName>
    <formula>TEXT(Bill_Code__r.IM_Product_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billings__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Used to capture the source system of Billings Transactions uploaded into system</description>
    <label>Source System</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/IM_Customer_Account__c.object-meta.xml
<CustomObject>
    <description>This object represents Customer Account, Billing Account and Inventory Account in BI and Siebel</description>
    <label>Customer Account</label>
    <nameField>
        <label>Customer Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Account__c.field-meta.xml
<CustomField>
    <fullName>IM_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Accounts</relationshipLabel>
    <relationshipName>Customer_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Product_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Product_Class__c</fullName>
    <description>The Product class relating to the client account. Populated from the opportunity for IME and maintained manually.</description>
    <label>Product Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Consulting Services</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Data Products</fullName>
            </value>
            <value>
                <fullName>Data Protection</fullName>
            </value>
            <value>
                <fullName>Destruction Services</fullName>
            </value>
            <value>
                <fullName>Digital Archiving and Discovery</fullName>
            </value>
            <value>
                <fullName>Digital Data Protection and Recovery</fullName>
            </value>
            <value>
                <fullName>Document Management Solutions</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Film and Sound</fullName>
            </value>
            <value>
                <fullName>Fulfillment Services</fullName>
            </value>
            <value>
                <fullName>Intellectual Property Management</fullName>
            </value>
            <value>
                <fullName>Records Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/IM_Status__c.field-meta.xml
<CustomField>
    <fullName>IM_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IM_Customer_Account__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Gitlab #29287 making picklist as restrict pick list</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>44033.X22082</fullName>
                <isActive>false</isActive>
                <label>44033.X22082</label>
            </value>
            <value>
                <fullName>ACVMS</fullName>
                <isActive>false</isActive>
                <label>ACVMS</label>
            </value>
            <value>
                <fullName>Archivum CHE</fullName>
            </value>
            <value>
                <fullName>ARCVMS</fullName>
                <isActive>false</isActive>
                <label>ARCVMS</label>
            </value>
            <value>
                <fullName>ArcVms</fullName>
                <isActive>false</isActive>
                <label>ArcVms</label>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
            </value>
            <value>
                <fullName>ARCVMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe</label>
            </value>
            <value>
                <fullName>ARC VMS Europe</fullName>
                <isActive>false</isActive>
                <label>ARC VMS Europe</label>
            </value>
            <value>
                <fullName>ARCVMS Europe Europe</fullName>
                <isActive>false</isActive>
                <label>ARCVMS Europe Europe</label>
            </value>
            <value>
                <fullName>ArcVms Europe�</fullName>
                <isActive>false</isActive>
                <label>ArcVms Europe�</label>
            </value>
            <value>
                <fullName>ARVE</fullName>
                <isActive>false</isActive>
                <label>ARVE</label>
            </value>
            <value>
                <fullName>Business central</fullName>
                <isActive>false</isActive>
                <label>Business central</label>
            </value>
            <value>
                <fullName>Business Central - ITRenew</fullName>
            </value>
            <value>
                <fullName>Documenta COL</fullName>
            </value>
            <value>
                <fullName>ESS</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>IMAPIS</fullName>
                <isActive>false</isActive>
                <label>IMAPIS</label>
            </value>
            <value>
                <fullName>IMLA SKP</fullName>
                <isActive>false</isActive>
                <label>IMLA SKP</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Key Soft IMAP</fullName>
            </value>
            <value>
                <fullName>Netsuite</fullName>
            </value>
            <value>
                <fullName>O&apos;Neil IMAP</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neil IMAP</label>
            </value>
            <value>
                <fullName>O&apos;Neils Europe</fullName>
                <isActive>false</isActive>
                <label>O&apos;Neils Europe</label>
            </value>
            <value>
                <fullName>Oneil</fullName>
                <isActive>false</isActive>
                <label>Oneil</label>
            </value>
            <value>
                <fullName>ONeil Europe</fullName>
                <isActive>false</isActive>
                <label>ONeil Europe</label>
            </value>
            <value>
                <fullName>ONeils</fullName>
                <isActive>false</isActive>
                <label>ONeils</label>
            </value>
            <value>
                <fullName>ONeils Europe</fullName>
            </value>
            <value>
                <fullName>ONeils IMAP</fullName>
            </value>
            <value>
                <fullName>SKP NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent_Billing_Market__c/Parent_Billing_Market__c.object-meta.xml
<CustomObject>
    <description>Object used to aggregate Billing Markets records that refer to the same Market</description>
    <label>Parent Billing Market</label>
    <nameField>
        <label>Parent Billing Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Billing Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent_Billing_Market__c/fields/Country_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Country_Coverage__c</fullName>
    <description>used to indicate country for  the BoB Coverage record reference</description>
    <label>Country Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/M4AggregateStorageRevenueBatchTest.cls
@isTest
private class M4AggregateStorageRevenueBatchTest {
    /*
	static Map<Id, Id> imgaToCA = new Map<Id, Id>();
	static Map<Id, List<Id>> pbmToBms = new Map<Id, List<Id>>();
	static Integer startPeriod = Integer.valueOf(label.BoB_M4_End_Period);
    static Integer invalidPeriod = Math.mod(startPeriod + 1, 12);
    static Integer startYear = Integer.valueOf(label.current_Commission_Year);
    

	static List<Account> setupIMGAccounts(Integer num) 
	{
		List<User> reps;
		System.runAs(TestingUtils.ADMIN_USER) 
		{
			reps = IMGAUtilities.insertSalesReps();
		}
		return IMGAUtilities.instantiateImgaAccounts(num, reps[0].Id, reps[1].Id);
	}

	static List<IM_Customer_Account__c> setupCustomerAccounts(List<Account> imgaccounts)
	{
		List<IM_Customer_Account__c> customerAccounts = new List<IM_Customer_Account__c>();
		for (Account acc : imgaccounts)
		{
			IM_Customer_Account__c customerAccount = new IM_Customer_Account__c ();    
            customerAccount.IM_Account__c      = acc.Id;
            customerAccount.IM_Status__c       = 'Active';
            customerAccount.Name               = acc.Name + ' CID 00';
            customerAccount.Source_System__c   = 'SKP NA';
            customerAccounts.add(customerAccount);
		}
		return customerAccounts;
	}

	static List<Parent_Billing_Market__c> setupParentBillingMarkets(Integer num) 
	{
		return TestingUtils.createParentBillingMarketRecords(num, false);
	}

	static List<Billing_Market__c> setupBillingMarkets(List<Parent_Billing_Market__c> pbms, Integer num)
	{
		List<Billing_Market__c> bms = new List<Billing_Market__c>();
		for (Parent_Billing_Market__c pbm : pbms)
		{
			for (Integer i=0; i<num; i++) 
			{
				bms.add(TestingUtils.createBillingMarket('Billing Market '+i, 'Market '+i, pbm.Id, false));
			}
		}
		return bms;
	}

	static List<Product2> setupProductsWithClass(Integer num, String className) 
	{
		List<Product2> products = new List<Product2>();
		for (Integer i=0; i<num; i++) 
		{
			Product2 pd = TestingUtils.createProduct('IM Product '+ className, false);
			pd.IM_Product_Class__c = className;
            pd.Include_in_M4_Coverage__c = true;
			products.add(pd);
		}
		return products;
	}

	static void setupBillings() 
	{
		List<Account> accounts = setupIMGAccounts(5);
		insert accounts;

		List<IM_Customer_Account__c> customerAccounts = setupCustomerAccounts(accounts);
		insert customerAccounts;

		for (IM_Customer_Account__c ca : customerAccounts) 
		{
			imgaToCA.put(ca.IM_Account__c, ca.Id);
		}

		List<Parent_Billing_Market__c> pbms = setupParentBillingMarkets(3);
		insert pbms;

		Parent_Billing_Market__c pbmWithoutMatchingM4 = setupParentBillingMarkets(1)[0];
		pbmWithoutMatchingM4.Name = 'Not matching PBM0';
		pbmWithoutMatchingM4.Country_Coverage__c = 'United States';
		insert pbmWithoutMatchingM4;

		List<Billing_Market__c> bms = setupBillingMarkets(pbms, 3);
		insert bms;

		for (Billing_Market__c bm : bms) 
		{
			if (pbmToBms.containsKey(bm.Parent_Billing_Market__c))
				pbmToBms.get(bm.Parent_Billing_Market__c).add(bm.Id);
			else
				pbmToBms.put(bm.Parent_Billing_Market__c, new List<Id>{bm.Id});
		}

		List<Billing_Market__c> bmsUnderUnmatchingPBM = setupBillingMarkets(new List<Parent_Billing_Market__c>{pbmWithoutMatchingM4}, 3);
		insert bmsUnderUnmatchingPBM;

		Product2 testProduct = setupProductsWithClass(1, 'RM')[0];
		insert testProduct;		 

		List<M4_Revenue_Coverage__c> m4s = new List<M4_Revenue_Coverage__c>();
		List<Billings__c> billings = new List<Billings__c>();
		for (IM_Customer_Account__c cAcc : customerAccounts)
		{
			for (Id pbmId : pbmToBms.keySet()) 
			{
				// Create M4 for each PBM
				m4s.add(IMGAUtilities.createTestM4(cAcc.IM_Account__c, pbmId, 'North America', 'RM'));

				for (Id bmId : pbmToBms.get(pbmId)) 
				{
					// Create Billings that match M4 via Parent Billing Market
					billings.add(IMGAUtilities.createTestBilling(cAcc.Id, Date.newInstance(startYear, 3, 5), bmId, testProduct.Id));
				}
				// Create a Billing that is not within the range of billing months
				billings.add(IMGAUtilities.createTestBilling(cAcc.Id, Date.newInstance(startYear, invalidPeriod, 5), pbmToBms.get(pbmId)[0], testProduct.Id));
			}
			// Create M4 without PBM
			m4s.add(IMGAUtilities.createTestM4(cAcc.IM_Account__c, null, 'North America', 'RM'));
			for (Integer i=0; i<3; i++) 
			{
				billings.add(IMGAUtilities.createTestBilling(cAcc.Id, Date.newInstance(startYear, startPeriod, 5), bmsUnderUnmatchingPBM[i].Id, testProduct.Id));
			}
			// Create a Billing that is not within the range of billing months
			billings.add(IMGAUtilities.createTestBilling(cAcc.Id, Date.newInstance(startYear, invalidPeriod, 5), bmsUnderUnmatchingPBM[0].Id, testProduct.Id));

		}
		insert m4s;
		insert billings;


		List<Account> actualAccounts = [SELECT Id FROM Account];
		System.assertEquals(5, actualAccounts.size());
		List<IM_Customer_Account__c> actualCustomerAccounts = [SELECT Id FROM IM_Customer_Account__c];
		System.assertEquals(5, actualCustomerAccounts.size());
		List<Billings__c> actualBillings = [SELECT Id, IMGA_Name_Formula__c, Billing_Period__c, Parent_Billing_Market__c, Customer_Account__r.IM_Account__c, Customer_Account__c FROM Billings__c];
		System.assertEquals(80, actualBillings.size());
		Set<Id> uniqueAccounts = new Set<Id>();
		for (Billings__c billing : actualBillings)
			uniqueAccounts.add(billing.Customer_Account__r.IM_Account__c);
		System.assertEquals(5, uniqueAccounts.size());
		List<M4_Revenue_Coverage__c> actualM4s = [SELECT Id FROM M4_Revenue_Coverage__c];
		System.assertEquals(20, actualM4s.size());
	}

	static void setupBillings2() 
	{
		List<Account> accounts = setupIMGAccounts(1);
		insert accounts;

		IM_Customer_Account__c customerAccount = setupCustomerAccounts(accounts)[0];
		insert customerAccount;

		List<Parent_Billing_Market__c> pbms = setupParentBillingMarkets(3);
		insert pbms;

		List<Billing_Market__c> bms = setupBillingMarkets(pbms, 10);
		insert bms;

		for (Billing_Market__c bm : bms) 
		{
			if (pbmToBms.containsKey(bm.Parent_Billing_Market__c))
				pbmToBms.get(bm.Parent_Billing_Market__c).add(bm.Id);
			else
				pbmToBms.put(bm.Parent_Billing_Market__c, new List<Id>{bm.Id});
		}

		Product2 testProduct = setupProductsWithClass(1, 'RM')[0];
		insert testProduct;		

		List<M4_Revenue_Coverage__c> m4s = new List<M4_Revenue_Coverage__c>();
		List<Billings__c> billings = new List<Billings__c>();
		for (Parent_Billing_Market__c pbm : pbms) 
		{
			// Create M4 for each PBM
			m4s.add(IMGAUtilities.createTestM4(customerAccount.IM_Account__c, pbm.Id, 'North America', 'RM'));

			for (Integer i=0; i<65; i++) 
			{
				// Create Billings that match M4 via Parent Billing Market
				billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[Math.mod(i, 10)], testProduct.Id));
			}
			// Create a Billing that is not within the range of billing months
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, invalidPeriod, 5), bms[0].Id, testProduct.Id));
		}
		insert m4s;
		insert billings;

		List<Account> actualAccounts = [SELECT Id FROM Account];
		System.assertEquals(1, actualAccounts.size());
		List<IM_Customer_Account__c> actualCustomerAccounts = [SELECT Id FROM IM_Customer_Account__c];
		System.assertEquals(1, actualCustomerAccounts.size());
		List<Billings__c> actualBillings = [SELECT Id, IMGA_Name_Formula__c, Billing_Period__c, Parent_Billing_Market__c, Customer_Account__r.IM_Account__c,Customer_Account__c FROM Billings__c];
		System.assertEquals(66*3, actualBillings.size());
		Set<Id> uniqueAccounts = new Set<Id>();
		for (Billings__c billing : actualBillings)
			uniqueAccounts.add(billing.Customer_Account__r.IM_Account__c);
		System.assertEquals(1, uniqueAccounts.size());
		List<M4_Revenue_Coverage__c> actualM4s = [SELECT Id FROM M4_Revenue_Coverage__c];
		System.assertEquals(3, actualM4s.size());
	}

	static void setupBillings3() 
	{
		List<Account> accounts = setupIMGAccounts(1);
		insert accounts;

		IM_Customer_Account__c customerAccount = setupCustomerAccounts(accounts)[0];
		insert customerAccount;

		List<Parent_Billing_Market__c> pbms = setupParentBillingMarkets(3);
		insert pbms;

		List<Billing_Market__c> bms = setupBillingMarkets(pbms, 10);
		insert bms;

		for (Billing_Market__c bm : bms) 
		{
			if (pbmToBms.containsKey(bm.Parent_Billing_Market__c))
				pbmToBms.get(bm.Parent_Billing_Market__c).add(bm.Id);
			else
				pbmToBms.put(bm.Parent_Billing_Market__c, new List<Id>{bm.Id});
		}

		Product2 testProductRM = setupProductsWithClass(1, 'RM')[0];
		Product2 testProductDM = setupProductsWithClass(1, 'DM')[0];
		insert testProductRM;	
		insert testProductDM;	

		List<M4_Revenue_Coverage__c> m4s = new List<M4_Revenue_Coverage__c>();
		List<Billings__c> billings = new List<Billings__c>();
		for (Parent_Billing_Market__c pbm : pbms) 
		{
			// Create M4 for each PBM
			m4s.add(IMGAUtilities.createTestM4(customerAccount.IM_Account__c, pbm.Id, 'North America', 'RM;DM'));

			// Create Billings that match M4 via Parent Billing Market
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[0], testProductRM.Id));
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[1], testProductRM.Id));
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[2], testProductDM.Id));
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[3], testProductDM.Id));
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, startPeriod, 5), pbmToBms.get(pbm.Id)[4], testProductDM.Id));

			// Create a Billing that is not within the range of billing months
			billings.add(IMGAUtilities.createTestBilling(customerAccount.Id, Date.newInstance(startYear, invalidPeriod, 5), bms[0].Id, testProductDM.Id));
		}
		insert m4s;
		insert billings;

		List<Account> actualAccounts = [SELECT Id FROM Account];
		System.assertEquals(1, actualAccounts.size());
		List<IM_Customer_Account__c> actualCustomerAccounts = [SELECT Id FROM IM_Customer_Account__c];
		System.assertEquals(1, actualCustomerAccounts.size());
		List<Billings__c> actualBillings = [SELECT Id, IMGA_Name_Formula__c, Billing_Period__c, Parent_Billing_Market__c, Customer_Account__r.IM_Account__c, Customer_Account__c FROM Billings__c];
		System.assertEquals(18, actualBillings.size());
		Set<Id> uniqueAccounts = new Set<Id>();
		for (Billings__c billing : actualBillings)
			uniqueAccounts.add(billing.Customer_Account__r.IM_Account__c);
		System.assertEquals(1, uniqueAccounts.size());
		List<M4_Revenue_Coverage__c> actualM4s = [SELECT Id FROM M4_Revenue_Coverage__c];
		System.assertEquals(3, actualM4s.size());
	}

	static void setupM4s() 
	{

	}

	static testMethod void testBatch_3BillingsPerM4() {
		setupBillings();

		Test.startTest();
			Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q1_Q2__c', 'CY YTD Q1 Q2'), 200);
			//Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q3_Q4__c', 'CY YTD Q3 Q4'), 200);
		Test.stopTest();

		List<Aggregate_Storage_Revenue__c> actualAS = 	[SELECT Id, Amount__c FROM Aggregate_Storage_Revenue__c];
	/*	System.assertEquals(20, actualAS.size(), 
			'A total of 20 Aggregate Storage records should be created. 1 for each M4 for the month of May');
		for (Aggregate_Storage_Revenue__c aas : actualAS) 
		{
			System.assertEquals(33, aas.Amount__c, 
				'Since each billing has a total price of 11, and there are 3 billings under each aggregate, the total should be 33');
		}* /
	}

	static testMethod void testBatch_65BillingsUnder3M4s() {
		setupBillings2();

		Test.startTest();
			Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q1_Q2__c', 'CY YTD Q1 Q2'), 200);
        	//Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q3_Q4__c', 'CY YTD Q3 Q4'), 200);
		Test.stopTest();

	/*	List<Aggregate_Storage_Revenue__c> actualAS = 	[SELECT Id, Amount__c FROM Aggregate_Storage_Revenue__c];
		System.assertEquals(3, actualAS.size(), 
			'A total of 3 Aggregate Storage records should be created. 1 for each M4 for the month of May');
		for (Aggregate_Storage_Revenue__c aas : actualAS) 
		{
			System.assertEquals(715, aas.Amount__c, 
				'Since each billing has a total price of 11, and there are 65 billings under each aggregtea, the total should be 715');
		}* /
	}

	static testMethod void testBatch_2AggregatesForEachM4() {
		setupBillings3();

		Test.startTest();
			Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q1_Q2__c', 'CY YTD Q1 Q2'), 200);
			//Database.executeBatch(new M4AggregateStorageRevenueBatch('M4_CY_YTD_Q3_Q4__c', 'CY YTD Q3 Q4'), 200);        
		Test.stopTest();

	/*	List<Aggregate_Storage_Revenue__c> actualAS = 	[SELECT Id, Amount__c, Product_Class__c FROM Aggregate_Storage_Revenue__c];
		System.assertEquals(6, actualAS.size(), 
			'A total of 3 Aggregate Storage records should be created. 1 for each M4 for the month of May. Actual: '+actualAs);
		for (Aggregate_Storage_Revenue__c aas : actualAS) 
		{
			if (aas.Product_Class__c == 'RM')
				System.assertEquals(22, aas.Amount__c, 
					'Since each billing has a total price of 11, and there are 2 RM billings under RM aggregtes, the total should be 22');
			else
				System.assertEquals(33, aas.Amount__c, 
					'Since each billing has a total price of 11, and there are 3 DM billings under DM aggregtes, the total should be 33');

		}* /
	}
	*/
}