force-app/main/default/objects/NAS_Integration_Error__c/NAS_Integration_Error__c.object-meta.xml
<CustomObject>
    <description>Stores handled Integration error messages occurred during custom code developed in North America Services</description>
    <label>NAS Integration Error</label>
    <nameField>
        <displayFormat>Err-{0000}</displayFormat>
        <label>NAS Integration Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NAS Integration Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAS_Integration_Error__c/fields/NAS_Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>NAS_Apex_Class_Name__c</fullName>
    <description>Stores the apex class name where the error occurred</description>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAS_Integration_Error__c/fields/NAS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>NAS_Error_Message__c</fullName>
    <description>Stores the stack trace of the error</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NAS_Integration_Error__c/fields/NAS_Request_Data__c.field-meta.xml
<CustomField>
    <fullName>NAS_Request_Data__c</fullName>
    <description>Stores the target data dump that was being processed by the Apex Class</description>
    <label>Request Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NAS_ErrorLogger.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Error Logger Class. Utilized in North America Services project to Logg Integration Errors to 
* Custom Object NAS_Integration_Error__c
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public without sharing class NAS_ErrorLogger {
    /**
     * @name log
     * @description Logs the error message received to NAS_Integration_Error__c custom object.
    **/
	public static void log(String className, String message, String dataDump)
    {
        INSERT new NAS_Integration_Error__c(
                NAS_Apex_Class_Name__c = className,
                NAS_Error_Message__c = message,
                NAS_Request_Data__c = dataDump
            );
    }
}